### ISSUE TITLE
米游社接口报错: invalid request

### ISSUE THREAD

**Issue by 2660922348** [Arondight/Adachi-BOT#107]
不知道是哪里的问题,是cookie写错了吗？

**Comment by Arondight** [comment]
不要泄漏 cookie，理论上可以通过 cookie 登录米游社，然后通过扫码登录游戏，历史记录我已经删除

**Comment by Arondight** [comment]
`git log -2 --pretty=format:'%h %s %d'` 看一下，是不是用的老代码

**Comment by 2660922348** [comment]
![image](https://user-images.githubusercontent.com/90884958/133721571-56f7e23e-d31d-490c-a90d-caaccb225724.png)

**Comment by Arondight** [comment]
代码没问题，检查 cookie 是否合法，如果合法，执行命令 `git checkout ./data/db/cookies.json` 后重启机器人

**Comment by 2660922348** [comment]
还是报错

**Comment by Arondight** [comment]
执行什么命令（请求）时报错的？

**Comment by 2660922348** [comment]
米游社账号绑定成功，但发送米游社就报错（米游社接口报错: invalid request）

**Comment by Arondight** [comment]
`git pull -p`，`git checkout ./data/db/cookies.json`，然后再试一下

**Comment by 2660922348** [comment]
更新完还是显示米游社接口报错: invalid request

**Comment by Arondight** [comment]
呃，Cookie 是有效的吗？

**Comment by 2660922348** [comment]
隔了一天突然就能用了
