### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by xiguadoudou** [Arondight/Adachi-BOT#115]
今天更新了一下就报错了好多次都会出现这种情况

**Comment by Arondight** [comment]
报错贴一下

**Comment by xiguadoudou** [comment]
![Uploading IMG_20210917_192539.jpg…]()

**Comment by xiguadoudou** [comment]
![IMG_20210917_192539](https://user-images.githubusercontent.com/89190859/133774917-8f884945-b60f-48a5-a824-a8353ec38573.jpg)

**Comment by Arondight** [comment]
9934 端口占用，你的机器人没关上又开了，如果你实在不知道怎么解决，重启电脑

**Comment by xiguadoudou** [comment]
![IMG_20210917_192953](https://user-images.githubusercontent.com/89190859/133775499-72c00386-fd6a-4549-8bf3-fbc260f3a998.jpg)
我初始化完停止后再输这个启动会这样

**Comment by Arondight** [comment]
windows 只要 `npm init` 就能用了，其他控制命令是 Linux 用的

**Comment by xiguadoudou** [comment]
奥奥

**Comment by xiguadoudou** [comment]
那之前的npm start呢

**Comment by Arondight** [comment]
> 那之前的npm start呢

跑起来就行，你用什么命令都可以

**Comment by Arondight** [comment]
对了，今晚我刚统一改了，`npm start` 不能用了，换成 `npm run init`
