### ISSUE TITLE
gachaBUG

### ISSUE THREAD

**Issue by 490720818** [Arondight/Adachi-BOT#117]
![image](https://user-images.githubusercontent.com/33067490/133878362-bb311944-b8c8-45ca-b2c5-a6e28a8c4eab.png)

**Comment by 490720818** [comment]
![image](https://user-images.githubusercontent.com/33067490/133878630-b98b56be-4763-4656-a362-84c00417371f.png)

**Comment by Arondight** [comment]
呃，这个小伙子怎么没写进去 `choice` 字段的，感觉得加个判断，但是没写进去其实是不正常的

**Comment by Arondight** [comment]
你拉 dev 试试看
