### ISSUE TITLE
服务端本地化

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#12]
不确定可行，目前仅有一个想法。

---

## 此项目

- [x] `/baseinfo/overview/${encodeURI(name)}.json`
- [x] `/characters/profile/`
- [x] `/gacha/items/`
- [x] `/gacha/items/background.png`
- [x] `/item/`
- [x] `/item/${this.data.name}.png`
- [x] `/item/lock.png`
- [x] `/item/rarity.png`
- [x] `/module/artifact.png`
- [x] `/module/card-new-bottom.png`
- [x] `/module/card-new-middle.png`
- [x] `/module/card-new-package.png`
- [x] `/module/element.png`
- [x] `/Version2/`
- [x] `/Version2/artifact/`
- [x] `/Version2/character/`
- [x] `/Version2/info/docs/$.json`
- [x] `/Version2/info/image/`
- [x] `/Version2/info/other/BaseBackground`
- [x] `/Version2/info/other/BaseStar`
- [x] `/Version2/wish/character/`
- [x] `/Version2/wish/weapon/`

## 原作者项目（新版本）

- [x] `/characters/profile/${ props.profile }.png`
- [x] `/item/${ props.data.name }.png`
- [x] `/item/lock.png`
- [x] `/Version2/${ link }`
- [x] `/Version2/artifact/${ id }/${ slot }.png`
- [x] `/Version2/artifact/artifact.yml`
- [x] `/Version2/artifact/other/${ props.pos }.png`
- [x] `/Version2/artifact/other/rarity.png`
- [x] `/Version2/character/${ props.id }.png`
- [x] `/Version2/info/docs/$.json`
- [x] `/Version2/info/image/${ name }.png`
- [x] `/Version2/info/other/BaseBackground${ props.rarity }.png`
- [x] `/Version2/info/other/BaseStar${ props.rarity }.png`
- [x] `/Version2/module/${ parseInt( props.level ) === 0 ? `
- [x] `/Version2/module/artifact.png`
- [x] `/Version2/module/card-bottom.png`
- [x] `/Version2/module/card-middle.png`
- [x] `/Version2/module/card-package.png`
- [x] `/Version2/module/element.png`
- [x] `/Version2/slip/index.yml`
- [x] `/Version2/wish/${ type }/${ props.d.name }.png`
- [x] `/Version2/wish/config/$.json`

```
Arondight $ grep -oP "(?<=aliyuncs\.com).+?(?=[\"'\`])" * -rins | cut -d: -f3 | sort | uniq
/baseinfo/overview/${encodeURI(name)}.json
/characters/profile/
/gacha/items/
/gacha/items/background.png
/item/
/item/${this.data.name}.png
/item/lock.png
/item/rarity.png
/module/artifact.png
/module/card-new-bottom.png
/module/card-new-middle.png
/module/card-new-package.png
/module/element.png
/Version2/
/Version2/artifact/
/Version2/character/
/Version2/info/docs/$.json
/Version2/info/image/
/Version2/info/other/BaseBackground
/Version2/info/other/BaseStar
/Version2/wish/character/
/Version2/wish/weapon/
SilveryStar $ grep -oP "(?<=aliyuncs\.com).+?(?=[\"'\`])" * -rins | cut -d: -f3 | sort | uniq
/characters/profile/${ props.profile }.png
/item/${ props.data.name }.png
/item/lock.png
/Version2/${ link }
/Version2/artifact/${ id }/${ slot }.png
/Version2/artifact/artifact.yml
/Version2/artifact/other/${ props.pos }.png
/Version2/artifact/other/rarity.png
/Version2/character/${ props.id }.png
/Version2/info/docs/$.json
/Version2/info/image/${ name }.png
/Version2/info/other/BaseBackground${ props.rarity }.png
/Version2/info/other/BaseStar${ props.rarity }.png
/Version2/module/${ parseInt( props.level ) === 0 ?
/Version2/module/artifact.png
/Version2/module/card-bottom.png
/Version2/module/card-middle.png
/Version2/module/card-package.png
/Version2/module/element.png
/Version2/slip/index.yml
/Version2/wish/${ type }/${ props.d.name }.png
/Version2/wish/config/$.json
```

1. 服务端资源直接存放到本仓库，同时修改API
2. 提供一个脚本可以一键更新

**Comment by 490720818** [comment]
不如自己建个OSS

**Comment by Arondight** [comment]
@490720818 这个我先研究研究，反正看上去也不紧急，我先看看怎么把原作者的服务端资源扒下来

**Comment by Arondight** [comment]
@490720818 今天难得空闲，把[同步脚本](https://github.com/Arondight/Adachi-BOT/blob/master/resources/update.sh)写好了，资源也都提交到[resources](https://github.com/Arondight/Adachi-BOT/tree/master/resources)目录了。虽然说以后还得追着原作者更新，不过至少从整体上看至少有希望和原作者的服务端解绑，成为一个完整的项目了。但是目前问题来了，我不知道如何把已有的 API 改成本地路径，大佬有空闲的话能不能帮忙改改，麻烦大佬了。

如果有缺失的文件麻烦留言一下，我给加上，不过我感觉应该是拉全了。

**Comment by Arondight** [comment]
@490720818 我查了一下Vue 好像没法用本地，我研究一下怎么用阿里云OSS

**Comment by Arondight** [comment]
经过测试切换 OSS 后所有功能正常。

**Comment by Arondight** [comment]
现在所有资源全部请求本地，可能存在一些安全问题，后续处理一下。
