### ISSUE TITLE
深渊查询误触发

### ISSUE THREAD

**Issue by Xm798** [Arondight/Adachi-BOT#136]
聊天中出现“深渊”二字便会触发渊月螺旋战绩查询。。
![image](https://user-images.githubusercontent.com/48074861/134509237-4c020305-2921-497d-80a6-0f3d63587fa5.png)
![image](https://user-images.githubusercontent.com/48074861/134509486-5be4cc50-4866-44b4-8890-fefaf9c5827c.png)
#114

**Comment by Arondight** [comment]
这算是历史遗留问题了，我晚上改一下
