### ISSUE TITLE
疑似卡住不动了

### ISSUE THREAD

**Issue by davidelectricfree** [Arondight/Adachi-BOT#139]
环境：Windows server 2016 x64

将npm安装好，并在项目文件夹使用npm install 安装必要的组件后，使用npm run init 指令进行初始化操作，如下图。
![tempsnip](https://user-images.githubusercontent.com/36690822/134617344-45a711a3-d068-41f3-96df-ae622e7e7273.png)
会一直卡在这个[2021-09-24T12:06:00.558] [INFO] [iPad:811055003] - 群消息复读的概率为 1%这里。
在群里面说关键词，uid +id或者十连的形式，bot一点反应都没有，按理说如果部署成功应该不会这样。

如果到这里，使用Ctrl+C进行退出，使用npm run start 指令，又会报错，如图（虽然这里作者在一个issue提到过Windows系统只需要使用npm run init指令即可，但是不知道哪里的问题确实卡住了，我只能尝试其他指令）
![图片](https://user-images.githubusercontent.com/36690822/134617860-76e5b141-5caa-4096-859c-da674c5415d5.png)

log信息如下：
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle adachi-bot@1.5.0~prestart: adachi-bot@1.5.0
6 info lifecycle adachi-bot@1.5.0~start: adachi-bot@1.5.0
7 verbose lifecycle adachi-bot@1.5.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle adachi-bot@1.5.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Adachi-BOT\node_modules\.bin;C:\Python39\Scripts\;C:\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\QCloud\Monitor\Barad;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Local\GitHubDesktop\bin;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Roaming\npm
9 verbose lifecycle adachi-bot@1.5.0~start: CWD: C:\Adachi-BOT
10 silly lifecycle adachi-bot@1.5.0~start: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npx cross-env-shell PM2_HOME=$INIT_CWD/bot.pm2/ pm2 start ./app.js --name bot; npx cross-env-shell PM2_HOME=$INIT_CWD/bot.pm2/ pm2 save'
10 silly lifecycle ]
11 silly lifecycle adachi-bot@1.5.0~start: Returned: code: 1  signal: null
12 info lifecycle adachi-bot@1.5.0~start: Failed to exec start script
13 verbose stack Error: adachi-bot@1.5.0 start: `npx cross-env-shell PM2_HOME=$INIT_CWD/bot.pm2/ pm2 start ./app.js --name bot; npx cross-env-shell PM2_HOME=$INIT_CWD/bot.pm2/ pm2 save`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid adachi-bot@1.5.0
15 verbose cwd C:\Adachi-BOT
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error adachi-bot@1.5.0 start: `npx cross-env-shell PM2_HOME=$INIT_CWD/bot.pm2/ pm2 start ./app.js --name bot; npx cross-env-shell PM2_HOME=$INIT_CWD/bot.pm2/ pm2 save`
22 error Exit status 1
23 error Failed at the adachi-bot@1.5.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Arondight** [comment]
`npm run init` 就行了，Windows 不需要后台保活，卡住的时候把那个扫码做完就行

**Comment by davidelectricfree** [comment]
> 
> 
> `npm run init` 就行了，Windows 不需要后台保活，卡住的时候把那个扫码做完就行

扫码做完了，我手机点同意，过了半小时一动不动

**Comment by davidelectricfree** [comment]
> 
> 
> `npm run init` 就行了，Windows 不需要后台保活，卡住的时候把那个扫码做完就行

对了，还有一个事，我手机端这边也没有另外一个登录提醒，按理来说，如果登录另一台设备，我手机端应该有显示我登录了IPAD，但是似乎并没有。

**Comment by Arondight** [comment]
完成了就可以了，你发 QQ 消息，就会有日志输出

**Comment by davidelectricfree** [comment]
> 
> 
> `npm run init` 就行了，Windows 不需要后台保活，卡住的时候把那个扫码做完就行



> 
> 
> 完成了就可以了，你发 QQ 消息，就会有日志输出

大佬，问题是真没有啊

**Comment by davidelectricfree** [comment]
> 
> 
> 完成了就可以了，你发 QQ 消息，就会有日志输出

我发消息了，服务器那边cmd界面一点反应都没有，而且，群里面也不回复，就好像没有生效一样。

**Comment by davidelectricfree** [comment]
> 
> 
> 完成了就可以了，你发 QQ 消息，就会有日志输出

大佬，你们是扫码登陆吗？我直接用账号密码登会237网络错误，看了你们的issue，下了那个APK，然后发现那个APK会回复一个ticket，但是我不知道把这个ticket粘贴到哪里，所以我就是用的扫码登录的。

**Comment by Arondight** [comment]
我没用扫码登录，那个 ticket 直接粘贴到 cmd 然后按回车就行

**Comment by davidelectricfree** [comment]
> 
> 
> 我没用扫码登录，那个 ticket 直接粘贴到 cmd 然后按回车就行

结果出来了，可能这个程序扫码有点问题，用输出ticket的方式成功运行了

**Comment by davidelectricfree** [comment]
> 
> 
> 我没用扫码登录，那个 ticket 直接粘贴到 cmd 然后按回车就行

十分感谢回复
