### ISSUE TITLE
windows部署之后，某些指令无法生效的问题

### ISSUE THREAD

**Issue by SunShineJF** [Arondight/Adachi-BOT#141]
作者大大，我按照你上一个issues中的操作后，成功部署，机器人部分指令可以正常工作，比如绑定米游社id，十连等操作。
但是有一些指令没有回复，比如米游社，uid查询。。

麻烦作者大大给看看
![1](https://user-images.githubusercontent.com/49141302/134646247-6cd956d9-32b6-47b6-b1df-2150be2192c5.jpg)

**Comment by Arondight** [comment]
代码确实有问题，你没有配置任何 Cookie，代码没有对这个情况作出处理。另外即使代码改了你这也是不行的，想要查询必须要有 Cookie
