### ISSUE TITLE
有没有可能支持多账号绑定

### ISSUE THREAD

**Issue by Xm798** [Arondight/Adachi-BOT#145]
有没有可能支持多账号绑定呢？比如我自己有三个米游社的账号，如果能够绑定多个账号的话，就不用记ID了，而且主要是`我的 XX`功能仅绑定状态下可用。
如果支持了多账号绑定的话，可以通过`我的 小号 XX`这样来调用，`小号`是绑定的时候自行设置的别名，例如`绑定 1234567 小号`。不选择账号的话默认就是默认账号。

**Comment by Arondight** [comment]
不准备做，怎么想都会用乱。我从反馈中感受到的就是用法越简单直白越好。
最开始是可以查别人的角色的，准确来说查的角色是你查的上一个 UID 或者 mys 的，但是我发现几乎所有人都理解不了，不知道为什么查的角色会变化。这群人甚至发过“（上期）深渊”这样的命令，我觉得还是牺牲功能换易用性吧……

发自我的iPhone
