### ISSUE TITLE
信息展示有问题

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#15]
随便找了个氪佬的号，`107430800`。
![图片](https://user-images.githubusercontent.com/13673702/126813921-93b25bd0-c038-4a09-9823-17a2fa684177.png)

**Comment by 490720818** [comment]
漏传了个png，已补

**Comment by Arondight** [comment]
```
SyntaxError: Unexpected token u in JSON at position 0
```

**Comment by 490720818** [comment]
> ```
> SyntaxError: Unexpected token u in JSON at position 0
> ```

哪个插件

**Comment by Arondight** [comment]
@490720818 如图，感觉是最近更改引入的
![D63951D9-0877-4B97-B9D0-39E57354BCBB](https://user-images.githubusercontent.com/13673702/126932756-ceaeb4ab-21f2-4caa-b157-f6a7cfffddc4.png)

**Comment by 490720818** [comment]
我直接下载的git代码 没这个问题

**Comment by Arondight** [comment]
@490720818 嗯，我排查一下

**Comment by Arondight** [comment]
@490720818 让公司的同事帮忙看了下找到原因了，上午同事帮忙更新bot 的时候设置了`http_proxy`和`https_proxy`，`unset`掉就可以了。恰巧是没有返回预期的数据同时程序不健壮就这样了
