### ISSUE TITLE
这个项目怎么来的（为什么会有两个同名项目）？

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#153]
我会使用PS，Illustrator制图，全日制研究生，有意愿参与项目维护。

但是在 #57 没有太看懂这个项目对于新卡池需要什么样的资源文件，对于图片的格式、分辨率等等有没有具体的要求。

希望能够详细了解一下现在这个项目需要什么样的图片资源，如果有例子的话更好

**Comment by Mark9804** [comment]
看上去好像目前资源是完整的（除了托马的头像），如果没有意见的话，我这边打算先参照[神里头像](https://github.com/Arondight/Adachi-BOT/blob/master/resources/characters/profile/10000002.png)完成托马的圆形头像，后续微调一下目前`resources/characters/profile`当中的图片，让每个角色的头都差不多大。

**Comment by Arondight** [comment]
首先是你的问题，回答是目前应该不需要。

然后我想说一下这个项目是怎么来的。最开始 [SilveryStar](https://github.com/SilveryStar) 写了项目的[旧版本](https://github.com/SilveryStar/Adachi-BOT/tree/ver1.4.6)。最开始我想制定一些命令， fork 了他的项目，然后慢慢的加了自己的插件。但是有一天原作者的旧版本不再维护了，另起炉灶用 TS 写了一个新版本，我完全不懂 JS 和 TS  ，所以写的插件移植不过去，就一直维护的旧版本。直到有一天，作者大幅改动了其 OSS 上的资源文件路径，导致这个项目无法工作了，那时候我开始看了一点 JS 语法，按照作者的 OSS 文件变化继续维护旧版本。

我那时刚刚接触 JS ，以前都是用 C 和 Python 干活的，意识到在不能保证原作者不乱动 OSS 的情况下，凭借我自己很难独立维护项目，再加上我已经在废弃的旧版本上叠了不少提交了，也有了大约十几个 star ，我向 GitHub 申请移除了此项目的 fork 关系，变为独立的项目。然后这个项目就可以被搜到了，这样虽然 GitHub 上有了两个 Adachi-BOT ，但是我可以吸引一些老大哥帮我去维护，最重要的任务是适配原作者的 OSS 。并且这时候有个大问题就是全部的资源都请求的原作者 OSS ，我这里的项目是无法独立工作的。

再后来，我写了个[脚本](https://github.com/Arondight/Adachi-BOT/blob/master/resources/update.sh)把原作者的 OSS 全部扒了下来，然后全部资源改成了本地，这样项目可以独立工作了，虽然仓库体积大了不少，但是至少是个好的开始。每次原作者更新资源，我就跑一下脚本把资源文件都扒下来。后来原作者因为学业原因不太积极了，池子开了几天都没得更新，所以我开了 #57 寻求帮助，因为我确实不会 PS 。但是一来原作者有次过来说以后的更新会及时一些了，二来找到了一个老哥 [Xm798](https://github.com/Xm798) 帮忙，也能自己制作资源文件了。所以说目前没有什么特别需要帮助的，代码我在做，资源文件也能靠着原作者吃饭，甚至有老哥能帮忙做一些。

然后加的插件和功能越来越多，随着对 JS 了解的多了一点，旧版本里我不喜欢的一些设计也可以独立修改了。原作者当时是作为一个高中生写的，代码有些地方比较稚嫩我不太喜欢，然后逐渐地去改了改。现在整个项目都在变得越来越好，渐渐地从原作者的项目里独立出来了。以后大概会成完全平行的两个项目吧，大概以后我会学学 Vue ，项目的图可能都不一样了，这样一来其实项目就没啥地方是一样的了，除了资源文件大部分还是从原作者那里扒的。

如果说这俩项目有啥不一样，我也说不好，大概是作者的喜好和偏向多少有些不同吧，差异其实并不大，本质上都是一个游戏助手。另外我这里可能活跃一点，我当前的工作实在是太摸鱼了……

**Comment by Arondight** [comment]
刚才编辑了楼上的冗长陈述，换了个稍微简短的版本。这里感谢一下楼主，这个项目靠着好几个老大哥的帮助活了下来，要不然作者改 OSS 的时候，我根本没接触过前端技术和 node ，大约已经因为无力维护而放弃了。另外特别感谢原作者，资源大部分都是扒的原作者的，算是坐享其成了。

**Comment by Mark9804** [comment]
我这边的想法是既然用了这个项目的话就尽可能的回馈，技术方面特别JS我现在也就面向百度编程的水平，但PS还算说得过去。所以我很乐意负责图像资源方面的处理工作。

[SilveryStar/Adachi-BOT](https://github.com/SilveryStar/Adachi-BOT/tree/master)和这个项目都是这两天接触到的，之前用的是SilveryStar的原项目，但是发现比起TypeScript来说还是JS我稍微能看懂一些，就决定在这个项目基础上尝试根据自己需求开发功能了。

之后如果有需要的话，我愿意分担一部分程序开发外的工作。术业有专攻，我现在的写bug水平也不太好意思参与开发，就先干干杂活。

**Comment by Arondight** [comment]
@Mark9804 感谢老大哥，已经发邀请了，帮忙的人总不嫌多

**Comment by Arondight** [comment]
@Mark9804 资源文件你要是有时间按照 #57 的说明直接添加到对应位置即可，老的文件能用的尽量不要动，因为会增加 git 仓库的体积，现在已经快 100M 了，还是挺大的。

**Comment by Mark9804** [comment]
> 老的文件能用的尽量不要动，因为会增加 git 仓库的体积，现在已经快 100M 了，还是挺大的。

了解

> 资源文件你要是有时间按照 #57 的说明直接添加到对应位置即可

不知道托马的资源现在是个什么进度，我看了一下仓库，因为之前的ID错误托马现在用的还是埃洛伊的图像资源。**如果没有其他人做的话我就新开个issue认领托马的资源制作了。**

> 如果没有其他人做的话我就新开个issue认领托马的资源制作了。

关于一些新的问题，例如

1. 内鬼网（Honey Impact）的数据更新周期变更导致之后这个项目的新人物资源更新周期也要跟着变动，
2. 关于图像资源的分辨率细节讨论

我也会放到这个新的issue里面

**Comment by Arondight** [comment]
@Mark9804 

> 内鬼网（Honey Impact）的数据更新周期变更导致之后这个项目的新人物资源更新周期也要跟着变动，

可以先做个图，json 晚点写，或者写了 json 到时候改就行

> 关于图像资源的分辨率细节讨论

我对此一无所知，有个图就谢天谢地了

---

如果你了解而且准备写点东西描述一些，建议新开一个 issue，然后打个 doc 标签，尽量 doc 标签的一个 issue 描述一个问题，我可以在 #57 里面链接过去

**Comment by Arondight** [comment]
另外提交的时候还是麻烦先提交 `dev` 或者别的临时分支，然后合入 `master`。

**Comment by Mark9804** [comment]
> 另外提交的时候还是麻烦先提交 `dev` 或者别的临时分支，然后合入 `master`。

我会先提交在我个人fork的`dev`分支，然后向`Arondight/Adachi-BOT`的`dev`分支提交PR

> 建议新开一个 issue，然后打个 doc 标签
> 尽量 doc 标签的一个 issue 描述一个问题

了解

**Comment by Arondight** [comment]
现在项目的差异太大了，我感觉没必要去解释为啥这两个项目是什么了，因为确实是两个项目，就是名字一致
