### ISSUE TITLE
重新拉取代码之后   图片报错 

### ISSUE THREAD

**Issue by HYTT0510** [Arondight/Adachi-BOT#157]
今天重新拉取了一份代码  然后所有图片都报错
![D JP_5O(PU1H(B`FHC%1470](https://user-images.githubusercontent.com/46914653/135274726-4699ce8d-0ddb-4733-bea6-709901da18e7.png)
![image](https://user-images.githubusercontent.com/46914653/135274748-8d7c7eb6-2151-4f1e-a449-e0bf12a98fb5.png)
![image](https://user-images.githubusercontent.com/46914653/135274774-1731cb46-fe0a-4538-861d-fbad5f71ddfb.png)

**Comment by HYTT0510** [comment]
看了一下日志  一直在循环进行此步操作
![image](https://user-images.githubusercontent.com/46914653/135275142-a099d8c8-019b-4fc1-852c-5f894fa8c614.png)

**Comment by Arondight** [comment]
有个正在运行的机器人你没关，如果你不知道怎么关，重启系统

**Comment by HYTT0510** [comment]
服务器重启过   重新拉取代码  但是图片依然不正确

**Comment by Mark9804** [comment]
可以尝试一下`npm run list`，查看目前有没有机器人在运行，没有运行的话列表是空的
![image](https://user-images.githubusercontent.com/9006264/135382819-1e2a4e98-ef97-45ed-b44f-8f1cb0963745.png)
如果有，并且你确定没有启动过机器人，可能是你之前设置了自动启动，运行`npm run unstartup`禁止它
最后运行`npm run stop`停止当前运行的机器人并自行启动，或者`npm run restart`重启机器人

我这边没有复现这个情况
