### ISSUE TITLE
【bug】“深渊”和“上期深渊”数据会相互覆盖

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#161]
# 复现
1. 查询`深渊`
2. 查询`上期深渊`
3. 查询`深渊`

# 预期结果
bot会拉取两次米游社深渊数据；
`上期深渊`会返回2021.09.16～09.30的挑战结果；`深渊`会返回10.01～10.15的挑战结果

# 实际表现
bot只会在第一次查询`深渊`时拉取一次米游社的本期深渊数据，后续两次查询全部使用缓存的本期数据

**Comment by Arondight** [comment]
晚上改，过节事情比较多

**Comment by Mark9804** [comment]
https://github.com/Arondight/Adachi-BOT/commit/ebfaaa2ed5709ed8b9f461da951abacf62a4ae89 又复现了这个问题

目前`aby.json`中，同一个uid只能同时存在一个记录（这期的或者上期的），不知道是不是lowdb限制了发挥（我也没整太明白，似乎是使用`db.init("dbname")`初始化数据库之后，后续就只能往默认的`user`当中push数据而不能再创建一个新的key），也许原作者在v2使用redis是一个正确的选择？

**Comment by Mark9804** [comment]
我感觉相比深渊功能两个bug的严重程度，暂时revert回https://github.com/Arondight/Adachi-BOT/commit/3fed2d2bed522b4f424b6118fdb97ce512e0862e 然后不去管它也行。 #163 的问题是可以通过堆可用cookie解决的

**Comment by Arondight** [comment]
> [ebfaaa2](https://github.com/Arondight/Adachi-BOT/commit/ebfaaa2ed5709ed8b9f461da951abacf62a4ae89) 又复现了这个问题
> 
> 目前`aby.json`中，同一个uid只能同时存在一个记录（这期的或者上期的），不知道是不是lowdb限制了发挥（我也没整太明白，似乎是使用`db.init("dbname")`初始化数据库之后，后续就只能往默认的`user`当中push数据而不能再创建一个新的key），也许原作者在v2使用redis是一个正确的选择？

目前就是这样的，和工具无关，这是数据库设计时的疏漏，没有考虑过缓存的问题，每个用户下的记录并不是数组，暂时不管这个问题，任何版本都存在。

**Comment by Arondight** [comment]
> 
> 
> 我感觉相比深渊功能两个bug的严重程度，暂时revert回[3fed2d2](https://github.com/Arondight/Adachi-BOT/commit/3fed2d2bed522b4f424b6118fdb97ce512e0862e) 然后不去管它也行。 #163 的问题是可以通过堆可用cookie解决的

已经 fix
