### ISSUE TITLE
【探讨】【极低优先度】使用paddleOCR提高圣遗物OCR的准确性和容错率

### ISSUE THREAD

**Issue by mark9804** [Arondight/Adachi-BOT#179]
目前[rating插件的OCR功能](https://github.com/Arondight/Adachi-BOT/blob/e488a11254c4d299d83aa21300cbafa65504f175/src/plugins/rating/index.js#L65)使用可莉特调的API，只能严格识别**背包中**的**屏幕截图**，遇到其他底色或者拍屏就歇逼了，但也不是不能用。

我今天尝试了一下[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)发现效果非常好，蓝底白字/红底白字和拍屏都能识别，而且正确率目前来看很高，小样本测试没发现可莉特调API存在的多个小数点或者缺失小数点的问题。不过错别字依然少量存在，和隔壁同样使用paddleOCR的椰羊一样需要一个correction map。
这个模型是完全在本地跑的，不用担心可莉特调删库跑路。

现在问题是paddleOCR没有官方的JS port，不知道能不能通过阳间方式整进`rating`插件里面。现在的圣遗物识别也不是不能用，就先作为一个想法搁置在这边吧。
我目前的想法是当可莉特调识别失败之后，调用paddleOCR作为备用选项。但是怎么直接从js获取shell命令的返回结果我就没思路了。目前的阴间构思是通过shell执行之后把结果写入文本文件，然后`rating.js`读取这个文件。

**Comment by Arondight** [comment]
这个我后来看了看其他的项目放弃了，例如这个 https://github.com/ProblemFactory/GenshinArtScanner 。

bot 的情况还要远远比圣遗物导出功能要复杂，差不多基本上算是搁置了。

**Comment by Arondight** [comment]
> 
> 
> 行，我在本地fork上看看能不能写个阴间实现，就关闭这个issue了

个人建议能将就则将就，文本处理向来是编程里极其麻烦的领域， ocr 只是返回一个原始文本而已，我所知道的几个圣遗物导出工具都是按照 ocr 返回的文本坐标来判断圣遗物的各个属性的值，你要支持各种情况例如门栓拍大屏，那肯定没法用坐标了，这时候麻烦就来了。

**Comment by Arondight** [comment]
多回复一下，我个人对文本处理大致判断麻烦不麻烦的办法就是能不能一眼找出来想要的东西，如果能一眼找出来那就说明编程实现不麻烦。例如圣遗物 ocr 不依靠坐标判断属性，结果大概是下面的样子

```
染血的骑士之杯
空之杯
风元素伤害加成
---此上截图可能不全---
46.6%
暴击伤害
20.1%
暴击率
10.1%
攻击力
4.7%
防御力
7.4%
---以下截图可能多余---
两件套
造成的物理伤害提高
```

看了看似乎也还行，只要默认一个数字是上一个属性的值就行，应该不至于费大劲。就是对于某一个 ocr 库需要有一个训练结果用于纠错，这个肯定是无法避免的。

**Comment by Mark9804** [comment]
举例来说的话，对于本条评论末尾的图片，paddleOCR给出的结果是这样的
```
[[[94.0, 40.0], [515.0, 34.0], [516.0, 110.0], [95.0, 116.0]], ('雷灾的子遗', 0.8789786)]
[[[80.0, 186.0], [255.0, 186.0], [255.0, 250.0], [80.0, 250.0]], ('死之羽', 0.997258)]
[[[76.0, 397.0], [253.0, 403.0], [252.0, 469.0], [74.0, 463.0]], ('攻击力', 0.8809344)]
[[[74.0, 485.0], [280.0, 479.0], [283.0, 595.0], [77.0, 601.0]], ('166', 0.8823493)]
[[[80.0, 638.0], [501.0, 636.0], [502.0, 706.0], [81.0, 708.0]], ('食★★★★', 0.60500467)]
[[[108.0, 972.0], [525.0, 972.0], [525.0, 1028.0], [108.0, 1028.0]], ('攻击力+4.1%', 0.96770275)]
[[[106.0, 1076.0], [723.0, 1074.0], [723.0, 1130.0], [106.0, 1132.0]], ('元素充能效率+5.2%', 0.9839014)]
[[[102.0, 1182.0], [594.0, 1182.0], [594.0, 1236.0], [102.0, 1236.0]], ('·暴击伤害+7.8%', 0.9497873)]
[[[102.0, 1288.0], [527.0, 1288.0], [527.0, 1344.0], [102.0, 1344.0]], ('·元素精通+40', 0.9342015)]
[[[76.0, 1390.0], [412.0, 1390.0], [412.0, 1452.0], [76.0, 1452.0]], ('如雷的盛怒：', 0.8993227)]
[[[80.0, 1496.0], [1086.0, 1490.0], [1086.0, 1546.0], [81.0, 1552.0]], ('02件套：获得15%雷元素伤害加成。', 0.9404091)]
[[[78.0, 1598.0], [1228.0, 1588.0], [1229.0, 1648.0], [79.0, 1658.0]], ('24件套：超载、感电、超导反应造成的伤', 0.85186505)]
[[[159.0, 1676.0], [1227.0, 1668.0], [1227.0, 1728.0], [159.0, 1736.0]], ('害提升40%。触发这些元素反应时，元', 0.92651653)]
[[[159.0, 1756.0], [1232.0, 1746.0], [1233.0, 1806.0], [159.0, 1816.0]], ('素战技冷却时间减少1秒。该效果每0.8', 0.96469367)]
[[[159.0, 1832.0], [621.0, 1832.0], [621.0, 1892.0], [159.0, 1892.0]], ('秒最多触发一次。', 0.9875989)]
```
因为圣遗物部位和副词条基本上是准确识别的，圣遗物名字不重要，所以我目前的想法是检查识别结果与所有可能出现的词条（可以直接硬编码成字典或者array）的中文文本相似度，然后通过`+`作为分隔符获取副词条数据，感觉理论上大概也许可能是可行的。
![image](https://user-images.githubusercontent.com/9006264/136249878-47039e4b-0ec7-47d6-a7e4-80f6ef7f2434.png)
