### ISSUE TITLE
米游社接口报错: Please login

### ISSUE THREAD

**Issue by citydirector** [Arondight/Adachi-BOT#180]
部分信息查询时会提示请登录，部分信息正常；私以为是cookie过期了，更新后（先停止再更新）依然如此

**Comment by citydirector** [comment]
注意休息（笑），问题不急
貌似的确是个玄学问题，用（账号c）的cookie也不行（直接复制过来的）
当然log也没有任何报错

**Comment by Arondight** [comment]
这报错大概率是 cookie 的账户被封了

**Comment by citydirector** [comment]
> 这报错大概率是 cookie 的账户被封了

应该不是，我尝试了复制在另一台服务器上正常工作的账号c的cookie过来，也会出现这种情况（见上文）

**Comment by Arondight** [comment]
> 
> 
> > 这报错大概率是 cookie 的账户被封了
> 
> 应该不是，我尝试了复制在另一台服务器上正常工作的账号c的cookie过来，也会出现这种情况（见上文）

还是确认一下吧，这种情况几乎无一例外都是 cookie 被米游社禁了，你登陆一下对应的账户试试能看战绩么，如果能看的话把新的 cookie 替换过去，不能看的话再买新的，前段时间封了很多号导致价格都贵了，另外 cookie 只需要 account_id 和 cookie_token 即可工作

**Comment by Arondight** [comment]
> 这貌似有点针对性，在进行部分账号的“米游社”查询时会出现以上错误，另外一部分账号则正常更新缓存；当然，也有一小部分昨天查询失败的账号（放了一晚上后）现在能正常查询
> 以上情况仅限于使用A和B账号查询

cookie 每天最多查 30 次，超过次数会查询失败， please login 错误还是建议检查一下帐号是否被封禁，没有的话重新拿 cookie ，这个错误几乎都是封禁的问题

**Comment by citydirector** [comment]
> 删除 cookie 缓存需要停止 bot 然后执行 rm data/db/cookies.yml

是cookies.json；
删除缓存后 成功查询到之前查询失败的账号。
但是又出现了上一个issue的问题：[https://github.com/Arondight/Adachi-BOT/issues/178#issuecomment-936687340]

**Comment by Arondight** [comment]
图没了和 cookie 没关系，应该就是网不行 https://github.com/Arondight/Adachi-BOT/issues/178#issuecomment-936704180
