### ISSUE TITLE
人已经社死 可以把setting配置文件这两个默认选项改掉吗

### ISSUE THREAD

**Issue by pianfanshaan** [Arondight/Adachi-BOT#184]
repeatProb: 1

groupHello: 1

这两组一开始没注意看 还是默认为0吧

人已经裂开QAQ

**Comment by Arondight** [comment]
食用前请仔细阅读说明呀，另外不建议使用个人常用账号挂 bot ，一般都是申请个新号

**Comment by Mark9804** [comment]
啊这，个人意见，大家应该都是成年人了，也得为自己的不小心承担责任……这两个选项的说明写的我觉得还算清楚

顺便关于申请新号的问题，最近打击比较严，刚申请的新号就直接拿来挂bot的话封号概率非常高，需要挂一段时间，具体是多久我没试出来，因为我自己刚申的小号也被封了
