### ISSUE TITLE
缓存数据不会随着 ID 变更而失效

### ISSUE THREAD

**Issue by Oyuanchu** [Arondight/Adachi-BOT#190]
对@的人数据总为上一个人的数据，绑定指令失效

**Comment by Arondight** [comment]
呃，没有理解，可以细说一下吗？

**Comment by Arondight** [comment]
呃，我还是没有明白，可以说的简单一些吗？我理解的是我不管绑定什么米游社账号，你先查了你的，那我再查我的，也会查出来你的，是这样吗？

**Comment by Mark9804** [comment]
看上去可能跟 #161 有一定相关性，都是读取了错误的缓存导致的问题

**Comment by tendapc** [comment]
![image](https://user-images.githubusercontent.com/69566610/136697305-5bdc77b1-aec3-4a71-9ca7-c7c3f75d9c27.png)

**Comment by Arondight** [comment]
哦，我明白你在说什么了。
我绑定了米游社账户 123 ，但是绑定错了， 123 是别人的，我查了 123 的数据。
然后我绑定了自己的 456 ，我查 456 的数据，得到的还是 123 的，是这样吧？
@tendapc

**Comment by tendapc** [comment]
是的

**Comment by tendapc** [comment]
这是最近更新才明显的

**Comment by tendapc** [comment]
导致每个人一个小时只能查询一个数据

**Comment by Arondight** [comment]
的确是这样的，本着克勤克俭用 cookie 的原则，我做了尽量多的缓存设定，也导致了这个问题。

**Comment by Arondight** [comment]
在变更数据的时候同时清空查询时间，下次强制拉取新数据，因为不紧急，所以晚一些修复。
