### ISSUE TITLE
圣遗物别名支持

### ISSUE THREAD

**Issue by mark9804** [Arondight/Adachi-BOT#191]
目前这个功能commit在我自己的实验分支 https://github.com/Mark9804/Adachi-BOT/commit/e3e2611806e92ed38e7bfc1a6d74b944a51cac3a

# 更改文件
`src/plugins/artifacts/index.js`
`config_defaults/artifacts.yml`
`config_defaults/command.yml`

# 功能更新
接到反馈说圣遗物本ID都是数字，很难记，因此在`artifacts.yml`中增加了副本的`nickname`字段，现在可以同时使用`圣遗物 副本ID`和`圣遗物 副本昵称（名称）`来进行刷取圣遗物。

针对查不到副本昵称的情况进行反馈。

# 效果
![image](https://user-images.githubusercontent.com/9006264/136695670-f3167dec-c300-4652-93a7-fd43d14195f4.png)

**Comment by Mark9804** [comment]
> 谢谢，这是个好功能，但是我更倾向于把这些写在 alias.yml 里，别名使用同一套机制和同一个配置文件，不会分散，而且用起来很简单，使用全局变量即可 `func(alias[name] || name)`

原来还有这种操作吗，之前写方舟掉落查询插件的时候我还造了个轮子，那我改动一下

> 如果可以的话尽量支持数字和别名、本名，个人觉得数字更方便

群友反馈说数字方便但是需要额外记忆一个数字和副本之间的对应关系，所以才有了这个功能，其他功能都是支持的
例如刷雷本，那么：
`圣遗物 1`和
`圣遗物 仲夏庭院`和
`圣遗物 雷本`

这三个命令都会被识别成刷取ID为1的圣遗物副本

**Comment by Mark9804** [comment]
关于`alias.yml`，其实我觉得可以稍微提升一下，让这个文件支持正则

我印象里目前通过alias匹配的方式是查找字典键值对，虽然相对而言效率高但是别名编写和匹配成功率都偏低，不知道大佬有没有意向支持一下

**Comment by Arondight** [comment]
> 
> 
> 关于`alias.yml`，其实我觉得可以稍微提升一下，让这个文件支持正则
> 
> 我印象里目前通过alias匹配的方式是查找字典键值对，虽然相对而言效率高但是别名编写和匹配成功率都偏低，不知道大佬有没有意向支持一下

这个我没有意向做

**Comment by Arondight** [comment]
@Mark9804 我想了一下，还是按照你这样写吧，nickname 不用写本命，我想做个圣遗物的全局变量，跟插件的用起来差不多，用全局变量来转换别名，大约是这个感觉 `artifacts.domains.alias[name] || name`

**Comment by Arondight** [comment]
1. `副本` 命令返回信息替换成根据两个全局变量以恰当的形式拼接出的每一个副本的 ID 、名称、别名。
2. `圣遗物` 命令的帮助信息里体现出能够使用副本 ID 、名称和别名的特性。
3. 因为圣遗物配置文件过于复杂，不提供其他的环境变量，不改变圣遗物配置文件的其他处理逻辑。

**Comment by Arondight** [comment]
> 提个建议：boss这个alias也许可以改成小写，之后的alias to name统一使用toLowerCase()转换之后进行查询

这个也可以在读入文件并转化为可用的数据结构的时候做，全部转小写，配置文件是个静止的，数据结构是可动的，问题应该不大，文档、配置文件、注释加一下标注就行
