### ISSUE TITLE
祈愿功能重复读取最后一次祈愿结果

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#195]
返回祈愿图片时，会返回重复的不属于自己的结果。祈愿功能完全无法使用。
![image](https://user-images.githubusercontent.com/9006264/136703970-0e4fc6c9-a406-42e8-ac92-79f0347aa96a.png)

在我和Arondight/dev同步的`dev`分支可以复现这个问题。

**Comment by Arondight** [comment]
https://github.com/Arondight/Adachi-BOT/blob/3bb7af1a6fff6d13820080ee98348b02650128dd/src/utils/render.js#L28

`${name}.json` 没有变量内插
