### ISSUE TITLE
角色的 ID 是哪里查的

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#20]
例如`神里绫华`的 ID 是`10000002`，这个在哪个网站能查到？

**Comment by monsterxcn** [comment]
这里：https://github.com/Arondight/Adachi-BOT/blob/926d4fcf618c70c5e826725267b886c10c2ae662/resources/update.sh#L49-L50

**Comment by Arondight** [comment]
@monsterxcn 啊这……这注释是我写的，去原作者的 OSS 上查的，我想知道原作者在哪里查的

**Comment by monsterxcn** [comment]
🤣确实，我一看你这 Owner badge 疑惑了

**Comment by 490720818** [comment]
https://genshin.honeyhunterworld.com/

**Comment by Arondight** [comment]
@490720818 这上面没发现额

**Comment by 490720818** [comment]
![image](https://user-images.githubusercontent.com/33067490/128964118-f2c7a03d-7a09-4f91-8d4f-4fc79cd0d8ed.png)

**Comment by Arondight** [comment]
@490720818 我的神，还是你强啊

**Comment by monsterxcn** [comment]
今天看到一个深渊数据的网站，这儿的角色 ID 还挺好查的，角色头像图片链接的文件名就是角色 ID。因为统计了使用率，所以角色也全乎了。

https://spiral-abyss.appsample.com/

**Comment by Arondight** [comment]
> 今天看到一个深渊数据的网站，这儿的角色 ID 还挺好查的，角色头像图片链接的文件名就是角色 ID。因为统计了使用率，所以角色也全乎了。
> 
> https://spiral-abyss.appsample.com/

原来这里就可以看啊，这网站的12 层竞速天梯榜上还有我的名字，哈哈

**Comment by 490720818** [comment]
没出的角色没有

**Comment by Dragon-Fish** [comment]
原本可以在这里查 [https://webstatic.mihoyo.com/hk4e/gacha_info/cn_gf01/items/zh-cn.json](https://webstatic.mihoyo.com/hk4e/gacha_info/cn_gf01/items/zh-cn.json)

查出来的数据过滤 `item_type` 为 `角色`，`item_id - 1000 + 10000000` 就是角色 id

但！是！怎么看都看得出来它现在不全。

**Comment by Arondight** [comment]
现在爬虫会自动处理这个字段，不再需要人工查了

**Comment by Mark9804** [comment]
真好啊，以前的顽固问题能解决
