### ISSUE TITLE
功能绘图失败

### ISSUE THREAD

**Issue by oha189** [Arondight/Adachi-BOT#202]
![image](https://user-images.githubusercontent.com/63651054/136745568-16573a31-2b77-4955-bfbd-23d5bd46113a.png)

**Comment by Mark9804** [comment]
更正一下：git **status**

**Comment by 2385706087** [comment]
![image](https://user-images.githubusercontent.com/69779315/136789994-77583266-8301-42b7-ab2f-0aca3a58550b.png)
我也遇到了这个问题，今天拉的代码，环境是阿里云的ubuntu20.04，但本地ubuntu没问题

**Comment by Arondight** [comment]
> 更新完重新运行了一下npm run init 变这样了

你的无头浏览器无法工作，你可以……

1. 手动解决 `libatk-1.0.so.0` 这个依赖，重复解决遇到的依赖问题，直到无头浏览器能够运行。
2. 按照说明手册中的步骤使用系统自带的浏览器，让包管理器为你解决一切依赖问题。

**Comment by 2385706087** [comment]
> 你的无头浏览器无法工作，你可以……
> 
> 1. 手动解决 `libatk-1.0.so.0` 这个依赖，重复解决遇到的依赖问题，直到无头浏览器能够运行。
> 2. 按照说明手册中的步骤使用系统自带的浏览器，让包管理器为你解决一切依赖问题。
感谢，目前已解决
https://blog.csdn.net/weixin_44388092/article/details/104220500  
根据这篇文章 安装完无头浏览器后能用了

**Comment by Arondight** [comment]
> 
> 
> 离谱，刚才拉了最新的代码，突然就正常了。。 还没搞明白哪有问题

可能是我昨天的一个提交有关，不过至少问题是解决了，如果还有问题请 reopen 。
