### ISSUE TITLE
【低优先度】更换渲染字体

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#205]
华文行楷和汉仪文黑的字库已经不够用了，可能需要更换其他字体
![image](https://user-images.githubusercontent.com/9006264/136837075-64a29187-0692-4690-8e39-4a8bea19a6a9.png)

我个人推荐[霞鹜文楷](https://github.com/lxgw/lxgwwenkai)，GitHub开源字体，不会因为版权问题被律师函警告

**Comment by Arondight** [comment]
我突然想起来一个问题，就是玩家数据的图上面不是有每个角色的武器嘛，我加的时候一直没做到把整个信息放在框的中间，现在武器是压着下边栏的，上面间距比下面的大，不知道这个能改吗，我只改了左右居中，上下实在没调好，不知道可以帮忙看看嘛

**Comment by Mark9804** [comment]
有图吗，米游社相关的图我都渲染不出来，上个月初申请了换宽带运营商现在也还没见到人影……

**Comment by Arondight** [comment]
> 有图吗，米游社相关的图我都渲染不出来，上个月初申请了换宽带运营商现在也还没见到人影……

![78DE23A2-3831-4F94-9D1F-94347B0971A7](https://user-images.githubusercontent.com/13673702/136943533-9312e9ec-59f8-4958-aff7-8028a0028cbc.png)

大致看一眼就行，不好改就不用动了，反正也没啥影响

**Comment by Arondight** [comment]
> 嗯，还有 info.html ，这俩文件几乎是一样的

这俩用的是同一个 css

**Comment by Arondight** [comment]
> > 嗯，还有 info.html ，这俩文件几乎是一样的
> 
> info.html渲染出来是什么样的，我能看一下吗

你可以认为是一模一样的，至少对这个问题是……

**Comment by Arondight** [comment]
🤣 要不以后再看吧，反正也没啥影响

**Comment by Arondight** [comment]
我感觉比以前好太多了，很明显地提升，以前有点花里胡哨的 😁
