### ISSUE TITLE
武器池定轨功能失效

### ISSUE THREAD

**Issue by mark9804** [Arondight/Adachi-BOT#211]
![DB762632-023E-4712-938B-3CB8A46C440E_1_105_c](https://user-images.githubusercontent.com/9006264/137054911-a6afd9d6-eff1-4001-b02d-4489bac1ebf8.jpeg)

**Comment by Mark9804** [comment]
哦不对我傻逼了，是这个问题![image](https://user-images.githubusercontent.com/9006264/137055776-64cf1f70-6643-405e-9ce9-8f6139f9b987.png)

**Comment by Arondight** [comment]
呃，我改一下

**Comment by Mark9804** [comment]
我复现了一下，抽了两把盾锁和一把天空枪
```json
    {
      "userID": 1561382166,
      "choice": 302,
      "indefinite": {
        "five": 1,
        "four": 1
      },
      "character": {
        "five": 69,
        "four": 9,
        "isUp": 1
      },
      "weapon": {
        "five": 2,
        "four": 3,
        "isUp": null
      },
      "path": {
        "course": 0,
        "fate": 3
      }
```

**Comment by Arondight** [comment]
@Mark9804 麻烦再试一下，刚才的定轨不要清零，更新后再抽一个黄，应该就是定轨武器了
