### ISSUE TITLE
您好，请问有将服务端剥离出来的打算吗

### ISSUE THREAD

**Issue by Vang-z** [Arondight/Adachi-BOT#221]
想询问一下各位大佬有将该项目的核心功能剥离出来单独使用 `web server` 托管的打算吗？这样方便直接使用 `api` 请求资源，将项目扩展到不限于 `qq bot` 的地方进行发展（顺带提一句，用 `vue` 写的界面雀食很好看 :) ）

**Comment by Mark9804** [comment]
https://github.com/Arondight/Adachi-BOT/discussions/201

和这个应该重复了

**Comment by Vang-z** [comment]
应该没有和上面的 `issue` 重合, 因为本人是做 `react` 开发的，今天稍微看了一下本项目，以及另一个项目, 发现是基于 `web` 制作的项目，所以好奇为什么不直接做成 `web` 形式的网站模式，反而使用 `qq bot` 限制项目的使用呢？如果做成 `web` 模式的话，可以直接去掉某些库，比如 `oicq`, 如果要使用 `qq bot`，可以转而使用性能更佳的产品做反向代理之类的

**Comment by Vang-z** [comment]
> @Vang-z 我明白你的意思了，你是想做一个 ws 插件出来，个人没有这个想法，我想要的只是一个独立运行的 bot ，不牵扯第二个仓库，我想什么时候 oicq 完蛋了我还没弃坑并且还有精力再考虑这个……

好的，谢谢大佬 :)

**Comment by Mark9804** [comment]
有一定道理，目前项目当中大量图片渲染确实是使用web server跑出来的，bot在这过程中干的也只是处理参数并发送给服务端的活

但是我个人理解的话，这个项目目前来说是**基于QQ的**原神助手，而不是说它首先是一个原神助手，然后加入了QQ bot支持。因果关系来说的话目前的web端是给bot打工的

你的建议不无道理，这个项目最不稳定的因素还是企鹅，所以也许哪天这个框架就给定点爆破了也说不定。不过目前来说，既然oicq目前能够稳定支撑服务，我感觉暂时没有充足的放下其他todo去改动当前架构的理由

**Comment by Vang-z** [comment]
> 有一定道理，目前项目当中大量图片渲染确实是使用web server跑出来的，bot在这过程中干的也只是处理参数并发送给服务端的活
> 
> 但是我个人理解的话，这个项目目前来说是**基于QQ的**原神助手，而不是说它首先是一个原神助手，然后加入了QQ bot支持。因果关系来说的话目前的web端是给bot打工的
> 
> 你的建议不无道理，这个项目最不稳定的因素还是企鹅，所以也许哪天这个框架就给定点爆破了也说不定。不过目前来说，既然oicq目前能够稳定支撑服务，我感觉暂时没有充足的放下其他todo去改动当前架构的理由

嗯嗯，因为最近翻看了很多类似的项目，最后发现本项目算是极为优秀的项目了，所以在看了源码过后才有目前的疑问。
