### ISSUE TITLE
改绑uid或通信证显示成功 结果并没成功

### ISSUE THREAD

**Issue by paiky** [Arondight/Adachi-BOT#223]
快点修理啦
![BZ L7E%$SSIJ67G VVF_F5R](https://user-images.githubusercontent.com/41196775/137297647-b5025540-9476-489f-b640-89ca664dbad6.png)

**Comment by Mark9804** [comment]
![image](https://user-images.githubusercontent.com/9006264/137298295-f94ef44c-adbf-4c64-a6f3-342f0af8e54d.png)
![image](https://user-images.githubusercontent.com/9006264/137298469-a4810db5-7ff1-4783-b99e-bce1d8e78457.png)
改绑功能我这边没问题啊

**Comment by Mark9804** [comment]
米游社ID和游戏内UID是不一样的，请确认一下

**Comment by Arondight** [comment]
> 我知道，我说了显示成功，结果没成功，查角色功能报错。“查询失败，如果您拥有该角色，使用【米游社】或【uid】更新游戏角色后再次查询。” 不信你去nga群里瞧瞧。
> ![BZ L7E%$SSIJ67G VVF_F5R](https://user-images.githubusercontent.com/41196775/137298736-51a5f1aa-ae37-4352-8c22-b11e95ad1d8d.png)

有按照提示使用【米游社】命令更新数据后再次查询吗

**Comment by paiky** [comment]
![image](https://user-images.githubusercontent.com/41196775/137299886-ef8db7b3-df3e-4cd6-a95f-1453bb671ab8.png)
![image](https://user-images.githubusercontent.com/41196775/137299904-bc6506e3-1d54-4c51-995a-64306810ef93.png)
下午那次不行 不过今晚的可以了 所以改绑两次就可以是吗=，=

**Comment by Mark9804** [comment]
> 下午那次不行 不过今晚的可以了

> 默认这个缓存有效时间为一周，缓存时间为一小时

**Comment by paiky** [comment]
搜嘎，好嘞，所以报错就要等1小时了吧
![L311O1}IK33{(VL`VBI8$CK](https://user-images.githubusercontent.com/41196775/137300320-9fdd0de7-77ed-45e4-80ae-0d590b8f15b9.jpg)

**Comment by paiky** [comment]
不过他并没有提示缓存问题噢

> 本着克勤克俭用 cookie 的原则，【我的 角色名】不会请求新数据，因为太过耗费 cookie ，而是使用【米游社】和【uid】的缓存，这个应该在命令输出里都有提示，默认这个缓存有效时间为一周，缓存时间为一小时

**Comment by paiky** [comment]
噢是这样 好吧

**Comment by paiky** [comment]
这个缓存时间一小时 可以理解为一小时内改不了对吧 我下午确实是先绑了uid好像
![](https://user-images.githubusercontent.com/41196775/137300768-f4533999-593c-40cc-bff8-a38c0a4d34cd.jpg)

**Comment by Arondight** [comment]
> 这个缓存时间一小时 可以理解为一小时内改不了对吧 我下午确实是先绑了uid好像
> ![](https://user-images.githubusercontent.com/41196775/137300768-f4533999-593c-40cc-bff8-a38c0a4d34cd.jpg)

麻烦你忘掉缓存这个名字以及你对它的一切理解，查角色先查那张有很多自己角色的图，记得这个就可以了，你可以在任意时间内绑定任意次数（只要你的手够快）

**Comment by paiky** [comment]
我的问题，米友社ID 182打成102，可能这ID不存在查不到 改绑只能绑米友社ID对吧

**Comment by Arondight** [comment]
#227 准备以牺牲 cookie 为代价做了这个功能
