### ISSUE TITLE
[建议]添加 查询他人账号的角色的详情 功能

### ISSUE THREAD

**Issue by citydirector** [Arondight/Adachi-BOT#226]
（这大概需要一条新的命令）

**Comment by citydirector** [comment]
> #227 做完之后，再打开此功能。之后可以查询他人角色，但是 cookie 会变得不经用。

可以在进行 米游社/uid 查询时一次性缓存下来，然后再次查询该账号数据时直接读取缓存

**Comment by citydirector** [comment]
> > #227 做完之后，再打开此功能。之后可以查询他人角色，但是 cookie 会变得不经用。
> 
> 可以在进行 米游社/uid 查询时一次性缓存下来，然后再次查询该账号数据时直接读取缓存

另一个建议是账号缓存默认超过一小时后再查询则更新一次，一小时内使用“米游社/uid/我的”等命令查询时只读取缓存；

**Comment by Arondight** [comment]
这个我现在有点犹豫了，因为按照配置，可能会出现查询别人的角色也拉取数据的情况，我目前的 cookie 根本顶不住，不难想象可能会有人一个 cookie 部了个 bot 上去眨眼用光的情况，我感觉需要考量一下。

**Comment by Arondight** [comment]
```
好友个数：5
群组个数：47
群友个数：4511
```

目前我 13 个  cookie ，查询用户不拉数据，这个数量完全顶得住，拉数据我还没试，但是我感觉能查别人的数据，可能就顶不住了

**Comment by citydirector** [comment]
> ```
> 好友个数：5
> 群组个数：47
> 群友个数：4511
> ```
> 
> 目前我 13 个 cookie ，查询用户不拉数据，这个数量完全顶得住，拉数据我还没试，但是我感觉能查别人的数据，可能就顶不住了

使用“米游社/UID”命令时默认不更新缓存，只有 使用“-更新”参数或者新的命令 时才进行更新，同时启用时间刻（例如默认一小时内不更新）

**Comment by Arondight** [comment]
```
@群友的 阿晴
@群友  的 阿晴
100000001 的 羊
100000001的 羊
我的 77
```

**Comment by Arondight** [comment]
沃日，没处理 qq 昵称里面带空格的情况

**Comment by Mark9804** [comment]
> 沃日，没处理 qq 昵称里面带空格的情况

还有一个问题

如果该群的查询权限是false的话，例如：

```json
db/authority.json
    {
      "userID": 123456789, // 这是一个群号
      "music": false,
      "feedback": false
    },
```
那么执行`@群友 的 阿晴` 会返回

```
TypeError: Cannot read properties of undefined (reading 'sendMessage')
    at sendPrompt (file:///Users/mark_chen/Documents/GitHub.nosync/Adachi-BOT-fork/src/utils/auth.js:4:13)
    at Plugin (file:///Users/mark_chen/Documents/GitHub.nosync/Adachi-BOT-fork/src/plugins/character/index.js:41:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Module.Wrapper (file:///Users/mark_chen/Documents/GitHub.nosync/Adachi-BOT-fork/src/plugins/character/index.js:119:5)
```

@Arondight

**Comment by Arondight** [comment]
应该没问题了
