### ISSUE TITLE
【中长期】解决“深渊的样式明显不一致”问题，ref #229

### ISSUE THREAD

**Issue by mark9804** [Arondight/Adachi-BOT#234]
目前打算全部推翻重写。

因为深渊页面的代码已经很完善了，主要就是如何显示如何排版，即使是完全重写的技术难度对我来说应该也不会非常大，所以就着手做了

作为重写的一个部分，今晚自己糊了一个用来显示深渊星数的字体`Genshin Abyss`，这个这个文字对应的字符是符号`*`。因为只有这一个字，所以字体只有不到一个文件page（4kb）的大小。

字体效果是这样子的
![image](https://user-images.githubusercontent.com/9006264/137637773-ee55f6cb-0271-453a-94bf-9dea32036574.png)

目前的风格打算向米游社靠齐，设计稿我也才新建文件夹，应该会作为一个长期todo了。

![image](https://user-images.githubusercontent.com/9006264/137637829-fa740f63-8a57-4618-b257-bf460f44b9ac.png)

**Comment by Mark9804** [comment]
> 哈哈哈哈哈，这个需要会点 js 的。 vue 其实我大致看得懂，数据怎么流转的基本上知道，照葫芦画瓢也能搞点，不过完全不懂前端

我是卡在组件这里了，理论上这套设计只需要两个组件：
这个
![image](https://user-images.githubusercontent.com/9006264/138098139-c1590ca4-020c-4b7f-9f75-aa5f8079fdc4.png)
还有这个
![image](https://user-images.githubusercontent.com/9006264/138098086-4d370d67-59d8-4b73-bd0a-c7065922ab02.png)

数值可以直接传递给组件，毕竟设想中只有三个变量：
* `image url`
* `rarity`（这个好像是通过`:v-bind`写到网页的`class`里面就可以了，后面的活交给CSS来干）
* 数据显示

理论上是这样的，现实是看不懂组件的组成，完全不会写

**Comment by Arondight** [comment]
> 角色图片和背景之间有一个凯尔特三角

啊这，我们公司的设计都没你这么专业，我感觉你毕业甚至可以搞搞这些

**Comment by Mark9804** [comment]
感谢，那 #229 的问题看来就只能通过加粗来解决了，但霞鹜mono就这一个字重，我再考虑一下换成非等宽版本的效果如何
