### ISSUE TITLE
希望添加更直观的本地调试功能

### ISSUE THREAD

**Issue by AzusaYukina** [Arondight/Adachi-BOT#236]
反复登录调试新功能很容易被腾讯判定为机器人账号，希望可以添加更简单直观的本地调试的方法。
比如通过本地端口向 bot 直接发送本地消息并且在控制台查看返回。（不过似乎需要建立一个文件夹来看返回图片）

**Comment by Arondight** [comment]
随手记一下想法。

1. 现在已经有一个前端调试选项了，本地调试应该单独做一个选项，配合前端调试完成图片显示
2. 本地调试应该能够创建一个模拟事件的客户端，并且重新实现 oicq 客户端中我们使用的方法
3. 使用单独的脚本模拟 QQ 发送消息，`npm run debug -- --group-message "roll 50"`、`npm run debug -- --online`，差不多是这个感觉

**Comment by Arondight** [comment]
这个功能至少需要在跟进 oicq 2.x 之后开始做才合适，因为 oicq 的数据结构有了改动， api 也有变更

**Comment by Mark9804** [comment]
关于这个我觉得可以以 master 插件的形式整一个沙箱，把特定符号开头的字符串消息作为代码块处理

<img width="211" alt="image" src="https://user-images.githubusercontent.com/9006264/152905106-286c6c00-1a3b-4438-9cdd-0fcce254df07.png">

**Comment by Arondight** [comment]
这个代码解释没啥用，以前我加过然后又删了，楼主的意思是可以抛开 oicq 运行插件、我觉得也有点必要不过实在懒得搞

**Comment by Mark9804** [comment]
原来是被去掉了吗，臭 bug 人还挺想要这两个功能二选一的
<img width="120" alt="image" src="https://user-images.githubusercontent.com/9006264/152908089-b8734a7f-fa82-45b3-8a3e-e89ee576bed3.png">

**Comment by Arondight** [comment]
这功能直接用api就可以了 https://github.com/glotcode/glot/blob/master/api_docs/run/run.md

**Comment by Arondight** [comment]
去掉的原因是没用+刷屏

**Comment by Mark9804** [comment]
主要是数据库操作的功能只能在 bot 环境做，比如我想整一个你今天已经清醒了多久的功能，现在就只能写一点然后重启试试，没 bug 再写一点

**Comment by Arondight** [comment]
> 主要是数据库操作的功能只能在 bot 环境做，比如我想整一个你今天已经清醒了多久的功能，现在就只能写一点然后重启试试，没 bug 再写一点

是这样的，所以理想的情况是 bot 有一个 debug 模式不再依赖于丘丘，而不是本地执行不明来路的代码

**Comment by Arondight** [comment]
这个我想也不会做了
