### ISSUE TITLE
切换历史卡池功能（自定义卡池）

### ISSUE THREAD

**Issue by KaguraSayuki** [Arondight/Adachi-BOT#250]
如题，在不少用户群中反馈得知希望可以使用历史卡池抽卡。尽管已经自行添加，但仍然希望这个项目之后能提供历史卡池。

**Comment by Arondight** [comment]
都一万个池子了，切换卡池是不可能了，打算以后加个自定义卡池，配套的有一个 yaml 配置文件，短期内不打算加

**Comment by AzusaYukina** [comment]
自定义也是个不错的解决方法，现在的改起来还是不那么方便。感谢回复。

**Comment by Arondight** [comment]
我觉得完全搞卡池复刻没啥必要，不是喜欢抽没 up 的角色爽一下么，那就应该随便抽，每一抽都出金，一个十连七个七七，完全搞一个抽卡概率都一样的我感觉没啥意义的……

**Comment by AzusaYukina** [comment]
就我个人使用和开发 bot 的情况来看，这样的事情就交给 Master 们去考虑吧，开发者提供一个接口和示范文件就足矣。

**Comment by Arondight** [comment]
> 开发者提供一个接口和示范文件就足矣。

新建文件夹了
