### ISSUE TITLE
打不满深境时新样式会出现留白和顺序错位

### ISSUE THREAD

**Issue by Xm798** [Arondight/Adachi-BOT#264]
问题：深境新样式对于没打满渊月螺旋9-12层的用户会出现大面积留白，对比度过高，非常不美观。且顺序也比较容易使人误解(指10层出现在了12层的位置)。如下图所示
![IMG_20211023_014004.png](https://i.loli.net/2021/10/23/HskBP5aK238bQDZ.png)
建议：即使没打的层数，依然保留卡片，只不过信息为空(或者显示未挑战的提示），避免出现大量刺眼的留白。且顺序应当依次出现。

@Mark9804

**Comment by Mark9804** [comment]
在修了在修了.jpg

深渊数据的读取结构偷懒用的原来的，现在重新写需要一点时间，应该能写出来吧，应该能
