### ISSUE TITLE
关于圣遗物评分算法

### ISSUE THREAD

**Issue by Xm798** [Arondight/Adachi-BOT#274]
好奇当前圣遗物评分调用的是API还是本地算法，感觉略有些不合理。（虽然确实是仅供娱乐罢了

![image](https://user-images.githubusercontent.com/48074861/138544204-f29ce5fa-2cad-47f4-ac03-c33d9ef22e63.png)

**Comment by Mark9804** [comment]
我在我自己的仓库开了一个圣遗物评分bug汇总（ https://github.com/Mark9804/Adachi-BOT/issues/22 ），这样我可以一边收集数据并且其他人也不会持续收到邮件轰炸，也欢迎补充。其实基本上都是强化等级没有正确识别的问题

我用来输出强化等级的代码commit在https://github.com/Mark9804/Adachi-BOT/commit/51b191e82dbedd74ec7e8a1758d1ffaf3be63584 ， https://github.com/Mark9804/Adachi-BOT/blob/51b191e82dbedd74ec7e8a1758d1ffaf3be63584/src/plugins/rating/index.js#L179-L180

**Comment by Arondight** [comment]
现在评分插件经过两次改良之后，除非是圣遗物 ocr 出问题，否则都能返回一个较为合理的评分了。

目前的问题就是有些特定套装的属性权重太低，例如风套的元素精通，例如魔女套的大生命，我在想与其做一个评分算法出来，不如做一个评分的二次修正，当遇到这些特定套装时，根据某些特殊词条把 API 返回的评分修饰一下。

做评分算法实际上和这种修饰是等级的，因为如果可莉特调跑路了，我们手里只会有一个做不了任何事情的算法。

**Comment by Mark9804** [comment]
有一个比较新的计算单个圣遗物词条的项目
https://github.com/tseflcz/artifact-calculator

**Comment by Arondight** [comment]
Duplicate of #732

**Comment by Arondight** [comment]
算分数的继续用 api 好了，真的怎么算都不合适

**Comment by Arondight** [comment]
这个 issue 关掉了，仅做存档用，有些许可能以后会照着其中的链接抄一个（看上去还算合理）的评分
