### ISSUE TITLE
关于体力、委托和探索派遣功能...

### ISSUE THREAD

**Issue by citydirector** [Arondight/Adachi-BOT#300]
最近发现米游社上线了可以查看这三个数值的功能，有无考虑添加查看和消息提醒功能？

消息提醒是指比如体力满了或者派遣满了进行提醒，可以用定时查询或者缓存&本地计算时间实现

**Comment by ID114514** [comment]
> 你有需要的话可以直接合入 #301 ，一个老大哥帮忙做的。
> 
> https://patch-diff.githubusercontent.com/raw/Arondight/Adachi-BOT/pull/301.patch

这个项目好像有点问题，合入后查询直接报错
