### ISSUE TITLE
ExperimentalWarning: stream/web is an experimental feature

### ISSUE THREAD

**Issue by Xm798** [Arondight/Adachi-BOT#311]
`2|bot  | (node:3301) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
2|bot  | (Use `node --trace-warnings ...` to show where the warning was created)`

查看日志发现最近bot经常因为以上错误异常退出

**Comment by Arondight** [comment]
作者自己的 pr 已经合入了，看起来坐等一个新版本就可以了
