### ISSUE TITLE
加入自动撤回功能

### ISSUE THREAD

**Issue by Alpiiine** [Arondight/Adachi-BOT#312]
场景：
多次使用抽卡 / 查询等功能后，聊天记录全是抽卡 / 查询图片。

需求：
加入自动撤回功能，可以设置xx分钟后自动撤回机器人发言以及相对应的命令。
该功能需要将机器人设置为群内管理员才可用

**Comment by Arondight** [comment]
最迟这周末可以做完，这段时间工作日估计没精力了，又到了领导刷 kpi 的季节

**Comment by Mark9804** [comment]
我跟几个群管理讨论了一下，觉得应该允许某些消息不被撤回，比如说：

* 抽了七次十连出了个77，那么前六次的十连消息可以撤回，出金消息保留下来；
* 查询人物或角色没有命中的消息可以撤回，命中并且返回图片的消息可以保留下来；
* 深渊没有查询到信息（无渊月螺旋记录）的消息可以撤回，返回图片的消息可以保留下来

**Comment by Arondight** [comment]
> 应该允许某些消息不被撤回

这个当前做不到，会让消息机制复杂很多

**Comment by Sucharles** [comment]
> 我跟几个群管理讨论了一下，觉得应该允许某些消息不被撤回，比如说：
> 
> * 抽了七次十连出了个77，那么前六次的十连消息可以撤回，出金消息保留下来；
> * 查询人物或角色没有命中的消息可以撤回，命中并且返回图片的消息可以保留下来；
> * 深渊没有查询到信息（无渊月螺旋记录）的消息可以撤回，返回图片的消息可以保留下来

这个逻辑有点复杂 工作量 好大  其实主要就是十连和圣遗物这两个  刷起屏来要命

**Comment by Sucharles** [comment]
其实  最近我有个想法  也可以说一直有这么个想法  就是与其做自动撤回  不如将娱乐功能积分制，结合原神背景，可以做两种虚拟积分，1.原石2.树脂，群员通过完成虚拟的每日任务或直接签到的形式给予原石奖励，原石奖励多少设置为参数可调，十连功能与其联动，使用十连命令消耗账户内相应的原石积分，原石不足则不响应或提示原石不足，树脂设置为自动回复，可与游戏保持一致8分钟回复1点，圣遗物命令需要消耗20树脂，这样做可以达到限制使用这两个娱乐功能的目的，不会造成大量的刷屏，因为受到积分的制约；但是  制作这个功能  可能就不能继续用现在的这个数据库了，而且工作量也会不小，但是就当一个设想提出吧。

**Comment by Arondight** [comment]
@Sucharles 你说的这个我觉得很简单，积分制无非多加俩函数，内存维持几个 object ，每个功能执行前做一次验证就行。但是分情况撤回真的很难做

**Comment by Sucharles** [comment]
> @Sucharles 你说的这个我觉得很简单，积分制无非多加俩函数，内存维持几个 object ，每个功能执行前做一次验证就行。但是分情况撤回真的很难做

∩_∩，那开坑吗？

**Comment by Arondight** [comment]
> ∩_∩，那开坑吗？

不开，我不太想做这种限制，我觉得刷屏挺好的，关于你的那个需求我觉得只要在内存维持一个时间戳就好 `[{qq, time, command }]`，大约这个样子，检查函数只好算一下时间差就可以

**Comment by Sucharles** [comment]
23333 找个类似的先去学习下 可以的话做成插件

**Comment by Mark9804** [comment]
积分制我本来有这个构想，后来觉得和数据库交互太麻烦了就没提出来

分情况撤回我本想的是把撤回模组独立出来，当某条消息需要撤回的flag为真时才进行工作，可能我想的太简单了，实际上要大改才能实现这个功能，那就算了

例如
```
bot.sendMessage("无渊月螺旋记录", withdraw=true);
```

**Comment by Arondight** [comment]
> 23333 找个类似的先去学习下 可以的话做成插件

我想没办法做成插件，做几个接口比较合适

**Comment by Arondight** [comment]
> 积分制我本来有这个构想，后来觉得和数据库交互太麻烦了就没提出来

我想不需要和数据库交互，例如一次性最多用五次，用完之后没分钟回复一下次数，这个需求简单的在内存维持数据结构即可

**Comment by Sucharles** [comment]
> > 积分制我本来有这个构想，后来觉得和数据库交互太麻烦了就没提出来
> 
> 我想不需要和数据库交互，例如一次性最多用五次，用完之后没分钟回复一下次数，这个需求简单的在内存维持数据结构即可

这个逻辑nice

**Comment by Arondight** [comment]
> 这个逻辑nice

这个需求本身是很简单的，复杂的是变量的控制，我要设置多长时间合适呢，某个时间对某些人合适，对另一些又不合适，或者 bot 加入一个简单的频率判断动态调整这个逻辑，我又不会写，所以我觉得刷屏挺好，做不好限制不如不做限制

**Comment by Sucharles** [comment]
> > 这个逻辑nice
> 
> 这个需求本身是很简单的，复杂的是变量的控制，我要设置多长时间合适呢，某个时间对某些人合适，对另一些又不合适，或者 bot 加入一个简单的频率判断动态调整这个逻辑，我又不会写，所以我觉得刷屏挺好，做不好限制不如不做限制

这个我觉得不用过多顾虑，设置了规则，就都接受规则，所有人都是在一个规则下，不接受规则就不使用这个命令。

**Comment by Arondight** [comment]
> 设置了规则，就都接受规则，所有人都是在一个规则下，不接受规则就不使用这个命令

我觉得这是不好的，我的逻辑倾向于我不知道该给你什么，那就全给你，而不是给一些我觉得你需要的东西，或者什么都不给

**Comment by Sucharles** [comment]
> > 设置了规则，就都接受规则，所有人都是在一个规则下，不接受规则就不使用这个命令
> 
> 我觉得这是不好的，我的逻辑倾向于我不知道该给你什么，那就全给你，而不是给一些我觉得你需要的东西，或者什么都不给

主要也是无奈啦  众口难调 一刀切规则大都是出于无奈，另外，新简易撤回机制实测好像不生效

**Comment by Arondight** [comment]
> 新简易撤回机制实测好像不生效

我这里几个号都没问题， bot 需要是管理员，因为非管理只能撤回 30 秒，图还没看清楚就没了

**Comment by Arondight** [comment]
> 撤回 30 秒

好吧，原来是两分钟，那可以把非管理做了，两分钟后再做管理校验
