### ISSUE TITLE
查询游戏数据的时候显示米游社接口报错：

### ISSUE THREAD

**Issue by FengLing11** [Arondight/Adachi-BOT#318]
![CMVJI~}Q OTIY8RTGJJA1J9](https://user-images.githubusercontent.com/92540917/139380211-4f8315ff-ef72-4a81-bbca-5b02642f3e63.png)

有些UID可以查有些查不了

**Comment by Arondight** [comment]
> 
> 
> @FengLing11 你没有登录过米游社是怎么拿到 cookie 的

虽然我还没有理解这个过程，不过还是把这种 cookie 判定为无效 cookie 了

**Comment by Mark9804** [comment]
> 没有登录过米游社是怎么拿到 cookie 的

可能意思是“过于干净的账号（不仅实名制信息，连米游社用户名都没有填写）”？

**Comment by FengLing11** [comment]
之前登录进去同意了个协议，像这样的
![F2A32$6%RW`X}{I62) V~KC](https://user-images.githubusercontent.com/92540917/139579120-8a77fbaa-a1ff-44ac-8ee1-9a70e858968b.png)
