### ISSUE TITLE
你好，请问为什么我每次更新BOT后，我的setting和cookie里边的内容就全部被重置了

### ISSUE THREAD

**Issue by avadiana** [Arondight/Adachi-BOT#32]
除了setting和cookie的内容，绑定的米游社信息也全部消失了，要重新绑定，请问下是什么原因呢

**Comment by Arondight** [comment]
是按照[说明](https://github.com/Arondight/Adachi-BOT#%E6%9B%B4%E6%96%B0)更新的吗？

**Comment by avadiana** [comment]
是的，按照大佬您文档里的那个更新命令进行更新的

**Comment by Arondight** [comment]
`git stash list` 看一哈

**Comment by Arondight** [comment]
如果有问题请reopen
