### ISSUE TITLE
如果 fetch 工作了很久，那么或许整个页面加载完数据都不会被读入

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#329]
归根结底， fetch 是一个异步方法，既然有了一个异步方法，那么就永远无法保证其顺序，如果 fetch 工作了很久，那么或许整个页面加载完数据都不会被读入

_Originally posted by @Arondight in https://github.com/Arondight/Adachi-BOT/discussions/328#discussioncomment-1566220_

**Comment by Arondight** [comment]
下面的数据在 `computed` 中不能保证是已经读取完成的，目前读一个文件出问题的概率很低，多加一个文件就会大概率出现数据 undefined 。

https://github.com/Arondight/Adachi-BOT/blob/3778a4bf405ed11b18a66e3a16e784eaa0f0e3c8/src/views/genshin-artifact.html#L105-L120

**Comment by Arondight** [comment]
我在想这个问题有可能是无法解决的，因为 vue 的 hook 有可能就不能保证顺序执行，看样子好像是某个阶段启动某个 hook ，没说会等上一阶段的执行完毕

**Comment by Arondight** [comment]
> 这个问题有可能是无法解决的

我在想是不是这个项目的使用方式有问题，我感觉我得学学 vue 🤨

**Comment by Mark9804** [comment]
这个项目的vue的部分确实挺不成熟的，感觉我们几个人里面最能写的是 @490720818 这个老大哥

**Comment by Arondight** [comment]
我泠帮忙看看这问题咋处理呀 @impasse

**Comment by Arondight** [comment]
问了几个老大哥，似乎 vue 在 v-bind 读到数据后（无论是不是 undefined ），当 mounted 中函数工作完成后，v-bind 会再次读入数据。

**但是**当前 fetch 是异步的，所以函数执行完毕时数据读取极大概率尚未完成，再次刷新时可能仍然会读到 undefined （或者其他初始化的数据而非 json 中的数据）

**Comment by Arondight** [comment]
@Mark9804 @490720818 我注意到 @SilveryStar 可能为了避免这个问题，不再使用文件给浏览器传递数据，而是直接把数据写到了 url 的参数中，我感觉我们也可以学的这么做。

https://github.com/SilveryStar/Adachi-BOT/blob/aeebf063a5234bf74bc345cbe425f9d502444abb/src/plugins/genshin/utils/render.ts#L40

**Comment by Mark9804** [comment]
[url最长有2048字符数的限制](https://stackoverflow.com/a/417184)，能塞得下就行

不过假设我们总是有一个氪佬用户氪了全图鉴，那`米游社`的参数之后会越来越长……

**Comment by Arondight** [comment]
@Mark9804 就是说现代浏览器支持超长 url 吗

**Comment by Mark9804** [comment]
> @Mark9804 就是说现代浏览器支持超长 url 吗

理论上是这样，不过Chrome具体能多长我没测试过，或者也有可能现在用的server不支持这么长的url，当前项目用的什么server我还没看过。

超长url是一个木桶，对长url支持最差的一个节点决定这个url能多长。比如chrome支持上万字符，当前的localhost只支持到2048字符还是一样不行的，会返回414 too long

**Comment by Arondight** [comment]
@Mark9804 node 本身应该不会出现问题，因为他们[添加了参数](https://github.com/nodejs/node/issues/24692) `--max-http-header-size` ，我想即使没有参数默认 `8 * 1024` 8KiB 也是够用的

**Comment by Arondight** [comment]
我想下周就做这件事情，现在使用缓存的逻辑本来就很奇怪，这件事情一下解决了两个问题。

**Comment by Arondight** [comment]
> 现在使用缓存的逻辑本来就很奇怪，这件事情一下解决了两个问题

肝了一天，现在代码终于正常一点了，只需把这个缓存逻辑改的正常一点，这个项目就终于有望看上去正常一些了。

**Comment by Arondight** [comment]
@Mark9804 你知道通过 url 数据后中文乱码是为啥么

![图片](https://user-images.githubusercontent.com/13673702/141609454-601c4b7c-747a-43f8-a433-d32eb92e05a4.png)

浏览器看也是乱码

![图片](https://user-images.githubusercontent.com/13673702/141609487-251aed58-76ac-49c9-852d-c536cd6685e6.png)

**Comment by Arondight** [comment]
后端： object -> string -> base64 -> object -> urlencode
前端： object -> base64d -> string -> object
我不知道浏览器是不是自动 url 解码的

**Comment by Mark9804** [comment]
经典前端问题，charset不一样，但是我已经指定了编码是`UTF-8`了呀，那很大可能传过来的数据编码不是utf-8

https://github.com/Arondight/Adachi-BOT/blob/c57c72ed72f4f14a9b56a0922a1204b9bbd58425/src/views/genshin-character.html#L4

**Comment by Arondight** [comment]
> 经典前端问题

查了下是浏览器的 atob 函数不支持 utf ，我看看咋搞

**Comment by Mark9804** [comment]
简单粗暴的解决方法是：只要知道传过去的是什么编码，我们在前端声明编码格式就可以了

这个meta标签如果要写完整的话是
```html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
```
其中charset可以是gbk，也可以是其他什么编码

**Comment by Arondight** [comment]
![图片](https://user-images.githubusercontent.com/13673702/141610298-37665081-6818-4cfa-b491-5035e71f7b41.png)

啊这，我搞定了

**Comment by Mark9804** [comment]
> 啊这，我搞定了

牛皮

**Comment by Arondight** [comment]
@Mark9804 因为现在所有的数据都通过 URL 传入，你原来的方法调试起来是有困难的，所以配置文件增加了参数 `viewDebug` ，调试的时候设置为 1 即可。

https://github.com/Arondight/Adachi-BOT/blob/c9ae0bcf4445acc1d5586b865f1a5ca253063b90/config_defaults/setting.yml#L106-L110
