### ISSUE TITLE
深渊时间记录表述带有误导性

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#331]
每层的开始时间甚至都远早于 9-1 的开始时间。

![图片](https://user-images.githubusercontent.com/13673702/139699095-5620a9d1-01d8-457c-b930-c75dcfaf8e4b.png)

**Comment by Arondight** [comment]
哦，原来上面的是日期，格式跟时间一模一样，我以为一个开始一个结束呢

**Comment by Arondight** [comment]
或许格式清楚一点比较好？例如 `2021-11-01 23:34:45` 这种

**Comment by Mark9804** [comment]
这个我思考过，是故意这么写的，因为
```
21.11.01
23:33:33
```
这两段文字的长度一样，比较美观一些

不过这么一说，确实有造成误导的可能性，日期使用斜杠分割或者短横线分割会好一些

**Comment by Mark9804** [comment]
借这个机会我重新微调一下深渊的排版
