### ISSUE TITLE
使用指令 我的 <> 问题

### ISSUE THREAD

**Issue by FengLing11** [Arondight/Adachi-BOT#335]
![7IM@VRK6ZM``9@D8NH%4KSR](https://user-images.githubusercontent.com/92540917/139797816-2d9efca7-193f-49a9-8595-ff903425cfe4.png)
这号没甘雨
是BUG吗。

**Comment by Arondight** [comment]
这个提示要改一改的

**Comment by Arondight** [comment]
得想办法做个字符串拆分，字符串不是别名或者本名是根据切分的数组进行匹配

**Comment by Arondight** [comment]
![23FC63D9-B1AB-4811-BD3B-A73A13EEFE53](https://user-images.githubusercontent.com/13673702/140009410-7a1967e0-6d87-41c6-9a18-1bf244001c71.png)

**Comment by Arondight** [comment]
看上去还行

![CF890922-B574-4F56-9CA7-64D6560307AC](https://user-images.githubusercontent.com/13673702/140009915-ae3278c9-f37f-459f-86fe-00b7c3547a8e.jpeg)

**Comment by Arondight** [comment]
![315A2A4E-B517-4F17-9BEC-EA8D9F7F2A39](https://user-images.githubusercontent.com/13673702/140010089-0b7192e3-a94d-46fd-89fb-6eeedd5e8951.jpeg)

**Comment by Arondight** [comment]
![9556ABC5-ADCA-4BB7-A827-543D955F60F0](https://user-images.githubusercontent.com/13673702/140020529-70ac14d8-43f1-4fbb-93f2-f8162816c77d.jpeg)
