### ISSUE TITLE
card插件：如果缓存中写入了错误的数据，则会读取错误数据缓存并展示

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#336]
# 预期的结果
`card`插件检测到用户对应缓存无效时，强制拉取新数据并覆盖无效缓存数据
# 实际结果
`info.json`：
![image](https://user-images.githubusercontent.com/9006264/139869379-d6e41efd-80f0-4811-8170-1638dbdb8d9c.png)
用户重复`米游社`指令，则调取该错误缓存，并返回：
![image](https://user-images.githubusercontent.com/9006264/139869531-251eb1d4-be57-4feb-9d0b-06e0f3a4523e.png)

**Comment by Arondight** [comment]
划水十分钟改了一下，应该可以了，这问题的改动很小
