### ISSUE TITLE
overview：潜在的元素overflow问题

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#340]
问题不大，暂时没有要立刻解决的必要

雷电将军的命座描述异常的长，有溢出页面的风险，要是之后出一个命座效果描述更长的角色就真要溢出去了

在维持现有视觉元素的前提下重写，背景图片比较复杂，要么把现在的背景图切开来实现自适应，要么直接[生成重复的SVG背景](https://stackoverflow.com/a/56311038)，不用jpg图片了

![image](https://user-images.githubusercontent.com/9006264/140071564-a6c4c2dd-8d05-44a2-b18a-720d4b53776b.png)

**Comment by FengLing11** [comment]
雾切之回光直接就溢出了

**Comment by FengLing11** [comment]
类似的还有终末嗟叹之诗，松籁想起之时

**Comment by Mark9804** [comment]
这几个都没有雷军这么厉害
![image](https://user-images.githubusercontent.com/9006264/140092402-7082b361-c2fb-47ab-96c9-b6b92b458548.png)

**Comment by FengLing11** [comment]
我和你查的不太一样啊。

**Comment by Mark9804** [comment]
> 我和你查的不太一样啊。

麻烦贴一下图我看看

**Comment by FengLing11** [comment]
![63929d15977c855795fb317a49cd78a0](https://user-images.githubusercontent.com/92540917/140104773-9c3a97e2-41fa-416f-9ce2-44416c3aaaf7.jpg
![d8f926240551f7fe3061c019d1804200](https://user-images.githubusercontent.com/92540917/140105020-a432e378-99ad-4d62-ae4f-629ae9f51286.jpg)
)
![f7f2df7d17bc6947e611cba0ca575147](https://user-images.githubusercontent.com/92540917/140105029-8e895268-6faa-4fb8-8533-0bda050dedc9.jpg)

**Comment by Mark9804** [comment]
麻烦贴一下`git log -1`的内容，这样可以看一下你的代码是不是最新的。

另外可以详细说明一下你的bot运行环境吗，是Windows系统还是Linux系统（是哪个分支），使用的浏览器是默认的chromium吗（如果按照readme安装的话默认就是chromium）

**Comment by Mark9804** [comment]
@Arondight 的 bot 上面有这个问题吗，就是`信息 雾切`的显示不正常，我和上面那个老大哥的图不太一样，想看看你那边显示出来是什么样的

**Comment by Arondight** [comment]
![78411DBF-0250-4C64-9FD1-9AAE8CF3ABCD](https://user-images.githubusercontent.com/13673702/140225574-b3e93795-b1c4-471b-b046-9ba415d8d444.jpeg)

**Comment by davidelectricfree** [comment]
> @Arondight 的 bot 上面有这个问题吗，就是`信息 雾切`的显示不正常，我和上面那个老大哥的图不太一样，想看看你那边显示出来是什么样的
> 
> 追加编辑：在我的Firefox，Chrome，Safari和chromium上都没复现

我的图和上面那个人的一样的，最新的代码，只不过可能是windows系统。

**Comment by FengLing11** [comment]
$ git log -1
commit 22d78b8993be4c5a9130d28196f78eeba0d974cb (HEAD -> master, origin/master, origin/dev, origin/HEAD)
Author: Qin Fandong <shell_way@foxmail.com>
Date:   Wed Nov 3 20:10:50 2021 +0800

    文档更清晰一些

$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

$ node -v
v17.0.1

$ npm -v
8.1.0

系统Windows 11
使用的默认的chromium

**Comment by Mark9804** [comment]
@davidelectricfree 你的运行环境是什么样的，也是 Windows + 默认的Chromium吗？

**Comment by Mark9804** [comment]
我今晚回家才有合适的Windows环境用，晚上我看看是不是在Windows下浏览器的字体渲染行为不太一样

**Comment by davidelectricfree** [comment]
> 
> 
> @davidelectricfree 你的运行环境是什么样的，也是 Windows + 默认的Chromium吗？

对，windows server 2016

**Comment by Mark9804** [comment]
那可能就是Windows环境下浏览器字体渲染行为和Linux不一样，晚上我确认之后看看怎么解决

**Comment by FengLing11** [comment]
我用CentOS开就是你那样的了

**Comment by Mark9804** [comment]
![image](https://user-images.githubusercontent.com/9006264/140260759-73893c31-2211-4fdf-a8ad-474cc0be110d.png)

我的Windows环境也没能复现这个问题，暂时先不做临时性的修复了，后面直接重写

**Comment by Arondight** [comment]
Duplicate of #343

**Comment by Mark9804** [comment]
#340 移动至 #515
