### ISSUE TITLE
您好，角色指令以及十连图片里无角色是什么情况呢？

### ISSUE THREAD

**Issue by paiky** [Arondight/Adachi-BOT#341]
不知是不是cookie问题，但uid指令是好的。对了，更换cookie时是直接重启机器人就好吗，还是得初始化一遍呢，我都做了，角色指令还是显示“查询失败，未知的名称【】“
日志好像并无特殊的显示情况
```linux
recv from: [Group: Mac(127689237), Member: 无憾(2859431743)] 角色 七七
```

（关于昨天不成功的情况，我今天删除项目重新部署，现在随时启动都有成功回复了 😃 ）

**Comment by paiky** [comment]
角色指令比如输入"角色 公子" 是直接返回"查询失败，未知的名称公子" , 而输入 "十连" 是显示图片 但图片里没有角色武器

**Comment by Mark9804** [comment]
`角色`命令不会调用cookie相关的内容，和cookie没有关系

> 更换cookie时是直接重启机器人就好吗，还是得初始化一遍呢

更换cookie之后把`data/db`文件夹下面的`cookies.json`删掉，然后`npm run restart`。这个操作约等于`git checkout ./data/db/cookies.json`，哪一个能成功就用哪个

> "十连" 是显示图片 但图片里没有角色武器

想看一下是什么样的，是不是所有的图都显示error

感觉你这个是git仓库缺了文件。你检查一下bot仓库当中`resources/Version2/wish/character`和`resources/Version2/wish/weapon`这两个文件夹里面有没有东西，这两个文件夹是和抽卡插件相关的

我今天在学校，摸不了鱼，Arondight最近在给老板冲kpi，不知道他今天会不会有时间帮你远程看看

最后能说明一下你的运行环境吗，我现在只知道你的系统是CentOS，是服务器（国内还是国外的）还是在本地系统跑的虚拟机不太清楚。我现在在想有没有两次git仓库都没有clone完全的可能性

**Comment by paiky** [comment]
我是线上的腾讯云服务器，用的centos，因为今天早上直接git clone发现没动静，可能卡住也可能两百多M比较久，于是我本地git clone，然后xftp传输到服务器，不过好像没有.git文件夹了。刚才检查了一遍Version2两个文件夹里的图片都还在，十连没显示的情况确实是都显示error
感谢你的回复 😄

**Comment by Arondight** [comment]
`git status` 检查一下仓库完整性，然后 `git log -1` 检查仓库是否过旧

**Comment by paiky** [comment]
```linux
[root@VM-4-12-centos Adachi-BOT]# git log -1
commit 22d78b8993be4c5a9130d28196f78eeba0d974cb
Author: Qin Fandong <shell_way@foxmail.com>
Date:   Wed Nov 3 20:10:50 2021 +0800

    文档更清晰一些

```

**Comment by paiky** [comment]
下午重新又部署一次，这下可以了，这次没执行startup命令，也不敢执行了，怕有什么隐藏问题 😢

**Comment by Arondight** [comment]
> 也不敢执行了，怕有什么隐藏问题

Linux 下应该不会有什么问题
