### ISSUE TITLE
Todo：overview页面使用响应式布局

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#343]
ref #340 

我还真没想好这能怎么解决，给Windows另外写一套css吗……
![-62314b3c16763828.jpg](https://user-images.githubusercontent.com/36690822/140233667-890463b1-8195-4fab-a065-2b36c20d9a8a.jpg)

**Comment by Arondight** [comment]
我觉得可以不解决，我个人没有意向非得支持 windows

**Comment by Arondight** [comment]
我已经在[文档](https://github.com/Arondight/Adachi-BOT/tree/22d78b8993be4c5a9130d28196f78eeba0d974cb#%E9%83%A8%E7%BD%B2)中写的很明白了，我感觉不必费力去做这个，我们既然有了声明，那么 windows 有异常也是清理之中的事情。

**Comment by Mark9804** [comment]
那这个就留到后面处理吧，不过至少证明溢出问题确实是存在的，大规模出现只是时间问题，比如米忽悠真的写了一篇阅读理解，大家一起裂开

**Comment by Arondight** [comment]
> 写了一篇阅读理解，大家一起裂开

怎么可能，我们完全是自己维护的数据，又没拉官方接口，阅读理解再长我们可以总结呀，就算非常长到了几千字，我们也可以只写两个字`很强`

**Comment by Mark9804** [comment]
很强，这个我喜欢

**Comment by Mark9804** [comment]
#343 移动至 #515
