### ISSUE TITLE
图片过期

### ISSUE THREAD

**Issue by davidelectricfree** [Arondight/Adachi-BOT#352]
碰到有的图片过期（深渊图片），然后重复指令也是直接调用缓存，发出来的同样是过期图片

**Comment by Arondight** [comment]
贴个图

**Comment by davidelectricfree** [comment]
![Screenshot_20211104-193232.jpg](https://user-images.githubusercontent.com/36690822/140306492-12c75b1b-75f9-404b-9fc3-11be0ed01511.jpg)

**Comment by Arondight** [comment]
这问题我还真没见过……只有这个人的是这样，还是说所有的深渊数据都是这样，是不是网络的问题？

**Comment by davidelectricfree** [comment]
![Screenshot_20211104-193410.jpg](https://user-images.githubusercontent.com/36690822/140307085-46a8edd9-5fdd-4bb1-b26c-9edcbd59ecf9.jpg)

**Comment by Arondight** [comment]
看上去只是网络原因啊，浏览器不可能给你渲染一个感叹号出来，你在查询一个感叹号之后，执行一下命令 `cat data/record/genshin-aby.json` ，贴一下

**Comment by davidelectricfree** [comment]
> 这问题我还真没见过……只有这个人的是这样，还是说所有的深渊数据都是这样，是不是网络的问题？

上期深渊 100357661
好像我自己的没问题，你可以试试

**Comment by Arondight** [comment]
> 上期深渊 100357661

一切正常

**Comment by davidelectricfree** [comment]
> 看上去只是网络原因啊，浏览器不可能给你渲染一个感叹号出来，你在查询一个感叹号之后，执行一下命令 `cat data/record/genshin-aby.json` ，贴一下
> 

我确实看到json里面有文件，那这种情况是什么引起的呢？腾讯云的服务器网络应该没问题啊。。。

**Comment by Arondight** [comment]
> 这种情况是什么引起的呢？

我也比较好奇，但是不太好猜测

**Comment by davidelectricfree** [comment]
> > 这种情况是什么引起的呢？
> 
> 我也比较好奇，但是不太好猜测

算了，那你看后续有没有其他人遇到吧

**Comment by Mark9804** [comment]
是客户端为watch产生的问题吗，什么时候开始的

**Comment by davidelectricfree** [comment]
> 是客户端为watch产生的问题吗，什么时候开始的

少概率能遇到，目前就这一个，今天晚上遇到的，到目前为止都查不到这个id的上期深渊，本期能查得到。

**Comment by Mark9804** [comment]
我这边也正常，复现不出来

**Comment by davidelectricfree** [comment]
> 我这边也正常，复现不出来

我估计等缓存重新上传图片看应该能看到，猜是不是缓存上传出了一点问题，对了，我这边显示的是图片已过期，emmmmmm
