### ISSUE TITLE
您好，请问查询角色信息时报错功能绘图失败的原因是？

### ISSUE THREAD

**Issue by LuoshuiTianyi** [Arondight/Adachi-BOT#354]

**Comment by Arondight** [comment]
贴日志或者截图，我猜可能是你没有提供一个可运行的无头浏览器

**Comment by LuoshuiTianyi** [comment]
截图如下
![image](https://user-images.githubusercontent.com/32975657/140317625-17d0dc57-01d6-4fb1-959f-4b83b75b46b1.png)
但是现在又可以了。

事实上我是直接使用了windows下的chrome，也许因此存在了一些问题？

**Comment by Arondight** [comment]
看上去是机器内存太小了

**Comment by Arondight** [comment]
> 事实上我是直接使用了windows下的chrome

我确认一下你没有在 Linux 下使用 Windows 的 chrome 吧

**Comment by LuoshuiTianyi** [comment]
这应该不至于，我并非使用虚拟机部署

**Comment by LuoshuiTianyi** [comment]
> > 事实上我是直接使用了windows下的chrome
> 
> 我确认一下你没有在 Linux 下使用 Windows 的 chrome 吧

对的对的

**Comment by Arondight** [comment]
> > > 事实上我是直接使用了windows下的chrome
> > 
> > 
> > 我确认一下你没有在 Linux 下使用 Windows 的 chrome 吧
> 
> 对的对的

Linux 只能运行 ELF ，而 Windows 的可执行文件是 PE 格式，所以还没到兼容库这一层就无法继续了，建议按照文档使用包管理器安装一个 chromium
