### ISSUE TITLE
新的权限设计

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#355]
当前的含混不清，非常不好，需要按功能进行权限管理（集合设置，分开验证）

**Comment by Arondight** [comment]
把所有的非主人功能管理起来

**Comment by Arondight** [comment]
这之后，有很多曾经的权限设置会失效，我不打算兼容旧的数据库了

**Comment by Sucharles** [comment]
新权限设计 存在bug，例如禁止十连权限后，写入authority.json，没问题，再次允许十连权限后，写入authority.json，只有最后一条func会被写为true
