### ISSUE TITLE
功能idea：在进行耗时操作之前，预返回一个提示

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#365]
### 问题描述

这应该算是我一个比较个人的需求，不知道主线需不需要。相关commit： https://github.com/Mark9804/Adachi-BOT/commit/17a16f94ab0ab9d5e08801b434afb64a9ca4f83c

我这边查询米游社/深渊需要耗费10-20秒才能返回结果，在这个过程中机器人没有动静，用户会以为机器人挂掉了或者没收到，多次发送请求，反而增加了处理量。

我的做法是在进行渲染操作之前预先返回一个“正在查询相关信息，请稍后”的消息，告诉用户bot还活着，没加班猝死。

### 代码状态：当前提交

17a16f94ab0ab9d5e08801b434afb64a9ca4f83c (HEAD -> master, origin/master, origin/HEAD) 进行耗时的处理之前，先告诉用户自己还活着

**Comment by Arondight** [comment]
啊，这个应该加到 render.js 里……

**Comment by Arondight** [comment]
我感觉可以加一下，增加一个配置，我来搞把，另外 render 的参数太繁琐了，尽量精简一下

**Comment by Mark9804** [comment]
> 啊，这个应该加到 render.js 里……

render.js 返回角色信息的时候还是很快的，所以我就只单独给`米游社`, `深渊`和`我的`加上了这个，因为这三个指令需要从米忽悠的服务器下载图片

**Comment by Mark9804** [comment]
谢谢老大哥，我一是比较菜，二是自己的仓库还有很多计划做的东西，上云的话调试就不如现在本地方便了，打算等稳定了没什么改动了就上云

不过说到上云我想起来了一个问题，现在的前端是暴露在9934端口的吧，万一云服务器防火墙没配置好的话不就人人都能通过`http://x.x.x.x:9934/xxx.html`看到最近的一个查询数据？

虽然这些数据也不像身份证号啊之类的那么敏感，有接口人人都能查，但好像还是有点微妙的不同

**Comment by Arondight** [comment]
1. 申请一个测试用的 qq 单独本地跑测试
2. 不会暴露，外网连不上的，因为只监听本地回环

**Comment by Mark9804** [comment]
确实可以，是我格局小了

**Comment by Arondight** [comment]
到头来最简单的事情忘记了，周末再顺手加一下吧

**Comment by Arondight** [comment]
我想问一下，主要的耗时在哪儿，是从米游社拉 api 数据呢，还是浏览器从米游社拉图片呢

**Comment by Mark9804** [comment]
> 主要的耗时在哪儿，是从米游社拉 api 数据呢，还是浏览器从米游社拉图片呢

我这边的话，以客户端时间为准，从米游社拉数据大概是2-4秒，浏览器从米游社拉图片再到发送出去被客户端接收到按玄学从5秒到超时都有可能

所以我目前是在米游社API拉到数据之后立刻发送一条例如 “正在处理123456789的米游社数据，请等待至多30秒” 的提示信息

**Comment by Arondight** [comment]
> 所以我目前是在米游社API拉到数据之后立刻发送一条例如 “正在处理123456789的米游社数据，请等待至多30秒” 的提示信息

我现在不确定把提示放到开始拉数据的时候，还是拉完了数据即将写 `data/record` 的时候，比较合适

**Comment by Mark9804** [comment]
把提示放到开始拉数据的时候，假如用户提供了一个不存在的uid或者米游社ID的话，我觉得是双重打扰（“正在查询，请稍等……”、“未查询到信息”）

我更倾向于验证了用户提供的输入确实能够得到结果之后，在处理过程之前预先返回一个结果表示bot已经在干活了，请稍等一下，你要的图过一会就能渲染出来
