### ISSUE TITLE
[bug] 圣遗物权限开关失效

### ISSUE THREAD

**Issue by citydirector** [Arondight/Adachi-BOT#366]
### 问题描述

![IMG_20211109_110525](https://user-images.githubusercontent.com/45933075/140856548-2f187fe4-e963-43a0-b3cc-73d5ea5d93bf.jpg)
![IMG_20211109_110508](https://user-images.githubusercontent.com/45933075/140856561-ddffcad0-f0a6-4ffe-b152-8f5e513173ab.jpg)

### 代码状态：当前提交

b6061799dbbc73d67d6734b0fa1324ef97ab9125 更新议题模板

**Comment by Arondight** [comment]
额，你多试试几个人看看，这个因为之前代码写的不好，如果你在某个更新上用过这功能，数据库可能坏掉了，就是有好几条同一个 id 的记录，但是只有第一条生效

**Comment by Arondight** [comment]
```
{
  "user": [
    {
      "userID": 992737446,
      "reply": true
    },
    {
      "userID": 992737446,
      "artifacts": false,
      "strengthen": false,
      "dungeons": false
    }
  ]
}
```

类似于这种，我本来想写个定时数据库清理补救一下，但是一直没写

**Comment by citydirector** [comment]
> 额，你多试试几个人看看，这个因为之前代码写的不好，如果你在某个更新上用过这功能，数据库可能坏掉了，就是有好几条同一个 id 的记录，但是只有第一条生效

先在大群里突然出现了这个问题(今天)，然后我在私下的群里测试了还是能复现

**Comment by citydirector** [comment]
![IMG_20211109_110508](https://user-images.githubusercontent.com/45933075/140857957-ecc7c859-a612-4a18-9f37-188eabc14c05.jpg)

**Comment by citydirector** [comment]
![IMG_20211109_113927](https://user-images.githubusercontent.com/45933075/140857984-ccb5aa75-bd7f-4862-89ed-344c5511c988.jpg)

**Comment by citydirector** [comment]
难道只能删库了吗（不是

**Comment by Arondight** [comment]
额，我教研写错了，我统一解决一下把

1. 圣遗物权限教研有问题，参数传错了
2. 数据库拿数据应该合并所有带相同键值对的字段
