### ISSUE TITLE
写数据库有问题

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#372]
### 问题描述

难道我改的数据库有点问题？

### 复现流程

1

### 代码状态：当前提交

eca5c91b11ccc03c3c1d0bdd7bf331f6b57ada3a

### 运行环境：操作系统

Linux

**Comment by Mark9804** [comment]
可以出金，但是出金的时候感觉不正常，我的大保底不能正常工作，抽数显示也有问题，应该有五六十抽的
![image](https://user-images.githubusercontent.com/9006264/140890592-f05f8d8b-2e35-43ec-b5c3-a5d96d477326.png)
![image](https://user-images.githubusercontent.com/9006264/140890616-cfba8c2a-f0f7-446b-a617-1483bbce0e85.png)

**Comment by Mark9804** [comment]
感觉像是不读取水位了

**Comment by Arondight** [comment]
> 感觉像是不读取水位了

先本地回退吧，数据库 api 有点问题，深渊都拉不到了

**Comment by Arondight** [comment]
我感觉数据库得还原一下，这个问题解决了之后我发现未知 object 的合并我处理不了，我不知道里面有几层数据，细节是什么样的，还要处理可能的区别，我直接写的脑壳炸了

**Comment by Arondight** [comment]
lodash 的 merge 还是比较弱鸡的

**Comment by Arondight** [comment]
我发现未知数据结构的合并居然没有什么模块去做

**Comment by Arondight** [comment]
https://github.com/jonschlinkert/merge-deep

找到了一个，有空再搞搞

**Comment by Arondight** [comment]
之前的问题不仅是 merge 有问题， update 我实现的也有问题

**Comment by Arondight** [comment]
写数据库的问题最终查明了是因为深渊数据初始化出错导致了无法处理错误的 JSON ，所以数据丢失， duplicate of #373

**Comment by Arondight** [comment]
Duplicate of #373

**Comment by Arondight** [comment]
没想到这么长时间一直是错误的方法得到了正确的结果，初始化数据是错的，数据库 api 是错的，结果是正常的，初始化的数组被数据库 api 转换成了 object ，然后再进行的数据增改。这么长时间数据库的 push 方法一直是有问题的

**Comment by Mark9804** [comment]
用bug堆出来的feature原来真的存在

**Comment by Arondight** [comment]
> 用bug堆出来的feature原来真的存在

代码很稳定，千万不要乱动.jpg

**Comment by Mark9804** [comment]
本地 clone 了一份全新代码进行测试，抽卡还是不能正常读取水位

**Comment by Arondight** [comment]
查了一下是改插件参数的时候批量替换错了，当时审了几遍代码，不过没查出来，数据库的字段太乱了

**Comment by Arondight** [comment]
> 查了一下是改插件参数的时候批量替换错了，当时审了几遍代码，不过没查出来，数据库的字段太乱了

这个问题出现的原因是数据存在判断总为假，所以每次都会插入一条初始化数据（抽卡次数为1），而 db.get 读数据时为了处理可能的多值错误问题会将所有数据进行合并，这时后面得初始化数据覆盖了旧数据，所以抽卡基数总为 1 ，十连结束后，已抽次数总为 11 。

这是数据存在性判断写错了，但是只要 db.get 合并数据前先做一个逆序，就能一定程度上改善错误代码下的行为

**Comment by Arondight** [comment]
> db.get 合并数据前先做一个逆序

目前数据库可能的同字段多值错误还没有以新数据为准的，所以逆序之后以老数据为准虽然不一定对，但是至少不是错的。

**Comment by Arondight** [comment]
> db.get 合并数据前先做一个逆序

ee07504e31daf1a9cb9ace2ff0c3634a61a6cc22
