### ISSUE TITLE
米游社角色信息重复

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#375]
### 问题描述

使用`米游社`命令，角色会重复出现
![image](https://user-images.githubusercontent.com/9006264/140954841-e8afa43a-158c-4b9a-b7af-46d8f48ac1a9.png)

### 复现流程

使用`米游社`命令

### 代码状态：当前提交

1d4d0ce8f04af37c9b6ad5dc7bf3ac3da8ed2321 Merge branch 'master' of https://github.com/Arondight/Adachi-BOT into Arondight-master

### 代码状态：是否修改

Clean

### 运行环境： Node.js 版本

v17.0.1

### 运行环境： npm 版本

8.1.0

### 运行环境：操作系统

macOS

**Comment by Arondight** [comment]
看起来是使用的 merge-deep 有问题，并没有按照想象中的 merge

**Comment by Arondight** [comment]
`rm -vf ./data/db/time.json`
