### ISSUE TITLE
当前前端vue版本可能因为bug和兼容性问题被回撤了

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#392]
### Discussed in https://github.com/Arondight/Adachi-BOT/discussions/391

<div type='discussions-op-text'>

<sup>Originally posted by **Mark9804** November 13, 2021</sup>
vue 现在的稳定版本（也可能是 vue2 最后的稳定版本）是 2.6.14，现在项目里用的版本是 2.6.12， 换源到 2.6.14 之后直接爆炸。微痛迁移到 vue3 更是做梦了

如果是2的最后一版稳定版倒也不是不能用，主要是 [Releases](https://github.com/vuejs/vue/releases) 里面找不到 2.6.12 ，看着 [.13](https://github.com/vuejs/vue/releases/tag/v2.6.13) 一排的 bug fixes，我觉得八成现在我们在用的 .12 版本因为bug太多被回撤了

要解决这个问题的话，可能得找个有能力而且熟悉vue各版本之间差异的真前端，这贴可以加到 #297 的下面，#229 我们现在已经没什么大问题了，至少看上去没什么问题</div>

**Comment by Arondight** [comment]
希望后端尽快稳定下来，可以抽出时间看看前端的问题

**Comment by Arondight** [comment]
我想顺便把 vue 换成开发版本，我们不需要生产版本，因为我们的前端是一个黑盒

**Comment by Arondight** [comment]
@Mark9804 我用最新的开发版本跑了一下，问题应该不大，主要的问题是 vue 根本不工作，vue 的使用方法应该是没怎么变的

**Comment by Mark9804** [comment]
> 主要的问题是 vue 根本不工作

我这边用的前端IDE是 webstorm，如果换成开发版本的 2.6.14 版 vue ，它会大量报错，例如报错称在当前的`<div v-for…>`标签中，`v-for`在此处是不被允许的。但是我们在 2.6.12 上面这么写明明跑得好好的，现在也找不到对应的 .12 开发版本来验证究竟是谁的问题了，所以我也挺迷惑的

**Comment by Arondight** [comment]
新版本上了开发版，没上生产版本，我觉得开发版对我们是好的，而这两个版本很明显对用户来说没有任何区别

**Comment by Arondight** [comment]
> 微痛迁移到 vue3 更是做梦了

我找了一些介绍性的资料看了看，我觉得上 3 应该不会是一个大活，主要的工作都在学习上，真正的编码不会大改的，因为我们的 HTML 还有数据逻辑都是不变的，唯一改变的只是数据的使用方式

**Comment by Mark9804** [comment]
数据处理正好是我不擅长的，有空的时候我再学一学，理想的状态下我个人是希望能摸索着上 3，现在的前端虽然能跑，但知道它为什么能跑和为什么不能跑我觉得也挺有意思的

**Comment by Arondight** [comment]
> 为什么能跑和为什么不能跑

今天我在配置文件中加了个 `viewDebug` ，打开之后我发现图都少了一块，关掉就好了，类似这种能跑不能跑的问题我还是挺讨厌的

**Comment by Mark9804** [comment]
> 打开之后我发现图都少了一块

我傍晚用这个选项debug的时候也发现了，感觉像是 chromium 有头和无头状态下的 [viewport](https://developer.mozilla.org/zh-CN/docs/Web/CSS/Viewport_concepts) 位置不太一致，不知道和弹出来的那个 "Chrome is controlled by automation program" 的横幅占了位置有没有关系

前端最大的不确定因素还是各种浏览器的表现，之前很流行一个鬼故事叫做领导要求支持IE6。现在IE基本上断气了，Safari因为半年一更新，对新标准支持总是慢一拍，[内核](https://www.jianshu.com/p/f4bf35898719)特殊的原因被部分人叫做新一代IE。各种设备的窗口大小不一致也容易让元素错位或者溢出视图。我们这个项目前端视图至少宽度都是固定的，写起来就非常轻松

> 新版本上了开发版，没上生产版本，我觉得开发版对我们是好的，而这两个版本很明显对用户来说没有任何区别

是，vue 是用开发版本还是生产用的 min 版本在视觉上没有影响，min 本身是为了尽可能的缩减请求数据的大小从而提升加载速度，追求文件大小最小化（传输的数据包总数量最小化），不考虑可读性，也不需要展示 debug 信息给用户看。min 的使用环境默认是生产环境，理论上也应该只用于生产环境

我们的 vue 文件都在 localhost，传输速度不是问题，不一定要像商业化场景那样 1kb、2kb 的去抠数据包大小。只要尽可能的解决报`warning`和`error`带来的性能影响，我感觉这两者的差别不大或者几乎没有，但是开发版本可以帮助我们更好的 debug，如果要追求极致效率的话也可以用 dev 版本开发，准备 commit 的时候改成 min 

> Vue 3

Vue 3 的变动我之前提出上 3 的时候大概看过一下，当时是感觉 HTML 的部分感觉有差别但不是天差地别，现在看来更大的差别是在数据层面，我尽可能学，争取早日摆脱切图民工的地位

**Comment by Arondight** [comment]
> 如果要追求极致效率

哈哈哈那最先换掉的肯定是 chromium

**Comment by Arondight** [comment]
突然想到一个事情，当前的 `vue.js` 应该改名为 `vue2.js` ，将来可能有的 3 版本则会是 `vue3.js` ，这样在我们切换 vue 版本后，如果有其他人开发了自己的插件，那么他可以无感升级
