### ISSUE TITLE
[ bug]部分角色头像顶部缺失了一块

### ISSUE THREAD

**Issue by citydirector** [Arondight/Adachi-BOT#396]
### 问题描述

不多说，上图
![Screenshot_2021-11-16-09-43-21-952_com tencent tim](https://user-images.githubusercontent.com/45933075/141881739-874c368e-e8fa-47f2-9d42-adc831039aaa.jpg)

### 复现流程

1

### 代码状态：当前提交

1

### 运行环境：操作系统

Linux

**Comment by citydirector** [comment]
也是突然留意到这个问题，不太确定是哪一天更新出现的

**Comment by Mark9804** [comment]
我这里看图裂了，麻烦重新上传一下下
![image](https://user-images.githubusercontent.com/9006264/141881249-c158ab80-9dfc-43ef-8eb8-739b990870b8.png)

**Comment by Mark9804** [comment]
米忽悠的图就是这样的，帽子变不出来，正面图侧面图都有这个问题
![image](https://user-images.githubusercontent.com/9006264/141882734-37b77a41-be20-4df7-ab8f-c74fc5779d6c.png)

**Comment by citydirector** [comment]
啊这...感觉有点违和（）

**Comment by Mark9804** [comment]
本来这个部分是侧面照的，可能正面照美术组内部有详细规范，头要保持在哪个位置要多大尺寸，所以更统一一些。侧面照的话，米忽悠方的处理（特别对于长发角色）群魔乱舞，一千个角色里面有一千零一个标准，加上正面照比侧面照好认，所以最后想了想还是写了个函数把侧面照转成了正面照。

莫娜除非给她特殊写一套处理方式不然只能这样了，同样情况应该也会出现在帽子很长的丽莎身上，只不过丽莎没人带着打深渊所以到现在为止都没人发现

**Comment by Mark9804** [comment]
我想起来了，当时促使我决定用正面照代替侧面照的原因还真是莫娜，因为莫娜侧面照的帽子和头发直接给我来了个渐隐，实在给我整不会了
![image](https://user-images.githubusercontent.com/9006264/141887753-2ad05f00-03f1-494b-8559-a0c6cad54b5f.png)
↑这是莫娜侧面
↓这是雷军侧面
![image](https://user-images.githubusercontent.com/9006264/141887846-de93bf5b-8b5f-47cc-b458-981a8afc976c.png)

**Comment by Arondight** [comment]
无能为力的问题就别修了把

**Comment by citydirector** [comment]
要不试试把角色头像微微放大一点&位置上调一点？

**Comment by Mark9804** [comment]
我最近看不下去之前的组件复用率，打算重写的部分正好是这一块，到时候我看看

**Comment by Mark9804** [comment]
> 要不试试把角色头像微微放大一点&位置上调一点？ 或许可以没那么明显

https://github.com/Arondight/Adachi-BOT/commit/dea7a522f98f57b12120e7df77173b7f6ba93709 ,看看会不会好一点

**Comment by citydirector** [comment]
不知道是哪里姿势不对，更新后没有变化（）

**Comment by Mark9804** [comment]
> 不知道是哪里姿势不对，更新后没有变化（）

刚刚覆盖错文件了，确实没有变化

在[dev分支](https://github.com/Arondight/Adachi-BOT/tree/dev)里面，打算等改动多一点再一起PR

**Comment by citydirector** [comment]
> > 不知道是哪里姿势不对，更新后没有变化（）
> 
> 刚刚覆盖错文件了，确实没有变化
> 
> 在[dev分支](https://github.com/Arondight/Adachi-BOT/tree/dev)里面，打算等改动多一点再一起PR

那需要我切换到dev测试一下吗

**Comment by Mark9804** [comment]
直接checkout到dev分支里面就行了，不需要重启bot

**Comment by citydirector** [comment]
感觉好一些了（）
