### ISSUE TITLE
深渊前端应该加一个最小高度

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#399]
在特殊情况下房间元素会重叠，应该加一个最小高度限制
![image](https://user-images.githubusercontent.com/9006264/141964210-f0129b90-1116-4ec3-8f76-ba91bcebdcb7.png)

**Comment by Arondight** [comment]
我下午也有反馈说深渊查不到数据了，一直是这个图，不知道是不是这个问题

**Comment by Mark9804** [comment]
> 我下午也有反馈说深渊查不到数据了，一直是这个图，不知道是不是这个问题

这个是纯css问题，关于数据问题的话，我用自己的米游社app能查到完整数据，但是bot查不到，json里的floors也是空数组，我把这张图对应的json贴出来了

https://gist.github.com/Mark9804/1d6bc4ca156a84d28e81aa02a4737a23

**Comment by Arondight** [comment]
> 我用自己的米游社app能查到完整数据，但是bot查不到

啊这，你查一下上期深渊，再查这期，看一下有效果吗

**Comment by Mark9804** [comment]
> 啊这，你查一下上期深渊，再查这期，看一下有效果吗

上期深渊有数据，我觉得可能是因为如果用自己账户cookie查自己账户的数据有什么玄学加成？只能这么猜测了

关issue关成 #398 了，有点尴尬，不知道merge信息能不能修改

**Comment by Arondight** [comment]
啊这，先定性成米游社 api 有问题，明天再说，我晚上打打深渊，明天就有数据调试了

**Comment by Mark9804** [comment]
> 上期深渊有数据

感觉这句话有点歧义，我查`上期深渊`很正常，查当期`深渊`有一段时间会出现这个issue图中的数据（也参考 #323 ），等米游社那边完全更新了就不会了

我感觉现在米游社返回的数据分成几种
1. 正常完整的数据
2. 某一个部分为空数组的数据，比如最多击破什么的是空数组，或者像这个issue这样的，楼层挑战数据是空数组，之类的
3. “没有挑战过渊月螺旋”

其中1和3都是正常情况，主要遇到的异常情况是2

按照时间轴排列：

米游社还未更新，不管是谁都查不到数据
↓（一段时间后）
使用米游社app登陆本人账户可以看到完整数据，
但bot（非本人cookie）查询的话有可能遇到某个部分为空数组的情况
↓（一段时间后）
米游社app和bot都能查到完整数据

我感觉这个问题发生的原因很大可能是使用了非本人cookie，我们也不能为了这点小事就让用户都交一份cookie上来，就这样吧
