### ISSUE TITLE
设置功能默认关闭

### ISSUE THREAD

**Issue by MiniGrayGay** [Arondight/Adachi-BOT#40]
类似十连和圣遗物之类的功能，很多群不太喜欢这样的刷屏，能不能加个某个功能默认新群聊是关闭或者打开的选项

**Comment by Arondight** [comment]
暂时不会添加。

1. 这样需要一个配置文件，但是 bot 又有一个针对 QQ 或群的动态的权限控制，这两个加在一起，逻辑会乱
2. 默认关闭的话，你又会有一个相反的镜像问题，这是一个逻辑上的死循环
