### ISSUE TITLE
机器人只识别了首个cookie

### ISSUE THREAD

**Issue by TuanKay10** [Arondight/Adachi-BOT#403]
### 问题描述

机器人只识别了首个cookie

### 复现流程

机器人只识别了首个cookie

### 代码状态：当前提交

dfc4849cf38820f51c7cd20bf1b2427c9e005a38 (HEAD -> master) <E8> <BF><98><E5><8E><9F> config.js <E7><9A><84> getAll <E6><96><B9> <E6><B3><95><EF><BC><8C><E5>A0><E4><B8><BA><E7><8E><B0><E5><9C> <A8><E7><9A><84> mergeDeep <E9><80><BB><E8><BE><91><E5><B7><B2> <E7><BB><8F><E4><B8><8D><E5><86><8D><E9><80><82><E7><94><A8> <E4><BA><8E><E6><AD><A4>

### 代码状态：是否修改

Dirty

### 运行环境： Node.js 版本

v16.13.0

### 运行环境： npm 版本

8.1.0

### 运行环境：操作系统

Linux

**Comment by Arondight** [comment]
`grep times ./data/db/cookies.json | awk '{print $2}' | sort | tail` 看一下有没有超过 30 的数字。

然后明天再看一下 cookie 有没有异常。 `./data/db/cookies.json` 这个文件中正常来说 `user` 下面的数据应该和你 `./config/cookies.yml` 中的对应， `times` 随着使用次数增加，直到 30 次无效。

**Comment by Arondight** [comment]
另外 `git status` 看一下本地代码都改了啥

**Comment by Arondight** [comment]
后台日志不用补，不重要，我只是想看一下你的代码提交历史，还有本地是否已经有了修改

**Comment by TuanKay10** [comment]
> `grep times ./data/db/cookies.json | awk '{print $2}' | sort | tail` 看一下有没有超过 30 的数字。
> 
> 然后明天再看一下 cookie 有没有异常。 `./data/db/cookies.json` 这个文件中正常来说 `user` 下面的数据应该和你 `./config/cookies.yml` 中的对应， `times` 随着使用次数增加，直到 30 次无效。



> `grep times ./data/db/cookies.json | awk '{print $2}' | sort | tail` 看一下有没有超过 30 的数字。
> 
> 然后明天再看一下 cookie 有没有异常。 `./data/db/cookies.json` 这个文件中正常来说 `user` 下面的数据应该和你 `./config/cookies.yml` 中的对应， `times` 随着使用次数增加，直到 30 次无效。

没有超过30的数字，这会不会是报告无失效cookie的原因?

**Comment by Arondight** [comment]
> 会不会是报告无失效cookie的原因?

无效判定和这个是完全两套逻辑，这只是一个到达使用次数上限的判定

**Comment by TuanKay10** [comment]
> 另外 `git status` 看一下本地代码都改了啥

```
On branch master
Your branch is behind 'origin/master' by 28 commits, and can be
 fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working di
rectory)
        modified:   package-lock.json

no changes added to commit (use "git add" and/or "git commit -a
")
```

**Comment by Arondight** [comment]
```
git checkout package-lock.json
git pull -p
npm install
npm run restart
```

先把代码更新一下，然后明天看吧，太困了

**Comment by TuanKay10** [comment]
> ```
> git checkout package-lock.json
> git pull -p
> npm install
> npm run restart
> ```
> 
> 先把代码更新一下，然后明天看吧，太困了

好的，大佬晚安

**Comment by Arondight** [comment]
今天还有这个问题的话麻烦回复一下，昨天的 cookie 记录都失效了，今天是完全从头读的 cookie

**Comment by TuanKay10** [comment]
> 今天还有这个问题的话麻烦回复一下，昨天的 cookie 记录都失效了，今天是完全从头读的 cookie

第一个cookie暂时没有达到上限，我晚上再看看，昨天深渊更新群友战斗力太强了...

**Comment by Arondight** [comment]
> 第一个cookie暂时没有达到上限

看一下次数是不是分配到了两个 cookie 上

**Comment by TuanKay10** [comment]
> > 第一个cookie暂时没有达到上限
> 
> 看一下次数是不是分配到了两个 cookie 上

现在显示的cookie1次数是7次，cookie2是8次，分配了

**Comment by TuanKay10** [comment]
我还想问问关于时区应该如何设置，因为我是docker部署的，一开始忘记调时区了，然后现在模拟抽卡显示的时间都是0时区

**Comment by Arondight** [comment]
> 时区应该如何设置

bot 用的系统时区，你可能得自己 timedatectl 设置一下

**Comment by TuanKay10** [comment]
> > 时区应该如何设置
> 
> bot 用的系统时区，你可能得自己 timedatectl 设置一下

现在输入date显示的是CST，机器人也重启过了，时区还是不对...

**Comment by Arondight** [comment]
如果今天用到上限了，顺手看一下次数是不是到了30或者是一个很夸张得数字，然后查询报错的 QQ 再次查询就会被分配到另一个 cookie 上。

昨天的问题有可能是你改了配置文件没重启 bot ，现在只会在启动时读取一次配置，之后一直在内存中维持喝使用这个配置

**Comment by TuanKay10** [comment]
> 如果今天用到上限了，顺手看一下次数是不是到了 30 或者是一个很夸张得数字，然后查询报错的 QQ 再次查询就会被分配到另一个 cookie 上。
> 
> 昨天的问题有可能是你改了配置文件没重启 bot ，现在只会在启动时读取一次配置，之后一直在内存中维持、使用这个配置，我今天写到 readme 里了

在此之前，我每次修改配置都有重启过，应该不是这个原因，昨天那个``

**Comment by TuanKay10** [comment]
> 如果今天用到上限了，顺手看一下次数是不是到了 30 或者是一个很夸张得数字，然后查询报错的 QQ 再次查询就会被分配到另一个 cookie 上。
> 
> 昨天的问题有可能是你改了配置文件没重启 bot ，现在只会在启动时读取一次配置，之后一直在内存中维持、使用这个配置，我今天写到 readme 里了

在此之前，我每次修改配置都有重启过，应该不是这个原因，昨天那个`npm run db -- -d cookies -k cookie`用不了是提示`Missing script: "db"`，更新完之后才没问题的

**Comment by TuanKay10** [comment]
> 如果今天用到上限了，顺手看一下次数是不是到了 30 或者是一个很夸张得数字，然后查询报错的 QQ 再次查询就会被分配到另一个 cookie 上。
> 
> 昨天的问题有可能是你改了配置文件没重启 bot ，现在只会在启动时读取一次配置，之后一直在内存中维持、使用这个配置，我今天写到 readme 里了

**Comment by TuanKay10** [comment]
> 如果今天用到上限了，顺手看一下次数是不是到了 30 或者是一个很夸张得数字，然后查询报错的 QQ 再次查询就会被分配到另一个 cookie 上。
> 
> 昨天的问题有可能是你改了配置文件没重启 bot ，现在只会在启动时读取一次配置，之后一直在内存中维持、使用这个配置，我今天写到 readme 里了

那个问题又出现了，次数上限了，现在显示的是cookie1是30次，cookie2是2880293630次

**Comment by Arondight** [comment]
> 而cookie2实际并没有达到上限

手动把 cookie2 的次数改成 0，然后你查一下 102445054 ，看看 cookie2 能用么，同样地 cookie1 也做一次

**Comment by Arondight** [comment]
> 次数改成 0

停掉 bot ，改完后启动 bot

**Comment by TuanKay10** [comment]
> > 次数改成 0
> 
> 停掉 bot ，改完后启动 bot

次数都改成0次之后，再查uid，还是上限，现在两个都变成了2880293630次，而且我拿另一个账号上米游社还是可以看别人战绩

**Comment by Arondight** [comment]
> 再查uid，还是上限，现在两个都变成了2880293630次

那就是两个 cookie 确实都已经到头了

> 我拿cookie2的账号上米游社还是可以看别人战绩

已经查过的一直可以查，新的就不行了

**Comment by TuanKay10** [comment]
> > 再查uid，还是上限，现在两个都变成了2880293630次
> 
> 那就是两个 cookie 确实都已经到头了
> 
> > 我拿cookie2的账号上米游社还是可以看别人战绩
> 
> 已经查过的一直可以查，新的就不行了

那我再找新一个账号试试

**Comment by Arondight** [comment]
> cookie2好像到29的时候就停了

这大概率是一个误判，因为不论是本地代码的 cookie 次数上限判断逻辑

https://github.com/Arondight/Adachi-BOT/blob/f27b71b2388fa3ba9a66366b288acea94e4703ed/src/utils/cookie.js#L48-L50

还是根据 API 返回判定 cookie 超过上限的逻辑

https://github.com/Arondight/Adachi-BOT/blob/f27b71b2388fa3ba9a66366b288acea94e4703ed/src/utils/cookie.js#L168-L173

都不会出现 29 次的情况

**Comment by Arondight** [comment]
如果还有问题继续回复即可
