### ISSUE TITLE
深渊显示问题

### ISSUE THREAD

**Issue by citydirector** [Arondight/Adachi-BOT#404]
### 问题描述

又是一个奇奇怪怪的问题...话不多说，上图
![QQ图片20211117163813](https://user-images.githubusercontent.com/45933075/142166626-8b67f16e-5857-4079-aabc-28df57d54049.jpg)

**Comment by Arondight** [comment]
api 返回的数据改了，就剩这点了，今天下午改的，我感觉也没啥能做的，万一样式改了官方反复横跳也不好。

@Mark9804 你要不瞅瞅，你要是觉得也不用改什么就关了吧

**Comment by Arondight** [comment]
> 将HEAD切换回master

git checkout master

**Comment by citydirector** [comment]
> api 返回的数据改了，就剩这点了，今天下午改的，我感觉也没啥能做的，万一样式改了官方反复横跳也不好。
> 
> @Mark9804 你要不瞅瞅，你要是觉得也不用改什么就关了吧

官方限制最为致命...

**Comment by citydirector** [comment]
> > 将HEAD切换回master
> 
> git checkout master

试了，不好使

**Comment by Arondight** [comment]
> 官方限制最为致命...

本来官方的 api 有很多米游社里不显示的数据，bot 给展示了出来，现在官方又移除了这些数据，就成这样了

**Comment by Arondight** [comment]
> git show 显示处于dev分支，
> git status 显示处于master分支

那不用管啊，这就是正常的，你在 master 分支中 HEAD 指向什么是我决定的，你如果不自己改动也做不了什么，你现在应该 HEAD 指向了很多东西吧，其中有本地的 dev master ，还有远端的

**Comment by citydirector** [comment]
> > git show 显示处于dev分支，
> > git status 显示处于master分支
> 
> 那不用管啊，这就是正常的，你在 master 分支中 HEAD 指向什么是我决定的，你如果不自己改动也做不了什么，你现在应该 HEAD 指向了很多东西吧，其中有本地的 dev master ，还有远端的

懂了。
branch显示有5个（本地的dev, master, 还有三个远程的)

**Comment by Mark9804** [comment]
怎么连这都改，他们程序员上班就干这个？

12月中上旬之前我会很忙，要不先把silverystar的抄过来，他的现在是这样的
![image](https://user-images.githubusercontent.com/9006264/142177224-97fc3310-348b-47a0-a14b-9bf40da474fa.png)

**Comment by Arondight** [comment]
> 要不先把silverystar的抄过来，他的现在是这样的

不用，我觉得现在就很好

**Comment by citydirector** [comment]
> 怎么连这都改，他们程序员上班就干这个？
> 
> 12月中上旬之前我会很忙，要不先把silverystar的抄过来，他的现在是这样的 ![image](https://user-images.githubusercontent.com/9006264/142177224-97fc3310-348b-47a0-a14b-9bf40da474fa.png)

人疯掉系列（）

**Comment by Mark9804** [comment]
如果要改的话，我的想法是把左边四栏全部改成最强一击的那种样式，然后把最强一击也移到左边去，这样就能把现在的空白给挤掉了

**Comment by citydirector** [comment]
> 如果要改的话，我的想法是把左边四栏全部改成最强一击的那种样式，然后把最强一击也移到左边去，这样就能把现在的空白给挤掉了

我倒是有个想法，来自于莫娜的占星盘，做个圆，圆周五个点各一个头像(最强一击/最多击破/最多承伤/元素战技次数/元素苏爆发次数)+数值

**Comment by Mark9804** [comment]
> 做个圆，圆周五个点各一个头像

和整体风格不匹配，而且难排版

**Comment by Arondight** [comment]
@Mark9804 忙完再搞吧，我感觉目前也没啥大问题

**Comment by Xm798** [comment]
> 怎么连这都改，他们程序员上班就干这个？
> 
> 12月中上旬之前我会很忙，要不先把silverystar的抄过来，他的现在是这样的 ![image](https://user-images.githubusercontent.com/9006264/142177224-97fc3310-348b-47a0-a14b-9bf40da474fa.png)

程序员经常在奇怪的地方格外勤奋
