### ISSUE TITLE
“米游社”图片没有传送锚点解锁计数

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#406]
无伤大雅，`"way_point_number"`是在我们的`info.json`字段里面的
![image](https://user-images.githubusercontent.com/9006264/142647333-76bf3762-2277-4fbf-b431-fe24314715e8.png)

**Comment by Arondight** [comment]
我刚注意到前面的汉字居然是写在图片上的，我说怎么找了半天没看到在哪儿……

**Comment by Mark9804** [comment]
> 我刚注意到前面的汉字居然是写在图片上的，我说怎么找了半天没看到在哪儿……

之前忘了哪个issue提到玩家数据加了奇馈宝箱但是我们没有的时候，我提到过字是写死在图上的，当时看的我都蒙了

加两个div补到最后就行了，今天稍晚一点我加上，不用改动图片

**Comment by Arondight** [comment]
> 

这个不急，我就是随手看一下

另外我看原项目好像没实现图片左上角放丘丘头像啊，图片好像都阿里云拉下来的角色头像，是我分支看错了吗

https://github.com/SilveryStar/Adachi-BOT/blob/14573eb/src/plugins/genshin/components/card/upper.js#L88-L90

**Comment by Mark9804** [comment]
哦我当时看的时候没看到作者回复，是个误会， https://github.com/SilveryStar/Adachi-BOT/issues/86

**Comment by Arondight** [comment]
我没发现 oicq 怎么看头像 https://github.com/takayama-lily/oicq/discussions/256

如果作者回复了方法我可以很方便的加上这个功能
