### ISSUE TITLE
在bot未启动的情况下运行 npm run view 会导致异常终止

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#408]
### 问题描述

就想单纯`run view`偷个懒
```
~/Documents/GitHub.nosync/Adachi-BOT dev > npm run view -- -n card                                   21:47:44

> Adachi-BOT@1.5.0 view
> npx node ./tools/view.js "-n" "card"

file:///Users/mark_chen/Documents/GitHub.nosync/Adachi-BOT/src/utils/render.js:103
    msg.bot && msg.bot.say(msg.sid, imageCQ, msg.type, msg.uid, toDelete, "\n");
        ^

TypeError: Cannot read properties of undefined (reading 'bot')
    at render (file:///Users/mark_chen/Documents/GitHub.nosync/Adachi-BOT/src/utils/render.js:103:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.0.1
```

### 复现流程

`npm run stop; npm run view -- -n card`

### 后台日志

```Text
~
```

### 代码状态：当前提交

9f59ce868f045d636eeaabcabed0f7bcd806c207 (HEAD -> dev, origin/master, origin/dev, origin/HEAD, master) 更新文档

### 代码状态：是否修改

Clean

### 运行环境： Node.js 版本

v17.0.1

### 运行环境：操作系统

macOS

**Comment by Mark9804** [comment]
感觉没什么意义，要是bot不启动的话连前端server都不会工作……
我是正好自己的fork是工作状态，但是暂时不想花时间拉代码处理冲突，才想clone原仓库偷这个懒来着

**Comment by Arondight** [comment]
这个改不改都行，我改一下吧

**Comment by Arondight** [comment]
> 

建议自己的仓库拉一个 upstream 分支，不要污染自己的代码

**Comment by Arondight** [comment]
我想加一个特性，如果 bot 没有启动，那么 view.js 自己起一个 server

**Comment by Arondight** [comment]
https://www.npmjs.com/package/tcp-port-used
