### ISSUE TITLE
pm2可以使用pm2-logrotate插件实现日志分割

### ISSUE THREAD

**Issue by Xm798** [Arondight/Adachi-BOT#41]
当前日志会全部输出到一个log文件中，时间长了体积会非常庞大，不方便查看。建议为pm2启用pm2-logrotate插件，并配置每天4:00自动分割日志，方便管理~

**Comment by Xm798** [comment]
当前日志会全部写入到一个log文件中，时间长了体积会非常庞大，不方便查看。建议可以启用pm2-logrotate插件，每天自动分割日志。

**Comment by Arondight** [comment]
呃…… `pm2` 只是 README 中的部署文档，目的是为了让机器人在断开 SSH 后不退出。`pm2-logrotate` 算是个人可选的进阶方案了，应该不用写到 README 中，步骤太多反而会让人迷惑。

补一个官方[文档](https://github.com/keymetrics/pm2-logrotate/blob/master/README.md)，如果有人对这个功能感兴趣可以自己配置一下。

**Comment by Arondight** [comment]
```
# du -chd0 ./bot.pm2/logs/
766M	./bot.pm2/logs/
766M	total
```

太凶了，我要新开一个 issue 去说这个事情
