### ISSUE TITLE
【我的】误触

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#413]
### 问题描述

- [x] 200的充能
- [ ] 我的电脑用固态

### 复现流程

？

### 后台日志

```Text
？
```

### 代码状态：当前提交

111

### 运行环境：操作系统

Linux

**Comment by Arondight** [comment]
1. `数字`的，把数字用正则限制一下，见后文代码段
2. `我的`角色名，先用 simhash 看看吧，`我的娜娜`可以判断为想使用该功能，`我的女神瓦尔迷娜`肯定不行

https://github.com/Arondight/Adachi-BOT/blob/0225a24ca4eec3cb79a747ef9178422f0e8c9c1e/src/utils/id.js#L11-L13

**Comment by Mark9804** [comment]
`我的意思是`也会误触发

**Comment by Arondight** [comment]
一般来说汉明距离小于 4 则说明有较高的相似性，我这里用的是 5 ，可能会有一些误判，需要在使用中观察再做校正

**Comment by Arondight** [comment]
我感觉使用了汉明距离算字符串相似度后，汉明距离的值和别名之间可能都有一个相互的选择，值和别名不合适都会导致比较微妙的结果，这方面就需要在使用中积累经验了
