### ISSUE TITLE
前端图像资源缺失鬼兜虫

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#414]
`resources/Version2/info/image/鬼兜虫.png`

不太了解添加图像资源要怎么添加，资源的事情就拜托了.jpg
![image](https://user-images.githubusercontent.com/9006264/142750656-423f492b-8d67-4b50-ad51-a1eee93ca922.png)

**Comment by Arondight** [comment]
我感觉先嫖一下原作者的呗，说不定过几天就更新了

**Comment by Mark9804** [comment]
我本来的大概计划是想，内鬼网上面有各种物品的素材，但是没有背景，那想办法去抓一个背景下来之后写一个脚本缝合起来，这样就方便多了

但是只抓到了稀有度4和5的紫色和金色背景，稀有度1、2的绿色背景还有稀有度3蓝色背景到处找也找不到

**Comment by Xm798** [comment]
来了 我来看看

**Comment by Arondight** [comment]
> 稀有度1、2的绿色背景还有稀有度3蓝色背景到处找也找不到

这个我在 #57 里面写了，这里可以找到 https://genshin-impact.fandom.com/wiki/Prithiva_Topaz_Sliver

**Comment by Mark9804** [comment]
> > 稀有度1、2的绿色背景还有稀有度3蓝色背景到处找也找不到
> 
> 这个我在 #57 里面写了，这里可以找到 https://genshin-impact.fandom.com/wiki/Prithiva_Topaz_Sliver

还真有，等我想个办法变成我们的

**Comment by Arondight** [comment]
> 还真有，等我想个办法变成我们的

哈哈哈，我开始也找了很久。我不清楚你要做的是什么啊，如果是类似于模板的文件，随便谁导入到 adobe 中就能很方便的制作素材，建议放到 `//resource_templates` 里面提上来

**Comment by Xm798** [comment]
材料从BWIKI获取即可，https://wiki.biligame.com/ys/%E6%9D%90%E6%96%99%E4%B8%80%E8%A7%88

**Comment by Mark9804** [comment]
> 材料从BWIKI获取即可

原来可以这样，方向错了的人竟是我自己
