### ISSUE TITLE
无法查询我的旅行者

### ISSUE THREAD

**Issue by davidelectricfree** [Arondight/Adachi-BOT#415]
### 问题描述

无法查询旅行者信息

### 复现流程

我的旅行者

### 代码状态：当前提交

无法触发我的旅行者

### 运行环境：操作系统

Windows

**Comment by Arondight** [comment]
忘了还有这么个角色了，晚上处理一下

**Comment by Mark9804** [comment]
这个我弄好了，我待会push上来

alias样式改了之后要疯狂在中文输入法与英文输入法之间切换，有点难受

**Comment by Arondight** [comment]
> 样式改了之后要疯狂在中文输入法与英文输入法之间切换

以前的文件太长了，很容易改晕了，虽说比较正式的写法确实是以前的那种
