### ISSUE TITLE
当前角色、武器误响应问题的合集

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#417]
# 1. 个人改进建议
https://github.com/Arondight/Adachi-BOT/commit/04fc8e621bab46fb4ed991dcad5564a9613f3226#commitcomment-60639808
<details>
<summary>把原评论搬运了过来</summary>

> 现在我们用的是单纯的hamming距离来判断是否需要接受该指令，我们预先设置的别名越短，用户的输入越短，就越容易碰到这个阈值
> 
> 例：
> 
> > 我的**鱼** → hamming距离 = 0，响应此次指令
> > 我的**驴** → hamming距离 = 1，响应此次指令
> 
> 如果把hamming距离除以字符串长度，得到一个浮点数，把这个浮点数作为字符串的【不相似率】进行处理会不会更好一些？就类似知网查重那样
> 
> 例：
> 
> > 我的**鱼** → 不相似率 0.00，响应此次指令
> > 我的**驴** → 不相似率 1.00，不响应此次指令
> 
> 或者我们可以在这个基础上更进一步，假如用户输入的字符串与已知的`characterNames`均不匹配，但是和某个`characterNames`的不相似率低于某个阈值（例如0.40，三个字当中只有一个字不一样），我们可以猜测用户的本意就是想查询这个名称
> 
> 例：
> 
> > 查询**达达利亚** → 与【达达利亚】的不相似率 = 0.00 ≤ 0.40，响应此次指令，返回达达利亚
> > 查询**达达利**鹅 → 与【达达利亚】的不相似率 = 0.33 ≤ 0.40，响应此次指令，返回达达利亚
> > 查询塔塔利娅 → 与【达达利亚】的不相似率 = 0.66 > 0.40，不响应此次指令，或不认为这是一个有效指令
</details>

# 2. 误响应问题合集
## 2.1 【我的/别人的某个角色】
![image](https://user-images.githubusercontent.com/45933075/142772587-ca8f1f68-c44f-46b0-9ba0-8d5b171dfcbc.png) 
![image](https://user-images.githubusercontent.com/45933075/142772579-1af8ca92-946b-4652-94f6-73ebd29cd802.png)

## 2.2 不太清楚这是怎么匹配上的
![image](https://user-images.githubusercontent.com/45933075/142772987-8f0110e4-d714-4728-a888-73ef39c9eb67.png)
感觉这个如果真能匹配上也能返回天空书的图片也不算什么坏事，补充说明，就当是feature了

**Comment by Arondight** [comment]
1. 2.1 没这个问题
2. 2.2 把角色的逻辑放到武器上就好了

**Comment by Arondight** [comment]
这个建议很好呀，我试一下

**Comment by Arondight** [comment]
另外别名需要删一删，现在别名太多导致匹配也有问题

**Comment by Arondight** [comment]
行秋的秋秋和秋秋人明显是重复的，心海的鱼和热带鱼也是，现在的别名似乎成了一个梗字典，我觉得需要删掉大部分

**Comment by Arondight** [comment]
1. 琴：琴团长，有人愿意输入琴必然不想再输入一个团长，所以应该只保留团长
2. 莫娜：占星术师，永远不会用到的别名，同样的还有早柚的幼颜龙蜥，托马的家政官

之前我写了一条原则但是删掉了，我觉得应该补回来

https://github.com/Arondight/Adachi-BOT/blob/f0ee821f8ca82cd4746675dc42b7b4dc9a129fc4/config_defaults/alias.yml#L3

**Comment by Arondight** [comment]
之前删掉了这个原则是因为我们不太依赖这个配置文件的规范性，大家玩得开心就好，其实从给出查找建议开始就应该规范起来

**Comment by Arondight** [comment]
另外别名应该具有时效性，例如凯亚明显不再是矿工头子了，事实上半年前入坑的人就不知道凯亚为什么叫这个，硬要说的话现在的矿工头子应该是钟离

**Comment by Arondight** [comment]
再说一下你这个建议，我细看了一下你算距离和实际上的不太一样，理论上是很好的，不过距离其实不是这么算的。首先算 simhash ，文本分词，每个词算 hash ，每个 hash 按位加权后按位相加，然后进行归一变为一串二进制，至此 simhash 完成，认为这串二进制代表了文本的特征。然后汉明距离是两个二进制异或取置位个数

**Comment by Arondight** [comment]
英文名字也是需要删掉的，永远不会被使用，除了一些国内玩家常用的例如 xiao dio

**Comment by Arondight** [comment]
还有明显不需要处理的错别字，例如肖宮：小攻，相应反而会显得不正常

**Comment by Mark9804** [comment]
就是说汉明距离已经包含了我想法里的步骤了吗，我的理解是从一个字符串到另一个字符串需要替换的字符个数，所以借鉴论文查重提出了这个想法。
实际上跟我理解不一样的是，汉明距离是一个相对抽象的概念，已经可以（一定程度上）代表两个字符串之间的不相似率了吗？

**Comment by Arondight** [comment]
@Mark9804 不是这样的，汉明距离是判断信息编码相似性的一种做法，我们传递给他的信息编码是 simhash ——文本的特征值

**Comment by citydirector** [comment]
补充一些奇奇怪怪的触发
![image](https://user-images.githubusercontent.com/45933075/142799928-a2fde995-454d-4725-bb53-d04ebedb772e.png)
![image](https://user-images.githubusercontent.com/45933075/142799984-b2f4628d-20d1-418c-881e-6dc261cb89be.png)
![image](https://user-images.githubusercontent.com/45933075/142800016-3956d76b-72ab-410c-8d09-94fe29329e0f.png)

**Comment by Arondight** [comment]
我这里还有 `武器池` 的问题，但是后两个没有，我看看怎么做一些进一步的相似性检测

**Comment by Arondight** [comment]
> 补充一些奇奇怪怪的触发

1. 现在降低了很多误触，例如 `信息池`
2. 删除了武器和角色，本来这俩也没出现在帮助信息上

**Comment by Arondight** [comment]
另外加了一个旅行者的 json ，里面都是瞎写的，晚上有空再填

**Comment by citydirector** [comment]
等大佬们更新完这个阶段我再更新试试（自定义了部分配置文件，每次都要重新写0.0）

**Comment by Mark9804** [comment]
之前我提出的相似性检测方法可能因为有误解导致说的不太清楚，但应该大方向是没问题的，我在我自己分支尝试一下

**Comment by Mark9804** [comment]
`simhash`感觉有点奇怪，我预期中`达达鹅`和`达达吖`的响应应该是一样的，而不是一个响应一个不响应
![image](https://user-images.githubusercontent.com/9006264/142815580-7167145c-81d1-4f83-a1e6-30a6c80f2ecd.png)

**Comment by Arondight** [comment]
你可以单独写个脚本尝试

```
import { hamming, simhash } from "./src/utils/tools.js"
var s1 = "钟离";
var s2 = "钟来";
console.log(hamming(simhash(s1), simhash(s2)))
```

现在分词器是我自己写的，如果用 Segment 库分词就会很像了

**Comment by Arondight** [comment]
但是分词太好就会过于相似或者不相似了，所以我自己写了个分词。例如 `迪卢克` 会被 Segment 分词成一个词语 `迪卢克` ，但是会被我分成 `迪`、`卢`、`克`，对于每个分词都计算 hash ，然后加权、纵向相加、归一。所以 `迪卢克` 这一个词相当于不会有加权、相加和归一的过程，就是绝对准确的。这就导致了一个问题，`迪卢克` 和 `迪卢壳` 就是完全两个东西

**Comment by Mark9804** [comment]
这个结果感觉太不稳定了，有没有可能simhash在非英文环境下的表现比我们想象中的要差一些
```javascript
import { hamming, simhash } from "./src/utils/tools.js"
const s1 = "达达利吖";
const s2 = "达达利鸭";
const s3 = "达达利亚";

console.log(hamming(simhash(s1), simhash(s3)))
console.log(hamming(simhash(s2), simhash(s3)))
```
```
5
8
```

**Comment by Arondight** [comment]
我感觉跟英文没关系，他这算法不关心语言编码，反正我现在是两层校验了， hamming 好不好我也不是很在意了

**Comment by Mark9804** [comment]
不经过`simhash`，我感觉这种结果是好的
```javascript
import { hamming} from "./src/utils/tools.js"

const s1 = "达达利吖";
const s2 = "达达利鸭";
const s3 = "达达利亚";

console.log(hamming(s1, s3))
console.log(hamming(s2, s3))
```
```
1
1
```

**Comment by Arondight** [comment]
不经过 simhash 不行的，你把顺序改一下一下试试，例如 `达达里亚` 和 `公子达达利亚`

**Comment by Arondight** [comment]
而且对于汉明距离来说这个串实在是太短了，算不出什么有代表性的东西

**Comment by Mark9804** [comment]
确实得过一遍 simhash ，我再想想

**Comment by Mark9804** [comment]
老大哥能提供一下现在的分词器的位置么

**Comment by Arondight** [comment]
```
import { segment } from "./src/utils/tools.js"
console.log(segment('今天星期 3，原神的名字为什么会叫Genshin Impact呢？'))
```

**Comment by Arondight** [comment]
实际上我试了下，少于六个字符，这样分词更加合理一下

**Comment by Arondight** [comment]
我更新了一下分词器，现在不会分出来空白字符了

**Comment by Mark9804** [comment]
https://github.com/xmcp/pakku.js/blob/1ef9d3998a27e6b69daf792bcbbbe79e13c1b525/pakkujs/core/edit_distance.js

上面是一个判断B站不同弹幕相似度并自动合并的项目，判断的是2-gram频率向量的夹角（不是那个编辑距离/莱文斯坦距离）

**Comment by Arondight** [comment]
我晚上回去看一下，这些算法我感觉在短字符串上表现都不一定多好，特征很容易变动，长字符串就不会

**Comment by Mark9804** [comment]
补充一条
![image](https://user-images.githubusercontent.com/9006264/142860711-738ec845-75df-4ad5-b07b-b3ba5b8c3a07.jpeg)

**Comment by Mark9804** [comment]
拉了一下代码重启试了试，确实会误触发![image](https://user-images.githubusercontent.com/9006264/142861026-eba63c4e-8653-4b8d-951f-de014d7a8fb3.jpeg)

**Comment by Arondight** [comment]
定轨我忘了加了，这个加一下限制就好，不需要算相似性。以前的代码因为有正则过滤掉很多不合适的聊天内容，所以插件内部都没有做这个工作。

**Comment by Arondight** [comment]
哦，定轨是需要算的，我晚上统一处理一下吧，中午加的旅行者 json 我也得改一下

**Comment by Mark9804** [comment]
开了个倒车，试了 Levenshtein 距离（编辑距离）

```javascript
const levenshtein = require('fast-levenshtein');

let s0 = "玩具销售员达达利亚"
let s1 = "达达里亚";
let s2 = "公子达达利亚";
let s3 = "亚利达达"

let sn = "达达利亚";

console.log(levenshtein.get(s0, sn));
console.log(levenshtein.get(s1, sn));
console.log(levenshtein.get(s2, sn));
console.log(levenshtein.get(s3, sn));
```
```
5
1
2
4
```

**Comment by Mark9804** [comment]
我最初的想法应该是基于编辑距离的，触发点是我们预先设置好的某一个不相似率的阈值

**Comment by Arondight** [comment]
这个看上去不错，虽然计算量会变很多

**Comment by Arondight** [comment]
@Mark9804 麻烦多试试，你这里如果得出结论可以的话我就直接换了，我还在改这堆防误触的东西

**Comment by Mark9804** [comment]
我这个测试用的脚本暂时整合不进tools.js里，会报`require is not defined in ES module scope`

刚刚我是直接把根目录的`package.json`里面的`"type":"module"`干掉来单独测试的，待会我再看看

**Comment by Arondight** [comment]
我来吧，我改完防误触了

**Comment by Arondight** [comment]
好在可以在算编辑距离之前首先算一下可能的别名，如果有的话再算编辑距离，我看了一下，这个算法跟汉明距离一比的确是小号太大了，而且 simhash 还是加载配置文件之后就把所有别名算好的

**Comment by Mark9804** [comment]
https://www.npmjs.com/package/fastest-levenshtein

这个包不知道表现会不会好一些

**Comment by Arondight** [comment]
> 这个包不知道表现会不会好一些

反正我也一时半会看不懂这算法，哪个名字牛逼就用哪个

**Comment by Mark9804** [comment]
两个字猜错一个，感觉误触率会不会太高……

> ：来我**屋**里
> ：我给你康好康的

屋里 → 神里

**Comment by Mark9804** [comment]
刚刚看了一下网上对于距离算法的优化基本上是提前返回结果终止循环，但我们字符串不在长而在多，意义不大

有一种矩阵版本的距离算法（[中文](https://www.cnblogs.com/ymind/archive/2012/03/27/fast-memory-efficient-levenshtein-algorithm.html)，[英文](https://www.analyticsvidhya.com/blog/2021/02/a-simple-guide-to-metrics-for-calculating-string-similarity/#h2_5)），但很可惜我数学不好，看天书了属于是

**Comment by citydirector** [comment]
![IMG_20211123_134612](https://user-images.githubusercontent.com/45933075/142977965-3b1ad2b0-aba4-4b1d-b0d9-40926498dddf.jpg)

**Comment by citydirector** [comment]
（日常忘记打码）
![IMG_20211123_140916](https://user-images.githubusercontent.com/45933075/142978084-982eec6e-cdd3-49ba-aadc-a9455c905925.jpg)

**Comment by Arondight** [comment]
@citydirector 这个没法避免了，唯一的优化只是看看能不能把候选词列表做得好一点，你要是想避免这个问题可以选择机器人只响应 @信息 或者需要加前缀

**Comment by Arondight** [comment]
https://github.com/Arondight/Adachi-BOT/blob/60f6e4250a106015c5dee5e3c99337587b0fe401/config_defaults/setting.yml#L41-L43

https://github.com/Arondight/Adachi-BOT/blob/60f6e4250a106015c5dee5e3c99337587b0fe401/config_defaults/setting.yml#L80-L88

**Comment by Mark9804** [comment]
评论是可以二次编辑的，不过就算删掉了原评论邮件也能看到，所以还是注意点

照理来说应该不会触发吧？远超过0.5了
你们这个群机器人魔改的比较厉害，你得问问管理现在的alias是怎么回事
为什么我会知道呢，因为一个群友天天问我什么时候加上你们bot的涩图功能
![image](https://user-images.githubusercontent.com/9006264/142978797-717ee8f8-1cfc-46c6-be30-a3c29ea9ecd0.png)

**Comment by Arondight** [comment]
也可能他用的还是老代码，我们昨天才换的匹配算法

**Comment by Arondight** [comment]
老代码的 simhash 在短文本的情况下确实不咋地，长文本还行

**Comment by citydirector** [comment]
233，我自己的话色图bot用了go-cqhttp用了不同设备登录，不冲突
应该是昨晚8点多的版本

凝光那个alias只有“富婆、天权、天权星”三个，其他的也没有跟跟“凝光”两个字沾边的

**Comment by Mark9804** [comment]
不知道是不是没有从内存读取配置的问题，我感觉这个算法的资源消耗和读取配置的时间一对比感觉还行……

```javascript
import levenshtein from "fastest-levenshtein";
import { readConfig } from "./src/utils/config.js";

console.time("配置读取时间")
readConfig();
const names = Object.keys(alias.allNames);
console.timeEnd("配置读取时间")
console.log()

const n0 = "胡桃堂主想把我送走"

let n1 = process.argv[2];
if (n1 === undefined ) {
  n1 = n0
}

console.time("\n匹配时间");
for (const n2 of names) {
  const d = levenshtein.distance(n1, n2) / n1.length;

  if (d < 1) {
    console.log(`${n1} - ${n2} - ${d}`);
  }
}
console.timeEnd("\n匹配时间");
```

```javascript
配置读取时间: 72.957ms

胡桃堂主想把我送走 - 胡桃 - 0.7777777777777778
胡桃堂主想把我送走 - 桃子 - 0.8888888888888888
胡桃堂主想把我送走 - 桃桃 - 0.8888888888888888
胡桃堂主想把我送走 - 桃典 - 0.8888888888888888
胡桃堂主想把我送走 - 堂主 - 0.7777777777777778
胡桃堂主想把我送走 - 胡堂主 - 0.6666666666666666
胡桃堂主想把我送走 - 胡亚娜 - 0.8888888888888888
胡桃堂主想把我送走 - 胡虫 - 0.8888888888888888

匹配时间: 6.103ms
```

**Comment by Mark9804** [comment]
长文本的表现也还可以，应该没有性能瓶颈啊
```
配置读取时间: 99.741ms

放火烧山真菌 - 火花骑士 - 0.8333333333333334，拒绝
放火烧山真菌 - 放火烧山真君 - 0.16666666666666666，接受
放火烧山真菌 - 火神 - 0.8333333333333334，拒绝
放火烧山真菌 - 凝冰渡海真君 - 0.8333333333333334，拒绝
放火烧山真菌 - 雪山果子 - 0.8333333333333334，拒绝
放火烧山真菌 - 柴火棍 - 0.8333333333333334，拒绝

匹配时间: 3.115ms
```

**Comment by Mark9804** [comment]
> 共匹配了493次，找到55个建议，接受1个建议

我的进一步想法是，如果接受的建议有且只有一个，那么就认为用户是想查询这个人了

**Comment by Arondight** [comment]
我晚上想一想搞一搞，上班上得脑壳疼，下班回去睡觉了

**Comment by Arondight** [comment]
> 我很想使用这个算法作为候选列表的算法

晚上干脆搞了得了，之前的那个候选词算法怎么看都太傻了

**Comment by Arondight** [comment]
睡醒了试了一下，感觉给出建议会不会有点牵强，例如下面是所有和 `白枪` 匹配的名字

```
{
  '白影': 0.5,
  '白辰': 0.5,
  '白缨枪': 0.5,
  '鸟枪': 0.5,
  '绿枪': 0.5,
  '岩枪': 0.5,
  '盾枪': 0.5
}
```

**Comment by Arondight** [comment]
我感觉或许还是给一个候选词列表而不是直接猜一个可能对的会好一些？或者改成猜测先实际运行一段时间观望一下

**Comment by Mark9804** [comment]
> **如果接受的建议有且只有一个**，那么就认为用户是想查询这个人了

在有多个可能性的时候，我们就不做猜测了

**Comment by Mark9804** [comment]
作为生物来说我们的做法是 字形+拼音相似度，在项目里这么搞当然也可以，只是工作量就直接上来了

所以我的想法是例如：
# 例1
```
放火烧山真菌 - 火花骑士 - 0.8333333333333334，拒绝
放火烧山真菌 - 放火烧山真君 - 0.16666666666666666，接受
放火烧山真菌 - 火神 - 0.8333333333333334，拒绝
放火烧山真菌 - 凝冰渡海真君 - 0.8333333333333334，拒绝
放火烧山真菌 - 雪山果子 - 0.8333333333333334，拒绝
放火烧山真菌 - 柴火棍 - 0.8333333333333334，拒绝
共匹配了493次，找到6个建议，接受1个建议

匹配时间: 3.723ms
```
在这个例子中，匹配的有6个建议，接受的（≤0.5）的只有一个建议，那么就认为用户想查询“放火烧山真君”

# 例2
```
白枪 - 白影 - 0.5，接受
白枪 - 白辰 - 0.5，接受
白枪 - 白缨 - 0.5，接受
白枪 - 白缨枪 - 0.5，接受
白枪 - 鸟枪 - 0.5，接受
白枪 - 绿枪 - 0.5，接受
白枪 - 岩枪 - 0.5，接受
白枪 - 盾枪 - 0.5，接受
共匹配了493次，找到8个建议，接受8个建议
```
在这个例子中，接受的建议数量 ≥ 1，那么我们不应该替用户做选择。除非我们进一步引入拼音比对，认为在这八个建议当中，`baiqiang`和`baiyingqiang`最为接近，认为用户想查询白缨枪。但是这样工作量太大了，收益也不大。用户得到了想要的数据，但我们花费了大量资源和时间，这一切不值得

**Comment by Arondight** [comment]
确实，我本来想的是要做统一做了，直接把候选词给砍掉，不过没啥好办法，先这么做吧

**Comment by Mark9804** [comment]
> 要做统一做了，直接把候选词给砍掉

简历上可以加一条“精通自然语言处理”了

我们可以综合用多种算法模型来给用户一个最接近他想法的猜测，但是出于资源消耗（不管是计算资源消耗还是我们的时间精力消耗），我觉得这样做不太值得

**Comment by citydirector** [comment]
> 简历上可以加一条“精通自然语言处理”了

太强了qwq

**Comment by Mark9804** [comment]
> 太强了

开玩笑的

**Comment by Arondight** [comment]
@Mark9804 算是部分达成了你的想法吧，可能还差点意思

**Comment by Mark9804** [comment]
有雏形就行了，我可以微创新

**Comment by Arondight** [comment]
> 有雏形就行了，我可以微创新

效果好的话顺手提一下，我感觉现在的主要问题，是编辑距离除以字符串长度这个权值颗粒度太粗了

**Comment by Mark9804** [comment]
> 我感觉现在的主要问题，是编辑距离除以字符串长度这个权值颗粒度太粗了

我暂时也想不到什么更骚的操作了，要解决这个问题比如弄个拼音匹配，这样就等于变相拉长了两个字符串的长度，说不定最后还是能够回到汉明距离上

**Comment by Arondight** [comment]
我感觉现在只能算一个持续的优化吧，我们又对这个领域不熟，只能一点点搞了，先这样吧，你说的效果至少是达成了，就是这个颗粒度太粗略不好控制

**Comment by Arondight** [comment]
我想到了一个优化，现在猜名字是根据别名和本名猜的，然后结果填到数组，如果数组只有一个元素，那么就使用这个名字。所以应该把所有的别名换成本名，做一次数组去重

**Comment by Arondight** [comment]
![图片](https://user-images.githubusercontent.com/13673702/143027872-565a7034-58fc-4baa-8458-d6becf111c82.png)

至此 alias.yml 的存在感越来越稀薄了

**Comment by Arondight** [comment]
但是这样的话， alias.yml 加回去一些别名比较合适

**Comment by Mark9804** [comment]
我觉得这还是要回到“ alias 对用户来说意味着什么”这个问题上来

对于我个人来说 alias.yml 除了是一个纠错字典之外也是一个玩梗的地方，如果只能够根据本名查询的话感觉乐趣降低了，所以打算在自己仓库把 c6f93036c542c7e2e5d298cdc124925db80f8b7f 回滚掉

**Comment by Arondight** [comment]
我的看法不一样，我觉得 alias 现在不建议由用户自行修改，一来这个文件改起来是需要机巧的，例如优菈的别名只有尤拉就够了，优拉和尤菈都是多余的，二来别名越多误触越多，例如有人说我舅放火烧山进去了，然后 bot 贴出来一张可莉

**Comment by Arondight** [comment]
另外当前的权重只偏向一个字符串好像是有一点问题的，但是目前也没有权衡两个字符串的好办法，因为用户说的话不知道有多长

**Comment by Mark9804** [comment]
确实有这个问题，还是让用户自己根据使用场景决定吧，我们保留最小的数据集，不建议用户修改别名，但如果用户想要修改的话，我们也最好能够给他修改并且体现这些修改的权利

**Comment by Arondight** [comment]
> 确实有这个问题，还是让用户自己根据使用场景决定吧，我们保留最小的数据集，不建议用户修改别名，但如果用户想要修改的话，我们也最好能够给他修改并且体现这些修改的权利

嗯，目前是这样的。

另外我刚才修改别名，感觉一般用户真的改不好（不好和不能用是两码事），例如。

1. 天空大剑作为天空之傲的别名是没有意义的
2. 狗和狗崽两个别名同时存在是没有意义的（因为狗崽会被识别成狗）
3. 但是金珀作为试做金珀的别名是必要的（因为金珀不会被识别成试做金珀）

我该起来都得写程序测，用户必然改不好的，这也和我们的权重计算不好有关，狗到狗子，和，狗子到狗，结果不一样

**Comment by Mark9804** [comment]
如果我们把分母改成两个字符串长度相加，然后因为分母变大，所以我们需要再乘以一个现在我也不知道是多少的修正系数。

这样的话虽然可以解决结果不一样的问题，但是整个算法就逐渐变得玄学起来了

越魔改越像训练神经网络的时候瞎几把调参了，这样感觉不是很好，我们再想想有没有其他办法吧

**Comment by Arondight** [comment]
我本地只是简单的除以两个字符串长度的最小值，结果好多了

**Comment by citydirector** [comment]
贴个bug出来：`0的优菈` 到 `9999的优菈` 都会出现结果，结果等同`我的优菈`

**Comment by citydirector** [comment]
我可能是传说中的bug体质...

**Comment by Arondight** [comment]
> 贴个bug出来：`0的优菈` 到 `9999的优菈` 都会出现结果，结果等同`我的优菈`

这个是我本来限制了 UID 正则，后来我又给去掉了，我讨厌硬编码

**Comment by citydirector** [comment]
> 记错了，没有去掉，可能是我一直想做这个事情，以为已经做过了，大约是你的代码没更新吧

两分钟前更新了（）

**Comment by citydirector** [comment]
试了一下，用什么别名都没有的埃洛伊也能复现

**Comment by Arondight** [comment]
> > 记错了，没有去掉，可能是我一直想做这个事情，以为已经做过了，大约是你的代码没更新吧
> 
> 两分钟前更新了（）

你确定 `config/` 下的 `command.yml` 也更新了吗

```
./scripts/whats_updated_in_the_configuration_files.sh
```

**Comment by Mark9804** [comment]
重启了吗

**Comment by Arondight** [comment]
> 我的锅，之前改过“我的xxx”命令的正则匹配表达式，忘记了。。。

再更新一下，测测 bug ，我先摸了，体力还没打呢

**Comment by citydirector** [comment]
老实说，这个脚本好像没有正常工作的样子...
![image](https://user-images.githubusercontent.com/45933075/143035860-8b2fc65c-f190-434b-adc8-16774565718e.png)

**Comment by Arondight** [comment]
> 老实说，这个脚本好像没有正常工作的样子... ![image](https://user-images.githubusercontent.com/45933075/143035860-8b2fc65c-f190-434b-adc8-16774565718e.png)

俺不管，你的 diffutils 版本太低了

**Comment by Arondight** [comment]
比较奇怪为啥我的 bot 用了当前的算法后反应总是慢一拍，难道是单纯的网络原因？

**Comment by Mark9804** [comment]
> 比较奇怪为啥我的 bot 用了当前的算法后反应总是慢一拍，难道是单纯的网络原因？

看一下后台log吧，我这里基本上是秒反应的

**Comment by Arondight** [comment]
> > 比较奇怪为啥我的 bot 用了当前的算法后反应总是慢一拍，难道是单纯的网络原因？
> 
> 看一下后台log吧，我这里基本上是秒反应的

开游戏了，今天太累了，我下午四点就回到出租屋睡觉了，明天看看如果不会拖慢速度我把 alias 文件里的说明删掉，省的别人不敢放心玩

**Comment by Mark9804** [comment]
还有一个可以优化的点，假如用户输入的选择有两个建议，而这两个建议都指向同一个对象，那么可以认为用户就是想查询这个对象

```yaml
五郎:
  - 狗崽
  - 狗
```
查询： 狗仔，返回“狗”和“狗崽”两个结果，但是他们指向的对象都是五郎，所以也可以认为用户想查询五郎

**Comment by Arondight** [comment]
> 还有一个可以优化的点，假如用户输入的选择有两个建议，而这两个建议都指向同一个对象，那么可以认为用户就是想查询这个对象
> 
> ```yaml
> 五郎:
>   - 狗崽
>   - 狗
> ```
> 
> 查询： 狗仔，返回“狗”和“狗崽”两个结果，但是他们指向的对象都是五郎，所以也可以认为用户想查询五郎

这个我已经实现了，但是被你 revert 了，虽然实现的和你的设想可能有一点点区别

**Comment by citydirector** [comment]
大概摸明白了，然后想到一个
`信息xxx<字符串>` 这样子的，只要字符串长度小于前面`信息xxx`长度和的一半就会被判定为true
比如说`角色摩拉克斯的枪`这样子的（当然这个例子有点牵强）

**Comment by Mark9804** [comment]
> 大概摸明白了，然后想到一个 `信息xxx<字符串>` 这样子的，只要字符串长度小于前面`信息xxx`长度和的一半就会被判定为true 比如说`角色摩拉克斯的枪`这样子的（当然这个例子有点牵强）

emmm，能再详细一点说明一下吗，没有计算过程不给分的

**Comment by citydirector** [comment]
> emmm，能再详细一点说明一下吗，没有计算过程不给分的

233
“信息摩拉克斯abc”这样就能触发，因为‘abc’字数是3个字，‘信息摩拉克斯’是6个字，3≤6所以能触发

**Comment by Arondight** [comment]
> emmm，能再详细一点说明一下吗，没有计算过程不给分的

我国古代的科学一般都是先通过现象总结事物规律，然后创造一套符合已知现象的理论，如果这理论能够进一步得到验证，一般就认为这个理论是对的了，例如中医的阴阳五行、五运六气，从这个角度来说他总结的还挺好的😄

**Comment by Mark9804** [comment]
？？？

**Comment by citydirector** [comment]
> 我国古代的科学一般都是先通过现象总结事物规律，然后创造一套符合已知现象的理论，如果这理论能够进一步得到验证，一般就认为这个理论是对的了

淦，想一块去了

**Comment by Mark9804** [comment]
？？？？

> “信息摩拉克斯abc”这样就能触发

这个确实能触发，并且会返回唯一结果钟离

虽然我感觉其实不应该触发，因为这给我的感觉是它明显不应该是一个指令，指令应该是`信息摩拉克斯`，后面不跟东西的

**Comment by Arondight** [comment]
信息dio娜

**Comment by citydirector** [comment]
> 信息dio娜

这个当alias中只有“[ dio ]”的时候又应该被触发，
所以不同角色由于不同的外号会有不同的长度判定，不如把这个长度判定交给使用者？

**Comment by Arondight** [comment]
现在没有长度判定吧，正则是捡破烂模式

**Comment by citydirector** [comment]
> 现在没有长度判定吧，正则是捡破烂模式

没，只是个想法（）

**Comment by Mark9804** [comment]
> 我国古代的科学一般都是先通过现象总结事物规律，然后创造一套符合已知现象的理论，如果这理论能够进一步得到验证，一般就认为这个理论是对的了，例如中医的阴阳五行、五运六气，从这个角度来说他总结的还挺好的😄

我理解了，我去，还真是这个算法，我们的算法好像就是长这样的

**Comment by Mark9804** [comment]
![image](https://user-images.githubusercontent.com/9006264/143169571-3fe3e4a9-7726-4952-8e48-6009d6e69894.png)

**Comment by Arondight** [comment]
更一下代码就行了

**Comment by Mark9804** [comment]
0.5感觉确实容易点出炒饭
![C9E51382-8D5F-41EF-B699-857FC89C1B95](https://user-images.githubusercontent.com/9006264/143239180-b786d058-3a4e-47a7-9141-5a56761f525c.jpeg)

**Comment by Arondight** [comment]
这不是也挺好的嘛

**Comment by Mark9804** [comment]
https://github.com/Arondight/Adachi-BOT/blob/eff322f92caaec371e84716a652efdef4e485974/config_defaults/names.yml#L69

> 信息 老**婆**

**Comment by Arondight** [comment]
哈哈哈，我觉得没啥问题，你可以自己改一下 tools.js 那个常量，我们这也算是阴差阳错的钦定了旅行者的老婆了

**Comment by Mark9804** [comment]
现在有一个匹配优先度的问题，

```yaml
天空之刃（单手剑）: [ 痛苦小剑 ]
天空之傲（双手剑）: [ 痛苦大剑 ]
```
如果是这样的话，查询“痛苦小剑”出来的是双手剑的结果，查询“痛苦大剑”的话出来的是单手剑的结果

如果把这两个别名反过来，单手剑叫痛苦大剑，双手剑叫痛苦小剑，那么返回的结果就正常了

因为“痛苦大（小）剑“与痛苦（小/大）剑的不匹配度是`0.25`，也就是四个字当中只有一个字不一样，但是我们强行赋给了正确的结果一个`0.3`的值，反而把正确的结果给挤下去了

**Comment by Arondight** [comment]
那就别偷懒了，算吧，哪个小用哪个，我原本想着能省点资源

**Comment by Mark9804** [comment]
> 我原本想着能省点资源

省资源我觉得可以提前跳出循环，比如说“如果编辑距离=0，那么结束循环并返回该结果”

**Comment by Arondight** [comment]
之前的逻辑是匹配后设置一个固定值，我觉得需要改成一个动态的，例如 `1 - s2 / s1` ，这样 `大大利亚` 和 `大` 之间的匹配度是 `0.75` ， 而 `大大` 的匹配度就是 `0.5`

**Comment by Arondight** [comment]
按照这个逻辑，也不需要该目前的代码流程，当 `痛苦小件` 匹配到 `痛苦小件` ，那么最后拿到的值是 0 ，匹配痛苦大件则是 0.25 ，最后还是选择的痛苦小件

**Comment by Mark9804** [comment]
是不需要，但如果想省资源的话，我觉得先使用键值对匹配一遍（就是最古老的完全匹配），如果没有得到结果，就进入模糊匹配流程，这样会不会好一些

**Comment by Mark9804** [comment]
> 当 `痛苦小件` 匹配到 `痛苦小件` ，那么最后拿到的值是 0 ，匹配痛苦大件则是 0.25 ，最后还是选择的痛苦小剑

我的优化建议是拿到一个为0的值就可以退出了，不用计算下面的名称，因为不可能比0更小，也不可能有两个完全一样的名称存在于 names.yml 当中，接下去的匹配是没有意义的

**Comment by Arondight** [comment]
```
import { readConfig } from "./src/utils/config.js";
import { guessPossibleNames } from "./src/utils/tools.js";
readConfig();
console.log(guessPossibleNames("痛苦小件", ["痛苦大件", "痛苦小件"]));
```

```
$ node t.js   
[ '痛苦小件' ]
```

**Comment by Arondight** [comment]
5077565

**Comment by Mark9804** [comment]
https://github.com/Arondight/Adachi-BOT/blob/507756545f87c727ff4de57c8f056031c7d03403/src/utils/tools.js#L127

这里的`l >= 0.5`不知道是不是过于严格了

> ：信息 稻光
> ：：返回：凝光

预期应该返回`薙草之稻光`，五个字命中两个，感觉 0.4 就够了。像`终末嗟叹之诗`这种过长的名字我们可以手动添加一个`终末(弓)`

**Comment by Arondight** [comment]
这里0.5是随便写的，晚上改一下，当时写的时候就想反正也要实际使用中调整，就随手写了一个看起来还行的

**Comment by Arondight** [comment]
昨天的修改之后又有不少别名成了毫无疑义的了，晚上清理一下

**Comment by citydirector** [comment]
武器也纳入一下？
![IMG_20211128](https://user-images.githubusercontent.com/45933075/143764678-ec49ed92-cc4e-4c99-82a5-92445b1f41ac.jpg)

**Comment by citydirector** [comment]
不对啊，按理来说应该不会触发的啊（）

**Comment by Arondight** [comment]
大概是写的逻辑有问题，明天再看吧，今天太累了

**Comment by Arondight** [comment]
哦，看了一下还真是，我把 undefined 压到权重里了，过会回去我用手机改改吧，累的不想开电脑了

**Comment by citydirector** [comment]
没事，明天再弄也行（）

**Comment by Arondight** [comment]
@citydirector 拉一下代码

**Comment by citydirector** [comment]
> @citydirector 拉一下代码

正确地解决了BUG √
