### ISSUE TITLE
如何配置多个Cookie

### ISSUE THREAD

**Issue by xiguadoudou** [Arondight/Adachi-BOT#42]
一个cookie上限之后怎么自己切换下一个，都写在里面他不会自动换，上限了只能手动删

**Comment by Arondight** [comment]
可以自动切换的，详见 #33

**Comment by xiguadoudou** [comment]
好的，谢谢了

**Comment by Arondight** [comment]
之前的策略，是 cookie 池中，每次查询随机到一个 cookie，现在是保证每个 cookie 查满 30 个依次使用，如果代码较旧建议使用最新代码。如果查询出现问题，再查一次就可以了。新代码 cookie 利用率也较高，尽量保持 bot 按时更新。

**Comment by xiguadoudou** [comment]
我是萌新云端更新没研究明白，只能手动下载替换

**Comment by Arondight** [comment]
> 我是萌新云端更新没研究明白，只能手动下载替换

按照 cookie.yml 的注释格式，每行一个 cookie，依次罗列即可，随后重启 bot 就会载入所有 cookie

**Comment by xiguadoudou** [comment]
这我知道，现在就是不会云端更新

**Comment by xiguadoudou** [comment]
![7f8264867e0c1c86](https://user-images.githubusercontent.com/89190859/130482579-fb8cd5ab-a6ec-41af-a123-b77611eb7e4e.jpg)
我是这么弄的，但是他还是只会使用一个，就只会读到一个cookie

**Comment by 490720818** [comment]
> ![7f8264867e0c1c86](https://user-images.githubusercontent.com/89190859/130482579-fb8cd5ab-a6ec-41af-a123-b77611eb7e4e.jpg)
> 我是这么弄的，但是他还是只会使用一个，就只会读到一个cookie

![image](https://user-images.githubusercontent.com/33067490/130488738-ac3c3a0c-8888-4a1d-9468-e7a5ceeaadbd.png)

**Comment by Arondight** [comment]
@xiguadoudou `#` 开头的行是注释，代表这一行只是说明，没有实际作用，你需要把注释打开，就是把`#`删掉

**Comment by Jasondrain1024** [comment]
你好，问一下怎么获取这么多的cookie？ 现在自己的cookie太少 群友们玩一会就上限了。。

**Comment by xiguadoudou** [comment]
> 你好，问一下怎么获取这么多的cookie？ 现在自己的cookie太少 群友们玩一会就上限了。。

一个号获取一个，去多买点号，每个都获取一遍

**Comment by Arondight** [comment]
> 
> 
> 你好，问一下怎么获取这么多的cookie？ 现在自己的cookie太少 群友们玩一会就上限了。。

某宝一块五一个，163 邮箱的就行，改下邮箱和米游社密码

**Comment by miao-shi** [comment]
![image](https://user-images.githubusercontent.com/47521506/131248832-a14e0959-ba15-4b67-9840-dba7fe7eee68.png)
请问cookie怎么获取，我在浏览器和手机上抓的都不行

**Comment by 490720818** [comment]
> ![image](https://user-images.githubusercontent.com/47521506/131248832-a14e0959-ba15-4b67-9840-dba7fe7eee68.png)
> 请问cookie怎么获取，我在浏览器和手机上抓的都不行

浏览器访问https://bbs.mihoyo.com/ys/
登录账号
F12开发者模式
![image](https://user-images.githubusercontent.com/33067490/131248899-4aa4cdb7-307f-42b2-9c6e-387160232590.png)

**Comment by miao-shi** [comment]
> > ![图片](https://user-images.githubusercontent.com/47521506/131248832-a14e0959-ba15-4b67-9840-dba7fe7eee68.png)
> > 比如cookie怎么获取，我在浏览器和手机上抓的都不行
> 
> 浏览器访问https://bbs.mihoyo.com/ys/
> 登录账号
> F12开发者模式
> ![图片](https://user-images.githubusercontent.com/33067490/131248899-4aa4cdb7-307f-42b2-9c6e-387160232590.png)

我就是这样抓的，但还是用不了

**Comment by 490720818** [comment]
> > > ![图片](https://user-images.githubusercontent.com/47521506/131248832-a14e0959-ba15-4b67-9840-dba7fe7eee68.png)
> > > 比如cookie怎么获取，我在浏览器和手机上抓的都不行
> > 
> > 
> > 浏览器访问https://bbs.mihoyo.com/ys/
> > 登录账号
> > F12开发者模式
> > ![图片](https://user-images.githubusercontent.com/33067490/131248899-4aa4cdb7-307f-42b2-9c6e-387160232590.png)
> 
> 我就是这样抓的，但还是用不了

那是不是配置问题格式如下
![image](https://user-images.githubusercontent.com/33067490/131249146-9e0042ce-87ae-4634-97a9-2b5c5367fbc0.png)

**Comment by miao-shi** [comment]
> > > > ![图片](https://user-images.githubusercontent.com/47521506/131248832-a14e0959-ba15-4b67-9840-dba7fe7eee68.png)
> > > > 等cookie怎么获取，我在浏览器和手机上抓不行
> > > 
> > > 
> > > 浏览器访问https://bbs.mihoyo.com/ys/
> > > 登录账号
> > > F12开发者模式
> > > ![图片](https://user-images.githubusercontent.com/33067490/131248899-4aa4cdb7-307f-42b2-9c6e-387160232590.png)
> > 
> > 
> > 我这样就是抓的，但还是用不了
> 
> 那是不是配置问题格式如下
> ![图片](https://user-images.githubusercontent.com/33067490/131249146-9e0042ce-87ae-4634-97a9-2b5c5367fbc0.png)

还是不行，其他插件正在用的cookie（也是米游社的）复制过来也用不了

**Comment by Arondight** [comment]
看看是不是有中文空格、中文换行符、QQ复制因为表情转换导致的字段丢失等，你这并不是 Cookie 无效，是文件中有非法字符

**Comment by miao-shi** [comment]
还是不行，各种方法抓的cookie都不行

**Comment by Arondight** [comment]
> 
> 
> 还是不行，各种方法抓的cookie都不行

`git diff config` 看一看，肯定是你的这个文件出了什么问题

**Comment by Arondight** [comment]
@miao-shi @490720818 #83 https://github.com/Arondight/Adachi-BOT/issues/81#issuecomment-916632341
