### ISSUE TITLE
npm i 失败

### ISSUE THREAD

**Issue by citydirector** [Arondight/Adachi-BOT#422]
### 问题描述

![image](https://user-images.githubusercontent.com/45933075/142832881-486a5f0b-9183-4434-a765-15bd2d778fd7.png)
![image](https://user-images.githubusercontent.com/45933075/142832022-5d43faac-ef86-43eb-a258-a382a52ce8ee.png)

### 复现流程

1

### 代码状态：当前提交

b040992202a676e089c0696cdd35ab424da28700 屏蔽 t.js

### 运行环境： Node.js 版本

v16.13 & v17.1

### 运行环境： npm 版本

8.1.2

### 运行环境：操作系统

Linux

**Comment by citydirector** [comment]
感觉像是漏了啥（）

**Comment by Arondight** [comment]
```
# npm show systeminformation version
5.9.15
```

**Comment by Arondight** [comment]
![图片](https://user-images.githubusercontent.com/13673702/142840883-49c4d178-1cba-42c1-bab8-7a4aa8f8f083.png)

你自己查一下吧

**Comment by citydirector** [comment]
头痛，不太会用这个工具，只会用来查查硬件信息（）

**Comment by Arondight** [comment]
> 头痛，不太会用这个工具，只会用来查查硬件信息（）

那你把 `5.19.15` 改成 `5.19.14` 不就行了

**Comment by citydirector** [comment]
不是很明白原因，`wget https://registry.npmjs.org/`任意内容都是ok的，但是npm的任何操作都是error400，然后用nvm卸载又重装了node16&17版本折腾来折腾去好像也不管用，当然也尝试过 `npm config rm http-proxy` `npm config rm https-proxy` `npm config set registry https://registry.npmjs.org` ，这不应该呀（指什么都没做npm突然就嗝屁了）

**Comment by Arondight** [comment]
啊这，你非得用最新的版本干啥，我就是顺手改的

**Comment by citydirector** [comment]
虽然有备份可以恢复，但是这玩意真的是有毒的
![image](https://user-images.githubusercontent.com/45933075/142853672-5d38fb4d-7572-49d5-8a13-5414b4346185.png)

**Comment by Arondight** [comment]
npm 配代理了吧，有的话给清了

**Comment by citydirector** [comment]
> 当然也尝试过 `npm config rm http-proxy` `npm config rm https-proxy` `npm config set registry https://registry.npmjs.org` 

前面试过了，莫得代理

**Comment by citydirector** [comment]
我开始怀疑是不是tcp端口动态范围被消耗完了

**Comment by Arondight** [comment]
不可能啊，`export ｜ grep -i npm` 看看

**Comment by citydirector** [comment]
> `export ｜ grep -i npm` 看看

emmmm
![image](https://user-images.githubusercontent.com/45933075/142855626-1ec365d9-7750-4a9b-b5aa-ddae5f3d2601.png)

**Comment by Arondight** [comment]
我用手机打的，切英文麻烦，你自己把竖线换成英文符号

**Comment by citydirector** [comment]
没有输出结果

**Comment by citydirector** [comment]
declare -x npm

**Comment by Arondight** [comment]
查不到就别纠结了，降个版本，改个数字的事

**Comment by citydirector** [comment]
好像真的是tcp端口号用完了...

**Comment by Arondight** [comment]
> 好像真的是tcp端口号用完了...

干啥了，听起来就跟 inode 用完了一样离谱，我感觉肯定是别的什么地方有问题，这玩意儿怎么可能用完

**Comment by citydirector** [comment]
我也觉得离谱，这个问题应该只出现在windows上才对...
但之前node的配置、系统代理(位于/etc/profile)都检查过没有任何问题，重启network.service也似乎没什么用...npm update都能报e400就非常离谱
最后无奈重启了服务器居然自己好了...

**Comment by citydirector** [comment]
神了，另一台服务器上自从Nov 17, 2021的版本之后一直没更新，然后刚刚也顺手更新了一下出现了同样的问题
