### ISSUE TITLE
「旅行者」详情页面布局异常

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#423]
声优太多了会溢出，又因为那个属性banner的位置是absolute，不会移动，导致重合
然后图像资源没有那个钻石碎片
最后给“周一二三”和“四五六日”中间加个换行符 \n 好了
![image](https://user-images.githubusercontent.com/9006264/142871659-666b9a29-6015-4fe6-9943-ed71394804c4.png)

**Comment by Arondight** [comment]
啊这，声优那就别写派蒙的了，周几直接写 `周一至周日`，钻我忘了从哔哩哔哩 wiki 扒图了

**Comment by Arondight** [comment]
生日怎么还是 `原子能量球` 啊

**Comment by Mark9804** [comment]
旅行者的生日就是玩家生日

https://github.com/Arondight/Adachi-BOT/blob/09852019892c94d3e44f51dcdcd825234a0d5fd0/resources/Version2/info/docs/%E6%97%85%E8%A1%8C%E8%80%85.json#L7

**Comment by Arondight** [comment]
啊这，那要不就写个空字符串吧

**Comment by Mark9804** [comment]
这个我来照猫画虎写一个吧，用[web api](https://github.com/takayama-lily/oicq/blob/main/web-api.md)抓用户生日，然后写进去
有了抓群头像的代码，抄一个应该不难，用法都差不多

**Comment by Mark9804** [comment]
可以暂时先改成空字符串，最近实在是没有时间了……

**Comment by Arondight** [comment]
应该不用这么搞，大概率引起误解，而且大多数丘丘用户也不知道自己瞎填的啥生日

**Comment by Arondight** [comment]
沃日，下载的 png 全都是 html

**Comment by Mark9804** [comment]
是直接`wget`了吗，bwiki 好像也没做反抓取啊

**Comment by Arondight** [comment]
我又浏览器邮件保存了一波，这次没问题了

**Comment by Mark9804** [comment]
虽然没有理解，但是右键应该可以直接下载的
![image](https://user-images.githubusercontent.com/9006264/142886642-c2d8550a-d670-47ee-a1ef-5bf0b890c9ce.png)

**Comment by Arondight** [comment]
![图片](https://user-images.githubusercontent.com/13673702/142886807-7888f4f4-efb5-4c32-b6a6-b57873a37246.png)

凑合能看了，暂时就这样吧

**Comment by Mark9804** [comment]
我把「旅行者」前面的点给去掉了，https://github.com/Arondight/Adachi-BOT/commit/1796120b6a2f6a5f3169306e7de20437ae9d5959 ，https://github.com/Arondight/Adachi-BOT/commit/c7233628d7f7ddd6688b18b473993b645ea51a87
