### ISSUE TITLE
“我的”前端页面结构优化

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#424]
- [x] 网页：使用 flexbox 而不是`position: relative`进行排版
- [x] 后端：寻找圣遗物图片与链接的映射关系，完全用本地图片替代米游社图片

> ![image](https://user-images.githubusercontent.com/9006264/142994110-ff51d278-aa86-40f6-adb6-83f33c4c67df.png)

_Originally posted by @Mark9804 in https://github.com/Arondight/Adachi-BOT/issues/178#issuecomment-976290905_

**Comment by Mark9804** [comment]
通用格式：`https://upload-bbs.mihoyo.com/game_record/genshin/equip/UI_RelicIcon_五位数ID_一位数部位.png`

| 圣遗物 | 部位 | 圣遗物套装ID | 部位 |
| ------ | ---- | ------------ | ---- |
| 魔女   | 花   | 15006        | 4    |
| 魔女   | 毛   | 15006        | 2    |
| 魔女   | 杯   | 15006        | 1    |
| 魔女   | 头   | 15006        | 3    |
| 乐团   | 沙   | 15003        | 5    |

待补充

**Comment by Arondight** [comment]
我觉得这个是不是应该后端来做？前端处理这个不太好吧

**Comment by Arondight** [comment]
我没明白为啥要有一个对应关系，不是简单的替换 url 的 domain 就可以吗

**Comment by Mark9804** [comment]
> 对应关系

就是替换url的意思，我在找某个米游社链接应该对应哪一个圣遗物，然后我们本地不是有所有圣遗物的图片么，这样就不用去请求米游社的数据了，速度可以提升很多

但是武器图片我们好像没有这个样式的，所以只能向米游社请求一张武器图。就算这样也把六个请求精简成一个了，六倍的提升

**Comment by Mark9804** [comment]
这个步骤在后端能做，前端也能做，老大哥要是不想接这个锅就我来，想接这个锅我就甩给你。这个步骤可有可无，唯一的优势是加快渲染速度

**Comment by Arondight** [comment]
哦，就是我们的数据中圣遗物 url 用了 id ，但是我们本地存放圣遗物用的名字对吧

**Comment by Arondight** [comment]
我知道是啥了，例如魔女，套装把 `15006` 换成 `3` ，部位把 `4/2/5/1/3` 换成 `0/1/2/3/4` 就可以了，我感觉再资源目录里面维持一个 json 比较好，然后呢，在 json 中找到对应，那就替换，找不到，返回原始路径，应该后端直接处理数据比较合理

**Comment by Mark9804** [comment]
我们的圣遗物图片的路径虽然是`圣遗物套装ID/圣遗物部位ID`，
例：
```
/resources/Version2/artifact/6/0.png
                             ↑ ↑
                          套装  部位
```
但是米游社的套装ID、部位ID和我们是不一样的
```
UI_RelicIcon_15006_4.png
               ↑   ↑
```
所以如果要使用本地的圣遗物图片的话，我们需要做这个替换

**Comment by Mark9804** [comment]
> 感觉再资源目录里面维持一个 json 比较好

这个json可以定期通过解析 https://genshin.honeyhunterworld.com/db/artifact/?lang=CHS 的网页源代码进行更新

**Comment by Arondight** [comment]
你先处理一下前端渲染问题，数据我来做，咱俩工作互不影响，双方都做完，就完成了

**Comment by Mark9804** [comment]
前端已经改好了，现在文字个个都是钉子户
![image](https://user-images.githubusercontent.com/9006264/143187915-3d961eda-5b65-44c7-9635-e2e644f236d0.png)

**Comment by Arondight** [comment]
你先提上去吧，后端我还一点都没搞
