### ISSUE TITLE
【圣遗物评分】能添加评分记录嘛？

### ISSUE THREAD

**Issue by DongGua-Jun** [Arondight/Adachi-BOT#425]
### 问题描述

评分记录后可以生成排行榜（按部位划分

甚至再细化出 群（各部位）排行榜 和 bot记录的总（各部位）排行榜

### 代码状态：当前提交

git log -1 --format=oneline

**Comment by Arondight** [comment]
当前的评分本来就不准确，排行榜也没啥意义，现在的评分系统表现太差了，我还拿它没有办法

**Comment by Arondight** [comment]
每个QQ记录一个最高分，总排名不好做，总不能把QQ号打出来

**Comment by Mark9804** [comment]
你要找的是不是这个
https://genshin.pub/relic
![image](https://user-images.githubusercontent.com/9006264/143041307-c6a63dd1-cb98-4a66-b5f4-e44e40b183ff.png)

**Comment by DongGua-Jun** [comment]
> 每个QQ记录一个最高分，总排名不好做，总不能把QQ号打出来

可以记录当时的名片，或记录评分人的游戏UID？（如果他有绑定的话

**Comment by Arondight** [comment]
uid也是隐私吧，只记录名片倒是可以

**Comment by Arondight** [comment]
虽然这个功能很简单，我还是想优先级放低，数据库没加一个靠谱的可选后端之前我心里不踏实

**Comment by DongGua-Jun** [comment]
> 虽然这个功能很简单，我还是想优先级放低，数据库没加一个靠谱的可选后端之前我心里不踏实

先挖个坑.png

**Comment by Arondight** [comment]
#732 因为无力给出一个合理的评分计算，所以将会改用词条数描述，所以这个也不做了
