### ISSUE TITLE
render： genshin-package 功能绘图失败：Error: Node has 0 height

### ISSUE THREAD

**Issue by simo8102** [Arondight/Adachi-BOT#435]
### 问题描述

render： genshin-package 功能绘图失败：Error: Node has 0 height

### 复现流程

render： genshin-package 功能绘图失败：Error: Node has 0 height

### 后台日志

```Text
render： genshin-package 功能绘图失败：Error: Node has 0 height
```

### 代码状态：当前提交

render： genshin-package 功能绘图失败：Error: Node has 0 height

### 运行环境： Node.js 版本

最新

### 运行环境： npm 版本

最新

### 运行环境：操作系统

Linux

**Comment by Arondight** [comment]
代码提交是哪个？

**Comment by Arondight** [comment]
有问题 reopen
