### ISSUE TITLE
深渊战绩和角色信息查询功能已废

### ISSUE THREAD

**Issue by Xm798** [Arondight/Adachi-BOT#436]
![1](https://user-images.githubusercontent.com/48074861/143379635-bcc7b59b-006a-4c76-91bd-e2c6c1e3d421.jpg)

**Comment by Mark9804** [comment]
米忽悠，你把人变成鬼

这么一来，不光是我们项目，深渊黑白榜也全爆炸了啊

**Comment by Xm798** [comment]
> 米忽悠，你把人变成鬼
> 
> 这么一来，不光是我们项目，深渊黑白榜也全爆炸了啊

是的 深渊排行也无了

**Comment by Mark9804** [comment]
#399 

https://github.com/Arondight/Adachi-BOT/issues/399#issuecomment-970196910
> 我感觉这个问题发生的原因很大可能是使用了非本人cookie

什么嘛，我猜bug原因还蛮准的……

**Comment by Mark9804** [comment]
我还没想好措辞，我现在用的是这个

https://github.com/Mark9804/Adachi-BOT/commit/e0ca541a7f723127febdcee964dfa66cf9deacf5

**Comment by Arondight** [comment]
估计得改改深渊样式了，游戏公司方面不太可能改了，这数据估计耽误赚钱了

**Comment by Mark9804** [comment]
Ref #404 

不知道会不会进一步限制

**Comment by Mark9804** [comment]
完全废掉的功能有：

* `我的`，那么 #424 的后端部分就可以暂时不做了

半残的功能有：

* `米游社`
* `深渊`

以上功能都只要改前端，只有我受伤的世界完成了

**Comment by Arondight** [comment]
做还是要做的，就还得把提示信息改改了

**Comment by Arondight** [comment]
我下午把代码打个 tag ，省的以后官方反复横跳找起来难受

**Comment by Arondight** [comment]
这周先看看黑白榜怎么处理这件事，这俩如果改成自行上传 cookie ，那基本上就没办法了，后续再看看要不要跟进，如果 cookie 满天飞那我们死活不做这功能也没意义，这个加起开倒是好加

**Comment by Xm798** [comment]
大概是前几天的那个小程序吧，搞账号估价，还拿来盈利，搞的规模太大了

**Comment by Xm798** [comment]
> 这周先看看黑白榜怎么处理这件事，这俩如果改成自行上传 cookie ，那基本上就没办法了，后续再看看要不要跟进，如果 cookie 满天飞那我们死活不做这功能也没意义，这个加起开倒是好加

自行上传肯定是不会传的……

**Comment by Arondight** [comment]
> 大概是前几天的那个小程序吧，搞账号估价，还拿来盈利，搞的规模太大了

跟这个没关系，单纯是游戏公司不太行，角色做的不平衡，所以也不敢放数据。魔兽世界一直开放英雄榜和各种榜单也没见因为这事黄了，玩魔兽大家都是月卡不服你也练一个，玩原神不行，你知道几千块钱抽的没人白嫖的厉害就会不开心。单纯是游戏质量有问题，不应该指责那个小程序，他只不过统计了官方的公开数据

**Comment by Xm798** [comment]
> > 大概是前几天的那个小程序吧，搞账号估价，还拿来盈利，搞的规模太大了
> 
> 跟这个没关系，单纯是游戏公司不太行，角色做的不平衡，所以也不敢放数据。魔兽世界一直开放英雄榜和各种榜单也没见因为这事黄了，玩魔兽大家都是月卡不服你也练一个，玩原神不行，你知道几千块钱抽的没人白嫖的厉害就会不开心。单纯是游戏质量有问题，不应该指责那个小程序，他只不过统计了官方的公开数据

但不能否认的是那个小程序确实引起了很多氪佬的不满…而氪佬都是有专属客服的

**Comment by Arondight** [comment]
所以目前来说我们的 bot 在查询官方数据这块意义就比较小了，以后我会想想还有什么能做的事情，不过好在还能查一点零星的数据，如果以后数据进一步管制的话，估计各种项目都会没啥用了，那时候我就把这个项目归档了

**Comment by MiniGrayGay** [comment]
> 米忽悠，你把人变成鬼
> 
> 这么一来，不光是我们项目，深渊黑白榜也全爆炸了啊

提交深渊战绩时顺带提交ltuid和login_ticket（雾）

**Comment by Mark9804** [comment]
深渊这边查询也返回了一些让vue无法渲染的数据，我晚上回来看看
```
TypeError: Cannot read properties of undefined (reading 'levels')
```
```json
{
    "uid": 123456789,
    "data":
    {
        "schedule_id": 34,
        "start_time": "1637006400",
        "end_time": "1638302399",
        "total_battle_times": 16,
        "total_win_times": 12,
        "max_floor": "11-3",
        "reveal_rank": [
        {
            "avatar_id": 10000036,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Chongyun.png",
            "value": 12,
            "rarity": 4
        },
        {
            "avatar_id": 10000005,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_PlayerBoy.png",
            "value": 12,
            "rarity": 5
        },
        {
            "avatar_id": 10000021,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ambor.png",
            "value": 12,
            "rarity": 4
        },
        {
            "avatar_id": 10000039,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Diona.png",
            "value": 12,
            "rarity": 4
        }],
        "defeat_rank": [
        {
            "avatar_id": 10000052,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Shougun.png",
            "value": 65,
            "rarity": 5
        }],
        "damage_rank": [
        {
            "avatar_id": 10000052,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Shougun.png",
            "value": 72204,
            "rarity": 5
        }],
        "take_damage_rank": [
        {
            "avatar_id": 10000052,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Shougun.png",
            "value": 264149,
            "rarity": 5
        }],
        "normal_skill_rank": [
        {
            "avatar_id": 10000052,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Shougun.png",
            "value": 113,
            "rarity": 5
        }],
        "energy_skill_rank": [
        {
            "avatar_id": 10000036,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Chongyun.png",
            "value": 66,
            "rarity": 4
        }],
        "floors": [
        {
            "index": 9,
            "icon": "",
            "is_unlock": true,
            "settle_time": "0",
            "star": 9,
            "max_star": 9,
            "levels": []
        },
        {
            "index": 10,
            "icon": "",
            "is_unlock": true,
            "settle_time": "0",
            "star": 8,
            "max_star": 9,
            "levels": []
        },
        {
            "index": 11,
            "icon": "",
            "is_unlock": true,
            "settle_time": "0",
            "star": 4,
            "max_star": 9,
            "levels": []
        }],
        "total_star": 21,
        "is_unlock": true
    }
}
```

**Comment by Arondight** [comment]
我感觉先临时处理一下吧，好像只有米游社不让看了，也可能是个暂时性的，可怜的白榜是死翘翘了，黑榜倒是没影响

**Comment by Arondight** [comment]
我刚发了个版当归档用了，以后如果官方放开数据改回来也方便

**Comment by JDYuuki** [comment]
说是暂不支持，真要大规模 cookie 自由估计 mhy 更头疼

**Comment by Mark9804** [comment]
肯定对外说是“暂”不支持呀，但是究竟会暂多久呢，话语权就掌握在mhy手上了
就像睿叔叔暂不支持海外IP直播暂了两年，现在也可以继续暂下去

我稍微改了一下深渊是否存在详细楼层信息的判断， https://github.com/Mark9804/Adachi-BOT/commit/4941ed895b50b0a5fe4e652cb3b437bec02243e3 ，
但是具体文案要怎么写让用户能看懂我还在考虑，
因为假如我们说“mhy已禁止查询他人信息”，用户会很迷惑，我明明查的是我自己的号啊怎么就成他人了

米游社那边就很怪异，能查到几个人的，但是不能查看全部角色。我考虑在角色的 container 后面跟一句说明，但是这句说明应该怎么写我也没想好

**Comment by Arondight** [comment]
hoyolab 也改了，看来是不会改回去了

https://bbs.nga.cn/read.php?tid=29588712

**Comment by Arondight** [comment]
所以不要考虑怎么说明了，以后直接改一下布局吧，只显示官方让显示的数据

**Comment by Mark9804** [comment]
我在`dev`分支屏蔽了精确到层的数据模块，如果没有查询到floor信息的话，就不会显示；如果将来米爹大发慈悲放开了，这个网页也会立刻响应变化

![image](https://user-images.githubusercontent.com/9006264/143403642-a1352435-255d-4643-9aef-9b63ceec1297.png)

我现在想把横向排版的网页改成纵向，还好当时重写的比较早，现在只要改最外层 container 的排列参数然后微调一下其他边距就可以了，但是`米游社`的页面我暂时拿它没有办法

**Comment by Arondight** [comment]
@Mark9804 做得好啊老大哥，另外我看黑榜公告似乎他们不死心的样子，或许未来还有转机吧

**Comment by ixCiel** [comment]
突然就被限制了，我fork的只好加了私人Cookie判断。用自己的Cookie是可以查的，而且数据和接口完全一致Orz

**Comment by citydirector** [comment]
闲来无事，做点别的插件玩玩吧（悲）

**Comment by Mark9804** [comment]
> 闲来无事

也不能算闲来无事， Arondight 想要整合一个正经数据库，我要对米游社和深渊前端下手了，短时间内应该不会有什么新功能做出来，但是如果你有什么好想法的话之后说不定也会做的

**Comment by Arondight** [comment]
> 只好加了私人Cookie判断

如果最后搞成 cookie 满天飞，大家都开始满不在乎地把 cookie 交给各种网站，那我再坚持也就没意义了，不过我还是不希望有那一天把，用隐私换方便我不反对，用安全换方便我就比较抵触了

**Comment by KimigaiiWuyi** [comment]
可以参考一下[我的](https://github.com/KimigaiiWuyi/GenshinUID/issues/34)
还有待测试

**Comment by Mark9804** [comment]
> 可以参考一下[我的](https://github.com/KimigaiiWuyi/GenshinUID/issues/34) 还有待测试

是 https://github.com/KimigaiiWuyi/GenshinUID/commit/82ad1efb19837dbbded18f066e921e8f1fe553bf 这个commit吗？

**Comment by KimigaiiWuyi** [comment]
> > 可以参考一下[我的](https://github.com/KimigaiiWuyi/GenshinUID/issues/34) 还有待测试
> 
> 是 [KimigaiiWuyi/GenshinUID@82ad1ef](https://github.com/KimigaiiWuyi/GenshinUID/commit/82ad1efb19837dbbded18f066e921e8f1fe553bf) 这个commit吗？

是的，可以只看`getImg.py`的改动

**Comment by Mark9804** [comment]
> 是的，可以只看`getImg.py`的改动

感谢，虽然看起来相当暴力，但是也提供了一种可能性

**Comment by KimigaiiWuyi** [comment]
> 

是可以正常获取到所有信息，唯一的疑虑就是，会不会因为多线程，被mhy当成DDos然后banip

**Comment by Arondight** [comment]
大致看了一下，周末再说吧，每个 uid 大概得查四五十次，查多了不知道 bot 还能活着么

**Comment by Arondight** [comment]
我觉得这个接口应该是不会被改的，至少有了一种获取数据的方法，周末我看有空就跟进一下

**Comment by Arondight** [comment]
@KimigaiiWuyi 你那里如果使用有异常的话麻烦说一下，毕竟短时间内几个人查这就是二三百次请求，我担心有点多了

**Comment by KimigaiiWuyi** [comment]
> @KimigaiiWuyi 你那里如果使用有异常的话麻烦说一下，毕竟短时间内几个人查这就是二三百次请求，我担心有点多了

我是小群用，群成员加起来不过六十多个，不可能会有那么大的请求量，我主要是怕其他用户用了会被BanIP，所以想请你们测一测，（顺带防一手mhy玩不起，八个线程就给我BanIP）

**Comment by KimigaiiWuyi** [comment]
> > @KimigaiiWuyi 你那里如果使用有异常的话麻烦说一下，毕竟短时间内几个人查这就是二三百次请求，我担心有点多了
> 
> 我是小群用，群成员加起来不过六十多个，不可能会有那么大的请求量，我主要是怕其他用户用了会被BanIP，所以想请你们测一测，（顺带防一手mhy玩不起，八个线程就给我BanIP）

但不开多线程就十分慢了，所以这方面我就分享出来，这边人多可以多测试，但还是希望不要大范围传播（虽然大多数人迟早会知道）

**Comment by Arondight** [comment]
那几乎不用测了，肯定会被ban 的，用 bot 群用户数量从几百到一两万的都有，八线程都被ban 了，那肯定跑不了

**Comment by KimigaiiWuyi** [comment]
> 那几乎不用测了，肯定会被ban 的，用 bot 群用户数量从几百到一两万的都有，八线程都被ban 了，那肯定跑不了

我的意思是 我没被ban，但是怕

**Comment by Arondight** [comment]
原来如此，我有空搞一下，主要是我被ban了之后也挺麻烦的，我想周末先看一下黑白榜的反应吧，另外似乎你这直接挂个脚本跑一下压测也可以知道是不是会被ban，就是无论公司还是vps被ban就很难受

**Comment by Mark9804** [comment]
白榜黑榜也有大量请求的需要，他们是怎么做到的，服务器集群吗？我感觉他们不像是有钱到不在意这个支出的团队

因为他们的数据不要求这么精确的时效性，我猜测他们的做法是把请求数量在某个时段（比如全天）之内平均分配，我们是不是可以效仿这种做法？就像搜索引擎一样，先用 spider 把全网数据扒下来，用户发送查询请求的时候使用这些缓存来处理用户请求

换句话说，以后用户查询`米游社`就真的是在纯调用缓存了，
不过看起来`我的`这个功能给这么一整是可以复活的，直接通过角色名查表获得角色ID，然后向对应API发送请求就可以了

**Comment by KimigaiiWuyi** [comment]
> 原来如此，我有空搞一下，主要是我被ban了之后也挺麻烦的，我想周末先看一下黑白榜的反应吧，另外似乎你这直接挂个脚本跑一下压测也可以知道是不是会被ban，就是无论公司还是vps被ban就很难受

无论VPS还是公司或者家里的IP 我都不想被Ban，只能push到开源社区让大家评估一下了；
另外黑白榜无论难不难受，从这次国际服同步那么快看来，mhy估计不可能放出深渊信息查询了（只是我感觉）；
第三点是这个方法既然能用，那当然要想想怎么保护好，而不是瞬间几千个访问，让mhy第二天就封掉，所以希望各位测试谨慎点；
第四点是，也许可以不用暴力遍历，有方法可以先获取到前8个，然后再把常见4星（御三家+国家队）给获取了，剩下的再遍历

**Comment by Arondight** [comment]
@MiniGrayGay 小白鼠来了

![C85DE140-58D0-41F3-824B-5E6E4B30E6A0](https://user-images.githubusercontent.com/13673702/143470552-f1de0919-547c-4963-ac53-37042a94324d.jpeg)

**Comment by Arondight** [comment]
@SilveryStar 老大哥瞅一瞅

**Comment by KimigaiiWuyi** [comment]
> @MiniGrayGay 小白鼠来了
> 
> ![C85DE140-58D0-41F3-824B-5E6E4B30E6A0](https://user-images.githubusercontent.com/13673702/143470552-f1de0919-547c-4963-ac53-37042a94324d.jpeg)

我和小灰灰今天下午就在研究了（

**Comment by Arondight** [comment]
哈哈哈，你扯上灰灰那还保护了个啥，他其中一个 bot 就快六万个用户，分分钟上千请求不是小意思 🤣

**Comment by citydirector** [comment]
怎么看封账号的概率都比封ip概率大的多

**Comment by KimigaiiWuyi** [comment]
> 哈哈哈，你扯上灰灰那还保护了个啥，他其中一个 bot 就快六万个用户，分分钟上千请求不是小意思 🤣

正常测试没办法，以后总会有人发现这个方法的

**Comment by Mark9804** [comment]
我觉得我们重新思考一下`米游社`这个功能的需求场景吧

我群里使用`米游社`的更多作用主要是用来“更新角色数据”，然后才是“查看自己已经拥有的角色图鉴”，最后是“查看自己的统计数据”

那么从这个角度来说的话，我们也许不需要强行认为【只要有用户发送`米游社`指令，我们就必须给他一个完整的角色列表】

比如说啊，比如说，我们的功能调整成只有当用户输入是`米游社 --all`的时候才强制获取一遍用户的所有角色信息，剩下的时候我们只需要给他返回八个角色，就足够了。当用户使用`我的`指令的时候，先看一看这八个角色里面有没有他的，如果没有，那么再用这个方法请求对应的角色，然后缓存进这个用户的数据库当中

**Comment by SilveryStar** [comment]
我的看法在这 https://github.com/SilveryStar/Adachi-BOT/issues/116#issuecomment-979316672
~~说实话研究怎么减少查询次数不如研究怎么在cookie可查询数据的情况下保障账户安全~~
这个能多塞id的方法说实话也不大行，毕竟他这一个缺了都不行

**Comment by Arondight** [comment]
> 我们重新思考一下`米游社`这个功能

我大致的想法就跟之前说的一样，如果最后就只能查很有限的数据了，cookie 满天飞，那我也会加 cookie 收集，如果没有 cookie 满天飞，那就先这样。至于这个新发现的奇怪方法，我先等灰灰测完的

**Comment by Mark9804** [comment]
其余的时候我们在`settings.yml`里面加一个`lazyload`（？随便起的，我喜欢这个名字）的字段，设置成`0`的时候不干活，设置成`1`的时候，bot就在空闲时间按照一定间隔慢慢轮询用户的角色

cookie前段时间才刚泄漏出来一堆，我大概看了一下，虽然大部分都是脚本号，但其中还是有一些正常玩家的，我们应该作为前车之鉴

> 我觉得我们重新思考一下`米游社`这个功能的需求场景吧
> 
> 我群里使用`米游社`的更多作用主要是用来“更新角色数据”，然后才是“查看自己已经拥有的角色图鉴”，最后是“查看自己的统计数据”
> 
> 那么从这个角度来说的话，我们也许不需要强行认为【只要有用户发送`米游社`指令，我们就必须给他一个完整的角色列表】
> 
> 比如说啊，比如说，我们的功能调整成只有当用户输入是`米游社 --all`的时候才强制获取一遍用户的所有角色信息，剩下的时候我们只需要给他返回八个角色，就足够了。当用户使用`我的`指令的时候，先看一看这八个角色里面有没有他的，如果没有，那么再用这个方法请求对应的角色，然后缓存进这个用户的数据库当中

**Comment by Arondight** [comment]
> 研究怎么减少查询次数不如研究怎么在cookie可查询数据的情况下保障账户安全

其实这个意义是不大的，因为我们是在做开源项目，并不是一个网站或者微信小程序

**Comment by SilveryStar** [comment]
那这个只能说，实在是没办法……深渊那边的事把这些都搞没了。另外在我看来，就算短时间内这种多线程硬查的办法可行，mhy那边也迟早会管……

**Comment by KimigaiiWuyi** [comment]
> 那这个只能说，实在是没办法……深渊那边的事把这些都搞没了。另外在我看来，就算短时间内这种多线程硬查的办法可行，mhy那边也迟早会管……

我是这么想的，如果真是深渊那边的问题，那查角色其实对mhy影响不大？当然mhy是自由的，想封随时都能封，我和灰灰讨论了一下，觉得`缓存`是个不错的机制，毕竟角色只会多而不会少，数据库需要存好每个uid的角色列表，这样只需要第一次查询 需要遍历了

**Comment by SilveryStar** [comment]
> 觉得`缓存`是个不错的机制

这倒也是一种可行的策略……我再思考一下吧，主要还是一方面在大群什么情况都可能发送，得想想遍历数据的更合适的时机。另一方面我这边的项目也是资源全线上的，要考虑的地方还是比较多…… ~~我先溜了，早八高数~~

**Comment by MiniGrayGay** [comment]
> 

但是开箱即用的存储数据办法对于这样子的大量数据io好像没有比较完美的方案。如果是Linux上的话，感觉目前silvery用的redis应该是部署速度最快+性能最好的办法了

**Comment by MiniGrayGay** [comment]
Bot号目前虽然被企鹅封了，封之前是接近500个群，6w+群友，用体力查询功能的人在1k左右

**Comment by Xm798** [comment]
> 白榜黑榜也有大量请求的需要，他们是怎么做到的，服务器集群吗？我感觉他们不像是有钱到不在意这个支出的团队
> 
> 因为他们的数据不要求这么精确的时效性，我猜测他们的做法是把请求数量在某个时段（比如全天）之内平均分配，我们是不是可以效仿这种做法？就像搜索引擎一样，先用 spider 把全网数据扒下来，用户发送查询请求的时候使用这些缓存来处理用户请求
> 
> 换句话说，以后用户查询`米游社`就真的是在纯调用缓存了，
> 不过看起来`我的`这个功能给这么一整是可以复活的，直接通过角色名查表获得角色ID，然后向对应API发送请求就可以了

为什么需要服务器集群？直接用代理池不就好了……

**Comment by Mark9804** [comment]
> 为什么需要服务器集群？直接用代理池不就好了……

确实，可能当时脑子抽了

**Comment by Xm798** [comment]
> > 为什么需要服务器集群？直接用代理池不就好了……
> 
> 确实，可能当时脑子抽了

其实如果真的需要这么做的话，上代理池就好了，例如[proxy_pool](https://github.com/jhao104/proxy_pool)，用多个 cookie 分别用不同的代理 ip 轮询。

**Comment by KimigaiiWuyi** [comment]
> > 觉得`缓存`是个不错的机制
> 
> 这倒也是一种可行的策略……我再思考一下吧，主要还是一方面在大群什么情况都可能发送，得想想遍历数据的更合适的时机。另一方面我这边的项目也是资源全线上的，要考虑的地方还是比较多…… ~我先溜了，早八高数~

突然想起来，昨晚忘说了，`https://api-takumi.mihoyo.com/game_record/app/genshin/api/character`这个API，好像现在只能一次发送八个id的请求，也就是说，即使有了缓存列表，想读也略麻烦……

**Comment by SilveryStar** [comment]
> `https://api-takumi.mihoyo.com/game_record/app/genshin/api/character`这个API，好像现在只能一次发送八个id的请求

那……我还是走 cookie 收集这条路吧……

**Comment by Arondight** [comment]
@MiniGrayGay 所以你那里最终怎么搞的

**Comment by Arondight** [comment]
问了下灰灰的情况，我觉得这个功能可以做

**Comment by Arondight** [comment]
https://stackoverflow.com/a/52262024

**Comment by Arondight** [comment]
现在已经可以正常查询角色，使用中的问题麻烦直接在此处留言

**Comment by Arondight** [comment]
关于缓存，不知道有没有什么比较好的办法可以做到缓存后自动更新角色，增加一条新命令（如更新角色列表）会极大降低易用性

**Comment by Arondight** [comment]
或许可以缓存上一次查询成功的结果，每次除了查询缓存外，其余的角色都轮询一遍，这样就可以自动更新了，但是查询次数减少的不是很多，大概能够减半吧

**Comment by Arondight** [comment]
加了一小会班把我上个回复中说的缓存机制做好了，使用过程中有问题麻烦各位在这里直接回复。

@KimigaiiWuyi @MiniGrayGay 这个缓存逻辑我试了一下似乎用起来还可以，当然肯定不如分两个命令例如 `查询当前缓存列表` 和 `更新缓存列表` 查的次数少，但是这样一来就不用分两个命令了，只对外提供一个命令例如 `查询` 即可。以我的账号为例，一共有 33 个角色，按照我的逻辑读取缓存再查询，一共 1 + 3 + 1 + 10 = 15 次，减少了 43 - 15 = 28 次；按照你们设想的逻辑一共查询 4 + 1 = 5 次，减少了 43 - 5 = 38 次。当前我用的缓存逻辑多了 10 次查询，不过用起来方便一些。如果有更好的办法麻烦敲我一下

**Comment by Arondight** [comment]
不过这样查起来新人的角色就效率很差了，几乎没啥卵用

**Comment by KimigaiiWuyi** [comment]
> 加了一小会班把我上个回复中说的缓存机制做好了，使用过程中有问题麻烦各位在这里直接回复。
> 
> @KimigaiiWuyi @MiniGrayGay 这个缓存逻辑我试了一下似乎用起来还可以，当然肯定不如分两个命令例如 `查询当前缓存列表` 和 `更新缓存列表` 查的次数少，但是这样一来就不用分两个命令了，只对外提供一个命令例如 `查询` 即可。以我的账号为例，一共有 33 个角色，按照我的逻辑读取缓存再查询，一共 1 + 3 + 1 + 10 = 15 次，减少了 43 - 15 = 28 次；按照你们设想的逻辑一共查询 4 + 1 = 5 次，减少了 43 - 5 = 38 次。当前我用的缓存逻辑多了 10 次查询，不过用起来方便一些。如果有更好的办法麻烦敲我一下

缓存逻辑可以这样来做，看当前的缓存列表，和基本信息中的`已获得角色`是否相等，不相等则自动缓存一遍即可。

**Comment by Arondight** [comment]
> 和基本信息中的`已获得角色`是否相等

这个字段在哪里？

**Comment by KimigaiiWuyi** [comment]
> > 和基本信息中的`已获得角色`是否相等
> 
> 这个字段在哪里？

就是原先那个只能获得八个的API啊，那个api能拿到基本信息，以及八个角色；基本信息中有已获得角色一项

**Comment by Arondight** [comment]
> 基本信息中有已获得角色一项

🐮🍺

**Comment by Arondight** [comment]
@KimigaiiWuyi 是这个么

![E587671D-2F39-4643-BF7A-CF028C0B1CC3](https://user-images.githubusercontent.com/13673702/144039874-9b6b3e54-f8f7-45fd-af26-cc35d3cf40a5.jpeg)

**Comment by KimigaiiWuyi** [comment]
> @KimigaiiWuyi 是这个么
> 
> ![E587671D-2F39-4643-BF7A-CF028C0B1CC3](https://user-images.githubusercontent.com/13673702/144039874-9b6b3e54-f8f7-45fd-af26-cc35d3cf40a5.jpeg)

嗯对，这个获取的时效性是有保障的，可以和缓存的角色id目录做对比，是一个不错的方案

**Comment by Arondight** [comment]
坐等黑榜的深渊解决办法

![7E70D0A3-D648-47F3-A223-071B5F5C33D5](https://user-images.githubusercontent.com/13673702/144042994-8ab1128e-96cb-4199-a209-c81b3d276460.jpeg)

**Comment by Arondight** [comment]
我感觉这个是假的吧，上场角色是拿不到的，最多通过游戏内 orc 查看一下公开角色的练度

![D3F412C7-2E60-47DA-BB75-CB320FD6F871](https://user-images.githubusercontent.com/13673702/144158630-24879cf2-9e17-4695-b134-35bfc41636e4.jpeg)

**Comment by Mark9804** [comment]
看他的说法，似乎是在分析之前挑战数据的基础上，自己捣鼓了一个算法来计算角色使用情况

我猜测是让用户提供UID，然后从米游社API拿到上场角色的信息，综合现在深渊API返回的数据（主要应该是挑战次数，高光角色）判断用户12层打了几星
![image](https://user-images.githubusercontent.com/9006264/144159871-9e56303d-9ff8-4b0a-a285-029f7c86ee83.png)

**Comment by Arondight** [comment]
> 米游社API拿到上场角色的信息

这个拿不到吧？

**Comment by SilveryStar** [comment]
> 这个拿不到吧？

那个出战次数之类的数据是公开的，要自己查的是每一层的具体数据

**Comment by Arondight** [comment]
> 出战次数之类的数据是公开的

所以他不知道一个 uid 究竟用谁打深渊了嘛，只能查到四个上场最多角色、最多承伤等等，这些我感觉没法下结论

**Comment by Mark9804** [comment]
> > 米游社API拿到上场角色的信息
> 
> 这个拿不到吧？

比如说玩家上场的角色是神里修女天帝心海，我们知道这四个人的角色ID，那么就可以通过米游社API查到他们的等级，圣遗物和使用的武器

他们可能是默认9-10层是满的（或者不满的概率分布相对很低），然后通过问卷调查玩家12层打了多少颗星，就可以计算出玩家11层的星数，再与自己的算法模型生成的结果做比较

然后再说到为什么要调用米游社角色API，我觉得应该是为“11层没打满，12层也没打满”的情况考虑的，比如说米游社看到神罗天征四个人都只有60级，深渊这边痛苦了一百多次，星数也不是36，然后可能他们内部有一个数据模型，可以反推出一般这种情况下渊星的分布概率是怎么样的

> 要自己查的是每一层的具体数据

**Comment by Mark9804** [comment]
他们因为有大量数据可以用来做多因子分析所以可以建立模型，模型算法肯定是不会公开出来的，除非国服这边也有人用他们开放的数据和白榜开放的数据做同样的事情

我个人猜测是这样

**Comment by SilveryStar** [comment]
感觉这数据有点脏……

**Comment by Mark9804** [comment]
> 感觉这数据有点脏……

是说这个数据噪声太多还是来路不正？

**Comment by SilveryStar** [comment]
> 是说这个数据噪声太多还是来路不正？

是，而且就我个人看来往期的数据量也不足以得到准确度够高的模型……

**Comment by Mark9804** [comment]
> 就我个人看来往期的数据量也不足以得到准确度够高的模型……

这个就不知道他们的算法是怎样的了，主要还是看他们最终决定有哪些相关因素相关因素越多结果的误差越大，单说数据量的话，一万多份数据在我心理学专业这边做梦都能笑醒

**Comment by SilveryStar** [comment]
另外这个推算出来的结果是不是会随版本更迭越来越偏离实际数据啊……

**Comment by Mark9804** [comment]
> 另外这个推算出来的结果是不是会随版本更迭越来越偏离实际数据啊……

模型随时间推移有效性会降低，需要定期修正或者重新评估

**Comment by Arondight** [comment]
总之无论黑榜的算法准不准，对我们都没卵用了，深渊应该也做不了什么了，只能说充分展示一下能到手的数据吧，这个 issue 的问题解决了一半，另外一半没法解决，暂时关闭了

**Comment by Mark9804** [comment]
按照NGA的说法，外服深渊API又改回来了，我这边暂时没有可以用来验证的数据，总之我们也只能等了
https://bbs.nga.cn/read.php?tid=29722309

**Comment by Arondight** [comment]
不知道外网能查全部角色了没
