### ISSUE TITLE
适配米游社新的 API 数据以及其他

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#441]
### 问题描述

- [x] 新卡池 @Arondight 
- [x] 临时处理一下深渊网页，尽量能够显示打了几星 @Mark9804 
- [x] ~~调整一下米游社、uid 功能网页每行显示人物的个数（最大宽度）~~ @Mark9804 这个我感觉不用改，改完效果不会比现在好
- [ ] 处理一下米游社、uid 功能的说明 @Arondight 
- [x] 处理一下角色查询失败的文本 @Arondight 
- [x] 圣遗物图片 url 转换 @Arondight 
- [ ] 写一个版本升级 todo list 文档 @Arondight 
- [ ] 新版本的材料武器天赋图 @Arondight 

暂时想到了这些，随时补充，什么时候做随意

- [x] 把占卜用的数据源扒下来，做成 yaml

### 代码状态：当前提交

v1.5.1

**Comment by Mark9804** [comment]
**深渊网页**
截止到目前的dev commit ( 67e63bda607d3047447f1b119677212806f4f0d1 ) 已经能够很好的处理有楼层数据和没有楼层数据的情况了

刚刚改了一下竖屏，现在大概长这样，虽然个人不是很满意（比原来乱），但也不是不能看

<details>
<summary>有完整数据的情况……</summary>

![image](https://user-images.githubusercontent.com/9006264/143444768-070dd537-e173-418c-9e5a-196e96012e5d.png)
</details>

<details>
<summary>只有当前API返回的残缺数据的情况……</summary>

![image](https://user-images.githubusercontent.com/9006264/143444887-21469851-05cb-4a20-acd4-c7dd58650e36.png)
</details>

**Comment by Arondight** [comment]
辛苦老大哥，后续要是那几个最强击破啥的能做成一行就好了，如果不好改就算了，这个也不知道会有多久，后续如果米游社再开放查询我还是想回退到以前那个版本的样式上

**Comment by Mark9804** [comment]
深渊改起来相对比较容易，我还没想好要做成什么效果

米游社和UID不太好改，这两个网页除了看上去很正常之外哪里都不太正常
![image](https://user-images.githubusercontent.com/9006264/143449327-0655dab8-c88c-4bcd-8130-3152354fdfd4.png)

**Comment by Mark9804** [comment]
现在深渊样式是这样
![image](https://user-images.githubusercontent.com/9006264/143454558-5b1eb0d0-7fc2-4716-acbe-27d68474d310.png)

**Comment by Xm798** [comment]
> 现在深渊样式是这样 ![image](https://user-images.githubusercontent.com/9006264/143454558-5b1eb0d0-7fc2-4716-acbe-27d68474d310.png)

个人感觉啊 这个是不是有点长了（

**Comment by Mark9804** [comment]
> 个人感觉啊 这个是不是有点长了

我也这么觉得 但原来的感觉有点短了

**Comment by Arondight** [comment]
主要是大小有点不一致，看上去有点奇怪

**Comment by Mark9804** [comment]
要不就做成官方那样吧，打一张 3×4 的表，然后把头像什么的放上去
![image](https://user-images.githubusercontent.com/9006264/143467809-bb9a4115-7ac1-46fa-b60c-52b7d68d5f3e.png)

**Comment by Arondight** [comment]
我感觉这个也不急，我想看看黑白榜的反应，如果我们都适配完了，官方又加了个权限开关给改回来了，那也有点尴尬

**Comment by Mark9804** [comment]
米游社我大概弄明白这个网页是一个什么结构了，但是不知道怎么下手，不管是一排排两个还是四个还是干脆八个都和现在半斤八两

https://github.com/Arondight/Adachi-BOT/discussions/398#discussion-3687973 还是这个竖屏的好看，现在也不用担心图片过长的问题了，米忽悠帮我们解决了图片过长的问题
