### ISSUE TITLE
关于小群查询深渊以及米游社问题的建议

### ISSUE THREAD

**Issue by uyaddayu** [Arondight/Adachi-BOT#443]
### 问题描述

2种设想：
1、私聊机器人功能增加一个提交cookie功能，比如cookieadd uid cookie内容，存进redis或者写进文件里。后台得到查询该uid时，先判断有没有对应的cookie，有就使用私人cookie，没有就使用公用的cookie查询（内容不够就换UI展示）。
2、增加一个privateCookies.yml，专门让小群bot管理者收集uid对应cookie的文本信息存入到这个yml里，查询时先查这个文件是否有对应cookie，没有再用公用查询。
====
望采纳！！！

**Comment by Arondight** [comment]
我非到万不得已不会做这个功能，收集 cookie 是一件很糟糕的事情，而且这是一个开源项目，所有的安全防护都是没有意义的，换言之我们没法做出用户 cookie 不被滥用的保证
