### ISSUE TITLE
无法识别切换的目标卡池时，返回一个当前可用卡池的列表

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#444]
### 问题描述

例：
> ：卡池 test
> ：：您想要切换的卡池不存在。当前可用卡池为：角色、角色2、武器、常驻。
> ：卡池/卡池列表
> ：：当前可用卡池为：角色、角色2、武器、常驻。

**Comment by Arondight** [comment]
这个做不到，防止误触所以卡池命令也加入了候选词猜测，所以 `卡池test` 是没有响应的，只能说卡池不带参数打个列表出来把

**Comment by Arondight** [comment]
看了下代码搞错了，卡池没加候选词猜测，这个也得加上
