### ISSUE TITLE
求签功能这个凶签出现的概率有点太高了

### ISSUE THREAD

**Issue by sfycyh** [Arondight/Adachi-BOT#451]
### Discussed in https://github.com/Arondight/Adachi-BOT/discussions/448

<div type='discussions-op-text'>

<sup>Originally posted by **sfycyh** November 29, 2021</sup>
我觉得凶签和大吉的概率可以调低点</div>

**Comment by Mark9804** [comment]
现在好像所有签的内容都已经本地化了吧，可以自己改了

**Comment by Mark9804** [comment]
https://github.com/Arondight/Adachi-BOT/pull/442/commits/77264b96d51b74a2cc895378a10483a4f824b1b8 在这个commit，已经是本地化的内容了

**Comment by sfycyh** [comment]
ok，那我自己改配置文件吧
