### ISSUE TITLE
深渊前端所有显示模块都应该加上数据存在性检验

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#455]
### 问题描述

目前深渊API的行为不稳定，每个字段都有可能出现数组为空的情况，不应该信任`aby.json`中的结果。但是鉴于旧版本深渊布局并不是根据当前场景设计的，所以此 bug 不做处理，在新的深渊设计中再做考虑。
![85EA2818-CD0E-4DB5-AE00-5511C91FC9DD_1_102_o](https://user-images.githubusercontent.com/9006264/144200288-831484a9-6841-488e-be43-b264079c5c90.jpeg)
```
{
    "uid": 110009190,
    "data":
    {
        "schedule_id": 35,
        "start_time": "1638302400",
        "end_time": "1639598399",
        "total_battle_times": 11,
        "total_win_times": 10,
        "max_floor": "12-3",
        "reveal_rank": [],
        "defeat_rank": [],
        "damage_rank": [],
        "take_damage_rank": [],
        "normal_skill_rank": [],
        "energy_skill_rank": [],
        "floors": [
        {
            "index": 9,
            "icon": "",
            "is_unlock": true,
            "settle_time": "0",
            "star": 9,
            "max_star": 9,
            "levels": []
        },
        {
            "index": 10,
            "icon": "",
            "is_unlock": true,
            "settle_time": "0",
            "star": 9,
            "max_star": 9,
            "levels": []
        },
        {
            "index": 11,
            "icon": "",
            "is_unlock": true,
            "settle_time": "0",
            "star": 9,
            "max_star": 9,
            "levels": []
        },
        {
            "index": 12,
            "icon": "",
            "is_unlock": true,
            "settle_time": "0",
            "star": 9,
            "max_star": 9,
            "levels": []
        }],
        "total_star": 36,
        "is_unlock": false
    }
}
```

### 复现流程

疑似随机

### 代码状态：当前提交

87b0403cdbb91342b642823f9d79291ef6d8fb4a (HEAD -> master, origin/master, origin/HEAD) 本地更新与与远程仓库同步

### 代码状态：是否修改

Clean

### 运行环境： Node.js 版本

v17.0.1

### 运行环境： npm 版本

8.1.0

### 运行环境：操作系统

macOS

**Comment by Arondight** [comment]
这是正常的数据吧？我看我的 bot 数据好多这样的啊

**Comment by Arondight** [comment]
哦，我明白了，你是说的有 `floors` 但是没有其他的例如 `defeat_rank` 之类的

**Comment by Mark9804** [comment]
`floors`这个数据是一定存在的，只是在特殊情况下这会是一个空数组，参考 #399

`reveal_rank`等数据只要有过出战次数就不应该是空数组，这种情况之前在 #323 中出现过，应该和 API 变动有关，在这之前前端一直是信任`aby.json`文件的正确性的，现在我觉得应该检验每个 array 的长度是否为`0`

**Comment by Alpiiine** [comment]
如果有人只打到8-3（其实只要低于9-1都有这个问题），查询深渊数据也会出现一楼图片里的问题

**Comment by Mark9804** [comment]
> 如果有人只打到8-3（其实只要低于9-1都有这个问题），查询深渊数据也会出现一楼图片里的问题

那应该会被认为没打啊，低于九层不应该返回图片，会直接说没打，检查一下代码是不是最新的

**Comment by Alpiiine** [comment]
> 

是最新的，刚刚更新完再次查询还是有这个问题。是不是因为缓存的原因？
uid 207337710

**Comment by Mark9804** [comment]
我理解了，这种情况的话确实也不能算是没打，我再想想
