### ISSUE TITLE
检测到无效 cookie 时自动换用 cookie 重新查询

### ISSUE THREAD

**Issue by Xm798** [Arondight/Adachi-BOT#466]
### 问题描述

当前使用无效的 cookie 查询时，会直接返回`米游社接口报错: Please login`的错误信息，同时提示`发现以下无效 Cookie ，请及时在 config/cookies.yml 中删除`，用户使用时会表示迷惑，建议在检测到无效 cookie 时可以自动换用其他 cookie 重新查询。

### 代码状态：当前提交

5c703fd4a923125e16712e45996d227b649194f8 歪比巴卜

**Comment by Arondight** [comment]
先挖个坑吧，做起来稍微麻烦点

**Comment by BTMuli** [comment]
我记得hoshinobot的genshinuid插件支持cookie添加，通过qq的那种

**Comment by Xm798** [comment]
> 我记得hoshinobot的genshinuid插件支持cookie添加，通过qq的那种

本项目不收集用户 Cookie，见 #361

**Comment by Arondight** [comment]
不做了，都忘了这个了
