### ISSUE TITLE
接入青云客API添加聊天功能

### ISSUE THREAD

**Issue by xiaofeicn** [Arondight/Adachi-BOT#467]
### 问题描述

+ 1、群聊
         群聊中@BOT讲话时，BOT根据内容 POST 请求青云客API，将API返回聊天回复发送至群
+ 2、私聊
         私聊时BOT根据内容 POST 请求青云客API，将API返回聊天回复发送私聊窗口
       

### 代码状态：当前提交

5c703fd4a923125e16712e45996d227b649194f8 (HEAD -> master, origin/master, origin/dev, origin/HEAD) 歪比巴卜

**Comment by Arondight** [comment]
这个感觉不太行啊，api 质量有点差，质量好的例如图灵需要收费，结果就没什么合适的用了。反正请求也很简单，暂时自己写个插件吧，这个 issue 先关掉了，我后续想做这个功能地时候参考一下。
