### ISSUE TITLE
重写一下每日素材

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#475]
基本上没有可用的图了，先改个文字版或者最简单的 html

https://adachi-bot.oss-cn-beijing.aliyuncs.com/Version2/daily/daily.yml

https://github.com/SilveryStar/Adachi-BOT/blob/7add0a37025719daa4f296718d69e3dac9caa14b/src/plugins/genshin/components/daily/unit.js#L46-L51

顺手把图扒下来

**Comment by Arondight** [comment]
数据已经构造出来了，还不确定怎么用比较好。

```
{
  character: {
    '「勤劳」的哲学': [ '甘雨', '胡桃', '枫原万叶', '香菱', '重云' ],
    '「抗争」的哲学': [
      '莫娜',   '优菈',
      '迪卢克', '琴',
      '雷泽',   '诺艾尔',
      '班尼特'
    ],
    '「风雅」的哲学': [ '神里绫华', '荒泷一斗', '九条裟罗' ]
  },
  weapon: {
    '凛风奔狼的断牙': [
      '天空之傲',     '天空之刃',
      '天空之卷',     '天空之翼',
      '终末嗟叹之诗', '决斗之枪',
      '嘟嘟可故事集', '暗巷的酒与诗',
      '流浪乐章',     '祭礼大剑',
      '祭礼弓',       '降临之剑',
      '黑剑',         '龙脊长枪',
      '讨龙英杰谭',   '沐浴龙血的剑',
      '神射手之誓',   '笛剑',
      '黎明神剑'
    ],
    '雾海云间的金丹': [
      '无工之剑', '磐岩结绿',
      '匣里灭辰', '宗室猎枪',
      '昭心',     '试作斩岩',
      '试作澹月', '试作金珀',
      '雨裁',     '黑岩刺枪',
      '黑岩斩刀', '以理服人',
      '信使',     '吃虎鱼刀',
      '甲级宝珏', '钺矛'
    ],
    '鸣神御灵的亲爱': [ '飞雷之弦振', '掠食者', '桂木斩长正', '破魔之弓', '曚云之月', '赤角石溃杵' ]
  }
}
```

**Comment by Arondight** [comment]
代码暂时存放在 dev 分支

**Comment by Arondight** [comment]
@Mark9804 @Xm798 两位老大哥谁有空帮忙看看页面布局的问题，我搞不定了，代码在 dev 分支，数据我已经调通了，css 我直接复制的，不知道为啥就不行呢

**Comment by Mark9804** [comment]
从overview复制过去的那就我来吧，可能跟我之前写的缝合怪布局有关

**Comment by Arondight** [comment]
@Mark9804 我直接从原项目四合一的

https://github.com/SilveryStar/Adachi-BOT/blob/7add0a37025719daa4f296718d69e3dac9caa14b/src/plugins/genshin/views/daily.html#L7-L10

https://github.com/SilveryStar/Adachi-BOT/blob/7add0a37025719daa4f296718d69e3dac9caa14b/src/plugins/genshin/styles/reset.css

https://github.com/SilveryStar/Adachi-BOT/blob/7add0a37025719daa4f296718d69e3dac9caa14b/src/plugins/genshin/styles/daily/app.css

https://github.com/SilveryStar/Adachi-BOT/blob/7add0a37025719daa4f296718d69e3dac9caa14b/src/plugins/genshin/styles/daily/column.css

https://github.com/SilveryStar/Adachi-BOT/blob/7add0a37025719daa4f296718d69e3dac9caa14b/src/plugins/genshin/styles/daily/unit.css

**Comment by Mark9804** [comment]
晚上打完狗含剑之后我康康

**Comment by Mark9804** [comment]
@Arondight 老大哥能麻烦在 `npm run view`里面加一个每日素材的选项么

**Comment by Arondight** [comment]
不用加的吧，我记得选项是动态生成的啊

**Comment by Arondight** [comment]
你跑过天赋或者武器命令， npm run view — -l 应该就能看到了

**Comment by Mark9804** [comment]
现在有了，刚刚没跑过所以没看到

**Comment by Mark9804** [comment]
调试功能调用不了了，是这个仓库的`dev`分支
```
Adachi-BOT dev > npm run view -- -n material                               00:49:00

> Adachi-BOT@1.5.1 view
> npx node ./tools/view.js "-n" "material"

node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:120:11)
    at Object.resolve (node:path:1098:7)
    at render (file:///Users/mark_chen/Documents/GitHub.nosync/Adachi-BOT/src/utils/render.js:52:26)
    at main (file:///Users/mark_chen/Documents/GitHub.nosync/Adachi-BOT/tools/view.js:66:9)
    at file:///Users/mark_chen/Documents/GitHub.nosync/Adachi-BOT/tools/view.js:87:1
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:331:24)
    at async loadESM (node:internal/process/esm_loader:88:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v17.2.0
```

**Comment by Arondight** [comment]
现在应该好了

**Comment by Mark9804** [comment]
老大哥忘记把`unit.css`合进来了

然后现在的问题是`unit.js`当中的`rarity`函数没有正确调用，显示不出稀有度背景，这个折腾一下就可以了
https://github.com/Arondight/Adachi-BOT/blob/ef6ea87fc7161041f493c78557f522860c15207a/src/views/component/material/unit.js#L43

![image](https://user-images.githubusercontent.com/9006264/145153192-6192f9fe-524e-48e6-a9b5-2852c1780af8.png)
如果正确显示的话，右边标蓝位置的style应该是这样的
`style="background: http://localhost:9934/resources/Version2/thumb/stars/4-Star.png; background-size: 100% 100%;"`
现在缺了`background`

**Comment by Mark9804** [comment]
是我搞错了，这个`background`声明不合法，我自己来

**Comment by Mark9804** [comment]
已经能够正常使用
ef6ea87fc7161041f493c78557f522860c15207a , 8f130ef519a76a39a9fd9456634c7fb843850b42

**Comment by Mark9804** [comment]
要是再加一个五星排在最前面的排序算法就完美了
![image](https://user-images.githubusercontent.com/9006264/145156228-ad58c76c-d4fc-4e2e-9e63-cb73f99a9a47.png)

**Comment by Arondight** [comment]
🐮🍺

**Comment by Arondight** [comment]
阿哲，所以我是漏了一个 css ？

**Comment by Mark9804** [comment]
> 阿哲，所以我是漏了一个 css ？

以普遍理性来说，确实

**Comment by Arondight** [comment]
> 以普遍理性来说，确实

哎，太菜了
![BB69A7A6-990F-4D99-91D1-87258AAAED1C](https://user-images.githubusercontent.com/13673702/145162667-bbb9f3ad-244c-4b05-afcc-abbea93c8757.jpeg)
