### ISSUE TITLE
[建议]关于readme.md的一些改进建议...

### ISSUE THREAD

**Issue by citydirector** [Arondight/Adachi-BOT#479]
关于安装方法，有两处可以改进的地方：（未进行语言组织）

①安装nodejs建议用nvm一键安装，无烦恼：
* 安装nvm：`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash`或者`wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash`

断开ssh，重新连接，然后：
* 安装最新版本nodejs：`nvm install node`

②安装chrome建议用安装包安装，先在本地科学上网下载安装包再用sftp上传到服务器进行安装：
* (Ubuntu/Debian)安装包下载：`https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb`
* (CentOS)安装包下载：`https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm`

下载好后通过sftp上传到服务器，然后安装：
* (Ubuntu/Debian)安装：apt install ./google-chrome-stable_current_amd64.deb
* (CentOS)安装：yum localinstall ./google-chrome-stable_current_x86_64.rpm

**Comment by citydirector** [comment]
当然，本着送佛送到西的原则，我还想加个“(可选)配置fastgithub”的来着（）

**Comment by Arondight** [comment]
1. 我试了一下，实际上 nvm 在不使用代理的情况下速度堪忧，话说回来如何安装软件是系统的问题，还是让系统的使用者自己去想办法解决吧
2. 已经在推荐项中写了`你要做的是用包管理器安装 Chromium`，至于如何安装软件是系统的问题，还是让系统的使用者自己去想办法解决吧

**Comment by citydirector** [comment]
nvm挺快的呀。刚刚给一台腾讯云上海的机子重置了系统，然后在升级完后第一时间就装上了nvm，确实特别快和好用，不需要代理
