### ISSUE TITLE
人物信息查询坏掉惹，出现大量重复

### ISSUE THREAD

**Issue by Xm798** [Arondight/Adachi-BOT#486]
### 问题描述

![R5W@79545UDTQ42UTOB7SM4](https://user-images.githubusercontent.com/48074861/145981245-a8ffa0ff-dca8-4dc1-8b1d-71dcb3184a78.gif)

### 复现流程

米游社

### 代码状态：当前提交

6f3b4243c131d568e7c84c69332545ca72d00d2d

### 运行环境：操作系统

Linux

**Comment by Arondight** [comment]
啊这，难道是下午数据库改坏了，先回退看一下

**Comment by Arondight** [comment]
好像不是数据库的问题，你退回一下提交看看

**Comment by Arondight** [comment]
@KimigaiiWuyi 是 api 又改了吗

**Comment by Xm798** [comment]
怀疑是接口问题，UID也存在这个问题。提交回退到d5005f92792a28f552e10d4649bcfca2895c1911，问题依然存在的。

**Comment by Arondight** [comment]
额，好麻烦，国外的信息都已经开放了，国内还在瞎改 api

**Comment by SilveryStar** [comment]
接口出问题了，我那边单查全是神里

**Comment by Arondight** [comment]
> 接口出问题了，我那边单查全是神里

奇怪，米游社诶屁屁还是正常的

**Comment by SilveryStar** [comment]
可能只是单查出问题了？我这边 uid 查八个和带 cookie 的私人服务都是正常的
可能就是在拦你们这种查法？
![ab8028b44a1a8eb3eb32ebf978c29330](https://user-images.githubusercontent.com/42149290/145986493-08a82bd5-65bf-41a6-8432-a66047c36095.png)
![cd8e3cdcb943cb5dc06568083fac6a94](https://user-images.githubusercontent.com/42149290/145986504-6fb21f8d-3c1d-4dd6-beee-c86dbe655493.png)

**Comment by Arondight** [comment]
确实，查八个是正常的，这个 api 没得问题

![25671480-8676-42C3-A6D7-BF1342E7C73F](https://user-images.githubusercontent.com/13673702/145988745-e625a06c-6449-4497-b007-08a73ced15bb.jpeg)

**Comment by SilveryStar** [comment]
其实不是八个也是对的，我查了一个只有两个角色的 uid，正常

**Comment by KimigaiiWuyi** [comment]
就离谱……

**Comment by Arondight** [comment]
> 其实不是八个也是对的

意思就是单独查一个角色查也是可以的？

**Comment by KimigaiiWuyi** [comment]
> 

单查一个肯定是对的，因为可以点进单个的角色详情信息，接口不会有问题

问题是限制了并发，导致这种查询方法很难搞

**Comment by KimigaiiWuyi** [comment]
> 

我觉得离谱的就是 国外深渊都开放了，国内查角色的为啥还抠抠索索

**Comment by Arondight** [comment]
> 问题是限制了并发

那我们单独查嘛，无非八个一组现在成了单蹦的数组了，无非慢一点

**Comment by KimigaiiWuyi** [comment]
> > 问题是限制了并发
> 
> 那我们单独查嘛，无非八个一组现在成了单蹦的数组了，无非慢一点

还没有具体测试，但是万一改成有cd的，那你查一次怕是要等三十秒多

**Comment by Xm798** [comment]
> 确实，查八个是正常的，这个 api 没得问题
> 
> ![25671480-8676-42C3-A6D7-BF1342E7C73F](https://user-images.githubusercontent.com/13673702/145988745-e625a06c-6449-4497-b007-08a73ced15bb.jpeg)

插句题外话：这个app是啥呀

**Comment by Arondight** [comment]
> 但是万一改成有cd的

api 都改的这么匆忙，cd 应该是没有的

**Comment by Arondight** [comment]
> 这个app是啥呀

http catcher，这是收费的，还有一个功能一样但是免费的叫 stream

**Comment by KimigaiiWuyi** [comment]
> > 但是万一改成有cd的
> 
> api 都改的这么匆忙，cd 应该是没有的

你看看测试一下吧，什么限度不会触发这个……我现在还不能测试

**Comment by Arondight** [comment]
> 你看看测试一下吧

我晚上回去看一下，最多俩小时之后就能有结论了

**Comment by SilveryStar** [comment]
> 那我们单独查嘛，无非八个一组现在成了单蹦的数组了，无非慢一点

单独查只会返回角色 id 最小的角色，我们这边反馈基本就是查什么都是神里的信息

**Comment by KimigaiiWuyi** [comment]
> > 那我们单独查嘛，无非八个一组现在成了单蹦的数组了，无非慢一点
> 
> 单独查只会返回角色 id 最小的角色，我们这边反馈基本就是查什么都是神里的信息（因为神里 002

单独发一个角色id过去查，然后等一秒再发一个id查，最后合并结果不行吗
现在是调用这个api无论发什么只会返回最低的那一个嘛

**Comment by SilveryStar** [comment]
> 单独发一个角色id过去查，然后等一秒再发一个id查，最后合并结果不行吗 现在是调用这个api无论发什么只会返回最低的那一个嘛

嗯，我的号查谁都是神里，拿了一个只有主角和安柏的号，查安柏返回主角，甚至查其他角色也返回主角
![}QE%Z4 %GL K`6)VEU}VXNK](https://user-images.githubusercontent.com/42149290/145993864-16cd2842-a61f-4940-abf1-5bb4639ee29e.png)

**Comment by Arondight** [comment]
> 单独查只会返回角色 id 最小的角色

那是有点难办哦，还返回一个错误的角色过来，我感觉这个 api 只是临时紧急改了一下，这不像是一个正常 api 的行为，说不定明天官方改了又要继续跟着改的

**Comment by SilveryStar** [comment]
> 那是有点难办哦，还返回一个错误的角色过来，我感觉这个 api 只是临时紧急改了一下，这不像是一个正常 api 的行为，说不定明天官方改了又要继续跟着改的

但是意图很明显（

**Comment by KimigaiiWuyi** [comment]
> > 单独发一个角色id过去查，然后等一秒再发一个id查，最后合并结果不行吗 现在是调用这个api无论发什么只会返回最低的那一个嘛
> 
> 嗯，我的号查谁都是神里，拿了一个只有主角和安柏的号，查安柏返回主角，甚至查其他角色也返回主角 ![}QE%Z4 %GL K`6)VEU}VXNK](https://user-images.githubusercontent.com/42149290/145993864-16cd2842-a61f-4940-abf1-5bb4639ee29e.png)
> 
> ![S@(XW{Z{@}2N7BN%M{%)CM](https://user-images.githubusercontent.com/42149290/145994029-04722dfb-b5be-4655-ad5d-64db8539f4ff.png)

现在是这样，那个api无论你发什么过去，都只返回前八个的角色详细信息。

**Comment by SilveryStar** [comment]
> 现在是这样，那个api无论你发什么过去，都只返回前八个的角色详细信息。

这样吗
不过米游社里自带的那个排序好像确实也跟id有关

**Comment by Arondight** [comment]
黑榜好像又不行了？国外的接口好像又关了

**Comment by 6DDUU6** [comment]
确实，查别人的，无论发什么过去，都只返回前八个的角色详细信息。
看后面mhy会不会改回去了

**Comment by Arondight** [comment]
回去开电脑看了下，果然是这个样子，官方的 api 我抓了一下，逻辑是对得上的，我这里只好先简单改改了

**Comment by Arondight** [comment]
我当前只好先跟着官方走了，没得办法，提交刚才已经推上去了，看到这条 issue 的各位先更新一下，后续再观望吧

![图片](https://user-images.githubusercontent.com/13673702/146003909-234aa992-e984-4a11-8f16-3077b165b895.png)

**Comment by Mark9804** [comment]
今年十月底深渊 API 表现异常的时候我们一开始也以为是 bug，后来回过头来想想应该每次 bug 其实都是在测试什么东西的，我们还是做好打 tag 的准备吧

~~我听朋友说米哈游那边不加班啊，怎么程序员晚上六七点还在上线 feature~~

**Comment by Arondight** [comment]
后续找个时间把只查八个角色的和原项目对其，在 src/views/ 下面多创建一个 genshin-card-8.html，原来的留存不再使用

**Comment by Arondight** [comment]
@SilveryStar 顺便老大哥有考虑把你的那个用自己 uid 查所有角色的那个图，图片里的汉字用 html 替代吗，新加点东西做图困难

**Comment by SilveryStar** [comment]
不打算，那个准备扔了，要做新设计的

**Comment by Arondight** [comment]
> 不打算，那个准备扔了，要做新设计的

你这产能我抄都快跟不上了，太猛了

**Comment by SilveryStar** [comment]
> 做游戏不加班不可能的吧，做 IT 都是拿命换钱的工作，没啥清闲还来钱的活

mhy 好像确实除了版本上线前会晚一点，平时都是双休+到点下班的

**Comment by SilveryStar** [comment]
> 你这产能我抄都快跟不上了，太猛了

也没那么急，估计寒假写，估计这段时间也不会有太多更新（

**Comment by Arondight** [comment]
> mhy 好像确实除了版本上线前会晚一点

老大哥加油啊，说不定啥时候玩上你做的游戏了

**Comment by Arondight** [comment]
这个 issue 感觉也没多大作用了，官方改了 api 再开新的，这个先关了

**Comment by Mark9804** [comment]
> 做游戏不加班不可能的吧，做 IT 都是拿命换钱的工作，没啥清闲还来钱的活

可能程序组是这样，我认识的基本是没有bug可修的美术组，但是负责 Unity 那边的项目组压力会大很多

> 除了版本上线前会晚一点

感觉原神项目组每天都是版本上线的日子，版本前半段修 bug，版本后半段写 bug，听说是三组人轮流负责当前版本、未来版本和卫星版本的，项目管理真的无敌，老大哥加油什么时候让我们跟着吃一口甜甜花酿鸡

**Comment by Mark9804** [comment]
好像现在的 API 行为又正常了， #503 
不过我们还是防一手将来的更改吧

**Comment by KimigaiiWuyi** [comment]
> 好像现在的 API 行为又正常了， #503 不过我们还是防一手将来的更改吧

恢复了？

**Comment by Mark9804** [comment]
> 恢复了？

我自己没尝试，但是隔壁 issue 的图是正常的

**Comment by KimigaiiWuyi** [comment]
> > 恢复了？
> 
> 我自己没尝试，但是隔壁 issue 的图是正常的

我自己的插件的话，查自己是默认调用自己的ck，好像也不能说明什么……
你这边插件我就不太清楚，如果不是默认调用自己ck，那确实有可能恢复了

**Comment by SilveryStar** [comment]
![Q}Z~$@G Q4%@@UTZ7C3BF$D](https://user-images.githubusercontent.com/42149290/146509233-7923b739-2897-4c9f-8746-992d15f8ddc5.png)

**Comment by Arondight** [comment]
我试了一下什么都没有改变，大概是他用自己游戏账号 cookie 了把
