### ISSUE TITLE
oicq 更新到 2.x

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#487]
### 问题描述

1.x 快停止支持了，此事提上日程

### 代码状态：当前提交

a65608bdb2b9c9cb2d704c94b434ec0e373a9032

**Comment by Arondight** [comment]
看起来是有办法能够无感升级的，太好了，我想极力避免的事情就是我一升级，fork 全炸了

https://github.com/takayama-lily/oicq/discussions/275

**Comment by Arondight** [comment]
@SilveryStar 我已经搞完了，我看你的还是老版本，可以参考一下，实际上处理的东西还是比较少的

**Comment by SilveryStar** [comment]
> @SilveryStar 我已经搞完了，我看你的还是老版本，可以参考一下，实际上处理的东西还是比较少的

没打算跟进，为了兼容频道这边会进行一次大重构，到时候直接照着 2.x 的写

**Comment by Arondight** [comment]
频道我问过 oicq ，他说会跟进，如果你愿意等的话，无非多监听一个事件就行了，不用搞大重构了

**Comment by SilveryStar** [comment]
算了吧，我反正寒假有的是时间，现在的架构修修补补的本身也有问题，正好一起改了
