### ISSUE TITLE
查询角色图片一次

### ISSUE THREAD

**Issue by BumbleBee-hyf** [Arondight/Adachi-BOT#489]
### 问题描述

uid 100100343 之后 图片全部叠加了

### 复现流程

uid 100100343

### 代码状态：当前提交

git log -1 --format=oneline

### 运行环境： Node.js 版本

1.5.1

### 运行环境： npm 版本

16

### 运行环境：操作系统

Linux

**Comment by Arondight** [comment]
更新代码，被官方制裁了
