### ISSUE TITLE
有人帮忙规整一下每日菜单吗

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#49]
多次遭到投诉[当前菜单](https://github.com/Arondight/Adachi-BOT/blob/69595aa498755273bdc1c8738bc6fa0242ccf996/config/menu.yml)过于沙雕……例如早上吃奶酪啥的。

**Comment by SQSora** [comment]
早餐重新写一份，然后午餐和晚餐用同一个list的数据？

**Comment by Arondight** [comment]
我觉得可以，午餐和晚餐应该区别不大，规整一下也为了以后写一份更好的菜单做准备，例如每一餐多几个候选项瓜分 100% 的概率，当然也可能不会做，因为这个功能太过娱乐甚至显得有点多余。

**Comment by iorinoe** [comment]
这个功能群友每日必玩。就是玩多了菜单内容不够丰富了。看看有没有大佬再增加一下菜单。

**Comment by Arondight** [comment]
当前收到的投诉：

1. 过于沙雕，例如连着两顿黄焖鸡
2. 日常三餐不够丰富
3. 碳水过多？

**Comment by Arondight** [comment]
![图片](https://user-images.githubusercontent.com/13673702/132446048-5807b4eb-dbb6-48a9-a1f2-497e19e8c91b.png)

**Comment by SQSora** [comment]
因为你没写上日照烤鸭
