### ISSUE TITLE
无法获取无法获取可用 Cookie ！

### ISSUE THREAD

**Issue by YLN-lz** [Arondight/Adachi-BOT#503]
### 问题描述

无法获取可用 Cookie ！

### 复现流程

部署好后只有我一个人可以绑定并使用米游社等功能
![R2VIT8R$XF(3}UWX4N(~UCJ](https://user-images.githubusercontent.com/96196892/146506913-b8a1242b-1d49-47c9-bf5e-8cb547dce4d7.png)

### 后台日志

```Text
BECDE4EE2C/0?term=2]
0|bot      | [2021-12-17T14:58:18.513] [INFO] [Android:2705523350] - recv from: [Group: 提瓦特茶话会(130671305), Member: 提瓦特琴师(459645310)] 米游社
0|bot      | [2021-12-17T14:58:20.898] [WARN] [Android:2705523350] - 群消息被风控，将尝试使用分片发送。
```

### 代码状态：当前提交

Administrator@DESKTOP-O00GLSH MINGW64 ~/Desktop/新建文件夹/Adachi-BOT (master) $ git log -1 --format=oneline f075fcb15316b706ae639482b04a6d11125e78ce (HEAD -> master, origin/master, origin/dev, origin/HEAD) 改一下 npm 脚本，现在有点乱  Administrator@DESKTOP-O00GLSH MINGW64 ~/Desktop/新建文件夹/Adachi-BOT (master)

### 运行环境：操作系统

Windows

**Comment by Arondight** [comment]
```
npm run tool-db -- -d cookies -k cookie | grep -oP '(?<="times":\h)\d+'
```

贴一下结果

**Comment by Arondight** [comment]
有问题请直接回复，暂时关闭
