### ISSUE TITLE
增加一个可以自主开放和关闭卡池的功能。

### ISSUE THREAD

**Issue by brojp** [Arondight/Adachi-BOT#506]
### 问题描述

希望大佬可以增加一个自主开启和关闭卡池的功能。

**Comment by Mark9804** [comment]
能详细说明一下吗？

比如说，当你发送某条消息给机器人的时候，你希望机器人会执行什么功能？

**Comment by brojp** [comment]
机器人带的彩蛋卡池这种可以通过发送“彩蛋卡池开启”或者“彩蛋卡池关闭”命令来实现开启和关闭的动能。

**Comment by Arondight** [comment]
这个功能没有想法添加
