### ISSUE TITLE
对其原项目的八角色卡牌新样式

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#507]
### 问题描述

挖坑一分钟，填坑一整天（暂定）

**Comment by Mark9804** [comment]
这个吗，虽然觉得高仿没有必要，但确实观感比现在的好
![image](https://user-images.githubusercontent.com/9006264/146670047-93b861ea-0be6-4f34-b2cf-feeb0ea1538c.png)

**Comment by Arondight** [comment]
是这个，我额外加一个 html，原来的保留，这几天先把这个做了再把爬虫做了，但是我感觉可能得休息几点，这几天肝幻塔人都要肝没了

**Comment by Arondight** [comment]
备忘：角色的武器和精炼等级加上，每个角色的框拉宽来放武器名

**Comment by Arondight** [comment]
为啥角色右下角有个弧形

**Comment by Mark9804** [comment]
我觉得可以先看一下，如果右半边这个部分依然是排版写死（跟旧版本一样边框是画在图片上的）的话就可以终止了，渊下宫看样子也和雪山一样是一个独立区域，到时候这个不好整
![image](https://user-images.githubusercontent.com/9006264/146670284-a28d4548-b67d-4543-86c7-a2eca7d1b87b.png)

> 备忘：角色的武器和精炼等级加上，每个角色的框拉宽来放武器名
不用拉宽
![image](https://user-images.githubusercontent.com/9006264/146670400-6fa2d95b-f062-4aab-a99d-1e85a7f41b04.png)

> 为啥角色右下角有个弧形
[CSS实现的](https://developer.mozilla.org/zh-CN/docs/Web/CSS/border-radius)

**Comment by Arondight** [comment]
> 如果右半边这个部分依然是排版写死

这个我不会看的，他这个排版确实加区域是个大问题

**Comment by Mark9804** [comment]
暂时用一用吧，vue3 的数据结构能抄过来就减轻负担了，那天试了一下 gacha 网页的 2->3 ，头都给我写没

**Comment by Arondight** [comment]
好，另外我看图片应该不是画死的 https://adachi-bot.oss-cn-beijing.aliyuncs.com/Version2/module/user-base.png

排版我真不会看

**Comment by Arondight** [comment]
另外弧形我是想问为啥只有右下角有弧形……不应该是四个角都加的？

**Comment by Arondight** [comment]
https://adachi-bot.oss-cn-beijing.aliyuncs.com/Version2/module/user-nase-exp-bg.png

这个图叠上去的，应该还好，开了矿坑调整一下 css 就行

**Comment by Mark9804** [comment]
> 图片应该不是画死的

那我这边没有其他问题了，放心薅，只要数据能调通，排版就算一个都没有也给你重写一个出来

> 为啥只有右下角有弧形……不应该是四个角都加的

每个角可以单独调整的
```css
.class-element {
    border-radius: 10px 20px 30px 40px
}
```

![image](https://user-images.githubusercontent.com/9006264/146670707-5361c196-ca0b-4de2-9d3e-4ef47758f65d.png)

**Comment by davidelefree365** [comment]
> > 图片应该不是画死的
> 
> 那我这边没有其他问题了，放心薅，只要数据能调通，排版就算一个都没有也给你重写一个出来
> 
> > 为啥只有右下角有弧形……不应该是四个角都加的
> 
> 每个角可以单独调整的，从左上角开始，按顺时针方向分别是左上角→右上角→右下角→左下角的圆角数值
> 
> ```css
> .class-element {
>     border-radius: 10px 20px 30px 40px
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/9006264/146670707-5361c196-ca0b-4de2-9d3e-4ef47758f65d.png)

深渊有兴趣也改版吗

**Comment by Mark9804** [comment]
> 深渊有兴趣也改版吗

还没想好改成什么样，加上有前端框架老旧的历史包袱，暂时摆了
<img src="https://user-images.githubusercontent.com/9006264/146674436-017b1bfc-09f7-411b-8d59-f0f0c78e7b3a.jpeg" alt="8C8730D3-2350-4ACE-8259-6DA6BE5F3285_1_105_c" width="200"/>

**Comment by Arondight** [comment]
@Mark9804 老大哥，帮忙调一下

1. 武器显示到框外面了，我没调好，放了个半成品
2. 洞天仙力我不知道咋加，就暂时写在标题上了，这个不调也行

**Comment by Arondight** [comment]
> 加上有前端框架老旧的历史包袱

我可能得等到过年改了，年末公司好忙，划水都不安生，下班了又累

**Comment by Mark9804** [comment]
应付完教授就来调

> 年末公司好忙，划水都不安生，下班了又累

不急，我都还没想好就算适配完了要改什么，vue3 给我的感觉是比 2 来得更加组件化（也可能是 2 版本我们的网页写的太烂了），跨度还是挺大的。

就算有空了要改，也把 gacha.html 的优先级排到深渊前面吧，深渊是逃不掉数据+版面整个重写的，相比之下 gacha 只要数据跑通就能继续用，工作量更小，之后加入 n 连抽对用户的感知也更明显

**Comment by Arondight** [comment]
感谢老大哥，调完了顺手推一下master

**Comment by Mark9804** [comment]
> > 为啥只有右下角有弧形……不应该是四个角都加的
> 
> （CSS）每个角可以单独调整的

怎么世界上会有画一张圆角图片覆盖上去来实现圆角的做法？？？
![image](https://user-images.githubusercontent.com/9006264/146767203-2d2ea723-6eaa-4b9c-a34f-0e34387a77ae.png)

**Comment by Mark9804** [comment]
这个 corner 元素就算没有在网页中出现，我也不能在 css 里面把这个属性声明给删掉，一删掉排版就会爆炸，我也不知道为什么，感觉就跟明明只删了一行注释但是整个程序爆炸了一样……

**Comment by Arondight** [comment]
> 右下的圆角在游戏和米游社的卡片设计里面都有出现，我个人觉得还挺好看的

按照老大哥的喜好来就行，谁写代码谁有决定权

**Comment by Mark9804** [comment]
> 武器显示到框外面了

已解决

> 洞天仙力我不知道咋加，就暂时写在标题上了

这个布局比较紧凑，加在其他地方的话更丑了，还是写在标题上好一些

> 左边那一堆属性显示的感觉好丑

我暂时也想不到更好看的改法，说不定把数字字体改成手写体有什么奇效……就像以前手填表格那样的感觉

**Comment by Mark9804** [comment]
头像现在是随机的，要不要跟原来一样换成QQ头像就老大哥决定了

派蒙头像现在没有用到了

**Comment by Mark9804** [comment]
> 他这个排版确实加区域是个大问题

已经让页面自己动了，现在加成就，加区域，长度都会自动适应

**Comment by HYTT0510** [comment]
提几个建议
1.名片还是使用qq头像
2. 角色可以不展示属性，展示命座
3.诚哥壶目前没啥用，感觉可以顺便查一点深渊数据放在那块区域

**Comment by Mark9804** [comment]
1. QQ 头像我一臭写前端的不会弄，看看 owner 想不想挖这个坑
2. 命座没了我都没发现，这个可以加上
3.1. 深渊 API 是一个独立的 API，如果一次查询两个 API 的话时间感觉有点太长了
3.2. 而且也没想好查完了数据怎么展示出来，深渊返回的信息其实不多，也就战斗次数，最深抵达，获得渊星，然后还有四个 MVP 的头像

**Comment by Arondight** [comment]
QQ头像我不想加，我觉得现在很好；命座我觉得需要加，但是得楼上来做，样子差不多就和旧的一样右上角有一个角标，不满命一个颜色，满命一个颜色，没命没角标

**Comment by Arondight** [comment]
命座的数据都是有的，怎么用得前段处理了，我加不好，只能加一行文字，css 不会写

**Comment by Arondight** [comment]
深渊不加

**Comment by Mark9804** [comment]
命座摸完了，马上就能commit
<img src="https://user-images.githubusercontent.com/9006264/147059806-4d2e775a-56e6-4ea6-91ac-3556cdb66bf2.png" alt="image" width="400">

**Comment by Arondight** [comment]
🤣 满命能搞个特效吗

**Comment by Mark9804** [comment]
> 不满命一个颜色，满命一个颜色，没命没角标

坏了，做完才看到新需求，吃完饭再整了

满命整个啥特效啊

**Comment by Arondight** [comment]
就是和不满命有区别就行，毕竟满命代表了毕业，例如背景颜色或者字体颜色不一样

**Comment by Arondight** [comment]
那个零命也显示我感觉还挺好的

**Comment by Mark9804** [comment]
满命特效我再想想，现在也不是不能用

**Comment by Arondight** [comment]
这个金色传说有点意义不明，但是数字加个金色传说意义就很明显

**Comment by Mark9804** [comment]
＠HYTT0510 命座已经加上了，麻烦拉一下最新的代码；QQ头像和深渊没有打算加

**Comment by davidelectricfree** [comment]
> ＠HYTT0510 命座已经加上了，麻烦拉一下最新的代码；QQ头像和深渊没有打算加

大佬，冒险等级打算加上吗？

**Comment by Arondight** [comment]
冒险等级目前有个技术问题就是不知道怎么根据数据动态生成页面，因为用 uid 查是没有冒险等级的，米游社 id 查才有，以前也有这个技术问题，是通过把一份 html 复制成两份解决的，这次就不要了吧

**Comment by Mark9804** [comment]
可以做呀，只是没想好加在哪，感觉没地方加了，有想法了就加上

**Comment by Mark9804** [comment]
感觉成品不一定比现在的好看
![Uploading image.png…]()

**Comment by Mark9804** [comment]
太难看了，去洗个眼睛再想想

emmmm要不直接把冒险等级扔到下面的成就统计里面？
![image](https://user-images.githubusercontent.com/9006264/147266481-d277c292-4448-4eeb-9b32-f5840f97be1e.png)

**Comment by Mark9804** [comment]
@davidelectricfree 冒险等级已经加上了，拉一下代码

**Comment by davidelectricfree** [comment]
> @davidelectricfree 冒险等级已经加上了，拉一下代码

谢谢，我拉了一下，好像米游社指令完全不好用了，是我一个人这样吗

**Comment by Mark9804** [comment]
> > @davidelectricfree 冒险等级已经加上了，拉一下代码
> 
> 谢谢，我拉了一下，好像米游社指令完全不好用了，是我一个人这样吗

你的代码不是最新的，记得在最新代码上测试一下有没有问题

**Comment by davidelectricfree** [comment]
> > > @davidelectricfree 冒险等级已经加上了，拉一下代码
> > 
> > 谢谢，我拉了一下，好像米游社指令完全不好用了，是我一个人这样吗
> 
> 你的代码不是最新的，记得在最新代码上测试一下有没有问题

啊，看到了另一个issue，云服务器ip禁止访问是真的吗

**Comment by davidelectricfree** [comment]
> > > @davidelectricfree 冒险等级已经加上了，拉一下代码
> > 
> > 谢谢，我拉了一下，好像米游社指令完全不好用了，是我一个人这样吗
> 
> 你的代码不是最新的，记得在最新代码上测试一下有没有问题

最新的也显示不出来，米游社指令没反应

**Comment by Mark9804** [comment]
> 云服务器ip禁止访问是真的吗

暂时还没有十足证据

> 最新的也显示不出来

`npm run restart` 看看
