### ISSUE TITLE
可能要换新的 DS 了

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#51]
https://github.com/Arondight/Adachi-BOT/blob/69595aa498755273bdc1c8738bc6fa0242ccf996/src/utils/api.js#L32-L38

![图片](https://user-images.githubusercontent.com/13673702/130971668-4d7fba9c-4051-4e44-bb50-9fca8dc90713.png)

**Comment by Arondight** [comment]
我这里已经没法用老 DS 了，发什么请求都出错，谁能把这玩意儿换一下吗？

```
米游社接口报错: invalid request
```

**Comment by ixCiel** [comment]
反编译扒拉出一串旧DS代码好像是用于兼容的，只是key似乎不是ASCII了
新DS好像换加密算法了，增加了两个新的.so
`    public static String lk2() {
        int[] arrayOfInt = new int[32];
        arrayOfInt[0] = -88;
        arrayOfInt[1] = -120;
        arrayOfInt[2] = -108;
        arrayOfInt[3] = 162;
        arrayOfInt[4] = 102;
        arrayOfInt[5] = 162;
        arrayOfInt[6] = 174;
        arrayOfInt[7] = 192;
        arrayOfInt[8] = -98;
        arrayOfInt[9] = 78;
        arrayOfInt[10] = -74;
        arrayOfInt[11] = 198;
        arrayOfInt[12] = 150;
        arrayOfInt[13] = -82;
        arrayOfInt[14] = -82;
        arrayOfInt[15] = -82;
        arrayOfInt[16] = 180;
        arrayOfInt[17] = -72;
        arrayOfInt[18] = -80;
        arrayOfInt[19] = 210;
        arrayOfInt[20] = 162;
        arrayOfInt[21] = 168;
        arrayOfInt[22] = -19683;
        arrayOfInt[23] = -2187;
        arrayOfInt[24] = -122;
        arrayOfInt[25] = 72;
        arrayOfInt[26] = 78;
        arrayOfInt[27] = -102;
        arrayOfInt[28] = 72;
        arrayOfInt[29] = 114;
        arrayOfInt[30] = -531441;
        arrayOfInt[31] = -104;
        StringBuilder stringBuilder = new StringBuilder();
        ArrayList<Integer> arrayList1 = new ArrayList(arrayOfInt.length);
        int i = arrayOfInt.length;
        for (byte b = 0; b < i; b++) {
            int j = arrayOfInt[b];
            if (j < 0) {
                if (-j >= Math.pow(3.0D, 6.0D)) {
                    j = (int)(Math.log(-(j)) / Math.log(3.0D) - 6 + 48);
                } else {
                    j = j;
                }
            } else {
                j = j / 3 + 48;
            }
            arrayList1.add(Integer.valueOf(j));
        }
        ArrayList<StringBuilder> arrayList = new ArrayList(32);
        for (int value:arrayList1
             ) {
            stringBuilder.append(Character.forDigit(value,10));
            arrayList.add(stringBuilder);
        }

        String str = stringBuilder.toString();
        return str;
    }`

**Comment by Arondight** [comment]
@ixCiel 改了下样式，坐等一个路过的老大哥重写一下 `getDS`

**Comment by Arondight** [comment]
另外根据 https://github.com/Azure99/GenshinPlayerQuery/issues/20#issuecomment-912931997 来看，API 也已经改变

**Comment by Arondight** [comment]
https://github.com/SilveryStar/Adachi-BOT/commit/bfa75444c28299d60491454989b250eeb7b9ce94

**Comment by Arondight** [comment]
我照着抄了一个，但是仍然不行，谁帮我看看哪儿出问题了 https://github.com/Arondight/Adachi-BOT/commit/c005718a2d0b57228131218c7fdcec100386ed97

**Comment by icetech233** [comment]
> 反编译扒拉出一串旧DS代码好像是用于兼容的，只是key似乎不是ASCII了
> 
> 新DS好像换加密算法了，增加了两个新的.so
> 
> ```
>     public static String lk2() {
>         int[] arrayOfInt = new int[32];
>         arrayOfInt[0] = -88;
>         arrayOfInt[1] = -120;
>         arrayOfInt[2] = -108;
>         arrayOfInt[3] = 162;
>         arrayOfInt[4] = 102;
>         arrayOfInt[5] = 162;
>         arrayOfInt[6] = 174;
>         arrayOfInt[7] = 192;
>         arrayOfInt[8] = -98;
>         arrayOfInt[9] = 78;
>         arrayOfInt[10] = -74;
>         arrayOfInt[11] = 198;
>         arrayOfInt[12] = 150;
>         arrayOfInt[13] = -82;
>         arrayOfInt[14] = -82;
>         arrayOfInt[15] = -82;
>         arrayOfInt[16] = 180;
>         arrayOfInt[17] = -72;
>         arrayOfInt[18] = -80;
>         arrayOfInt[19] = 210;
>         arrayOfInt[20] = 162;
>         arrayOfInt[21] = 168;
>         arrayOfInt[22] = -19683;
>         arrayOfInt[23] = -2187;
>         arrayOfInt[24] = -122;
>         arrayOfInt[25] = 72;
>         arrayOfInt[26] = 78;
>         arrayOfInt[27] = -102;
>         arrayOfInt[28] = 72;
>         arrayOfInt[29] = 114;
>         arrayOfInt[30] = -531441;
>         arrayOfInt[31] = -104;
>         StringBuilder stringBuilder = new StringBuilder();
>         ArrayList<Integer> arrayList1 = new ArrayList(arrayOfInt.length);
>         int i = arrayOfInt.length;
>         for (byte b = 0; b < i; b++) {
>             int j = arrayOfInt[b];
>             if (j < 0) {
>                 if (-j >= Math.pow(3.0D, 6.0D)) {
>                     j = (int)(Math.log(-(j)) / Math.log(3.0D) - 6 + 48);
>                 } else {
>                     j = j;
>                 }
>             } else {
>                 j = j / 3 + 48;
>             }
>             arrayList1.add(Integer.valueOf(j));
>         }
>         ArrayList<StringBuilder> arrayList = new ArrayList(32);
>         for (int value:arrayList1
>              ) {
>             stringBuilder.append(Character.forDigit(value,10));
>             arrayList.add(stringBuilder);
>         }
> 
>         String str = stringBuilder.toString();
>         return str;
>     }
> ```

大佬，你们什么工具抓的 salt
