### ISSUE TITLE
thumb当中人物证件照的处理

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#513]
### 问题描述

明明记得加上了来着，睡了，明天看看咋回事
![image](https://user-images.githubusercontent.com/9006264/146790885-f025ad26-9fea-4f12-b754-e8cb24273c4b.png)

### 复现流程

周二素材

### 代码状态：当前提交

刚拉过一遍，睡了，摆了

### 运行环境：操作系统

macOS

**Comment by Arondight** [comment]
这个图在 tumb 里，我更新一下 #57

**Comment by Mark9804** [comment]
这个图似乎是内鬼网上面的正面证件照，我回去对比一下尺寸是不是和其他人一样的，
不一样的话网页做一下适配，一样的话也可以弄成自动化流程了

比如直接用`wget`抓下来，重命名完塞到`thumb`里面

如果把重复的行为交给自动化脚本，开发者专注于功能实现，合法摸鱼就指日可待了

**Comment by Arondight** [comment]
> 如果把重复的行为交给自动化脚本，开发者专注于功能实现

其实现在差不多就是这个情况（指无脑接原作者的资源）

**Comment by Mark9804** [comment]
> > 如果把重复的行为交给自动化脚本，开发者专注于功能实现
> 
> 其实现在差不多就是这个情况（指无脑接原作者的资源）

美术资源外包了属于是

**Comment by Mark9804** [comment]
> 对比一下尺寸是不是和其他人一样的

太遗憾了，不一样，不过也不是完全不能用

![image](https://user-images.githubusercontent.com/9006264/146888196-8cbc880a-c4a2-4035-a613-6c351ccd55de.png)

![image](https://user-images.githubusercontent.com/9006264/146888082-c1b40cd2-7e47-497d-b652-be31ae9c92be.png)

**Comment by Mark9804** [comment]
证件照还是等官方喂，不做内鬼了
