### ISSUE TITLE
最新版本的bot，进行uid查询，部分会出现空白页面bug

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#519]
### Discussed in https://github.com/Arondight/Adachi-BOT/discussions/518

<div type='discussions-op-text'>

<sup>Originally posted by **yylmzxc** December 22, 2021</sup>
![ZGHQ34V0)OPWPPIW E`9X9G](https://user-images.githubusercontent.com/90677130/147095484-74285d9a-b9cb-4031-af0d-f3db50123826.png)
![D3C _VKB7VCD 9AZT5W{RL4](https://user-images.githubusercontent.com/90677130/147095492-328afbea-74dd-479e-8987-b51bc6b478d3.png)
![M@1T)@FN0GP01PIK`O _QSU](https://user-images.githubusercontent.com/90677130/147095499-5463c7e5-f38c-4028-b1fe-b750114c851c.png)
![D3C _VKB7VCD 9AZT5W{RL4](https://user-images.githubusercontent.com/90677130/147096072-c2565dc4-286d-48b8-85fd-565b3dd5fc44.png)
![ZGHQ34V0)OPWPPIW E`9X9G](https://user-images.githubusercontent.com/90677130/147096167-c3a613c2-9e79-48c5-b2db-5681367421fc.png)

目前推测原因应该是查询无元素主角，没有找到元素导致的bug</div>

**Comment by Mark9804** [comment]
uid 161046205
![image](https://user-images.githubusercontent.com/9006264/147097039-60554e78-09c6-4ebe-8b28-eb116f72d34c.png)

**Comment by Mark9804** [comment]
@Arondight 老大哥来看看，好像是假如人物只有一个旅行者的话，因为旅行者在 commit eec1f547207ce1c9e85425351fa97f0aabfd374a 当中被踢出去了，所以人物列表为空，读取不到 `id` 来生成名片的报错


`app.js:98`是这个
https://github.com/Arondight/Adachi-BOT/blob/e6fa636c1ae73b0431088db2d7a1a11704373a65/src/views/component/card-8/app.js#L98

**Comment by Arondight** [comment]
那就这样，弄个旅行者的名片吧，然后就不用踢出去了

**Comment by Mark9804** [comment]
有旅行者的名片，但是没有头像，我整一个头像来

**Comment by Arondight** [comment]
元素似乎也得有个无元素的图

**Comment by Arondight** [comment]
有了图之后把 `charsWithoutYe` 换成 `params.avatars` 就行了

**Comment by Mark9804** [comment]
无元素就不显示元素了，旅行者这边的名称得对 `data` 做一个更改，
因为旅行者有男女，
`10000005` 对应哥哥，`10000007` 对应妹妹，但是在前端数据里面都叫“旅行者”，不知道要抓哥哥还是妹妹的

我想把 id 为 `10000005` 的人物的 `name` 属性改成 "旅行者男" 或者 “哥哥”， `10000007` 改成 “旅行者女” 或者 "妹妹"，这样方便从 `thumb` 里面抓对应的图，老大哥看这事情是在前端做还是后端做了

这么说来的话……理论上 `material.html` 也会出现这个问题吧？
![image](https://user-images.githubusercontent.com/9006264/147102397-bc07bd97-6fcb-45be-b05d-a968330b68af.png)
