### ISSUE TITLE
米游社可能已经禁止国内特定VPS服务商的IP或ASN

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#522]
例如腾讯云、阿里云等等，如果你已经更新到了最新的代码，查询游戏信息时发现迟迟没有反应，而你的机器人又部署在云上，那么可能是被禁掉了。当前没有解决办法，尝试在你本地的个人设备（例如个人电脑或树莓派等开发板）上部署吧。

我已经挪到树莓派上了，资源占用差不多如下图，仅供参考。

![图片](https://user-images.githubusercontent.com/13673702/147329491-d3559a3a-ecc6-45b6-8410-493ccb5cb8db.png)

如果你有更多问题请直接回复。如果你知道有什么没有被封禁的VPS服务商也请回复一下。

---

总结评论区目前已知的情况如下。

| 服务商 | 可用 |
| --- | --- |
| 华为云 | ❌ |
| Oracle 春川 | ✔️ |
| DigitalOcean 新加坡 | ✔️ |
| 腾讯云 | ❌ |
| 阿里云 | ❌ |
| DMIT 美西 | ❌ |

**Comment by Arondight** [comment]
@SilveryStar @KimigaiiWuyi @wudifeixue @ixCiel

**Comment by wudifeixue** [comment]
刚刚在日本的Azure上用curl测试了下api地址，能正常使用返回正确信息

**Comment by ixCiel** [comment]
结合你之前的错误信息和这里的统计信息
个人猜测，可能不是米游社封禁了VPS服务商
是VPS服务商的防火墙误判了
误判的原因可能是：米游社改了接口，因为你配置了比较多的群，一段时间内大量请求报错，而且是同域名下的，于是防火墙误判
国外的廉价vps一般是不会提供防火墙的，于是就没事
如果是米游社封禁的话，应该不会由阿里云来给出提示

**Comment by Arondight** [comment]
> 如果是米游社封禁的话，应该不会由阿里云来给出提示

应该是米游社跑在阿里云上，我的VPS是腾讯云的，然后访问米游社却拿到了阿里云的警告

**Comment by ixCiel** [comment]
那就比较危险了
单纯封VPS服务商还好
如果根据接口访问量来的话
家里的树莓派也危险

**Comment by Mark9804** [comment]
这个首先一定是应对 bot 和爬虫的措施，应不应该被解读成“米忽悠盯上了我们 bot ”我觉得再看看吧

关于这个问题，我觉得最合理的解释是“出于某种原因，米游社 API 的 Web应用防火墙[WAF](https://help.aliyun.com/product/28515.html) 被配制成禁止 ASN（[\[1\]](https://www.zhihu.com/question/21024981), [\[2\]](https://zh.wikipedia.org/wiki/%E8%87%AA%E6%B2%BB%E7%B3%BB%E7%BB%9F) ）归属于阿里云和腾讯云的访问”的规则

每家的 WAF 一般是有两大套以上的规则集（Ruleset）：大家一起用的 OWASP 规则集，还有自己维护的一套规则集，然后应该阿里云也允许用户自己修改规则集。这个拒绝访问的行为的源头可能是某一个“ bot 行为防护（跑在云上肯定不是人）”规则集，或者是米忽悠自己添加了“如果 ASN 为 45104（阿里云）或者 45090（腾讯云）则拒绝访问”的规则

![image](https://user-images.githubusercontent.com/9006264/147338853-647ca3de-390b-423e-841b-a43cfe03e84a.png)

当然防火墙规则一定不止一条，基本的 IP 黑名单，访问速率限制（Rate limiting）应该也是有全套的

**Comment by Mark9804** [comment]
隔壁有讨论了
![IMG_1006](https://user-images.githubusercontent.com/9006264/147340417-74821717-d20d-4bd7-adc4-f24c59139548.jpg)

**Comment by Arondight** [comment]
没看明白这图有了什么结论？是多了个参数吗

**Comment by Mark9804** [comment]
> 没看明白这图有了什么结论？是多了个参数吗

没有多参数，那个说多了个 dc 的应该是 ds 看走眼了……

也不能说有什么新结论吧，只能说有更多信息来验证之前的假设

1. 迁移后理论上米游社 API 都有了 WAF：
  - 玩家统计信息；
  - 玩家角色详细信息；
  - 深渊详细信息；
  - 实时便签（图中验证）；
  - 活动应该也是有的（未经验证）
2. 这次只改了 API 路径，加上了 WAF，API 本身的行为确实没有变化（跟我们几个人的抓包测试结果比起来，更多人验证了这个猜想）

我觉得上防火墙算是一个正常公司都会做的安防行为，现在的疑点是防火墙的规则是按 ASN 还是按 IP（或IP段） 还是按照请求速率进行限制访问的，上面这张图是一个原神和米游社混合签到项目，等明天看看群里面有没有更多消息

**Comment by Arondight** [comment]
我也在群里

**Comment by 741807012** [comment]
还好我有软路由，然后里面安装个win系统专门挂机器人/微笑

**Comment by CMHopeSunshine** [comment]
今天上午刚更新的代码，部署在华为云上，uid、米游社等指令仍然可用

**Comment by Mark9804** [comment]
[AS/BGP report for the country China.](https://dnslytics.com/bgp/cn)

| ASN          | 所属                                              | 状态   |
| ------------ | ------------------------------------------------- | ------ |
| 55990        | Huawei Cloud Service data center                  | 可用   |
| 45090/132203 | Shenzhen Tencent Computer Systems Company Limited | 不可用 |
| 45102        | Alibaba (US) Technology Co., Ltd.                 | 不可用 |

**Comment by Mark9804** [comment]
如果有条件的话，可以试试看最新的阿里云/腾讯云的机房，如果是按照 IP 段进行 block 的话，这些新机房可能还没写进规则，也就是可以正常访问。

如果这样的话，拒绝按照 ASN 屏蔽的假设，支持按照 IP 段进行屏蔽的假设

**Comment by Alpiiine** [comment]
> [Autonomous System Lookup (AS / ASN / IP)](https://hackertarget.com/as-ip-lookup/) [AS/BGP report for the country China.](https://dnslytics.com/bgp/cn)
> 
> ASN	所属	状态	备注
> 55990	Huawei Cloud Service data center	可用	
> 4713	OCN NTT Communications Corporation, JP	可用	日本
> 45090/132203	Shenzhen Tencent Computer Systems Company Limited	不可用	
> 45102	Alibaba (US) Technology Co., Ltd.	不可用

37963 阿里云上海 不可用

**Comment by Nuevo009** [comment]
ASN | 所属 | 状态 | 备注
-- | -- | -- | --
|31898 | ORACLE-BMC-31898 |可用 |Oracle Cloud chuncheon 
|14061 | DIGITALOCEAN-ASN |可用 |DigitalOcean Singapore

**Comment by Mark9804** [comment]
> 今天上午刚更新的代码，部署在华为云上，uid、米游社等指令仍然可用

是在国内的数据中心上的华为云吗？

**Comment by CMHopeSunshine** [comment]
> > 今天上午刚更新的代码，部署在华为云上，uid、米游社等指令仍然可用
> 
> 是在国内的数据中心上的华为云吗？

是的，在上海的HECS（云耀云服务器），弹性公网IP

**Comment by citydirector** [comment]
我刚刚试了下DMIT的(美西)服务器，发送米游社指令后看log有显示cookie，然后没了下文

**Comment by Mark9804** [comment]
> 我刚刚试了下DMIT的(美西)服务器，发送米游社指令后看log有显示cookie，然后没了下文

那应该是不能用了，而且 DMIT 连国内的数据中心都没有，这样的话“只禁了国内运营商”的假设就是错的

**Comment by KimigaiiWuyi** [comment]
这一波有一点难受，挂VPN也不是办法，毕竟vpn服务商也偶尔会有网络波动；
而且不排除米游社未来扩大范围，华为云等其他云也有被屏蔽的可能性

**Comment by davidelectricfree** [comment]
为了一个软件去买个树莓派？感觉不划算啊，老老实实挂着当个wiki机器人算了

**Comment by NepPure** [comment]
其实这问题说麻烦也不麻烦，不想换服务器自己搭建个反向代理，或者简单点直接找个能用的cdn回源米游社

**Comment by Arondight** [comment]
> 其实这问题说麻烦也不麻烦，不想换服务器自己搭建个反向代理，或者简单点直接找个能用的cdn回源米游社

反代还是要有个能用的 IP 吧，cdn 的话有现成的吗

**Comment by citydirector** [comment]
> > 其实这问题说麻烦也不麻烦，不想换服务器自己搭建个反向代理，或者简单点直接找个能用的cdn回源米游社
> 
> 反代还是要有个能用的 IP 吧，cdn 的话有现成的吗

看到cdn第一个反应是cloudflare...(没记错的话实际上cf的国内cdn是百度提供的)

**Comment by 1055169799** [comment]
目前我能想出的方法是用CCProxy，在插件里把机器人的数据通过映射端口到个人/公司的电脑上，转发给米游社，然后得到结果再传回去。要求就是个人电脑不能关机（公司电脑不关机应该还好），但经过这步转发，出消息的速度上可能会慢一些。

**Comment by NepPure** [comment]
套个CDN完事，应用防火墙没有封各大CDN回源IP，低调使用就是了。

各大云白嫖额度反正用不完。

当然你想用国内线路你得有个备了案的域名

**Comment by Putarku** [comment]
我刚刚腾讯云的机器人又可以获取api数据了，你们检查一下试试

**Comment by 1055169799** [comment]
> 我刚刚腾讯云的机器人又可以获取api数据了，你们检查一下试试

出了出了！哇，喜大普奔。我的诺艾尔活过来了。

**Comment by KimigaiiWuyi** [comment]
> 我刚刚腾讯云的机器人又可以获取api数据了，你们检查一下试试

阿里云依旧挂

**Comment by KimigaiiWuyi** [comment]
> > 我刚刚腾讯云的机器人又可以获取api数据了，你们检查一下试试
> 
> 阿里云依旧挂

阿里云已正常

**Comment by Arondight** [comment]
过一周如果依然正常这个 issue 就关掉

**Comment by 1055169799** [comment]
> > 我刚刚腾讯云的机器人又可以获取api数据了，你们检查一下试试
> 
> 出了出了！哇，喜大普奔。我的诺艾尔活过来了。

高兴太早了,查询开了半小时,又出现了
JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
我原以为是限制了每个IP查询次数，结果隔壁群机器人也是这个结果。

**Comment by Arondight** [comment]
🤔那是个什么逻辑呢

**Comment by CMHopeSunshine** [comment]
完犊子，刚刚我华为云也开始JSONDecodeError了，之前一直能用

**Comment by Mark9804** [comment]
抓一个米忽悠的人来逼供一下就知道是什么逻辑了，我感觉可能他们也在纠结要不要向 bot 提供这个查询服务吧……

**Comment by Arondight** [comment]
我觉得我们还没到值得官方特意去改 api 来限制的程度，充其量顶多是官方打压什么顺手一巴掌把我们拍死的体量

**Comment by Mark9804** [comment]
> 我觉得我们还没到值得官方特意去改 api 来限制的程度，充其量顶多是官方打压什么顺手一巴掌把我们拍死的体量

我也是这个看法，我们被波及的可能性比较大，被动适应就完事了

**Comment by 1055169799** [comment]
> 抓一个米忽悠的人来逼供一下就知道是什么逻辑了，我感觉可能他们也在纠结要不要向 bot 提供这个查询服务吧……

那还得抓技术部相关人员才能知道。我估计是动了米游社的蛋糕了，毕竟有了机器人，要查询账号的用户打开APP的次数变少了。如果像我一样把签到都挂在第三方的，半个月都不开一次米游社。（以上纯属个人瞎猜）

**Comment by KimigaiiWuyi** [comment]
> > 抓一个米忽悠的人来逼供一下就知道是什么逻辑了，我感觉可能他们也在纠结要不要向 bot 提供这个查询服务吧……
> 
> 那还得抓技术部相关人员才能知道。我估计是动了米游社的蛋糕了，毕竟有了机器人，要查询账号的用户打开APP的次数变少了。如果像我一样把签到都挂在第三方的，半个月都不开一次米游社。（以上纯属个人瞎猜）

签到是一切正常的，甚至之前DS变动都没影响到签到

**Comment by Arondight** [comment]
> 我估计是动了米游社的蛋糕了

这么说我感觉米哈游得给广告费的哈，本质上是玩家联合把广告直接打到了丘丘里，还得自己买 vps 用

**Comment by 1055169799** [comment]
> > 我估计是动了米游社的蛋糕了
> 
> 这么说我感觉米哈游得给广告费的哈，本质上是玩家联合把广告直接打到了丘丘里，还得自己买 vps 用

确实，用爱发电，我一口气续了三年服务器，为了防止风控还给bot充了会员和黄钻，前几天还熬夜排查问题，折腾跳板转发（希望能感动米忽悠，把权限给开开，大家都开心）

**Comment by Arondight** [comment]
我的意思是说机器人是能给官方起到宣传作用的，没有说官方会喜欢哈，这种事就跟你妈让你喝枸杞泡水一样，想的太好容易自我感动，官方懒得动手拍死我们就挺好了，说不定哪天一个 dmca 就过来了

**Comment by 1055169799** [comment]
> 我的意思是说机器人是能给官方起到宣传作用的，没有说官方会喜欢哈，这种事就跟你妈让你喝枸杞泡水一样，想的太好容易自我感动，官方懒得动手拍死我们就挺好了，说不定哪天一个 dmca 就过来了

要什么时候能混到观测枢那个地位就好了。

**Comment by Mark9804** [comment]
> 要什么时候能混到观测枢那个地位就好了。

做做梦就好了这个

**Comment by citydirector** [comment]
> > > 我估计是动了米游社的蛋糕了
> > 
> > 
> > 这么说我感觉米哈游得给广告费的哈，本质上是玩家联合把广告直接打到了丘丘里，还得自己买 vps 用
> 
> 确实，用爱发电，我一口气续了三年服务器，为了防止风控还给bot充了会员和黄钻，前几天还熬夜排查问题，折腾跳板转发（希望能感动米忽悠，把权限给开开，大家都开心）

我也是...

**Comment by wudifeixue** [comment]
> 

微信的提瓦特小助手比较大规模，针对那个可能性比较大吧

**Comment by wudifeixue** [comment]
> 我觉得我们还没到值得官方特意去改 api 来限制的程度，充其量顶多是官方打压什么顺手一巴掌把我们拍死的体量

微信的提瓦特小助手比较大规模，针对那个可能性比较大吧

**Comment by Mark9804** [comment]
> 微信的提瓦特小助手比较大规模，针对那个可能性比较大吧

已知消息：
1. 微信某个抽卡+分析小程序被重拳出击了
2. 微信某个纯抽卡模拟小程序被重拳出击了
3. 提瓦特小助手没事

**Comment by Arondight** [comment]
> 这年头就，人不能老实过头了

是这样的，但是人家是生意，和米家法务部对刚大概率啥事没有，不过前提是米家动了你的饭碗才值得

**Comment by KimigaiiWuyi** [comment]
> > 这年头就，人不能老实过头了
> 
> 是这样的，但是人家是生意，和米家法务部对刚大概率啥事没有，不过前提是米家动了你的饭碗才值得

刚接到反馈，老api（也就是不加`-record`的原本的api），已经恢复，并且可以在VPS上使用

**Comment by Arondight** [comment]
> 老api（也就是不加`-record`的原本的api），已经恢复

我观察一下，因为米家整天反复横跳，我担心啥时候又关了，或者只是重新开的忘了加屏蔽了

**Comment by KimigaiiWuyi** [comment]
> 

根据我收到的反馈来看，已经好了至少有两天了……因为他一直没更新新版本，很早就恢复了；

**Comment by KimigaiiWuyi** [comment]
> > 老api（也就是不加`-record`的原本的api），已经恢复
> 
> 我观察一下，因为米家整天反复横跳，我担心啥时候又关了，或者只是重新开的忘了加屏蔽了

根据我收到的反馈来看，已经好了至少有两天了……因为他一直没更新新版本，很早就恢复了；

**Comment by Arondight** [comment]
> 根据我收到的反馈来看，已经好了至少有两天了……因为他一直没更新新版本，很早就恢复了；

令人迷惑的操作

**Comment by wudifeixue** [comment]
> 刚接到反馈，老api（也就是不加`-record`的原本的api），已经恢复，并且可以在VPS上使用

啊这，这。。要不要做个验证，两个api一个不行换另一个

**Comment by semyin** [comment]
等大佬更新

**Comment by Mark9804** [comment]
就是说现在旧版本API虽然不能获取超过八个角色的信息，但至少能用是吧

我觉得有没有可能是因为米忽悠收到了大量旧版本米游社app不能正常显示角色的报错？说到底好像很少人试过旧版本米游社的行为正不正常，不过我觉得旧API应该会在未来某一天完全停止服务的，只不过不知道这个边界条件是什么，可能是旧版本米游社app的占有率低于百分之多少

**Comment by f5723508** [comment]
@Arondight
API 回退，Ref #522
腾讯云正常了

**Comment by semyin** [comment]
@Arondight 
更新到最新的代码
阿里云正常了

**Comment by Mark9804** [comment]
旧的API没有网络防火墙，所以旧API不正常的话才是真不正常。

个人觉得现在可能是新旧API同时使用的过渡期，还需要继续观察

**Comment by KimigaiiWuyi** [comment]
> 旧的API没有网络防火墙，所以旧API不正常的话才是真不正常。
> 
> 个人觉得现在可能是新旧API同时使用的过渡期，还需要继续观察

旧的API之前是503错误？那时候我在车上不知道具体报什么错

**Comment by Mark9804** [comment]
> 旧的API之前是503错误？那时候我在车上不知道具体报什么错

就有且仅有 `503 service unavailable`

**Comment by Arondight** [comment]
两周过去了，看起来会安稳一段时间了，以后出问题了新开 issue
