### ISSUE TITLE
填坑

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#524]
- [x] 因为米游社开始封禁部分云主机服务商IP，所以现在当强求出错时返回一个非技术性的恰当的提示。
- [x] card 中有一个 css 里使用的 url 没有保存到本地
- [x] 更改数据库后无效 cookie 的处理似乎有问题，需要验证，如果有问题作出更改
  - [x] 无效项目的 times 没有拉满
  - [x] 删除配置中对应项目有，无效项目在数据库清理后没有被删除
- [x] Ctrl+C 停止 bot 有概率卡住
- [x] bot 被杀死的时候尝试给管理者发送一条消息（非异步）
- [x] 起浏览器的逻辑要优化一下

**Comment by Mark9804** [comment]
爬虫的海底隧道老大哥还打算填吗，我还有一丝息灾不用手动爬网页的幻想

**Comment by Arondight** [comment]
> 爬虫的海底隧道老大哥还打算填吗，我还有一丝息灾不用手动爬网页的幻想

填的，不过这个好像也不紧急，毕竟离下次用还有很长时间

**Comment by Arondight** [comment]
无效 cookie 的在 linux 上试了没有问题，我猜可能是 windows 上退出 bot 没有正确刷新数据库的原因？总之既然 linux 上正常，其他的平台我就不管了

**Comment by Arondight** [comment]
nodejs 为啥信号处理不支持异步呢

**Comment by Arondight** [comment]
狗日的 puppteeer ，信号处理错误查了半天，结果是让 puppeteer 截了

**Comment by Arondight** [comment]
![图片](https://user-images.githubusercontent.com/13673702/147553156-48bfd517-ebdb-4427-945b-e5c7d48b04e9.png)

就这样把

**Comment by Arondight** [comment]
虽然我没想明白为啥需要等一个延时，不过去掉确实是不能工作了，暂时就这样把
