### ISSUE TITLE
服务器繁忙

### ISSUE THREAD

**Issue by 673918731** [Arondight/Adachi-BOT#526]
### 问题描述

[](url)间歇性登入
大部分时间都服务器繁忙
手表登入方式
![QQ图片20211226221632](https://user-images.githubusercontent.com/88731781/147410852-9f427ddd-5dec-46b7-862a-73fa59de7579.png)

### 复现流程

貌似是qq登不上去

### 后台日志

```Text
Adachi-BOT@1.5.1 log
> cross-env-shell PM2_HOME=$INIT_CWD/bot.pm2/ npx pm2 log --lines 100 bot

[PM2] Spawning PM2 daemon with pm2_home=C:\Users\Administrator\BOT/bot.pm2/
[PM2] PM2 Successfully daemonized
[TAILING] Tailing last 100 lines for [bot] process (change the value with --lines option)
```

### 代码状态：当前提交

fatal: your current branch 'master' does not have any commits yet

### 运行环境： Node.js 版本

v17.0.1

### 运行环境： npm 版本

8.1.0

### 运行环境：操作系统

Windows

**Comment by Arondight** [comment]
似乎是个救问题，更新代码然后运行 `npm install` 试一下

**Comment by 673918731** [comment]
嗯嗯，解决了谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Arondight/Adachi-BOT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月26日(星期天) 晚上10:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Arondight/Adachi-BOT] 服务器繁忙 (Issue #526)





 
似乎是个救问题，更新代码然后运行 npm install 试一下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
