### ISSUE TITLE
uid查询用户信息

### ISSUE THREAD

**Issue by SQSora** [Arondight/Adachi-BOT#53]
建议使用 uid 也应该能够触发UID查询功能

**Comment by Arondight** [comment]
这个我要想想，最开始我做成大小写敏感是因为

1. 防止聊天内容误触 bot
2. 为了和其他的 bot 区分开，不要多个 bot 响应同一条信息

但是确实也带来一点使用上的不方便

**Comment by SQSora** [comment]
> 这个我要想，最开始我想做成大小写敏感是因为
> 
> 1. 防止聊天内容误触机器人
> 2. 为了和其他机器人区单独，不要有多个机器人同一响应条信息
> 
> 但是确实也带来一点使用上的不方便

可以做个判断：有包含UID的聊天内容里面是不是UID+纯数字 内容

**Comment by Arondight** [comment]
@SQSora 我明白你的意思，最开始我也是想规避掉其他机器人的命令，不过我感觉这个可以再评估一下，大家都用一个命令并不是我的错

**Comment by Arondight** [comment]
根据群广播的调查结果，此类命令改成大小写不敏感
