### ISSUE TITLE
API 返回的数据结构为啥被打印出来了

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#533]
### 问题描述

![图片](https://user-images.githubusercontent.com/13673702/147811109-bfc3d36e-be7f-4163-bae0-4f50fa863f15.png)

见了鬼了

### 复现流程

1

### 代码状态：当前提交

0c9acab

### 代码状态：是否修改

Clean

### 运行环境：操作系统

Linux

**Comment by Mark9804** [comment]
![image](https://user-images.githubusercontent.com/9006264/147811363-62c6d89f-246a-43bb-b09f-3e4fc9c79763.png)
我自己 fork 没看到，是不是哪里 debug 忘记删掉了

**Comment by Arondight** [comment]
没有啊，就是上游的代码

**Comment by Arondight** [comment]
有人遇到同样的问题麻烦回复一下？我很确定代码中没有任何单独的终端打印语句，这串东西哪儿来的？

**Comment by Arondight** [comment]
哦，原来是我在 node-fetch 里面加的调试

**Comment by Arondight** [comment]
哦，想起来了，我加了个调试发现 api 访问返回来个网页出来，才有了 #522
