### ISSUE TITLE
oicq 升级后无法支持陌生人聊天

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#535]
### 问题描述

https://github.com/takayama-lily/oicq/discussions/277

### 复现流程

1

### 代码状态：当前提交

1

### 代码状态：是否修改

Clean

### 运行环境：操作系统

Linux

**Comment by Mark9804** [comment]
oicq 1.x 的时候就已经有这个问题了，并不是 2.x 特有的问题

**Comment by Arondight** [comment]
> oicq 1.x 的时候就已经有这个问题了，并不是 2.x 特有的问题

1.x 我的 bot 是可以正常回应陌生人聊天的呀

**Comment by Mark9804** [comment]
哦哦，是我理解错了，1.x只是不能主动发起会话（例如给不是好友的 bot master 发送上线通知）但是可以使用快速回复，2.x 确实不行了

**Comment by Arondight** [comment]
晚上回家后紧急改一下，oicq 行为改变了，我在 `bot.say` 中做一些补救
