### ISSUE TITLE
评分时候需要加空格好多人没注意到

### ISSUE THREAD

**Issue by SQSora** [Arondight/Adachi-BOT#54]
这个理论上不会误触吧

**Comment by Arondight** [comment]
1. 会
2. 这是统一行为，去掉空格的话我会把所有的命令都去掉

我觉得这个可以考虑

**Comment by Arondight** [comment]
Dup #53

**Comment by Arondight** [comment]
根据群广播调查结果，命令维持加空格的传统，但是因为【评分】后跟图片的特殊性，此命令不需要加空格，在代码注释中进行说明并指向此 Issue
