### ISSUE TITLE
提示网络环境异常，错误码：237。

### ISSUE THREAD

**Issue by iorinoe** [Arondight/Adachi-BOT#55]
滑动最后一步取出ticket，打开活动页面之后，F12获取ticket，{"result":"0","ticket":"t038-jcKCMfNAmxQ
然后直接输入ticket部分？
输入完之后，提示 [禁止登录]当前上网环境异常，请更换网络环境或在常用设备上登录或 稍后再试。(错误码：237)
试过更换1-5设备，依然都是一样问题。本地直接登录这个账号是没问题的。求教这个是QQ账号问题还是登录的OICQ问题。

**Comment by Arondight** [comment]
#19

**Comment by Arondight** [comment]
如果想看原因参考：https://github.com/takayama-lily/oicq/issues/178

**Comment by iorinoe** [comment]
已解决，不过跟说的方式有点不一样。网页可以访问滑动页面，也可以获取ticket，但是输入之后，就是不提示第二步扫码，可能要求真机滑动才让进行下一步。流程如何：

1. 安装https://github.com/mzdluo123/TxCaptchaHelper/releases 这个apk在真机上滑动；
2. 滑动后，会再提示“登录保护我二维码验证地址”，这时候可以复制地址到浏览器，然后用登录该账号的QQ扫码解除保护，原QQ手机端下线。
