### ISSUE TITLE
“限定角色祈愿”和“限定武器祈愿”应该至少保留一个默认卡池

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#553]
### 问题描述

RT，今天下午一斗和巧乐兹的卡池关闭了，现在没卡可抽了，我觉得应该保留一个卡池的默认配置

![image](https://user-images.githubusercontent.com/9006264/148052377-ed732a9e-67ec-4b1d-80ac-c95be3302f9a.png)

**Comment by Arondight** [comment]
我觉得挺合理的，就先这样吧
