### ISSUE TITLE
个人信息展示海底的数据

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#563]
### 问题描述

米游社已经有数据了，老大哥有空做一下吧，没空就算了，我觉得不紧急

**Comment by Mark9804** [comment]
css改了忘记改js了，晚上就改造成全自动

**Comment by Mark9804** [comment]
原作者还没做渊下宫的 logo 图，我们现在有三个选择：
1. 放弃原作者画好的所有 logo，改为从米游社抓取（也可以抓回本地，我已经写好逻辑了），然后交由前端上色。
  这么做的好处是开新地区不用改任何东西就可以用（有空时抓回本地就行），突出一个安逸
2. 混用原作者 logo 和米游社 logo ，之后依然不用做任何适配，有空时抓回本地就行。前端这边需要一点额外 vue 代码来处理这部分逻辑
3. 自己整一个 logo ，或者等原作者整一个 logo ，之后每开一个新地区都手动做一个 logo 。这样代码量最小，需要我们维护者介入的部分在三种方案里面最多

**Comment by Mark9804** [comment]
@Arondight 老大哥决定一下，这个和更新脚本的行为有关

**Comment by Arondight** [comment]
假设我来做的话，我肯定是想在最小工作量的情况下混吃混喝，没图就显示个 error ，作者跑路了，我再想办法

**Comment by Mark9804** [comment]
用了方案2，现在全自动模式躺平了

如果老大哥饭后实在是想消化一下，想去抓米游社的图回本地，记得把渊下宫的映射加上，或者看不下去了重写也行

https://github.com/Arondight/Adachi-BOT/blob/d81110621c3b9730bd40adfb0bfd8ef59b307b06/src/views/component/card-8/exploration.js#L32-L38
