### ISSUE TITLE
如何为项目制作资源文件

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#57]
以下内容来自[资源制作.md](https://github.com/Arondight/Adachi-BOT/blob/master/docs/%E8%B5%84%E6%BA%90%E5%88%B6%E4%BD%9C.md) 。本 Issue 作为文档使用，永不关闭。资源文件制作细节请见 #317 。

---

# 资源制作

## 说明

你可以根据[原神数据库](https://genshin.honeyhunterworld.com/?lang=CN)制作每个卡池的角色，如果有人 PS 很拿手欢迎 PR。几乎所有的素材，都可以在数据库中搜索名称或者他通过左侧的索引找到。[这个网站](https://genshin-impact.fandom.com/wiki/Genshin_Impact_Wiki)中也有大量的素材，可以填充数据库中没有的部分。

### 结构

```
Adachi-BOT
├── resources                   # 资源文件目录
│   ├── characters
│   │   └── profile             # （弃用）角色头像
│   ├── gacha
│   │   ├── element             # 元素类型图标；genshin-gacha.html
│   │   ├── items               # 抽卡背景；genshin-gacha.html
│   │   └── type                # 武器类型图标；genshin-gacha.html
│   ├── item                    # 一些零碎图片
│   ├── module                  # 游戏信息展示框图；genshin-card.html
│   ├── paimon                  # （弃用）派蒙专属目录
│   └── Version2
│       ├── area                # 七国图标；genshin-card.html
│       ├── artifact            # 圣遗物套图；genshin-artifact.html
│       ├── character           # 角色立绘；genshin-overview.html
│       ├── emoticons           # （弃用）角色小表情
│       ├── info
│       │   ├── docs            # 角色信息数据：genshin-overview.html
│       │   ├── image           # 升级素材图片；genshin-overview.html
│       │   └── other           # 游戏信息展示框图；genshin-overview.html
│       ├── module              # 圣遗物展示框图；genshin-character.html
│       ├── namecard            # 角色名片；genshin-card.html
│       ├── thumb
│       │   ├── character       # 角色图标；genshin-material.html
│       │   ├── stars           # 星级图标背景；genshin-{card,material}.html
│       │   └── weapon          # 武器图标；genshin-material.html
│       ├── weapon              # 武器立绘；genshin-overview.html
│       └── wish
│           ├── character       # 角色抽卡图片；genshin-gacha.html
│           ├── config          # 角色和武器数据
│           └── weapon          # 武器抽卡图片；genshin-gacha.html
└── resources_custom            # 项目定制的资源文件目录
```

> `../resources_custom/` 的结构和 `../resources/` 完全一致，`../resources/update.sh` 会用前者覆盖后者。

#### resources

此目录是实际使用的资源目录，其中有一个脚本 `update.sh` ，会做两件事。

1. 向原作者的 OSS 请求资源文件并按路径保存到此目录。
2. 复制 `../resources_custom/` 目录下的文件，覆盖到此目录中的对应路径。

#### resources_custom

此项目制作的资源文件，应当按照目录组织存放到此处，会覆盖到 `../resources/` 目录下的对应路径。

### 说明

目录 `../resources_custom/` 是为了和原作者的资源分割开，在同步原作者的资源文件后会把此目录的资源文件全部覆盖过去。所以如果没 `../resources_custom/` 下没有对应的路径，你可以类比 `../resources/` 的目录结构，一级一级地去创建出来。

| 我在制作什么                                          | 我该参考什么                                       |
| ----------------------------------------------------- | -------------------------------------------------- |
| `../resources_custom/characters/profile/<角色ID>.png` | `../resources/characters/profile/<其他角色ID>.png` |

### 角色

新角色需要增加以下文件。

1. `../resources_custom/Version2/info/docs/<中文角色名>.json`，运行命令 `npm run tool-info -- -n 中文角色名`以生成此文件。
2. `../resources_custom/Version2/info/image/<中文物品名>.png`，包含 `1.` 中写明的所有的角色素材，会在`【信息】`和`【今日素材】`中使用。
3. `../resources_custom/Version2/character/<角色ID>.png`，这里是`【信息】`和`【我的】`上方的图，`角色ID` 查看 `1.` 中的对应字段。
4. `../resources_custom/Version2/thumb/character/<中文角色名>.png`，这里是`【今日素材】`、`【米游社】`和`【UID】`中的角色图标。
5. `../resources_custom/Version2/costumes/splashes/<中文时装名>.png`，可能的时装图，会在`【我的】`中使用。
6. `../resources_custom/Version2/costumes/avatars/<中文时装名>.png`，这里是`【米游社】`和`【UID】`中可能的时装图标。

### 武器

新武器需要增加以下文件。

1. `../resources_custom/Version2/info/docs/<中文武器名>.json`，运行命令 `npm run tool-info -- -n 中文武器名`以生成此文件。
2. `../resources_custom/Version2/info/image/<中文物品名>.png`，包含 `1.` 中写明的所有的武器素材，会在`【信息】`中使用。
3. `../resources_custom/Version2/weapon/<中文武器名>.png`，这里是`【信息】`上方的图。
4. `../resources_custom/Version2/thumb/weapon/<中文武器名>.png`，这里是`【今日素材】`中的武器图标。

### 卡池

新卡池需要增加以下文件。

1. `../resources_custom/Version2/wish/character/<中文角色名>.webp`，新角色的`【十连】`抽卡出货的图。
2. `../resources_custom/Version2/wish/weapon/<中文武器名>.png`，新武器的`【十连】`抽卡出货的图。

#### 额外的资源文件

如果一个版本包含了新地图、新洞天，那么需要参考上文中的目录结构注释添加对应的资源文件。

#### 角色和武器的描述文件

在 `../resources_custom/Version2/info/docs/*.json` 中，字段 `access` 必须是以下的值之一。

1. 祈愿
2. 商城
3. 纪行
4. 探索
5. 锻造
6. 活动
7. 联动

## 资源提交

使用 `git` 提交资源文件变更，并且向本项目的 `dev` 分支发起 Pull request 。

## 致谢

感谢各位游戏爱好者的工作！

**Comment by Arondight** [comment]
另，打算制作某个资源，请提交 Issue，可以避免他人的重复劳动

**Comment by iorinoe** [comment]
意思当前卡池抽出来的有些error，可以通过添加资源制作显示正常了？
还有，看到别人的机器人UID信息还可以显示武器信息，这个应该修改哪里？

**Comment by Arondight** [comment]
@iorinoe 
1. 是的，但是目前没有人去做，我也不会 PS，很头疼。
2. 改 Vue 就行，数据在 Json 里面都是有的

```
        {
          "id": 10000016,
          "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Diluc.png",
          "name": "迪卢克",
          "element": "Pyro",
          "fetter": 10,
          "level": 90,
          "rarity": 5,
          "actived_constellation_num": 4,
          "costumes": [],
          "weapon": {
            "name": "狼的末路",
            "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/equip/UI_EquipIcon_Claymore_Wolfmound.png",
            "rarity": 5,
            "level": 90,
            "desc": "狼的骑士所使的大剑。原本只是城中铁匠赠予的厚重的铁片，却在他与狼的情谊中，获得神话般的力量。",
            "affix_level": 2
          },
          "artifact": [
            {
              "name": "魔女的炎之花",
              "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/equip/UI_RelicIcon_15006_4.png",
              "pos": 1,
              "rarity": 5,
              "level": 20
            },
            {
              "name": "魔女常燃之羽",
              "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/equip/UI_RelicIcon_15006_2.png",
              "pos": 2,
              "rarity": 5,
              "level": 20
            },
            {
              "name": "魔女破灭之时",
              "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/equip/UI_RelicIcon_15006_5.png",
              "pos": 3,
              "rarity": 5,
              "level": 20
            },
            {
              "name": "平雷之器",
              "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/equip/UI_RelicIcon_14002_1.png",
              "pos": 4,
              "rarity": 5,
              "level": 20
            },
            {
              "name": "焦灼的魔女帽",
              "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/equip/UI_RelicIcon_15006_3.png",
              "pos": 5,
              "rarity": 5,
              "level": 20
            }
          ],
          "constellationNum": 4
        },
```

**Comment by SilveryStar** [comment]
大一刚开学正好撞上版本更新了，事情有点多，oss 资源会在明天中午之前更新完毕，以后版本大概会在更新当天十点前完成，你这边也辛苦了

**Comment by Arondight** [comment]
> 
> 
> 大一刚开学正好撞上版本更新了，事情有点多，oss 资源会在明天中午之前更新完毕，以后版本大概会在更新当天十点前完成，你这边也辛苦了

大佬现身了，有个老大哥制作了一些资源文件，你可以拿去用。另外 DS 要换了，你知道在哪个解包佬那儿可以抄一个吗？

**Comment by SilveryStar** [comment]
@Arondight 这得等一段时间了，我也是从别的 repo 那抄的

**Comment by Arondight** [comment]
[内鬼网无了](http://web.archive.org/web/20210910234717/https://genshin.honeyhunterworld.com/2021/09/10/米哈游在试图关闭g-hhw网站/?lang=EN)，我感觉资源不要提前做了 @SilveryStar

**Comment by Arondight** [comment]
@Xm798

**Comment by Xm798** [comment]
悲 没办法提前准备角色材料了

**Comment by Arondight** [comment]
> 对我来说影响最大的大概是 gacha splash 没地方找了，其他图片资源都是游戏更新后 genshin wiki 里弄的

也不一定，内鬼网正面刚上了，说找了一架无视 DMCA 的网站搬了过去，MHY 也不一定拿这毛妹有啥办法，之前发给 IONOS 的律师函也被转手发给毛妹了，毛妹还给公开挂了起来，总之我感觉内鬼网以后还不好说，撑过去，这件事反而是强势宣传了一波

**Comment by Arondight** [comment]
看了一眼，正面刚上了，发了个公告迁移完成了，还改了网站的版权说明……

![1](https://user-images.githubusercontent.com/13673702/132972671-ef9377fc-b598-4fa7-b002-2c27dbf4e2c6.png)

![2](https://user-images.githubusercontent.com/13673702/132972673-868b6851-6f77-47a5-9ed1-5c9797da0854.png)

**Comment by Arondight** [comment]
@Xm798 老大哥可以帮忙做个埃洛伊的图吗

![A92C9F10-F185-42F5-912F-3ACA18CB1F70](https://user-images.githubusercontent.com/13673702/134626771-838e6bf0-4631-4ee1-ab2a-416054b13ffa.png)

**Comment by Xm798** [comment]
> @Xm798 老大哥可以帮忙做个埃洛伊的图吗
> 
> ![A92C9F10-F185-42F5-912F-3ACA18CB1F70](https://user-images.githubusercontent.com/13673702/134626771-838e6bf0-4631-4ee1-ab2a-416054b13ffa.png)

这个我记得做过了 但是不知道为什么不显示
URI:resources/Version2/character/10000050.png

**Comment by Arondight** [comment]
呃，我过会看一下

**Comment by SilveryStar** [comment]
原因很明显，avatar id我是乱猜的，埃洛伊的实际 id 是 10000062 XD

**Comment by Xm798** [comment]
> 原因很明显，avatar id我是乱猜的，埃洛伊的实际 id 是 10000062 XD
> 我 oss 那边已经修复了，另外埃洛伊返回的 rarity 值是 105 (?)，如果你那边有用到的话注意一下

啊这……

**Comment by Arondight** [comment]
乱猜的没问题吧，不是只要和 json 对应上就行么，一切的入口都是从 json 开始的

**Comment by SilveryStar** [comment]
> 乱猜的没问题吧，不是只要和 json 对应上就行么，一切的入口都是从 json 开始的

char 这个页面的右下角图片是从 json 里的 id 去获取 oss 里的 character 图，两边 id 不一样当然 error 了

**Comment by Arondight** [comment]
@SilveryStar 在我这里是一致的，json 里是 50，图片的名字也是 50，没有用 oss，全部使用的本地资源，所以我不太理解为啥会 error

**Comment by SilveryStar** [comment]
> @SilveryStar 在我这里是一致的，json 里是 50，图片的名字也是 50，没有用 oss，全部使用的本地资源，所以我不太理解为啥会 error

米游社 api 返回的 id 是 62，你的图片都是 50 自然找不到，而且你这个脚本……
https://github.com/Arondight/Adachi-BOT/blob/69ad75d22af48e812d1ccf7b56a883d9a5320a7d/resources/update.sh#L58-L63

**Comment by Arondight** [comment]
@SilveryStar 我的神，还是你强啊，我刚想明白还有米游社的 API，我还以为只要本地资源自洽就可以呢

**Comment by Arondight** [comment]
@SilveryStar 改改项目的关键字尽量别被搜到吧，这游戏签到和辅助脚本的 repo 封了一些，估计前一阵法务部大战内鬼网之后又开始搞事情了

**Comment by Arondight** [comment]
@SilveryStar 我问了下被封的仓都引用了[条款](https://docs.github.com/en/github/site-policy/github-acceptable-use-policies)中的第九条，邮件的大意是仓库模拟了用户的真实行为，这个就可以随便扩张解释了

**Comment by SilveryStar** [comment]
> @SilveryStar 改改项目的关键字尽量别被搜到吧，这游戏签到和辅助脚本的 repo 封了一些，估计前一阵法务部大战内鬼网之后又开始搞事情了

我先把 topics 和 description 下了吧（

**Comment by Arondight** [comment]
我也改了，README 也把机器人的关键字去了，希望别中奖。迁移项目本身没啥，不过我把 issue 当 wiki 用，commit 里也写了大量的 issue 号，真的换地方还是有点烦。目前我知道的有个用户较多的签到项目，还有两个自动钓鱼都被封了，我也不知道这到底是 github 自己的行为（就跟前一阵封杀 action 一样），还是其他用户举报的

**Comment by Arondight** [comment]
是 github 自查的，所有的 DMCA 都会在 [github/dmca](https://github.com/github/dmca) 挂起来，我看了下没有米忽悠的

**Comment by Xm798** [comment]
最近更新的一批资源貌似都丢到了resources目录下，那么resources_custom还有存在的必要性嘛？

**Comment by Arondight** [comment]
> 那么resources_custom还有存在的必要性嘛

如果原作者做了一个相同的，会把我们做的覆盖掉

**Comment by Xm798** [comment]
> > 那么resources_custom还有存在的必要性嘛
> 
> 如果原作者做了一个相同的，会把我们做的覆盖掉，等到那天不再需要原作者的资源文件，这个目录就没必要了，不过我感觉这不太可能了……

意思是，如果原作者做了一个相同的资源文件，如果我们不放在 resources_custom 里，就会把我们的覆盖掉对吧？最近更新的一批资源文件是不是还是用的  SilveryStar 的版本？

**Comment by Arondight** [comment]
> 意思是，如果原作者做了一个相同的资源文件，如果我们不放在 resources_custom 里，就会把我们的覆盖掉对吧

就是这个样子。最近更新的资源如果没有在 custom 放着，那就已经换成原作者的版本了

**Comment by Xm798** [comment]
脚本好像有点问题
