### ISSUE TITLE
无法获取可用 Cookie ！

### ISSUE THREAD

**Issue by RheinFury** [Arondight/Adachi-BOT#571]
### 问题描述

已经在Ubuntu上按要求部署，QQ登录也正常，绑定uid后提示：无法获取可用 Cookie ！

**Comment by Mark9804** [comment]
麻烦检查一下 cookies.yml 格式
```yaml
cookies:
  - _MHYUUID=…
  - _MHYUUID=…
  - _MHYUUID=…
  
```

**Comment by Arondight** [comment]
你要先设置 cookie 才能查，至于怎么拿到 cookie 可以看 faq

**Comment by RheinFury** [comment]
已解决，感谢
还有个问题，提示绘图失败是不是缺少某些环境配置

**Comment by Arondight** [comment]
> 提示绘图失败是不是缺少某些环境配置

是的，建议参考文档中 chrome 的部分
