### ISSUE TITLE
能不能支持一下国际版原神

### ISSUE THREAD

**Issue by 12123ads** [Arondight/Adachi-BOT#573]
### 问题描述

国际版类似于米游社的网站：https://www.hoyolab.com/

### 代码状态：当前提交

0a2bdf63659adf6b35ced954c113794b4e1f3dcd (HEAD -> master, origin/master, origin/dev, origin/HEAD) 更新示例

**Comment by Arondight** [comment]
支持不了，没玩过国际版，不清楚里面的门门道道。另外这个 bot 初衷就是我自己客制化的，写着写着客制化的东西多了才申请了解除 fork 关系成为了独立的项目，国际版我也不玩，支持了我也用不到

**Comment by 12123ads** [comment]
好吧
