### ISSUE TITLE
米游社新闻推送

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#574]
### 问题描述

参考 #565 

- [x] 定时拉取新闻
- [x] 定时根据时间推送新闻
- [x] ~清理过期新闻~
- [ ] 添加权限开关

**Comment by Arondight** [comment]
关于清理，每次都直接覆盖就不需要清理了

**Comment by Arondight** [comment]
这些不归属于插件的权限应当在 config.js 中统一设置

**Comment by gaqwe767** [comment]
建议加个指定群号开启，我100多个群，差点就全发了，还好我设定了自动拦截，让机器人不允许发那么快信息。

**Comment by Arondight** [comment]
> 建议加个指定群号开启，我100多个群，差点就全发了，还好我设定了自动拦截，让机器人不允许发那么快信息。

没做这个功能，用这个凑合一下全关了吧

https://github.com/Arondight/Adachi-BOT/blob/2f55a2cf85d1a2940eb576dbdf523ac85597a542/config_defaults/setting.yml#L61-L63

**Comment by Arondight** [comment]
我应该把这个功能默认关掉

**Comment by Mark9804** [comment]
现在如果拉取某张图片失败之后就直接抛出错误退出了，这条消息也不再推送，感觉如果重试一下会好一些
```
[2022-01-11T14:17:43.002] [ERROR] [iPad:***] - 错误：拉取 https://upload-bbs.mihoyo.com/upload/2022/01/09/75276539/4689f3800b618e86e10fe1d7edcbbcfd_6908472772394506006.jpg 失败，因为“FetchError: Invalid response body while trying to fetch https://upload-bbs.mihoyo.com/upload/2022/01/09/75276539/4689f3800b618e86e10fe1d7edcbbcfd_6908472772394506006.jpg: aborted”。
```

**Comment by Arondight** [comment]
> 重试一下会好一些

五分钟拉一次，等下一轮吧

**Comment by Arondight** [comment]
我感觉这里没必要做 cache，直接把米游社的链接发出去岂不是更好，省的占用自己流量

**Comment by Mark9804** [comment]
我倒是觉得有图比没图好点，或者至少发个文字

**Comment by Arondight** [comment]
> 我倒是觉得有图比没图好点，或者至少发个文字

我的意思是不要往自己这儿拉图再发出去了，直接把图片的 url 给腾讯就不管了

**Comment by Mark9804** [comment]
这个好

**Comment by Arondight** [comment]
> 直接把图片的 url 给腾讯就不管了

想得太美了，构造的 cq 腾讯直接不支持，必须得传图，现在拉不到图就不发图了，也不会重新尝试
