### ISSUE TITLE
达拉然巨坑

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#577]
- [x] #497 拖不了太久了
- [x] #425 **不做了**
- [x] https://github.com/Arondight/Adachi-BOT/issues/274#issuecomment-985495795 **不做了**
- [x] #236 **不做了**
- [x] https://github.com/Arondight/Adachi-BOT/commit/396de2c839c54dd547ac8b0e1a909bddda002c81#commitcomment-63686323 文档中的图片示例使用 github issue 托管
- [ ] #466 这个我还不知道怎么做
- [x] #576 这个我还不知道怎么做
- [x] #412 ~目前还没看~这个交给 @Mark9804 做吧

**Comment by Mark9804** [comment]
#576 好像出于某种奇怪的原因自己修自己了
![image](https://user-images.githubusercontent.com/9006264/149265442-93eb2786-1669-4932-8941-afb206706f57.png)

**Comment by Arondight** [comment]
> #576 好像出于某种奇怪的原因自己修自己了

这个肯定是不稳定的，本质的时序问题没有解决，目前我还不知道该怎么解决

**Comment by Arondight** [comment]
我感觉今年有可能真的都坑了，年前忙的日报都能写作文了，能做多少算多少吧

**Comment by Mark9804** [comment]
我又来加需求了，老大哥有空能在 `src/plugins/gacha/data.js` 里面加一个返回定轨值（当前定轨的武器名字，当前的定轨值）吗，我自己没加明白

**Comment by Arondight** [comment]
例如我抽了两个保底都没吃定规，定规还是 0 ？ 如果我抽了四个 up 结果当前定规一次，那就是 1 ？

**Comment by Mark9804** [comment]
> 例如我抽了两个保底都没吃定规，定规还是 0 ？ 如果我抽了四个 up 结果当前定规一次，那就是 1 ？

显示完成 n 连抽之后准备写进数据库里的定轨结果，例如：

- 定轨息灾，喜提两把绿枪，返回类似于
```json 
"path": {
        "定轨的武器名称": "息灾",
        "当前的命定值": 2
      }
```
- 如果我抽了四个 up 结果当前定规一次
假设定轨的是息灾，最后一次抽出的是四风
```json 
"path": {
        "定轨的武器名称": "息灾",
        "当前的命定值": 1
      }
```
假设定轨的是息灾，最后一次抽出的是息灾
```json 
"path": {
        "定轨的武器名称": "息灾",
        "当前的命定值": 0
      }
```

**Comment by Arondight** [comment]
好~

**Comment by Mark9804** [comment]
图片示例我建好 wiki page 了

https://github.com/Arondight/Adachi-BOT/wiki/1.-%E5%9B%BE%E7%89%87%E7%A4%BA%E4%BE%8B

**Comment by Arondight** [comment]
感谢

**Comment by Arondight** [comment]
剩下的坑短时间内估计不会填了，最近一段时间我只做一些 bug 修复，最近在学技术准备提桶跑路，这些本来也就不太影响使用，等到未来某天跑路后再搞吧

**Comment by Arondight** [comment]
#604 这个还是可以慢慢搞一搞的

**Comment by Arondight** [comment]
这个先关闭了，#466 单独跟踪
