### ISSUE TITLE
不能正确复读结构化消息

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#580]
### 问题描述

猜测和风控导致消息被切片发送有关，如果这不是 `oicq.js` 的预期外行为的话就报给 oicq 吧
<img src="https://user-images.githubusercontent.com/9006264/149662722-704b5df3-83ee-4579-bcdf-bd731db24027.jpeg" alt="43343780-C477-4A1B-94E7-F0E3674782A1_1_102_o" width="200">

### 复现流程

让 bot 复读一条 json 消息

### 后台日志

```Text
0|bot      | [2022-01-16T22:41:46.629] [INFO] [iPad:****] - recv from: [Group: 心甘晴愿(****), Member: 酒吧炒饭真君(****)] {"app":"com.tencent.structmsg","config":{"autosize":true,"ctime":1642340506,"forward":true,"token":"996c3f0c801b818d49294079de16b9ac","type":"normal"},"desc":"新闻","extra":{"app_type":1,"appid":100951776,"uin":****},"meta":{"news":{"action":"","android_pkg_name":"","app_type":1,"appid":100951776,"ctime":1642340506,"desc":"UP主：****-房间号：********","jumpUrl":"https://b23.tv/******","preview":"https://external-30160.picsz.qpic.cn/df95b37254290a90458f8e2fadb740c1/jpg1","source_icon":"","source_url":"","tag":"哔哩哔哩","title":"原！","uin":****}},"prompt":"[分享]原！","ver":"0.0.0.1","view":"news"}
0|bot      | [2022-01-16T22:41:49.038] [WARN] [iPad:****] - 群消息可能被风控，将尝试使用分片发送
0|bot      | [2022-01-16T22:41:49.501] [INFO] [iPad:****] - succeed to send: [Group(****)] [json消息]原！"&#44;"ver":"0.0.0.1"&#44;"view":"news"},id=]
```

### 代码状态：当前提交

411fb0066c9163eea367f2d5ed9900b90b379e0a (HEAD -> dev, origin/master, origin/dev, origin/HEAD, master) 网页 card-8 配置和代码分离

### 运行环境：操作系统

macOS

**Comment by Mark9804** [comment]
被通过这种方式复读出来的消息在电脑端看不到
![image](https://user-images.githubusercontent.com/9006264/149662927-a52fcc99-68d3-4a63-a056-2abf05df4f1b.png)

**Comment by Arondight** [comment]
我晚上调一下，oicq 应该也做不了什么

**Comment by Mark9804** [comment]
在1.0版本可以正确复读分享消息，2.0基本上都会被风控，我不太确定原因是 oicq 新的消息结构还是我们的转换函数，又或者是 tx 风控策略升级了，我去 oicq 群里问一下有没有类似情况

**Comment by Arondight** [comment]
我感觉不用问了，肯定是转换函数的问题，官方提供的转换问题不少，我接着在本地修吧

**Comment by Arondight** [comment]
我大致根据你发的 log 看了下转换函数，肯定是正则无法处理括号嵌套引起的 `"prompt":"[分享]原！"` ，按照原来的写法，`分享` 后的那个闭括号会认为是 cq 码的结束，然后 json 的 cq 会被分成两部分，一个 json 的 cq 和一个 text 的cq

**Comment by Arondight** [comment]
摸鱼搞完了，现在应该可以了
