### ISSUE TITLE
米游社接口报错：Please Login

### ISSUE THREAD

**Issue by KiriyamaAya** [Arondight/Adachi-BOT#582]
### 问题描述

rt 按照  #120  #123 步骤都走了一遍 cookie按照步骤添加了 yml语言也没问题 但是一直报错 是什么问题

### 复现流程

    - UM_distinctid=.....; CNZZDAT...=....; _ga=....; _gid=.....; _MHYUUID=.....; _gat=1; ltoken=....; ltuid=....; cookie_token=.....; account_id=....  目前按照教程 复制下来的cookie 是这样的 

### 后台日志

```Text
0|bot  | [2022-01-18T02:22:53.603] [DEBUG] [iPad:....] - Cookie： MHY.... -> UM_distinctid=...; ...=...9; _ga=.....16...; _gid=....; _MHYUUID=.......; _gat=1; ltoken=....; ltuid=30..; cookie_token=....; account_id=....
0|bot  | [2022-01-18T02:22:54.225] [INFO] [iPad:....] - succeed to send: [Private(...)] 发现以下无效 Cookie ，请及时在 /home/aya/Adachi-BOT/config/cookies.yml 中删除。
0|bot  | account_id=1
0|bot  | account_id=2
0|bot  | account_id=3
0|bot  | account_id=4
0|bot  | account_id=5
0|bot  | account_id=6
0|bot  | account_id=7
0|bot  | [2022-01-18T02:22:54.350] [INFO] [iPad:....] - succeed to send: [Group(....)] @你小保底必歪 米游社接口报错: Please login
```

### 代码状态：当前提交

411fb0066c9163eea367f2d5ed9900b90b379e0a (HEAD -> master, origin/master, origin/ dev, origin/HEAD) 网页 card-8 配置和代码分离

### 代码状态：是否修改

Clean

### 运行环境： Node.js 版本

v16.13.0

### 运行环境： npm 版本

8.1.0

### 运行环境：操作系统

Linux

**Comment by Mark9804** [comment]
有个地方我没有太理解，你给出的 cookie 例子当中应该只有一个 cookie，但是为什么 bot 报了七个无效 cookie，我能理解成是按这种格式添加了总共七个不同的 cookie，并且每个 coookie 都含有 account_id 和 cookie_token 字段吗？

**Comment by Arondight** [comment]
拿 cookie 开无痕，要不然退掉账户 cookie 立马过期

**Comment by KiriyamaAya** [comment]
> 有个地方我没有太理解，你给出的 cookie 例子当中应该只有一个 cookie，但是为什么 bot 报了七个无效 cookie，我能理解成是按这种格式添加了总共七个不同的 cookie，并且每个 coookie 都含有 account_id 和 cookie_token 字段吗？

我添加的7个都无效了

**Comment by KiriyamaAya** [comment]
> 拿 cookie 开无痕，要不然退掉账户 cookie 立马过期

好的 我试试看
