### ISSUE TITLE
抽卡图片太大了

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#588]
### 问题描述

1. 彩蛋池子忽略数量永远十连
2. 检测一下抽卡的数量来决定缩放

**Comment by Mark9804** [comment]
这个谁来做都可以，缩减一下 `gachaDataToShow` 的数量就行，可以把三星数据给扔掉

https://github.com/Arondight/Adachi-BOT/blob/f83a3aa7b44b7ca2f256ec4a1d0e0b9d15aadd39/src/views/component/gacha/app.js#L74-L77

另外我感觉保底算法好像有点问题，以普遍理性而论 180 抽应该至少有两个金的

<img src="https://user-images.githubusercontent.com/9006264/150369636-772f676f-b392-4383-8c0c-f73e6f1a2331.png" alt="image" width="200">

**Comment by Arondight** [comment]
> 另外我感觉保底算法好像有点问题，以普遍理性而论 180 抽应该至少有两个金的

我明天看下，也可能是保底有问题，也可能是抽了俩神鹤但是不知道哪里的原因显示了一个

**Comment by Mark9804** [comment]
> 也可能是抽了俩神鹤但是不知道哪里的原因显示了一个

应该是这个问题，刚刚算了一下这张图里面加起来才 179 抽，明天再说了

**Comment by Arondight** [comment]
另外为什么抽卡都有个单位是180，这个是二游的一个约定俗成的单位么……如果是的话我也搞个180

**Comment by Mark9804** [comment]
天井每个游戏都不一样，60井，80井，100井，120井，150井，180井，240井，300井，~~fgo无穷大井~~

大约就是一个韭菜也愿意被割，股东也开心的临界点

**Comment by Mark9804** [comment]
蛋池数量限制应该由后端来做，前端这边目前打算

_Originally posted by @Mark9804 in https://github.com/Arondight/Adachi-BOT/issues/587#issuecomment-1017648213_

>  - 如果是十连，不处理；
>  - 如果去掉三星之后的物品少于 10 个，则不做处理，维持现状显示；
>  - 如果去掉三星之后的物品多于 10 个，就去掉三星物品，然后显示一个三星物品已被折叠的提示

**Comment by Arondight** [comment]
我本地写了还没提，我的想法是🥚十连，其他的不变也不要扔三星，大于是个缩放比1，否则1.5

**Comment by Mark9804** [comment]
三星我觉得还是像上面说的那样满足条件就折起来吧，我把史莱姆枪的图换成誓约胜利之剑一上午都没人发现，真没人看

**Comment by Arondight** [comment]
我感觉没必要吧，主要是生不了多点，我改了个缩放比，图片从快10m 一下子掉到2m，去三星顶天也就是2m 变1.5m，三星还没了

**Comment by Arondight** [comment]
话说我也没搞明白为啥缩放影响这么大，这个1.5 恐怕会变成原来的 2.25 哦，感觉体积增加的太夸张了，还有几个缩放2 的我也没细看

**Comment by Mark9804** [comment]
> 这个1.5 恐怕会变成原来的 2.25 哦

长和宽都乘以 1.5，那么面积不就是原来的 2.25 倍咩

> 去三星顶天也就是2m 变1.5m，三星还没了

主要是看定轨方便一些，看定轨的人比看三星的多，我做了个 patch

<details>
<summary>patch</summary>

![image](https://user-images.githubusercontent.com/9006264/150470542-184754ac-8bff-47e9-8601-d3a72c922a84.png)

</details>
