### ISSUE TITLE
定轨有点问题

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#597]
理论上应该是2/2，json 给刷没了，再观察观察
![image](https://user-images.githubusercontent.com/9006264/150509127-d5d2ed60-9761-4b97-b03a-4a8b9cffa24c.jpeg)

**Comment by Mark9804** [comment]
进行一个锅的甩
![image](https://user-images.githubusercontent.com/9006264/150510003-67cd8ca5-6bf2-40ef-a5fe-7200e14b6f48.png)

**Comment by Mark9804** [comment]
我懂了，是不是定轨变量没有更新，一直读取的是最初 initialize 的变量？之前都是十连十连的抽卡，所以这个问题不容易触发，现在 180 连之后就很容易出现这个问题

**Comment by Arondight** [comment]
我明天看一下，还没回去
