### ISSUE TITLE
对接原作者新API求助

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#6]
在此项目里，原作者写了一个插件[overview](https://github.com/Arondight/Adachi-BOT/blob/master/src/plugins/overview/index.js)用于展示角色的官方数据，在新版本中，原作者[废弃了](https://github.com/SilveryStar/Adachi-BOT/issues/21)此项目该插件使用的API，导致了依然使用旧API 的此项目无法查询新出角色的信息。原作者改用一个新的插件[info](https://github.com/SilveryStar/Adachi-BOT/blob/master/src/plugins/genshin/achieves/info.ts)，在可以展示角色官方数据的基础上，也加入了武器信息的展示。
此项目中对应的插件使用JS+Vue?，原作者的新项目则使用了TS+Vue3，因为我没有前端开发经验，所以在升级该项目插件的API 上遇到了困难。新的API 返回到Json 已经截然不同，而且Vue 的view 也有了较大改动，目前我的进展较慢，如果有熟悉的大佬欢迎帮忙修改一下。只需要能查询新出角色即可（现有功能对接到原作者的Version2 的API 上）。

**Comment by 490720818** [comment]
已pr
