### ISSUE TITLE
信息功能文本展示排版出问题

### ISSUE THREAD

**Issue by HYTT0510** [Arondight/Adachi-BOT#602]
### 问题描述

武器的信息描述出现问题  为竖向排列
![4G5G{0~NR9IG@YZD`Z19BA4](https://user-images.githubusercontent.com/46914653/150678910-7e48abb5-006d-4809-9bf6-0e612044e841.gif)

### 复现流程

更新之后

### 代码状态：当前提交

c3516dd092e12867564f384f58fbe93de4f35833 (HEAD -> master, origin/master, origin/                           dev, origin/HEAD) overview: 但申鹤，她实在是太大了 #515

### 运行环境：操作系统

Linux

**Comment by HYTT0510** [comment]
![6}%I~5E Q`(~7@J9OT}Y0 A](https://user-images.githubusercontent.com/46914653/150678972-15f86819-d9a0-41c8-8ca7-f4f8c6ba3f5d.gif)
![1{{U%M3F{H05OK3)YFH 70G](https://user-images.githubusercontent.com/46914653/150678974-0c95e8c6-7e40-4c0c-9546-d919fd40ff14.gif)

**Comment by Mark9804** [comment]
再拉一下代码
