### ISSUE TITLE
未知原因 macOS 下的 puppeteer chromium 截图时会带一条黑线

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#603]
RT，不能稳定复现，只有 mac 上的 chromium 会出现这个行为，只有 bot 截图并发送图片时会出现这个行为。我感觉是 chromium 版本太高了
<details>

![image](https://user-images.githubusercontent.com/9006264/150679895-0f084825-ae5c-4ba7-b6b3-df251d6eafa2.png)
![image](https://user-images.githubusercontent.com/9006264/150679909-87b0247f-a42f-44ed-b462-580580d22a5d.png)
</details>

# puppeteer 版本
`"puppeteer": "13.1.1",`

# Chromium 版本
`Version 98.0.4758.0 (Developer Build) (x86_64)`

**Comment by Arondight** [comment]
data/record 下面的图就这样的么，会不会是 oicq 或者腾讯的问题

**Comment by Mark9804** [comment]
啊这，当时没开这选项，现在复现不出来了，看缘分吧

**Comment by Mark9804** [comment]
现在完全无法复现，关了

**Comment by Mark9804** [comment]
猜到原因了，这个页面的缩放是 1.5，我自己的 fork 是2，但是 puppeteer 不能很好的处理 0.5 个像素，所以默认值需要改成能被 0.2 整除的数，比如 1.6 应该就可以避免这个问题

**Comment by Mark9804** [comment]
搞不好还真是 mac 背全锅
<img width="400" alt="image" src="https://user-images.githubusercontent.com/9006264/153984265-c3c70791-fea8-4e87-822f-ed6910c90f65.png">

<img height="400" alt="image" src="https://user-images.githubusercontent.com/9006264/153984300-ae834357-b606-4214-90e3-148c30641f03.jpeg">

**Comment by Mark9804** [comment]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/9006264/159146020-6d7aa53a-0a8c-481b-9917-15e14f22d3cf.png">
确实是截图的时候出了点问题，data/record 下面的图就是这样的
