### ISSUE TITLE
请求更新overview以适配新的命之座信息

### ISSUE THREAD

**Issue by Xm798** [Arondight/Adachi-BOT#608]
@Mark9804 从 GHW 扒了所有角色的命之座信息更新了 json 文件，增加了三五命，且描述文本全部更新为了官方文本，commit 到了 dev 分支，需要更新一下 overview 。
https://github.com/Arondight/Adachi-BOT/commit/5e7d2f963df72e83bcd084a087a9cec4991bccb7

https://github.com/Arondight/Adachi-BOT/discussions/607#discussioncomment-2030985

**Comment by Xm798** [comment]
题外话，之前的 json 难道是原作者手敲的……？这工作量，离谱了

**Comment by Mark9804** [comment]
下午有事，晚上抽完甘雨弄

**Comment by Mark9804** [comment]
> 之前的 json 难道是原作者手敲的……？

应该是有操作的吧……？我那天试着提了一个 json 上去，真复制粘贴到吐了，不过我当时就一个文件，写爬虫不比人肉爬快，批量做的话肯定爬了，最不济也淘宝花 50 找个程序员

**Comment by Xm798** [comment]
> > 之前的 json 难道是原作者手敲的……？
> 
> 应该是有操作的吧……？我那天试着提了一个 json 上去，真复制粘贴到吐了，不过我当时就一个文件，写爬虫不比人肉爬快，批量做的话肯定爬了，最不济也淘宝花 50 找个程序员

因为之前的overview有文本长度限制，所以原作者的命之座信息都是修改过的……所以至少他把所有角色的命之座都阅读理解并改写了一番，太强了

**Comment by Xm798** [comment]
> > 之前的 json 难道是原作者手敲的……？
> 
> 应该是有操作的吧……？我那天试着提了一个 json 上去，真复制粘贴到吐了，不过我当时就一个文件，写爬虫不比人肉爬快，批量做的话肯定爬了，最不济也淘宝花 50 找个程序员

临时学了一下`lxml`，用py写了个简陋的爬虫，可惜不懂js，不然就能用在#497里了……
