### ISSUE TITLE
新皮肤头像出错

### ISSUE THREAD

**Issue by HYTT0510** [Arondight/Adachi-BOT#624]
### 问题描述

发放了闲替衣装之后部分角色的头像图片出错
![(1~B~0G%((464%Z0GY@TSTY](https://user-images.githubusercontent.com/46914653/151690831-f4fecfe7-1e30-4de6-a214-71533b85ccb0.png)

### 复现流程

查询部分展示了闲替衣装的角色了

### 代码状态：当前提交

 bccb72dbdc5edd9b3af7ed2b07065cb73483dabc (HEAD -> master, origin/master, origin/dev, origin/HEAD) 微调 gacha 显示效果

### 代码状态：是否修改

Clean

### 运行环境： Node.js 版本

v16.13.0

### 运行环境： npm 版本

8.1.0

### 运行环境：操作系统

Linux

**Comment by Mark9804** [comment]
阿哲，确实我忘了这个问题了
