### ISSUE TITLE
为什么提示消息发送失败，因为“未找到陌生人 2011431241 所在的群组”。

### ISSUE THREAD

**Issue by Ya-Ma-Da** [Arondight/Adachi-BOT#626]

**Comment by Arondight** [comment]
大概是因为这个丘丘号不是机器人的好友也不是群友，所以发不了消息

**Comment by Ya-Ma-Da** [comment]
> 所有者

我小号和大号是在1个群，也是好友，小号注册也差不多有1年了

**Comment by Arondight** [comment]
奇怪，试一试机器人能和这个丘丘发起私聊么，另外登陆协议是什么

**Comment by Ya-Ma-Da** [comment]
协议我也不清楚，我按照大佬你们写的那个步骤部署的，这两个qq号我自己登录后私聊是可以的

**Comment by Arondight** [comment]
我还真没遇到这种情况……按照逻辑时候在

1. 好友中没发现目标丘丘
2. 所有的群中没发现目标丘丘

都满足的时候才会在发消息的时候有这个报错

**Comment by Ya-Ma-Da** [comment]
我是在初始化的时候出现的这个问题，我看我的小号也一直是离线状态

**Comment by Arondight** [comment]
额，你应该没完成设备认证吧

**Comment by Arondight** [comment]
你如果不会设备认证的话就不要填密码，起来后扫码登录就好了

**Comment by Ya-Ma-Da** [comment]
okk我试试

**Comment by Ya-Ma-Da** [comment]
感谢大佬！大佬神子必不歪，圣遗物强化必定全部双暴！

**Comment by Arondight** [comment]
🐮🍺 祝你十连满命
