### ISSUE TITLE
是否会加入角色天赋查询功能？

### ISSUE THREAD

**Issue by yuan488** [Arondight/Adachi-BOT#630]
### 问题描述

是否会加入角色天赋查询功能？

**Comment by Mark9804** [comment]
“天赋”的范围具体是AEQ技能的描述，还是包括被动技能在内的全部内容描述？

具体到几级AEQ分别对应多少倍率是不太可能加进来的，头都给写秃了，纯文字描述可以考虑一下，但是就算真的决定加上了，短时间内应该也不会去做

**Comment by Arondight** [comment]
没有这个计划
