### ISSUE TITLE
”圣遗物”抽取和传参代码的改进

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#633]
刚刚问了一下 Silvery

> `propertyName` 不单是用来描述主词条的，如果你看过 `artifact.yml` 的话，就知道这里面的顺序是对应词条的权重的
>
> _Originally posted by @SilveryStar in https://github.com/SilveryStar/Adachi-BOT/issues/174#issuecomment-1029970973_

但是主词条和对应词条并不是完全重合的，我还是感觉这样写会造成混淆，不过这不是前端应该关心的问题，

作为前端来说我的想法是主词条的具体信息和强化数值不应该由前端来计算，因为主词条未来一定是会改动的（会新增至少一个草元素伤害加成），到时候后端要改，前端还是要改，变成重复劳动了

然后两个数值错误要改一下

- 元素充能效率初始值是 7.8% ，不是8.7%
- 暴击伤害初始是 9.3%，不是 9.4%

----

现在的
```json
{
  "mainStat": 11,
  "base": { "name": "魔女的心之火", "artifactID": 3, "slot": 3, "level": 0 },
  "data": [
    { "name": "防御力", "data": "19" },
    { "name": "元素充能效率", "data": "4.5%" },
    { "name": "元素精通", "data": "16" }
  ]
}
```

设想的
```json
{
  "mainStat": "风元素伤害加成",
  "mainValue": "7.0%",
  "base": { "name": "魔女的心之火", "artifactID": 3, "slot": 3, "level": 0 },
  "data": [
    { "name": "防御力", "data": "19" },
    { "name": "元素充能效率", "data": "4.5%" },
    { "name": "元素精通", "data": "16" }
  ]
}
```

**Comment by Arondight** [comment]
我大概知道你是啥意思了，放到我头上了

**Comment by Arondight** [comment]
我的天，给忘了……

**Comment by Arondight** [comment]
备忘：计算并传递 `mainValue` 和 `mainStatText`

**Comment by Arondight** [comment]
> 我还以为老大哥在准备提桶就没提这事

没有那么快，这件事需要几个月的时间，不是那种完全呆不下去的情况，只是想找个更好的

**Comment by Arondight** [comment]
有的值我是瞎填的，不过好像也用不到

**Comment by Mark9804** [comment]
终于可以把我 stash 了两周的代码从垃圾桶里翻出来了

**Comment by Arondight** [comment]
> 终于可以把我 stash 了两周的代码从垃圾桶里翻出来了

我拉了，根本就没记得这个事，要不然早搞完了
