### ISSUE TITLE
爬到“测试角色”的时候使用输入参数代替名称

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#636]
<img width="854" alt="image" src="https://user-images.githubusercontent.com/9006264/152649018-d75d8678-d7ca-47d3-9eac-3f95445d4234.png">

**Comment by Arondight** [comment]
还有两个问题

1. 内鬼网概率性飙英文
2. 测试武器不知道为啥没爬下来

**Comment by Arondight** [comment]
浏览器哪个终端里能不能用 xpath 选择元素，我当前没有啥有效的调试手段，第二个问题昨天看了个半小时也没看出来

**Comment by Arondight** [comment]
搜了搜学会了，开发者工具真好使，我以前都是把 HTML 保存下来在 vim 里面数标签的

**Comment by Mark9804** [comment]
感觉内鬼网数据库不是很稳定，数据库炸了的时候可能就查不到某个特定的页面了，我记得之前那个维护的毛子说数据库结构太复杂了，只求能跑

**Comment by Arondight** [comment]
> 感觉内鬼网数据库不是很稳定，数据库炸了的时候可能就查不到某个特定的页面了，我记得之前那个维护的毛子说数据库结构太复杂了，只求能跑

应该对我们没有啥影响，我们以后也不会大规模跑爬虫的，一个多月跑两三次，也不在乎稳定性了，今天不成明天爬
