### ISSUE TITLE
gacha 的三星折叠逻辑再优化一下

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#637]
#515 太长了，不想每次都翻到最底下

现在的逻辑是 “如果四星和五星的卡片数量加起来 ≥ 9 ，那么折叠三星卡片”

那么在这种情况下，就不能完成折叠导致图片过长

<details>

![image](https://user-images.githubusercontent.com/9006264/152774447-96cd59c9-1637-47ed-a2f1-243d76c60d5d.png)
</details>

我想改成
- 如果五星+四星卡片的总数 ≤ 8 ，那么用三星卡片进行填充，直到卡片总张数为 9 ，最后一张卡片显示剩余的被折叠的三星；
- 如果四星和五星的卡片数量加起来 ≥ 9 ，那么折叠三星卡片

效果应该是这样的

<img width="650" alt="image" src="https://user-images.githubusercontent.com/9006264/152775713-82d77a87-89f8-431e-b1fb-6527242c2658.png">

**Comment by Arondight** [comment]
我觉得即使不够十个格子，三星折叠也没问题

**Comment by Mark9804** [comment]
不够十个格子的话稍微有点空，我看看写个 `reduce`
