### ISSUE TITLE
绿勾玉素材缺失

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#639]
![image](https://user-images.githubusercontent.com/9006264/152835877-f62b6696-04cc-4329-b0ae-97f4712f5e46.jpeg)

**Comment by Mark9804** [comment]
资源名字 `明惠` 打成 `明慧` 了可还行，之前 json 也全都是错的，所以两个错误的 bug 刚好合成了正确的结果……

**Comment by Arondight** [comment]
再感叹一下原作者的产能
