### ISSUE TITLE
信息功能可以加上固有天赋介绍吗

### ISSUE THREAD

**Issue by tendapc** [Arondight/Adachi-BOT#643]
### 问题描述

固有天赋方便了解角色

**Comment by Arondight** [comment]
@Mark9804 这个主要看前端的意见，牵扯到页面布局

**Comment by Mark9804** [comment]
这样？
<img width="800" alt="image" src="https://user-images.githubusercontent.com/9006264/153149396-91b7a803-22e9-4c5a-a7e6-a35c962652c5.png">

**Comment by Arondight** [comment]
我不知道，但是天赋描述文本真的很长很长，页面至少长一倍，特别是钟离这种大小技能写作文的，我保留意见，感觉现在挺好的

**Comment by Arondight** [comment]
哦，固有天赋应该是那个派遣-25%时间的吧，我以为是aeq呢

**Comment by Mark9804** [comment]
AEQ 确实大大的反向优化，固有天赋倒是有用，我觉得可以加，效果图就差不多上面那样

```json
{
  "talentTitle": "/html/body/div[2]/div[2]/div[1]/div[4]/div/div/div/div[3]/table[7]/tbody/tr[7]/td[2]/a",
  "talentDesc": "/html/body/div[2]/div[2]/div[1]/div[4]/div/div/div/div[3]/table[7]/tbody/tr[8]/td/div"
}
```

**Comment by Arondight** [comment]
那就加入有生之年计划（大概不会很久）

**Comment by Mark9804** [comment]
固有天赋的逻辑我提交上 dev 了，老大哥过个目

另外我感觉这个工具明显是面向开发者的，exception 是不是可以写得稍微详细一点，笼统的报错反而让用户迷惑了

**Comment by Arondight** [comment]
不用，因为除了咱俩没人用，我遇到问题了就手动加个打印了，甚至参数都懒得做

**Comment by Arondight** [comment]
备忘：爬虫和 config.js 的注释需要加新增的字段

**Comment by Mark9804** [comment]
我焯，好像我抓错地方了

**Comment by Arondight** [comment]
例如你写的 

```
handle = (await page.$x("//table[contains(@class, 'item_main_table')]"))[true === hasFourSkill ? 5 : 4];
const passiveTitle = await page.evaluate((e) => e.textContent, (await handle.$x("./tbody/tr[5]/td[2]"))[0]);
```

直接在控制台里面

```
var handle = $x("//table[contains(@class, 'item_main_table')]")[4];
$x("./tbody/tr[5]/td[2]")[0]
```

然后就选中你指定的 xpath 了（如果没写错 xpath 的话）

**Comment by Mark9804** [comment]
不行，太难看了，想回滚了
<img width="400" alt="image" src="https://user-images.githubusercontent.com/9006264/153401951-9a79120d-b96f-4e56-9854-4a25de7fe97b.png">

**Comment by Mark9804** [comment]
太难看了，默认关闭了，想要这个功能的话把下面这行 `false` 改成小写的 `true`

https://github.com/Arondight/Adachi-BOT/blob/43376e8f61b6a69fb285038361b27e3d5d252a74/src/views/component/overview/characterInfoBox.js#L107

**Comment by Arondight** [comment]
做成武器技能的样子会不会好点

![89839F27-35EA-471A-B7C3-4CD3CE9BE7A4](https://user-images.githubusercontent.com/13673702/153523853-2367a5e4-c177-4e30-8dc6-0f28731d6a6d.jpeg)

**Comment by Mark9804** [comment]
从结构上来说应该做成武器特效那样 `标题+内容` 的形式，但是从逻辑上来说固有天赋是对人物出身和性格的延伸，应该要和人物描述放在一起，我再想想
