### ISSUE TITLE
米游社 API 返回 avatar 为空

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#646]
### 问题描述

老大哥麻烦把这种情况判断成数据不可信
```json
{
  "retcode": 0,
  "message": "OK",
  "uid": 173552407,
  "nickname": "w在下",
  "level": 56,
  "avatars": [],
  …
}
```

### 复现流程

--

### 代码状态：当前提交

--

### 运行环境：操作系统

Linux

**Comment by Mark9804** [comment]
嗯，昨天晚上没拦住，前端给渲染出了一个白屏，我也看到了这段代码确实在我 fork 里面，有点迷惑

https://gist.github.com/Mark9804/2cbd59790861b500cdd62772fd6bb4a2

**Comment by Arondight** [comment]
这个确实有点诡异，我在两处应该处理的地方都在没拿到数据的情况下抛了异常

https://github.com/Arondight/Adachi-BOT/blob/43376e8f61b6a69fb285038361b27e3d5d252a74/src/utils/detail.js#L250-L252

https://github.com/Arondight/Adachi-BOT/blob/43376e8f61b6a69fb285038361b27e3d5d252a74/src/utils/detail.js#L297-L299

但是不知道为啥还会出现没数据的情况，正常来说 `characterDetail` 的那个异常就可以处理所有没数据的情况了，我再查一下吧

**Comment by Arondight** [comment]
我觉得是什么别的问题导致了这个现象，我伪造了数据试了下，错误处理是没有问题的，这种数据到不了后端，后续出现的话 reopen 一下然后看看能不能有更多有用的信息吧
