### ISSUE TITLE
有时候会在字体没渲染完成的情况下截图发送

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#649]
网络请求策略优化的太激进了，截图时浏览器有可能还在解析字体文件，瓶颈变成了纯硬件性能

<img src="https://user-images.githubusercontent.com/9006264/153708442-741c5bff-6411-4dcf-a4f2-3df9bb52ee71.png" width="200"/>

**Comment by Mark9804** [comment]
没有合适的 API ，摆了

**Comment by Arondight** [comment]
借个路，好像声望等级显示不太正常

![图片](https://user-images.githubusercontent.com/13673702/153714156-4144163a-75d4-4729-b622-0c83ea512033.png)

**Comment by Mark9804** [comment]
有 json 咩

**Comment by Mark9804** [comment]
很正常啊，米游社返回的结果就是这样的，我觉得这个号可能是个脚本号

**Comment by Arondight** [comment]
额，是那个 Lv 后面有的跟着数字，有的跟着一大块空白，不知道为啥蒙德和其他的不太一样，号应该没问题，以前卡 bug 的无元素主角号，只有俩角色

**Comment by Mark9804** [comment]
> 额，是那个 Lv 后面有的跟着数字，有的跟着一大块空白，不知道为啥蒙德和其他的不太一样

这个真的是 feature ，不知道老大哥有没有注意到数字的末尾是对齐的

<img width="600" alt="image" src="https://user-images.githubusercontent.com/9006264/153714900-a03057d5-8ac9-4471-b204-b4f2a2976440.png">

然后米忽悠用的这个字体不是等宽字体，1 要比 6，7，8，9 这样的字体瘦很多，效果就变成上面这样了，这就是为什么蒙德显示的正常（蒙德有 1 ）但是其他地区有空格的原因

针对这个问题我用了 `text-justify` 来缓解，因为 `text-justify` 目前只是一个实验性功能，等到 chromium 更新到 100？左右的时候下面这行声明就会生效

https://github.com/Arondight/Adachi-BOT/blob/43376e8f61b6a69fb285038361b27e3d5d252a74/src/views/component/card-8/card-8.css#L341-L342

效果是这样的
<img width="246" alt="image" src="https://user-images.githubusercontent.com/9006264/153714882-43eb75db-462e-4a78-8ef6-0f08020a2f8c.png">

**Comment by Arondight** [comment]
原来是这样
