### ISSUE TITLE
达拉然旧址

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#651]
- [x] #604 ， 不做了
- [x] ~webp 图片格式，目前武器还是 png~
- [x] 翻新 #317 ，资源从哪里获取如何加工
- [x] #625

**Comment by Mark9804** [comment]
武器图片倒也不一定要 webp ，其实我本来也不想多此一举，但是爬完人物卡池 png 一看我焯加起来总共 25M ，但是爬都爬了，就死马当活马医转成 webp 了，转完总共 5.6M ，还能接受，就往上扔了，武器池我觉得本来图就比较小，应该不会有这么夸张的提升了

**Comment by Arondight** [comment]
> 武器图片倒也不一定要 webp

那就无所谓了，我们在文档里面写明白一下怎么获取的就行

**Comment by Mark9804** [comment]
图像资源文件那个我来翻新吧，武器那个我刚看了一下发现原作者也是自己做的图，和内鬼网上的不完全一样，我想也统一成内鬼网上的，然后看这大小估计还是得 webp。不过既然有国内镜像就好一些了

**Comment by Arondight** [comment]
辛苦老大哥了

**Comment by Arondight** [comment]
老大哥有空翻新一下 3. 吧，我感觉我写不好，没空就算了，直接关掉这个 issue 即可

**Comment by Mark9804** [comment]
3 等我确定好 `米游社` 需要什么就开始填

**Comment by Mark9804** [comment]
我给忘了，这个睡醒起来写一下吧

**Comment by Mark9804** [comment]
好了
