### ISSUE TITLE
每日素材的武器确实可以加上武器名

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#655]
之前好像是 @Xm798 提出来的，原帖找不到了，刚刚大战八重池的时候想到了做法

**Comment by Arondight** [comment]
加不了吧，没空间呀

**Comment by Mark9804** [comment]
没有空间就创造空间

<img width="221" alt="image" src="https://user-images.githubusercontent.com/9006264/154201934-71b15958-8c30-413c-9415-7094207288ca.png">

nm，打字的时候朋友给我抽了个大大保底果盘，蚌埠住了

**Comment by Mark9804** [comment]
备个忘，果盘和证誓的武器描述没加

**Comment by Arondight** [comment]
俩绿箭不亏

**Comment by Arondight** [comment]
缺了将军的那三个大宝贝

**Comment by Mark9804** [comment]
将军那三个大宝贝现在好像还没人用吧？而且这个应该不属于日替本的内容（还没打）

**Comment by Arondight** [comment]
🦊要大宝贝的

**Comment by Mark9804** [comment]
我好像理解了，是 `信息八重` 应该显示将军的大宝贝而不是 `???.png` 吗

**Comment by Arondight** [comment]
嗯

**Comment by Mark9804** [comment]
顺便优化一下结构和性能
<img width="800" alt="image" src="https://user-images.githubusercontent.com/9006264/154239997-c98b3483-72bc-4b76-ad77-9e72f97b9e8d.png">

**Comment by Mark9804** [comment]
> 俩绿箭不亏

其实是一把绿剑一把痛苦枪，make 刻晴 great again

**Comment by Xm798** [comment]
芜湖~

**Comment by Arondight** [comment]
> make 刻晴 great again

璃月雷神表示赞同

![7AB27888-A592-4197-A2AA-377CD141981C](https://user-images.githubusercontent.com/13673702/154323423-a509389d-ad99-4dbf-9afa-0c6da045a846.jpeg)
![C60FF6C6-66FE-4EF5-BE4B-08DDFEC2151C](https://user-images.githubusercontent.com/13673702/154323432-6d396028-0816-4936-ba5b-d325217ddba1.png)

**Comment by Arondight** [comment]
从目前凌人的情况来看，绿箭是彻底不亏了，比专武强一点，专武叠满层跟绿箭打的有来有回
