### ISSUE TITLE
征求的建议+bug

### ISSUE THREAD

**Issue by HYTT0510** [Arondight/Adachi-BOT#658]
### 问题描述

**建议**
1. **我的角色**页面，可以将武器模块放在圣遗物之上，好看一些
2. **绑定** 米哈游通行证，总是有人绑定uid，能否在提示里强调一下
3. 是否可以在聊天页面实现动态配置cookie
4. 求签，抽取圣遗物，抽卡是否可以加上次数限制，求签最好是一日一次
5. 如果检测到配置了的cookie查自己的账户，使用自己的cookie进行查询

**bug**
 1. 圣遗物会出现错误的属性，比如说小生命的头，小公鸡的杯子
![1OJV`R}X`{{{)K}99JM9{MC](https://user-images.githubusercontent.com/46914653/154790765-6dd3f80a-4faf-44bd-8ff3-863fa988a817.png)
![P}L7T9P(I_Y_Z}4S)7$0`OY](https://user-images.githubusercontent.com/46914653/154790814-44c2d2b1-2cd3-438b-b04c-1ba62aed8335.png)

### 复现流程

征求的建议+bug

### 代码状态：当前提交

 3e2457f1a6e2f7063d8af00a1f2f2da033cf6276 (HEAD -> master, origin/master, origin/dev, origin/HEAD) character.css: letter-spacing 小数点多移了一位

### 运行环境：操作系统

Linux

**Comment by Mark9804** [comment]
1. 我觉得这样头重脚轻
<details>
<summary>效果</summary>

![image](https://user-images.githubusercontent.com/9006264/154792801-882fa927-5b83-4d4c-a9d9-8879602d3978.png)

</details>

2. 暂时可以通过修改以下提示的方式实现，你也可以添加截图，参考第二个链接
  https://github.com/Arondight/Adachi-BOT/blob/3e2457f1a6e2f7063d8af00a1f2f2da033cf6276/src/utils/id.js#L88
  https://github.com/Mark9804/Adachi-BOT-fork/blob/c0471c7b5166c36cf4d42bc0f0178db58d07d613/src/utils/id.js#L87-L89
3. <span>5</span>. 很长时间之内不会做支持，请查看 #361
4. 这个之前讨论过，讨论的结果是不加，人的命运要靠自己改变，然后圣遗物和抽卡问题我觉得本来游戏里就有限制，机器人没必要再整这个了吧……

**Comment by Mark9804** [comment]
圣遗物确实不太正常，好像是权重矩阵出了问题

<img src="https://user-images.githubusercontent.com/9006264/154792910-3f94a041-0d3d-40b1-a163-ac8fa54ef777.png" width="200" />

**Comment by HYTT0510** [comment]
1. 主要是武器在上面直观体现，圣遗物不会仔细去看，我询问了差不多十个人意见，绝大部分都是认为武器在上面好看一些
2. 好的
3. 是管理员进行动态配置，普通用户不允许
4. 主要是会出现用户刷屏的情况，如果直接禁止也不太好，就想着能不能限制一下每天的数量
5. 还有第五条

**Comment by Mark9804** [comment]
武器那个我刚刚问了一下雀氏如此，改掉了

圣遗物和其他要等一等后端老大哥，另外刷屏我们现在有发送之后撤回和限制使用频率两种方案，一定要限制数量吗

**Comment by HYTT0510** [comment]
因为吧我觉得   多少秒后撤回还是会影响当前群内的聊天质量，使用频率是可以防止短时间内多次使用，但是如果人多的情况下，也是会出现刷屏，做了限制数量既可以让群友都有的玩，不用直接关闭功能，又不会刷屏，不过我只是提建议，大佬们可以商量一下看看，主要体现在     **求签，抽取圣遗物，抽卡**  三个功能

**Comment by Arondight** [comment]
最终都做不了

2. 分不出来 uid 和 mysid
3. 技术上可以实现，但是我不想做，我竭力避免 bot 修改自身的配置文件，包括无效 cookie 也是避免 bot 自行删除的
4. 这个我也不想做，既然有了某功能的次数限制，那么其他功能没理由不支持，那么未来的新功能也没理由不支持，这会把事情变麻烦，尤其是这个项目的 fork 会头大。可以自己改配置文件把功能禁止掉，或者把这个群的对应权限给禁止掉，或者自己做个二次开发
5. 这个我做不到，因为当前的数据库结构导致无法判断这个行为，过去我想做来着，一看数据库结构要改就不了了之了，或许以后我会做支持，近期有事应该不会做这个了

只有 bug 改的了

**Comment by HYTT0510** [comment]
好的十分感谢！

**Comment by Mark9804** [comment]
2 我觉得可能不需要想这么复杂，直接从用户角度解决问题
<img src="https://user-images.githubusercontent.com/9006264/154794243-43671c1a-e8ac-4fe6-a17d-b083b68d8033.jpeg" width="400" />

<img src="https://user-images.githubusercontent.com/9006264/154794237-617e4216-ea2b-4067-99f9-e500c536ca31.png" width="400" />

**Comment by Arondight** [comment]
这个倒是可以，如果可以的话我完善一点提示信息吧（我也不知道写没写提示，代码写了太久了都忘了）

**Comment by HYTT0510** [comment]
那我感觉2这个点可以直接更新进去了，因为绑定错的人确实挺多的

**Comment by Mark9804** [comment]
非著名游戏制作人羽中曾经说过“我感觉我在做一款弱智保姆软件”，我们现在的提示还不够明显

**Comment by Arondight** [comment]
> 那我感觉2这个点可以直接更新进去了，因为绑定错的人确实挺多的

提示的作用是很有限的，主要是真的分不清绑定的是不是米游社通行证

**Comment by Mark9804** [comment]
> 提示的作用是很有限的，主要是真的分不清绑定的是不是米游社通行证

我加上图片之后，绑定错的人会明显变少，虽然还是偶尔有一两个人绑错

**Comment by Arondight** [comment]
啊这……图片我真的不想加了，我感觉这也太离谱了

**Comment by Arondight** [comment]
我想起来经常收到bot的反馈信息：`<带个话>`

**Comment by Mark9804** [comment]
我开始怀疑这个世界了，是不是真的要加个示例

<details>
<summary>不至于吧</summary>

![image](https://user-images.githubusercontent.com/9006264/156155252-aefdfd73-de8f-489b-a640-6a196703a452.jpeg)
</details>

**Comment by Arondight** [comment]
> 5\. 如果检测到配置了的cookie查自己的账户，使用自己的cookie进行查询

#730
