### ISSUE TITLE
插件开发指引还停留在 oicq 1.x

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#665]
刚刚看了一下，消息事件部分好像是被分散到了 [events.ts](https://github.com/takayama-lily/oicq/blob/main/lib/events.ts) 还有 [message.ts](https://github.com/takayama-lily/oicq/blob/main/lib/message/message.ts) 两个文件里面，我不够了解对应事件 API 就不自己瞎几把改了

**Comment by Arondight** [comment]
没理解你说的是哪一部分……

**Comment by Mark9804** [comment]
https://github.com/Arondight/Adachi-BOT/blob/50a8fb9acfef23489020ef492027ed3f989cb1f2/docs/%E5%BC%80%E5%8F%91%E6%8C%87%E5%BC%95.md?plain=1#L122
