### ISSUE TITLE
数据库 API 能力扩展

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#677]
### 问题描述

当前

1. 不合逻辑
2. 增删改查局限性太大

需要做向前兼容

**Comment by Arondight** [comment]
看了一下代码里的数据库操作，比较有问题的就是大颗粒度，例如为了改某个值把整个数据库直接重写了一遍，不过当前操作内存，应该不会造成太多性能下降吧，这部分改完了还要测，实在是懒了，没有肉眼可见的性能问题就放着了。

**Comment by Arondight** [comment]
> 看了一下代码里的数据库操作，比较有问题的就是大颗粒度，例如为了改某个值把整个数据库直接重写了一遍，不过当前操作内存，应该不会造成太多性能下降吧，这部分改完了还要测，实在是懒了，没有肉眼可见的性能问题就放着了。

另外新的 API 不止解决了颗粒度问题，整体风格也统一了，就是 `includes` 还没做风格统一，过一阵或许考虑一下给加上

**Comment by Arondight** [comment]
@Mark9804 现在你可以和之前一样写 `db.includes` 了

```
db.includes(name, "user", { id: 100 });
db.includes(name, "data", "p1", { p2: "text" });
```

**Comment by Mark9804** [comment]
感谢老大哥
