### ISSUE TITLE
[bug] 图片发不出来了（

### ISSUE THREAD

**Issue by citydirector** [Arondight/Adachi-BOT#680]
### 问题描述

今天的某项更新似乎会导致图片发不出来...

### 复现流程

米游社、信息 等会发送图片的命令

### 代码状态：当前提交

de3ab1dd41026ea3d36b9897e5197657db0b1c6b (HEAD -> master, origin/master, origin/dev, origin/HEAD) Update node modules

### 代码状态：是否修改

Clean

### 运行环境：操作系统

Linux

**Comment by Mark9804** [comment]
应该不会吧？
![image](https://user-images.githubusercontent.com/9006264/156200502-802d16f0-e900-492a-9de8-dc5f0b7b668d.png)

**Comment by Mark9804** [comment]
你在拉取更新并且重启之后有没有过更新系统 chromium 的操作？如果有的话，尝试 `npm run restart` ；如果没有的话，尝试回滚掉 75c3277 这个 commit，如果你不知道怎么操作，就把 `single-process` 那个参数给删掉

https://github.com/Arondight/Adachi-BOT/blob/75c327713f6aeb41ed4dae9a1c283daf2311797b/src/utils/render.js#L33

**Comment by citydirector** [comment]
不知道捏，我两台机器都是前天更新过，然后刚刚更新完图片就发不出来了（

**Comment by citydirector** [comment]
> 你在拉取更新并且重启之后有没有过更新系统 chromium 的操作？如果有的话，尝试 `npm run restart` ；如果没有的话，尝试回滚掉 [75c3277](https://github.com/Arondight/Adachi-BOT/commit/75c327713f6aeb41ed4dae9a1c283daf2311797b) 这个 commit，如果你不知道怎么操作，就把 `single-process` 那个参数给删掉
> 
> https://github.com/Arondight/Adachi-BOT/blob/75c327713f6aeb41ed4dae9a1c283daf2311797b/src/utils/render.js#L33

确实好了（）

**Comment by citydirector** [comment]
> 

root@VM-20-7-ubuntu:~# google-chrome --version
Google Chrome 98.0.4758.80 

抱歉，几天没上gayhub

**Comment by Mark9804** [comment]
这个问题从 #668 开始就存在了，我感觉是 chromium 95+ (>=96) 有 bug ，只能再观察看看了
