### ISSUE TITLE
无限推送米游社新闻   一轮接着一轮

### ISSUE THREAD

**Issue by HYTT0510** [Arondight/Adachi-BOT#687]
### 问题描述

打开米游社新闻推送之后   在推送一轮之后   会连续推送

### 复现流程

打开米游社推送之后

### 运行环境

```Text
> Adachi-BOT@1.5.2 tool-status
> npx node ./tools/status.js

操作系统：linux（CentOS Linux）
内核版本：4.18.0-305.10.2.el8_4.x86_64
内核架构：x64
处理器：  3.22%（Intel Xeon® Gold 6148 @ 2.4Ghz）
启动时间：3 days
内存使用：26.84%（1.05 GB / 3.92 GB）
数据占用：17.2 MB
Node.js： 16.13.0
npm：     8.1.0
浏览器：  Chromium 94.0.4606.81 Fedora Project
```

### 当前提交

```Text
commit a09ab1bf8ccfd6ca416d34e240402e109ebfef5f (HEAD -> master, origin/master, origin/HEAD)
Author: Qin Fandong <shell_way@foxmail.com>
Date:   Thu Mar 3 23:41:55 2022 +0800

    两点小小的工作
```

### 代码状态

```Text
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by Arondight** [comment]
如果很久没打开了，然后打开，确实会推送很多条……每种 10 条，一共三种，共计 30 条，不过应该不会有重复的，逻辑可能需要优化一下，例如关闭后再打开跳过第一轮推送。

如果你确认有的新闻推送了多次回复一下

**Comment by Arondight** [comment]
1. 关闭后再打开，跳过所有的新闻推送一轮
2. 每次推送一天内的新闻

当前逻辑上再加以上限制之一即可，明天搞一下

**Comment by HYTT0510** [comment]
是重复的推送  武器池子发两遍  然后被我停掉了

**Comment by Arondight** [comment]
> 是重复的推送 武器池子发两遍 然后被我停掉了

这有点奇怪，可能是是数据库读写出问题了，我白天测试一下

**Comment by Arondight** [comment]
我试了一下无法复现呢……推送是正常的，没有出现重复推送的现象

**Comment by Mark9804** [comment]
这个我熟，#583

**Comment by Arondight** [comment]
> 这个我熟，#583

看评论这个问题好像已经修好了

**Comment by Arondight** [comment]
哦，我看了一下代码是没完全修好的，现在的逻辑还是有可能部分推送多次，只要五分钟内没拉完 30 张图片

https://github.com/Arondight/Adachi-BOT/blob/43d16be8ec63e75b93ee6cb35a17b2a959dce677/src/jobs/news.js#L70-L76

https://github.com/Arondight/Adachi-BOT/blob/43d16be8ec63e75b93ee6cb35a17b2a959dce677/src/jobs/news.js#L92-L93

修的话需要把上面两段逻辑拆成两个循环，先计算时间戳，把对应字段写到数据库，然后再拉图片和发送，这样超过五分钟也不会发送下一轮了，不过目前问题也不大，加一下策略不要同时发送这么多就好，几个新闻总不会超时，晚上有时间了再改
