### ISSUE TITLE
2.6 版本（中长期工作）

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#689]
- [ ] 角色神里绫人     **缺一个角色半身图**
- [x] 武器波乱月白经津　**缺一个武器描述**
- [x] 装备辰砂往生录
- [x] 装备来歆余响

以及对应的资源文件

---

- [x] `../config_defaults/artifacts.yml`
- [x] `../config_defaults/names.yml`
- [x] `../config_defaults/pool_eggs.yml`
- [x] `../resources/Version2/wish/config/character.json` 使用原作者的版本不做维护
- [x] `../resources/Version2/wish/config/weapon.json` 使用原作者的版本不做维护
- [x] `../resources/update.sh`

**Comment by Arondight** [comment]
@Mark9804 剩下的需要老大哥在开新版本之前更新一下，资源文件都推上去然后把 json 生成一下推上去，有一些图片我从银色星星哪里拉过来了，做图之前记得翻一番 resouces 下面，可能已经有了

**Comment by Mark9804** [comment]
这个可以等绫人仰卧起坐结束了再做，我的绫人啊，多半是在寄的路上了

**Comment by Mark9804** [comment]
绫人怎么没有 `overview` 的图啊，是silvery还没做吗

**Comment by Arondight** [comment]
> 绫人怎么没有 `overview` 的图啊，是silvery还没做吗

再等等吧，肯定会做的，上线前搞就行

**Comment by Mark9804** [comment]
没，主要就觉得他已经做好了绫人的 json 但是没做图有点怪，摸了

**Comment by MiniGrayGay** [comment]
啊，你们Bot都是版本上之前更新的吗，我是版本上了之后才更的（摸鱼.gif

**Comment by Mark9804** [comment]
我急了.jpg

周天之前我和 silvery 至少有一个要动手

**Comment by Arondight** [comment]
0人的cv被我搞丢了

**Comment by Mark9804** [comment]
> 0人的cv被我搞丢了

到时候我补回来

备忘：检查武器效果，跟进武器描述

<img width="556" alt="image" src="https://user-images.githubusercontent.com/9006264/160266076-0d50e00c-cd10-4fec-bad5-9435901b8f35.png">
