### ISSUE TITLE
chromium内存占用过多

### ISSUE THREAD

**Issue by 12123ads** [Arondight/Adachi-BOT#694]
### 问题描述

![S20306-16264589](https://user-images.githubusercontent.com/69107029/156915271-908819e0-ed7b-4a94-bb46-38cb9f8406d2.png)
chromeium占用了大约23g

### 复现流程

正常运行之后就这样了

### 后台日志

```Text
1054888813] - recv from: [Group: 原神国际服交流群(三)(551088896), Member: The DOGE feat.USAO EX(911197626)] {image:3366027245124B883E378DA4A9B33886}
0|bot      | [2022-03-06T16:25:22.180] [DEBUG] [iPad:1054888813] - 同步：将数据库 aby 缓存写入到磁盘。
0|bot      | [2022-03-06T16:25:23.711] [DEBUG] [iPad:1054888813] - 同步：将数据库 artifact 缓存写入到磁盘。
0|bot      | [2022-03-06T16:25:23.989] [DEBUG] [iPad:1054888813] - 同步：将数据库 authority 缓存写入到磁盘。
0|bot      | [2022-03-06T16:25:23.989] [DEBUG] [iPad:1054888813] - 同步：将数据库 character 缓存写入到磁盘。
0|bot      | [2022-03-06T16:25:23.989] [DEBUG] [iPad:1054888813] - 同步：将数据库 cookies 缓存写入到磁盘。
0|bot      | [2022-03-06T16:25:23.990] [DEBUG] [iPad:1054888813] - 同步：将数据库 cookies_invalid 缓存写入到磁盘。
0|bot      | [2022-03-06T16:25:23.993] [DEBUG] [iPad:1054888813] - 同步：将数据库 gacha 缓存写入到磁盘。
0|bot      | [2022-03-06T16:25:24.590] [DEBUG] [iPad:1054888813] - 同步：将数据库 info 缓存写入到磁盘。
0|bot      | [2022-03-06T16:25:24.848] [DEBUG] [iPad:1054888813] - 同步：将数据库 map 缓存写入到磁盘。
0|bot      | [2022-03-06T16:25:2
```

### 运行环境

```Text
:~/Adachi-BOT# npm run tool-status
npm ERR! Missing script: "tool-status"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-06T08_35_44_920Z-debug-0.log
```

### 当前提交

```Text
~/Adachi-BOT# git log -1
commit a9d57d411b0dca25555f1300a4cb8c26045710b5 (HEAD -> master, origin/master, origin/dev, origin/HEAD)
Author: Qin Fandong <shell_way@foxmail.com>
Date:   Wed Feb 23 14:14:05 2022 +0800

    改两处很奇怪的逻辑
root@instance-20220223-1536:~/Adachi-BOT#
```

### 代码状态

```Text
:~/Adachi-BOT# git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
root@instance-20220223-1536:~/Adachi-BOT#
```

**Comment by Arondight** [comment]
怎么会拉起来这么多 pm2 服务（或 bot）

**Comment by Arondight** [comment]
1. 你把 bot 停掉看看内存释放了么
2. 更新一下代码看看

**Comment by 12123ads** [comment]
更新好了，我再看看吧

**Comment by Mark9804** [comment]
我感觉这像是一个 chromium 的内存溢出问题，麻烦给机器人发 `系统信息` 或者再跑一遍 `npm run tool-status` 看一下系统，之前可能是内存给撑爆了没运行出来

**Comment by Arondight** [comment]
> 之前可能是内存给撑爆了没运行出来

他是代码比较老

**Comment by 12123ads** [comment]
对了，这个系统信息也有bug
![S20306-17385055](https://user-images.githubusercontent.com/69107029/156917614-1b1b6d8d-2932-429c-8b4f-278644759aeb.png)
会显示CPU 0ghz

**Comment by Arondight** [comment]
> 对了，这个系统信息也有bug
> ![S20306-17385055](https://user-images.githubusercontent.com/69107029/156917614-1b1b6d8d-2932-429c-8b4f-278644759aeb.png)
> 会显示CPU 0ghz

这个问题提给 https://github.com/sebhildebrandt/systeminformation

**Comment by Mark9804** [comment]
> 怎么会拉起来这么多 pm2 服务（或 bot）

我试着重启了一下机器，确实有这么多 pm2

<details>
<summary>htop</summary>

<img width="976" alt="image" src="https://user-images.githubusercontent.com/9006264/156917821-fe568c8f-7438-4604-b82b-c5b1a8d45cfe.png">
</details>

然后 chromium 在前台空跑的情况又出现了，我再看看有没有解决方案

**Comment by Mark9804** [comment]
Neoverse N1 显示 0gHz的问题可能是 arm 平台没适配好，这是什么服务器

**Comment by 12123ads** [comment]
oracle的arm

**Comment by Mark9804** [comment]
> 会显示CPU 0ghz

这个问题我去跟上游库提一下，麻烦在你的服务器环境的 `Adachi-BOT目录` 里面跑一下下面这行代码，然后把结果发一下
```bash
echo 'import si from "systeminformation"; si.cpu().then((c) => console.log(c));' > test.js; node test.js; rm test.js
```
结果应该是形如这样子的
<img width="783" alt="image" src="https://user-images.githubusercontent.com/9006264/156926788-16761d75-1f03-46ce-8cb3-5bcdae07848f.png">

**Comment by Arondight** [comment]
> ```shell
> echo 'import si from "systeminformation"; si.cpu().then((c) => console.log(c));' > test.js; node test.js; rm test.js
> ```

```
echo 'const si = require("systeminformation"); si.cpu().then((c) => console.log(c));' | node --
```

**Comment by Arondight** [comment]
> ```
> echo 'const si = require("systeminformation"); si.cpu().then((c) => console.log(c));' | node --
> ```

```
node -e 'const si = require("systeminformation"); si.cpu().then((c) => console.log(c));'
```

**Comment by Arondight** [comment]
我觉得还需要贴一下 `/proc/cpuinfo` ， `lscpu` 恐怕不太够

**Comment by Mark9804** [comment]
居然能举一反三，太哈人了

```bash
cat /proc/cpuinfo; node -e 'const si = require("systeminformation"); si.cpu().then((c) => console.log(c));'
```

**Comment by Arondight** [comment]
写这代码的也是个人才，沃日

https://github.com/sebhildebrandt/systeminformation/blob/6cd3e654cd23a9f1efa87c294324eb588ea1b0ac/lib/cpu.js#L655-L662

**Comment by Arondight** [comment]
> 写这代码的也是个人才，沃日
> 
> https://github.com/sebhildebrandt/systeminformation/blob/6cd3e654cd23a9f1efa87c294324eb588ea1b0ac/lib/cpu.js#L655-L662

我想起来我几年前用了一个 perl 的网络模块获取本机 IP 地址，但是有的机器能正常工作，有的不能，我很疑惑，然后看了看代码，这个模块跑了一下 `ifconfig` 命令，然后用正则处理了一下拿第几行，新一点的 `ifconfig` 输出改了一点，这个模块就不能正常工作了， systeminformation 这个模块真是异曲同工

**Comment by Mark9804** [comment]
那可能是这个模组没有在 Oracle 云上面测试过吧，刚刚看了一眼价格一个月 47 刀，我直接家境贫寒

新的测试代码更新如下

```bash
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq; cat /proc/cpuinfo; node -e 'const si = require("systeminformation"); si.cpu().then((c) => console.log(c));'
```

**Comment by Arondight** [comment]
> 新的测试代码更新如下

啊这……你没理解他做了什么，他跑了一下 `lscpu` 命令，然后用正则抓出来 `module name` 那一行，之后用 `@` 分割了文本，第二节文本就是 `speed` 字段

**Comment by Mark9804** [comment]
我理解了，之前是猜可能 Oracle 云的表现不一定一样，所以想试试看 `/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq` 有没有东西，然后加上一段复现用的 nodejs 代码，不过确实，应该也看看 `lscpu` 长什么样

**Comment by 12123ads** [comment]
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       ARM
Model:                           1
Model name:                      Neoverse-N1
Stepping:                        r3p1
BogoMIPS:                        50.00
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via                                  prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics                                  fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp s                                 sbs
processor       : 0
BogoMIPS        : 50.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1

processor       : 1
BogoMIPS        : 50.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1

processor       : 2
BogoMIPS        : 50.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1

processor       : 3
BogoMIPS        : 50.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1

{
  manufacturer: 'Neoverse-N1',
  brand: '',
  vendor: 'ARM',
  family: '',
  model: '1',
  stepping: 'r3p1',
  revision: '',
  voltage: '',
  speed: 0,
  speedMin: NaN,
  speedMax: NaN,
  governor: '',
  cores: 4,
  physicalCores: 4,
  processors: 1,
  socket: '',
  flags: 'fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs',
  virtualization: false,
  cache: { l1d: '', l1i: '', l2: '', l3: '' }
}
root@instance-20220223-1536:~/Adachi-BOT#
===
这是那个代码执行结果

**Comment by Arondight** [comment]
> 这是那个代码执行结果

这样那个模块也做不了什么，我感觉就不要提 bug 了，就当是一个特性吧

**Comment by Mark9804** [comment]
> 这样那个模块也做不了什么

确实，等我有钱了再去提个PR

**Comment by 12123ads** [comment]
这个。。。。甲骨文有免费额度啊


---原始邮件---
发件人: &quot;Mark ***@***.***&gt;
发送时间: 2022年3月8日(周二) 中午12:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Arondight/Adachi-BOT] chromium内存占用过多 (Issue #694)




  
这样那个模块也做不了什么
  
确实，等我有钱了再去提个PR
 
&mdash;

**Comment by Mark9804** [comment]
我们可以尝试手动 gc ，但是应该没有什么太大的效果，这个锅主要还是应该 chromium 来背，我们顶多做个检测到内存泄漏之后干掉 chromium 再拉起来一个，但是说实话好像你是第一个遇到内存泄漏问题的……

[Automatically detect memory leaks with Puppeteer - Article by Christoph Guttandin - Media Codings](https://media-codings.com/articles/automatically-detect-memory-leaks-with-puppeteer)

**Comment by Arondight** [comment]
> 我们顶多做个检测到内存泄漏之后干掉 chromium 再拉起来一个

他这个想法不错，但是我们无法验证效果，甚至无法验证这段代码的正确性，所以没法加

**Comment by Arondight** [comment]
我看到这个想法💡有实践了，不过不是生产代码，只是测试用例

https://github.com/chrisguttandin/standardized-audio-context/blob/master/test/memory/module.js

**Comment by Arondight** [comment]
鸽，我觉得我们做不了什么

**Comment by Arondight** [comment]
这个内存检测我不准备加了，有问题再说吧
