### ISSUE TITLE
关于一些功能的建议

### ISSUE THREAD

**Issue by BTMuli** [Arondight/Adachi-BOT#697]
### 问题描述

还没仔细看程序跑的流程，先放一些默认配置下的建议在这边：

+ 信息查询目默认只有角色跟武器的，希望boss 圣遗物 秘境 材料之类的也能查到

+ 米游社目前只有绑定跟改绑的，解绑的也可以搞一下

+ 目前是bot上线的时候会通知，下线的时候也可以搞个通知

+ 采用command.yml后，在群里设置权限相关，消息是私聊的管理，可以改成在群里通知

姑且先想到这些

### 当前提交

```Text
commit 9bc605da400f61858b857fce272e1a1bc92251de (HEAD -> master, origin/master, origin/HEAD)
Author: Qin Fandong <shell_way@foxmail.com>
Date:   Sun Mar 6 21:48:17 2022 +0800

    修复了没法根据名字刷没别名的副本的问题
```

**Comment by Mark9804** [comment]
首先我们项目的后端最近会比较忙，没有太多时间来添加新功能，我只是个弱小的前端罢了

- 我确实在想要不要加上圣遗物套装的信息（二件套效果，四件套效果），但是 boss、秘境、材料完全没有这个想法，一是工作量太大，二是用的人实在太少了

- 24得后端决定
- 3 是有下线通知的啊，可能是个 bug
<img width="161" alt="image" src="https://user-images.githubusercontent.com/9006264/156962780-bfe2630d-0db1-4918-9b6e-5eb5bf76f54d.png">

**Comment by Arondight** [comment]
1. 不准备加更多东西的查询，没有这个精力去维护，两个主要维护人员主要靠个人时间去维护项目
2. 这个可以搞一下，只留一个绑定，不带 id 则删除，改绑没啥必要了
3. 有下线通知
4. 这个可以做

下线通知我这里做的不太好，希望能帮忙改改，但是现在肯定是可以用的

https://github.com/Arondight/Adachi-BOT/blob/9bc605da400f61858b857fce272e1a1bc92251de/src/bot/init.js#L78

`4.` 以前是要做的，我完全忘记了

https://github.com/Arondight/Adachi-BOT/blob/9bc605da400f61858b857fce272e1a1bc92251de/src/utils/auth.js#L15-L18

**Comment by Arondight** [comment]
另外有好的修改（特别是代码架构和健壮性）可以 pr 到 dev ，我觉得合适的话会合入，感谢

**Comment by BTMuli** [comment]
查询这个可以利用米游社wiki的数据吧，搞个爬虫？

**Comment by Arondight** [comment]
> 查询这个可以利用米游社wiki的数据吧，搞个爬虫？

目前在 tools 下面有个简单的爬虫 info.js ，角色和武器的信息是它生成的

**Comment by BTMuli** [comment]
那个通知的我刚刚试了一下，机器人下线的时候还是只通知管理账号，没有通知到群

**Comment by Arondight** [comment]
> 那个通知的我刚刚试了一下，机器人下线的时候还是只通知管理账号，没有通知到群

下线不通知群，只通知管理员

**Comment by Arondight** [comment]
你如果想通知的话自己加个广播就好了，oicq.js 中有api

**Comment by BTMuli** [comment]
那对于群的功能开关，在群内设置的话群号是否可以省略？

**Comment by Arondight** [comment]
> 那对于群的功能开关，在群内设置的话群号是否可以省略？

不能

**Comment by Arondight** [comment]
睡了一觉，把下线通知广播📢给加上了

**Comment by Mark9804** [comment]
> 睡了一觉，把下线通知广播📢给加上了

我记得之前是有一个歇逼模式的来着

**Comment by Arondight** [comment]
> 歇逼模式

那时候还是我接手项目不久纯自用的阶段，在这个项目神奇地 star 越来越多的时候我就把这个给改掉了……

**Comment by BTMuli** [comment]
晚上用的时候发现还有一些可以改进的

+ 抽签功能可以对应成鸣神大社的那个抽签&解签，然后一人一天一签，数据源我没找到，可以慢慢来

+ 查询 uid[uid] 的时候发现有的返回端口报错，就是那个次数限制的，后面我手动又添加了一个cookie，查询同一个uid，还是有这个问题，查询角色尝试更新信息的那个我在设置里是打开的，建议优化一下，可能是缓存那边的问题

+ 抽卡彩蛋池的时候发现图片有一张缺了个角色的
![9Z5@ZB%Z)41ZN}H_K@SM VF](https://user-images.githubusercontent.com/72692909/157052463-c601fe65-9285-4aff-ad98-11b12e98fd47.jpg)

log 我看看能不能找到...好吧，找不到了T_T

**Comment by Mark9804** [comment]
> 有一张缺了个角色的

不用找了，是神里绫人

**Comment by Mark9804** [comment]
> 查询 uid[uid] 的时候发现有的返回端口报错，就是那个次数限制的，后面我手动又添加了一个cookie，查询同一个uid，还是有这个问题

这可能是个 bug ，超过次数限制的 cookie 没有被禁用，等后端看看吧

> 抽签功能可以对应成鸣神大社的那个抽签&解签

这个数据源我有，但是后端更喜欢现在的（）我只是个弱小的前端

如果你喜欢的话，可以把 `config_defaults` 文件夹里面的 `prophecy.yml` 改成你想要的文本

**Comment by Arondight** [comment]
抽签是我个人的爱好，这些娱乐功能不想跟游戏扯上关系；cookie 那个我不知道为什么，这个场景去年测过的，cookie 无法使用后会立刻失效并解绑最后一个 id，所以你加新 cookie 应该会再绑定到新的 cookie 上了，你感兴趣的话可以看一下相关的逻辑和两个数据库 debug 一下，都在 cookie.js



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: BTMuli ***@***.***&gt;
发送时间: 2022年3月7日 22:28
收件人: Arondight/Adachi-BOT ***@***.***&gt;
抄送: Qin Fandong ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [Arondight/Adachi-BOT] 关于一些功能的建议 (Issue #697)





 
晚上用的时候发现还有一些可以改进的
  
 
抽签功能可以对应成鸣神大社的那个抽签&amp;解签，然后一人一天一签，数据源我没找到，可以慢慢来
 

 
查询 uid[uid] 的时候发现有的返回端口报错，就是那个次数限制的，后面我手动又添加了一个cookie，查询同一个uid，还是有这个问题，查询角色尝试更新信息的那个我在设置里是打开的，建议优化一下，可能是缓存那边的问题
 

 
抽卡彩蛋池的时候发现图片有一张缺了个角色的
 
 
 
log 我看看能不能找到...好吧，找不到了T_T

**Comment by Mark9804** [comment]
命运要靠自己改变，多抽抽挺好的

数据我自己 fork 整合起来了，只有正文，没有幸运物，本来想写一个完整大工程的，然后没时间，鸽了

https://github.com/Mark9804/Adachi-BOT-fork/blob/b593fad83a894430f29f501a551786c7c142443c/config_defaults/prophecy_narukami.yml

**Comment by Arondight** [comment]
我好懒，不想找了，最近比较心累，就算有 bug 应该问题也不大，这个我明天测试一下数据库 api ，多属性 object 匹配删除没问题那应该就是没问题的，这些场景都完备测试过了，之后数据库 api 完全重写了，我猜有问题的话多半是数据库 api 有缺陷而不是逻辑问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mark Chen ***@***.***&gt;
发送时间: 2022年3月7日 22:35
收件人: Arondight/Adachi-BOT ***@***.***&gt;
抄送: Qin Fandong ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [Arondight/Adachi-BOT] 关于一些功能的建议 (Issue #697)





  
查询 uid[uid] 的时候发现有的返回端口报错，就是那个次数限制的，后面我手动又添加了一个cookie，查询同一个uid，还是有这个问题
  
这可能是个 bug ，超过次数限制的 cookie 没有被禁用，等后端看看吧
  
抽签功能可以对应成鸣神大社的那个抽签&amp;解签
  
这个数据源我有，但是后端更喜欢现在的（）我只是个弱小的前端
 
如果你喜欢的话，可以把 config_defaults 文件夹里面的 prophecy.yml 改成你想要的文本

**Comment by Arondight** [comment]
关于那个 cookie 的问题，我开电脑写了个测试，数据库 api 没有问题，如果你再遇到的话直接开个 issue 吧，我看看未来某一天给修了，如果老大哥愿意帮忙修一下更好，关于 cookie 过期和失效的场景几乎都完备的测试过了（包括米游社 app 和 bot 共同增加次数的场景），我也有点好奇哪里出了问题

**Comment by BTMuli** [comment]
下线广播没有按照greeting.yml的来好像T_T

**Comment by Mark9804** [comment]
有截图咩

> 下线广播没有按照greeting.yml的来好像T_T

**Comment by BTMuli** [comment]
![image](https://user-images.githubusercontent.com/72692909/157473943-78472edf-eebb-43cd-905b-af05717914a9.png)

**Comment by Arondight** [comment]
> 下线广播没有按照greeting.yml的来好像T_T

不好意思，代码写错了……

**Comment by Arondight** [comment]
> 下线广播没有按照greeting.yml的来好像T_T

拉一下代码，应该可以了
