### ISSUE TITLE
复读引用消息多了个艾特

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#720]
<img src="https://user-images.githubusercontent.com/9006264/158304747-d1371974-d37f-4b00-b021-cbfcb604f9b3.jpeg" width="300" />

_Originally posted by @Mark9804 in https://github.com/Arondight/Adachi-BOT/issues/708#issuecomment-1067544178_

**Comment by Mark9804** [comment]
并且两个艾特都是无效艾特，纯字符串形式的，不是CQ形式

**Comment by Arondight** [comment]
> 并且两个艾特都是无效艾特，纯字符串形式的，不是CQ形式

我看了一下应该是我对引用消息理解出了问题

---

最原始的消息，体现不出引用的特性

```
[
  { type: 'at', qq: 992737446, text: '@陈晨' },
  { type: 'text', text: ' 哦哦' }
]
```

---

忘了我在哪里加了引用的 CQ 后转换为文本

```
[CQ:reply,id=Oyv4pgAASBUAAAAAYjBBJAE=][CQ:at,type=at,qq=992737446,text=@陈晨][CQ:at,type=at,qq=992737446,text=@陈晨] 哦哦
```
---

发送的文本

```
[CQ:reply,id=Oyv4pgAASBUAAAAAYjBBJAE=][CQ:at,type=at,qq=992737446,text=@陈晨][CQ:at,type=at,qq=992737446,text=@陈晨] 哦哦
```

---

发送的文本还原为 segment 数组

```
[
  { type: 'reply', id: 'Oyv4pgAASBUAAAAAYjBBJAE=' },
  { type: 'at', qq: 992737446, text: '@陈晨' },
  { type: 'at', qq: 992737446, text: '@陈晨' },
  { type: 'text', text: ' 哦哦' }
]
```

---

跟以前不一样了，我感觉应该只需要一个 reply 和发送的文本就够了，中间俩圈就不用了

**Comment by Arondight** [comment]
这段代码看了半天，始终无法理解当时的思路……
