### ISSUE TITLE
执行指令“npm run start”无法在后台一直执行

### ISSUE THREAD

**Issue by chongdong12** [Arondight/Adachi-BOT#721]
### 问题描述

测试时发现 “npm run start” 指令不能让机器人一直在后台运行，使用nohup npm run init & 时能后台运行，但是一关掉终端也会把进程杀死

### 复现流程

npm run init 正常
npm run start 能将机器人放进后台但没反应
nohup npm run init & 能后面运行机器人，但是关掉终端，机器人也跟着关掉

### 运行环境

```Text
操作系统：linux（Debian GNU/Linux）
内核版本：4.19.0-18-amd64
内核架构：x64
处理器：  5.98%（Intel Xeon® Gold 6148 @ 2.4Ghz）
启动时间：12 minutes
内存使用：23.69%（432 MB / 1.82 GB）
数据占用：23.7 kB
Node.js： 16.14.0
npm：     8.3.1
浏览器：  Chromium 100.0.4889.0
```

### 当前提交

```Text
commit 38ea9509febf0116d6241f2f8251995872d6d414 (HEAD -> master, origin/master, origin/dev, origin/HEAD)
Author: github-actions <github-actions@github.com>
Date:   Tue Mar 15 03:17:38 2022 +0000

    Update Node.js modules
```

### 代码状态

```Text
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        nohup.out

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by Mark9804** [comment]
一般这种情况是后台已经有一个机器人在运行了，占用了 9934 端口，导致后拉起的机器人不能正常监听

**Comment by chongdong12** [comment]
> 一般这种情况是后台已经有一个机器人在运行了，占用了 9934 端口，导致后拉起的机器人不能正常监听

目前没有 9934端口 在占用呢

**Comment by Arondight** [comment]
npm start 之后 npm run log 贴一下日志

**Comment by chongdong12** [comment]
> npm start 之后 npm run log 贴一下日志
npm run log 后 日志显示让我扫码
![QQ截图20220315165948](https://user-images.githubusercontent.com/95455587/158342282-f6e425f0-64c7-4b2f-b63a-3983cf0f5b7b.png)

**Comment by Arondight** [comment]
npm start 不需要扫码吗

**Comment by chongdong12** [comment]
> npm start 不需要扫码吗

npm start 后没有提示需要扫码，直接进pm2了
![QQ截图20220315165948](https://user-images.githubusercontent.com/95455587/158342942-60700ca6-9d6d-4c4c-b821-a29a271979d4.png)

**Comment by Arondight** [comment]
npm run init 跑一下，把账号登录上，再试试 npm start

**Comment by chongdong12** [comment]
> npm run init 跑一下，把账号登录上，再试试 npm start

npm run init 时不用扫码能正常登录
ctrl c 退出后执行npm start，查看日志还是一样需要扫码

**Comment by Arondight** [comment]
> npm run init 时不用扫码能正常登录
> ctrl c 退出后执行npm start，查看日志还是一样需要扫码

这应该是有问题，我查一下

**Comment by Arondight** [comment]
拉一下代码，然后再跑 npm start

**Comment by chongdong12** [comment]
> 拉一下代码，然后再跑 npm start

成功进入后台，qq也能收到上线提示，非常感谢！
