### ISSUE TITLE
其实我想整个时间线插件

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#727]
但是太菜了，做不出来

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/9006264/158821046-a30cdb09-868a-4629-8425-88d8f5f0b3cc.png">

**Comment by Arondight** [comment]
puppeteer 打开对应网址，page.$x 完成操作，对指定元素截图

**Comment by Mark9804** [comment]
突然悟了，它本质上就是一个 viewport 位置的问题

---

GitHub 炸了可还行

**Comment by Arondight** [comment]
> 可惜 paimon.moe 在国内不能正常访问

我不想在这个项目里添加这个功能，要维护的东西太多了，而且似乎也没有特别好的作用，时间提醒有新闻推送

**Comment by Mark9804** [comment]
那我 GitHub 恢复之后把它转到我自己 fork 下面去

**Comment by Arondight** [comment]
> 那我 GitHub 恢复之后把它转到我自己 fork 下面去

嗯，先你的 fork 里跑着吧，如果能在一个稳定的 API 上得到国服数据不需要手动维护，再 pr 过来，paimon.moe 国内访问也不太行，直接用是个问题，这种连接问题不是每天一个缓存就能解决的。

大致思路就是和新闻推送一样，一个 job 定时检查数据库时间戳生成图片，插件直接拿到图片发送
