### ISSUE TITLE
TODO: 米游社展示页面 V3

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#728]
在做 #684 的时候，感觉到了现有设计的天花板已经快要被摸到了，角色名片那边 Silvery 似乎也不更新了，做好接盘或者放弃的准备。

新版还是跟 `我的`、`信息` 一样使用竖排版，这样[下游的分支](https://github.com/ixCiel/Adachi-BOT)不用维护两个版本，我觉得主要 QQ 用户还是用手机的，横向排版并不友好，只要把关键内容放在第一屏就能看到的地方就可以了

**Comment by Mark9804** [comment]
哦对还有，被问到过很多次“为什么我的（游戏）头像明明是xxx但是图片上是yyy”的问题，我觉得初步评估一下还是改成 QQ 头像好了，印象里前端有这数据

**Comment by Arondight** [comment]
我感觉 card-8 可以改个名字，两个 vue2 版本的现在来看基本上删掉的了

另外我个人其实一直有个想法深渊如果能查详细信息能不能只显示12 层的，其他几层显示几星就够了，感觉太长了

**Comment by Arondight** [comment]
card-8 直接改名成 card 就好了，旧的 card 和 package 删掉，似乎这辈子用不上了

**Comment by Arondight** [comment]
> card-8 直接改名成 card 就好了，旧的 card 和 package 删掉，似乎这辈子用不上了

这个我好犹豫，旧版本到底要不要保留呢

**Comment by Mark9804** [comment]
> 深渊如果能查详细信息能不能只显示12 层的

要不直接 slice(-1) ？

**Comment by Arondight** [comment]
> 要不直接 slice(-1) ？

我感觉挺好的，最好 filter 过滤一下，因为实在太长了……

**Comment by Arondight** [comment]
> 这个我好犹豫，旧版本到底要不要保留呢

算了，还是跟现在一样吧，没必要折腾了，card-8 也挺好的

**Comment by Mark9804** [comment]
我也懒了，看看直接 `slice(-1)`看看能不能跑吧，我觉得应该够强壮，前端页面是一个快速迭代的东西，一个过时了到时候直接扔掉就完事了

card-8 可以改成 card ，旧版本没有存在意义了，当时也只是为了和旧版本做出区分，现在重新整合起来罢了

**Comment by Arondight** [comment]
> card-8 可以改成 card ，旧版本没有存在意义了，当时也只是为了和旧版本做出区分，现在重新整合起来罢了

那就改了吧，我一直犹豫是觉得万一哪天用得上呢，真的没有用就没必要留了

**Comment by Mark9804** [comment]
没有必要留，不可能用到了，旧版本连渊下宫都没有

**Comment by Mark9804** [comment]
> 没有必要留，不可能用到了，旧版本连渊下宫都没有

不仅没必要留，我甚至觉得 vue2 都可以删了

**Comment by Arondight** [comment]
> 我甚至觉得 vue2 都可以删了

这个留一下吧，别人会用到的

**Comment by Mark9804** [comment]
装饰参考
<img width="272" alt="image" src="https://user-images.githubusercontent.com/9006264/159037320-eafcc905-8a6b-41bc-9a84-92d494a69c46.png">

**Comment by Mark9804** [comment]
之前精炼用的是 `★` 来表示，经常会有人问为什么螭骨是五星武器 ~~本来就是~~

我觉得应该是五角星的象征意义和星级重复了，改成了精炼，但是没想到武器名称太长的时候会换行 https://github.com/Arondight/Adachi-BOT/discussions/729#discussion-3946409

我觉得如果用四角星的话就能做出区分了

**Comment by Mark9804** [comment]
<img width="277" alt="image" src="https://user-images.githubusercontent.com/9006264/159123773-916bee85-d986-4c0d-9039-91c42ea11188.png">

**Comment by Arondight** [comment]
> 我觉得初步评估一下还是改成 QQ 头像好了，印象里前端有这数据

https://github.com/Arondight/Adachi-BOT/blob/a37d7b5b60419d2dc5601c551b85568820845591/src/views/component/card/card.js#L41-L45

**Comment by Arondight** [comment]
仅能获取前八个人物改成受制于米游社角色展示限制之类的比较好，现在查出来很多角色的这句话就会有点突兀

**Comment by Mark9804** [comment]
> 仅能获取前八个人物改成受制于米游社角色展示限制之类的比较好，现在查出来很多角色的这句话就会有点突兀

数据不全时才会显示这句话

https://github.com/Arondight/Adachi-BOT/blob/a1a9fbbe6e504a9a72f6ee3551c5d1a9a96a47cb/src/views/component/card-8/app.js#L77

**Comment by Arondight** [comment]
我又来了提需求啦，武器能不能加个颜色区分

![图片](https://user-images.githubusercontent.com/13673702/159147457-02ac4d67-4f32-4485-9bbf-2612e6680378.png)

**Comment by Arondight** [comment]
另外似乎图有点糊，我看了看本地大小 1.3M ，似乎缩放比再调一下也能接受

**Comment by Arondight** [comment]
宝箱数神瞳数我感觉可以参考一下原项目的这个样式 https://docs.adachi.top/picture/#%E7%8E%A9%E5%AE%B6%E4%BF%A1%E6%81%AF%E5%8D%A1%E7%89%87

不管做不做图片我先拉下来，我感觉以后大概率用得到 https://github.com/SilveryStar/Adachi-BOT/blob/master/src/plugins/genshin/public/js/card-data-parser.js

**Comment by Mark9804** [comment]
那个图标不扒也行，我应该不会用这么写实的图标…

武器的颜色区分是加给星级还是稀有度？

**Comment by Arondight** [comment]
武器我想着文字加个颜色就挺好

图标那我给删掉吧，我还觉得他的图扣的挺好的……

**Comment by HYTT0510** [comment]
有没有想法把诚哥壶放到最下面   把角色展示上移  毕竟诚哥壶展示作用太小

**Comment by Mark9804** [comment]
移到底下太怪了有点……一个壶而已，算了算了

然后关于图标，设计本身也是有风格的，不同的风格混用就好像在一个 JS 项目里面混进去了一个 C++ 模块，不是不行，但是就很诡异，必要的时候我会自己动手的（或者万一我哪天修仙修成正果了下一个前端喜欢写实风格也行）

**Comment by Arondight** [comment]
by adachibot 没了

**Comment by Mark9804** [comment]
啊这，忘记了

**Comment by Mark9804** [comment]
@ixCiel 我们更新了 `米游社` 页面，现在你不用维护两个页面了

武器要不要加颜色区分我再考虑一下吧，感觉没有非要改的理由，那个精几的颜色跟其他不一样其实是我忘删了

**Comment by Arondight** [comment]
建议直接摆烂，有效防止🐆毙，拥有幸福人生。我一个 go tour 看了5⃣️天，摆的轻松快乐

**Comment by Mark9804** [comment]
> go tour

老大哥这是打算提桶跑去 web 后端吗

**Comment by Arondight** [comment]
还没想这些，随便看看，脚本语言写腻歪了

**Comment by Mark9804** [comment]
啊这，明天修吧
<img width="263" alt="image" src="https://user-images.githubusercontent.com/9006264/159162472-3c7d3c64-cf34-43f7-aad9-e50ab186bb8d.png">

**Comment by Mark9804** [comment]
今日新增1（指bug）
<img height="512" alt="image" src="https://user-images.githubusercontent.com/9006264/159289643-68745082-cc4c-4a14-a01a-1ff7afc1ada9.png">

**Comment by Arondight** [comment]
那些表情还需要么，没有后续使用计划我从数据里踢出去，url 短一点

**Comment by Mark9804** [comment]
没用了，我也正想说可以从数据里面踢出去

**Comment by Mark9804** [comment]
旅行者不该显示好感，但是当初好像没考虑这个，要改一下数据结构…
