### ISSUE TITLE
管理员QQ非好友不回复

### ISSUE THREAD

**Issue by citydirector** [Arondight/Adachi-BOT#731]
### 问题描述

如上，理想状态应当管理员QQ优先级大于 “是否回复陌生人” 的选项，即选项配置为0时，也应当回复管理员信息

### 当前提交

```Text
master
```

### 代码状态

```Text
master
```

**Comment by Mark9804** [comment]
我觉得不应该，tx可不管你是不是bot管理员，发现你给陌生人发消息就直接给你扬了……

**Comment by Arondight** [comment]
不回复的

**Comment by Mark9804** [comment]
可以参考 [这个issue](https://github.com/Tsuk1ko/cq-picsearcher-bot/issues/285)
