### ISSUE TITLE
米游社签到功能

### ISSUE THREAD

**Issue by HYTT0510** [Arondight/Adachi-BOT#735]
### 问题描述

昨天在群里闲逛时发现了一个米游社自动签到的机器人  搜了一下找到了这个[米游社签到](https://github.com/wickedll/genshin_sign)，但是这个是适配第一版本的也就是SilveryStar的项目，我看了一下都是ts写的，如果我想给做成适配此版本的插件，需要做哪些工作呢？

### 当前提交

```Text
commit 3df344e72d2305baa5bb1958a477c63ef55946f5 (HEAD -> master, origin/master, origin/dev, origin/HEAD)
Author: Mark Chen <9006264+Mark9804@users.noreply.github.com>
Date:   Fri Mar 18 23:53:53 2022 +0900

    补上绫人天赋本时间
```

**Comment by Mark9804** [comment]
https://github.com/ixCiel/Adachi-BOT

**Comment by HYTT0510** [comment]
十分感谢
