### ISSUE TITLE
深渊显示精简

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#736]
深渊如果能查详细信息能不能只显示12 层的，其他几层显示几星就够了，感觉太长了

_Originally posted by @Arondight in https://github.com/Arondight/Adachi-BOT/issues/728#issuecomment-1072329787_

**Comment by Mark9804** [comment]
显示数组中最后一层的内容；

除非某一间没打满，否则中间的内容只显示总星数

**Comment by Mark9804** [comment]
> 除非某一间没打满，否则中间的内容只显示总星数

划分成两个功能区，最后一层是“当前挑战”，其他是“历史挑战”，这样就可以名正言顺的把其他移到末尾了

**Comment by Mark9804** [comment]
开学季摆几天想想之后的规划，接下来打算看看 golang ，看看神经网络模型，js 和 node 就跟着老大哥混了

**Comment by Arondight** [comment]
我写 js 写的很傻逼，而且就地转的可能性也很小，只能维持一下。另外够浪感觉挺不错的，不过如果不写后台业务，跟 py 半斤八两吧

**Comment by Mark9804** [comment]
老大哥写了这么多年代码，程序结构设计和抽象能力都暴打我，我能学的地方多了去了，语言只是工具，我想多学一个 golang 主要是他和 py 对数据科学都相对友好

**Comment by Mark9804** [comment]
这个也暂时鸽了，电脑坏了

**Comment by Mark9804** [comment]
1. pop 出最后一层的信息
2. map 中间的信息
3. 分两个组件显示？

**Comment by Mark9804** [comment]
今天写一半没动力了，先写一半

**Comment by Mark9804** [comment]
没打满的显示一下留给群友指点江山，其他的全隐藏了

<img src="https://user-images.githubusercontent.com/9006264/162608573-ff7cb18f-9520-47a0-bb83-e538f3f164e3.png" width="360" />
