### ISSUE TITLE
增加别名机制

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#74]
`武器 鱼叉` 直接返回`「渔获」`的图片，不必输入`武器 「渔获」`，就是说别名匹配到直接等效于输入原名，不必返回一堆花里胡哨的猜测名称。

类似的还有角色的别名，`姥爷->迪卢克`、`炸弹人->可莉`这种。

支持多个别名，在`config`下引入配置文件。

**Comment by Arondight** [comment]
我大致想了一下，为了方便，每个原名设置一个同名的别名，大致的意思如下。

```
香菱:
  - 香菱
  - 香师傅
  - 卯小姐
```

**Comment by Arondight** [comment]
> 
> 
> 我大致想了一下，为了方便，每个原名设置一个同名的别名，大致的意思如下。
> 
> ```
> 香菱:
>   - 香菱
>   - 香师傅
>   - 卯小姐
> ```

还有一个方案，那就是只写必要的别名，查询不到的别名，一律返回原名，这样更好一些，整个配置文件比较简洁

**Comment by Arondight** [comment]
这个功能我来做，老哥们先不要搞

**Comment by Arondight** [comment]
我推了个文件，有补充的可以补充一下。

另外添加别名需要把命令配置的正则改成接受字母、数字，在此备忘一下。

**Comment by Xm798** [comment]
妙啊 前几天刚想开个issue提一下这个需求，今天过来一看竟然加上了，太强了！

**Comment by Arondight** [comment]
因为我自己查鱼叉打不出来那个括号，我木的办法

**Comment by Xm798** [comment]
需不需要开一个别名补充的issue，刚才想到哪添到哪，感觉有点不太合适，搞得commit有点乱。
又想到一个 北斗-大姐头

**Comment by Arondight** [comment]
没事，不怕乱
