### ISSUE TITLE
单元测试

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#740]
### 问题描述

我觉得还是有必要搞一个的，以前觉得项目也不复杂懒得搞，刚才写完 cookie 优化发现没得测试，还是不太行

- [ ] 单元测试应该用单独的数据库目录，即使在生产环境也可运行
- [ ] `#utils/cookie`
- [ ] `#utils/database`
- [ ] `#utils/file`
- [ ] `#utils/merge`
- [ ] `#utils/tools`

### 当前提交

```Text
可莉不知道哦
```

**Comment by Mark9804** [comment]
从来没见过实际的单元测试，想见见世面，以前只是听说过有这个东西

**Comment by Arondight** [comment]
https://github.com/mochajs/mocha#sponsors

直接使用自带的 assert ，不额外加流式断言模块了，可读性可以通过注释提高

**Comment by Arondight** [comment]
不做了，测个屁，只要代码没问题就不需要单元测试，只要不写新代码就没有新问题，太完美了！
