### ISSUE TITLE
2.6版本图片缺失

### ISSUE THREAD

**Issue by citydirector** [Arondight/Adachi-BOT#742]
### 问题描述

![2OTQN{ARBB44MA5~VYBUXOJ](https://user-images.githubusercontent.com/45933075/159408525-960cc9bd-12d4-47de-a696-167001bdbedb.gif)

### 复现流程

抽卡

### 运行环境

```Text
root@VM-20-7-ubuntu:~/Adachi-BOT# npm run tool-status

> adachi-bot@1.5.2 tool-status
> npx node ./tools/status.js

操作系统：linux（Ubuntu）
内核版本：5.13.0-30-generic
内核架构：x64
处理器：  0.84%（AMD EPYC 7K62 48-Core Processor @ 2.6Ghz）
启动时间：21 days
内存使用：28.48%（1.17 GB / 4.12 GB）
数据占用：3.26 MB
Node.js： 17.6.0
npm：     8.5.1
浏览器：  Chromium 100.0.4889.0
```

### 当前提交

```Text
commit 6764d6e5700969c50e5497a67d673184b2577733 (HEAD -> master, origin/master, origin/HEAD)
```

### 代码状态

```Text
On branch master
```

**Comment by Mark9804** [comment]
缺的是绫人图片

**Comment by Mark9804** [comment]
卧槽，chromium 100

**Comment by citydirector** [comment]
> 卧槽，chromium 100

我昨天apt update了一下就变成100了...纯属意外

**Comment by Mark9804** [comment]
我只是感叹一下已经100了，前端的千年虫要来了，对本项目没有影响

**Comment by citydirector** [comment]
> 我只是感叹一下已经100了，前端的千年虫要来了，对本项目没有影响

不少老项目得重写

**Comment by Arondight** [comment]
Duplicate of #689

**Comment by citydirector** [comment]
不如彩蛋卡池先屏蔽未上线的吧（）

**Comment by Arondight** [comment]
> 不如彩蛋卡池先屏蔽未上线的吧（）

我有考虑使用一个默认值，因为我也懒得维护这个配置文件了

**Comment by Mark9804** [comment]
> 不少老项目得重写

不用重写，这个问题是什么呢，是有一些网站会使用脚本获取当前浏览器 UA 中的浏览器版本，来判断你的浏览器是不是版本过低，过低的话就直接不让你访问了，但是当年妹人想到浏览器版本能卷到三位数啊，那就只取两位好了，于是 100 → 10 ，您的浏览器版本过低请尽快升级，我们项目没必要做这个判断

**Comment by BTMuli** [comment]
信息查询绫人的图也没有
![-6dea4da92bd74c3](https://user-images.githubusercontent.com/72692909/159450563-d1252fd7-3251-4606-a006-88039efcdf67.jpg)

**Comment by citydirector** [comment]
这么快就写上去了吗（）

**Comment by Mark9804** [comment]
图片的问题再等等

**Comment by Arondight** [comment]
> 这么快就写上去了吗（）

没有，新版本开放前会把图片补齐

**Comment by Mark9804** [comment]
卡池里有绫人的图啊
![image](https://user-images.githubusercontent.com/9006264/159475272-a0dd3afe-e54b-4055-b48b-ed6df388ea6c.png)

更新一下代码
