### ISSUE TITLE
彩蛋卡池不再提供跟随版本变化的配置文件

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#743]
### 问题描述

强制使用已写好配置文件的五星，我不想维护这么多文件了，如果有需要的麻烦留言一下，我会考虑选择性加载配置

### 当前提交

```Text
我也不知道哦
```

**Comment by Arondight** [comment]
算了，直接做选择性加载吧，辛苦一会，方便他人（数量可能为0⃣️）

**Comment by HYTT0510** [comment]
抽彩蛋卡池出bug啦
会出现非五星
![image](https://user-images.githubusercontent.com/46914653/159865439-be067e13-89fe-43e0-8f5a-7c27fddebc0f.png)

**Comment by Mark9804** [comment]
卧槽，我的图图呢

**Comment by Arondight** [comment]
忘记有🌟级了

**Comment by Arondight** [comment]
拉一下代码，把🌟加上了
