### ISSUE TITLE
更新执行npm install时报错error code EJSONPARSE

### ISSUE THREAD

**Issue by citydirector** [Arondight/Adachi-BOT#75]
npm ERR! code EJSONPARSE
npm ERR! path /root/Adachi-BOT/package.json
npm ERR! JSON.parse Unexpected token "<" (0x3C) in JSON at position 478 while parsing near "...   \"pm2\": \"^5.1.0\",\n<<<<<<< Updated upst..."
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.

**Comment by Arondight** [comment]
看看 `npm` 的版本？我两台机器都没问题

```
$ npm version | grep -oP '(?<=npm:\h).+(?=,)'
'7.21.0'
```

```
$ npm version | grep -oP '(?<=npm:\h).+(?=,)'
'6.14.13'
```

**Comment by Arondight** [comment]
如果仍然有问题可以r eopen

**Comment by citydirector** [comment]
今天重新试了一下stash push，然后提示settings.yml和两个包json没有合并

**Comment by Arondight** [comment]
stash 前不要有暂存（add）
