### ISSUE TITLE
puppeteer 截图时机优化

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#750]
https://github.com/Arondight/Adachi-BOT/blob/3a42828ae94516bea4238362f3716d0ee99ff67d/src/utils/render.js#L122

在 js 执行完毕后，创建一个空节点，让 puppeteer 监听这个节点的创建事件来决定截图时间

**Comment by Arondight** [comment]
🐮🍺 这样就有一个稳定的实现了

**Comment by Mark9804** [comment]
https://stackoverflow.com/a/9899701

For modern browsers (anything from IE9 and newer and any version of Chrome, Firefox or Safari), if you want to be able to implement a jQuery like `$(document).ready()` method that you can call from anywhere (without worrying about where the calling script is positioned), you can just use something like this:

```js
function docReady(fn) {
    // see if DOM is already available
    if (document.readyState === "complete" || document.readyState === "interactive") {
        // call on next available tick
        setTimeout(fn, 1);
    } else {
        document.addEventListener("DOMContentLoaded", fn);
    }
} 
```   

Usage:

```js
docReady(function() {
    // DOM is loaded and ready for manipulation here
});
```

**Comment by Mark9804** [comment]
？那我为什么不直接 `page.waitForFunction`

**Comment by Arondight** [comment]
> ？那我为什么不直接 `page.waitForFunction`

看上去是等某个函数执行而不是结束

**Comment by Mark9804** [comment]
感觉像是等待某一个函数返回结果为 `true`

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const watchDog = page.waitForFunction('window.innerWidth < 100');
  await page.setViewport({ width: 50, height: 50 });
  await watchDog;
  await browser.close();
})();
```

**Comment by Arondight** [comment]
> 感觉像是等待某一个函数返回结果为 `true`

我看了一下代码，怎么感觉这东西就是在浏览器里面执行了个自定义的函数然后等它跑完（类似 `await page.$eval` ）？

https://github.com/puppeteer/puppeteer/blob/34775e58316be49d8bc5a13209a1f570bc66b448/experimental/puppeteer-firefox/lib/DOMWorld.js#L502

**Comment by Mark9804** [comment]
好像我想复杂了，应该这样就可以了，不需要额外增加什么东西

```js
page.waitForFunction('document.readyState === "complete"');
```

对于 readyState 的解释如下

https://developer.mozilla.org/zh-CN/docs/Web/API/Document/readyState#%E5%80%BC

<h3 id="值">值</h3>

<p>一个文档的 <code><strong>readyState</strong></code> 可以是以下之一：</p>

<dl>
 <dt><code>loading</code>（正在加载）</dt>
 <dd>文档仍在加载。</dd>
 <dt><code>interactive</code>（可交互）</dt>
 <dd>文档已被解析，"<strong>正在加载</strong>"状态结束，但是诸如图像，样式表和框架之类的子资源仍在加载。</dd>
 <dt><code>complete</code>（完成）</dt>
 <dd>文档和所有子资源已完成加载。表示 `load` 状态的事件即将被触发。</dd>
</dl>

**Comment by Arondight** [comment]
我看了下应该行，直接改掉把

**Comment by Mark9804** [comment]
之后看看有没有表示 document fully loaded 之类的事件吧，这两天想摸了

**Comment by Arondight** [comment]
我当时完全是 google 的，好像 `waitUntil: "networkidle0"` 算是一个广大人民群众普遍认可的方法（虽然这样它显然也是不能保证稳定的），如果没有更好的方法就先这样把

**Comment by Mark9804** [comment]
就我看到的来说最接近的是 [load event](https://developer.mozilla.org/zh-CN/docs/Web/API/Window/load_event) 加一个 timeout ，但是和 idle0 妹有什么太大区别，而且我把所有公共的静态资源全 preload 了，onload 反而会让截图事件过早触发，就维持目前人民群众的智慧结晶吧
