### ISSUE TITLE
无法绑定米游社ID5位数的用户

### ISSUE THREAD

**Issue by yuan488** [Arondight/Adachi-BOT#755]
### 问题描述

出现了，id5位数的大佬
![-ed8836adc3ddd8d](https://user-images.githubusercontent.com/69119229/160151435-64ba7205-aa4f-4355-82ae-6db3ac4b134f.jpg)

### 复现流程

绑定 21106

### 运行环境

```Text
操作系统：linux（CentOS Linux）
内核版本：3.10.0-1160.59.1.el7.x86_64
内核架构：x64
处理器：  5.70%（Intel Xeon® Platinum 8255C @ 2.5Ghz）
启动时间：3 days
内存使用：58.88%（2.34 GB / 3.97 GB）
数据占用：36.3 MB
Node.js： 16.14.2
npm：     8.5.0
浏览器：  Chromium 99.0.4844.51 Fedora Project
```

### 当前提交

```Text
git log -1
```

### 代码状态

```Text
git status
```

**Comment by Mark9804** [comment]
拉一下代码并且重启，但是如果你的 `config` 目录当中也有一份 `command.yml` 的话这个改动不会生效，你需要手动更改
