### ISSUE TITLE
当用户抽的卡池未开放时，显式指出用户抽的哪个卡池未开放

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#761]
### 问题描述

当前 **此** 卡池未开放 → 当前 **【角色】** 卡池未开放，请选择其他卡池

<img width="400" alt="image" src="https://user-images.githubusercontent.com/9006264/160586274-6c874ed4-da67-40c0-9e60-c1fcb3d08c07.png">

### 当前提交

```Text
--
```

**Comment by Arondight** [comment]
好哒🆗
