### ISSUE TITLE
影流之层岩

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#767]
<img width="755" alt="image" src="https://user-images.githubusercontent.com/9006264/160773298-99fe7f3f-50cb-4ac9-9311-cbad316fef94.png">

**Comment by Mark9804** [comment]
是不是上下层分开来算的，我还没打

**Comment by Mark9804** [comment]
```json
[
{
      "level": 0,
      "exploration_percentage": 0,
      "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/city_icon/UI_ChapterIcon_ChasmsMaw.png",
      "name": "璃月层岩巨渊·地下矿区",
      "type": "Offering",
      "offerings": [
        {
          "name": "流明石触媒",
          "level": 0,
          "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/city_icon/UI_ChapterOffering_Lumenstone.png"
        }
      ],
      "id": 7,
      "parent_id": 6,
      "map_url": "https://webstatic.mihoyo.com/ys/app/interactive-map/index.html?bbs_presentation_style=no_header&lang=zh-cn&_markerFps=24#/map/9?&center=0.00,1.00&zoom=-1.00",
      "strategy_url": "",
      "background_image": "https://upload-bbs.mihoyo.com/game_record/genshin/city_icon/UI_ChapterBackground_ChasmsMaw.png",
      "inner_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/city_icon/UI_ChapterInnerIcon_ChasmsMaw.png",
      "cover": "https://upload-bbs.mihoyo.com/game_record/genshin/city_icon/UI_ChapterCover_ChasmsMaw.png"
    },
    {
      "level": 0,
      "exploration_percentage": 0,
      "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/city_icon/UI_ChapterIcon_ChasmsMaw.png",
      "name": "璃月层岩巨渊",
      "type": "Offering",
      "offerings": [
        {
          "name": "流明石触媒",
          "level": 0,
          "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/city_icon/UI_ChapterOffering_Lumenstone.png"
        },
]
```

**Comment by Mark9804** [comment]
看看到时候会不会共享探索度

**Comment by Mark9804** [comment]
找到肝佬的图了，不共通，而且后端返回的数据变成正序的了，不用 reverse 

<img width="293" alt="image" src="https://user-images.githubusercontent.com/9006264/160775827-3ec44c40-ce18-45fc-95f6-059cd8cc125d.png">

**Comment by Mark9804** [comment]
地上矿区 地下矿区 触媒等级![image](https://user-images.githubusercontent.com/9006264/160874704-12d1277f-4ee6-4473-8b04-1b4727d981bd.png)![image](https://user-images.githubusercontent.com/9006264/160874731-a7cf6ef3-3190-4b2b-8eee-3a75bcedcb87.png)![image](https://user-images.githubusercontent.com/9006264/160874747-37079021-ce1f-4af4-aac4-7cc451f41486.png)

**Comment by Arondight** [comment]
借道记个备忘新副本名字岩中幽谷需要在配置文件里写一下（虽然我没找到入口）

**Comment by Mark9804** [comment]
> 虽然我没找到入口

在门口机关盘的位置放一个岩造物，然后跑到小地图上的位置，用开山炮轰那个最不一样的石头，岩波会正好传到机关盘的位置，把你放的岩造物摧毁，然后通过共鸣的方式够到堵门的石头

我也思考了很久策划在这里放了三块大跳石是有什么深意，跳上去用了一下元素视野才发现有一门炮，，，
![原神 3_31_2022 3_02_25 PM](https://user-images.githubusercontent.com/9006264/160987377-67e7c863-6afb-450a-9f4c-2f29342f9c81.jpg)

**Comment by Arondight** [comment]
感谢，晚上试一下

**Comment by Mark9804** [comment]
米忽悠排序怎么排的，猴子排序法是吧
<img width="339" alt="image" src="https://user-images.githubusercontent.com/9006264/161000513-fe71b633-44f2-405f-a21c-9983b9af22e3.png">

**Comment by Arondight** [comment]
我给你整个 lodash ，写个数组用 index 排序吧

**Comment by Mark9804** [comment]
倒也用不上 lodash ，我自己写一个 sort id 然后 reduce 就行了

**Comment by Mark9804** [comment]
算了，不用白不用，来一个 lodash 吧

**Comment by Mark9804** [comment]
> 新副本名字岩中幽谷需要在配置文件里写一下

我顺路提交了

**Comment by Arondight** [comment]
我搞个 lodash 上来

```js
const a = ["一二三", "三四五", "七八九"];
const o = [{ p: "三四五" }, { p: "七八九" }, { p: "没有哦" }, { p: "一二三" }];
console.log(lodash.sortBy(o, (c) => (a.includes(c.p) ? a.indexOf(c.p) : Number.MAX_SAFE_INTEGER)));
```

**Comment by Mark9804** [comment]
用我会用，不过老大哥在 head 里面加载脚本的写法要注意一下，脚本加载时会阻塞渲染的，在实际极端情况下假如用户网速是10k/s，头部要加载一个 300k 的脚本，那理想情况下有十秒钟时间用户啥内容都看不到

**Comment by Arondight** [comment]
那么要怎么办捏

**Comment by Mark9804** [comment]
Async, defer, preload, server push（最后一种我不了解）
https://webspeedtools.com/async-vs-defer-vs-preload-vs-server-push/

https://javascript.info/script-async-defer

我项目里用的是 preload

**Comment by Mark9804** [comment]
> 为啥 vue 没有 preload 呢

其实是因为我懒得改了

**Comment by Arondight** [comment]
啊这，我以为有什么特殊性

**Comment by Mark9804** [comment]
我们项目 vue 不加载的话就是空网页，那我还不如让他加载，无所谓了

**Comment by Arondight** [comment]
为了避免 eslint 太多抱怨，建议起个别名

```js
const lodash = window._;
const chain = lodash.chain(o);
```

**Comment by Mark9804** [comment]
> 为了避免 eslint 太多抱怨，建议起个别名

ok

**Comment by Mark9804** [comment]
昨晚的 cd15cb5 改了一下探索度的显示逻辑，把判断该显示什么内容的工作上调到了 app.js ，理论上写一个 filter 就完事了

https://github.com/Arondight/Adachi-BOT/blob/cd15cb5a4714199ed69f0df24205d84a2dc9cf3d/src/views/component/card/cardComponents.js#L88-L91

就是这两行实现属实难看，想不到在不新建 component 的情况下进行键值对循环的方法

**Comment by Mark9804** [comment]
鸽了，电脑坏了
