### ISSUE TITLE
错误的数据进入了数据库

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#770]
### 问题描述

绑定未公开数据的账号后使用 `米游社` ，数据有可能进入缓存，直接用 `uid` 查貌似没这问题
<img src="https://user-images.githubusercontent.com/9006264/161019839-dd675a08-e6ab-4ec3-9a89-2fded897715b.jpeg" width="300" />

### 复现流程

--

### 运行环境

```Text
--
```

### 当前提交

```Text
--
```

### 代码状态

```Text
--
```

**Comment by Arondight** [comment]
我复现不出来……

**Comment by Arondight** [comment]
还能拿到他的数据嘛？数据库里的

**Comment by Mark9804** [comment]
没有了，后来他刷新掉了，难道是我 fork 的问题？我应该没改动这块代码，暂时先关了吧

**Comment by Arondight** [comment]
![图片](https://user-images.githubusercontent.com/13673702/161063271-6e23264d-40ed-461f-bc34-f3fbee61dd12.png)

我觉得大概率是这个判断遗留了什么情况，但是我这里的数据复现不了
