### ISSUE TITLE
关于消息响应&Bot退出

### ISSUE THREAD

**Issue by BTMuli** [Arondight/Adachi-BOT#774]
### 问题描述

首先是消息响应问题
今天更新后发现对于一些命令的响应异常，有的是没有回应，有的是同一个回应发了两次

好吧，刚刚看了一下，发现可能是被风控的原因，又发了一遍——但实际上之前那条消息是正确发送了的，所以发了两遍实际上

还有一个就是Bot退出的问题，之前我都是采用ctrl+C退出的，然后会有下线通知
这几天更新之后没有发送下线通知了
![image](https://user-images.githubusercontent.com/72692909/161370836-e2c208b1-df0a-4027-b523-afc88362f486.png)

### 复现流程

略（

### 运行环境

```Text
操作系统：Windows（Microsoft Windows 10 家庭中文版）
内核版本：10.0.19044
内核架构：x64
处理器：  16.05%（Intel Core™ i7-10510U @ 1.8Ghz）
启动时间：4 hours
内存使用：86.96%（14.8 GB / 17 GB）
数据占用：1.27 MB
Node.js： 16.14.2
npm：     8.6.0
浏览器：  chrome 100.0.4889.0
```

### 当前提交

```Text
commit 814126d37fe965a14f7a25b4b91b5f97c521f256 (HEAD -> fortune, origin/fortune)
Merge: c0a1e06 8e09beb
Author: BTMuli <72692909+BTMuli@users.noreply.github.com>
Date:   Sat Apr 2 14:25:05 2022 +0800

    Merge branch 'Arondight:master' into fortune
```

### 代码状态

```Text
On branch fortune
Your branch is up to date with 'origin/fortune'.

nothing to commit, working tree clean
```

**Comment by Arondight** [comment]
麻烦在 git bash 中跑，我实在无力在 windows 环境中全量测试和兼容

**Comment by Arondight** [comment]
参考 #140

**Comment by BTMuli** [comment]
用 gitbash 启动报错 `WARN logfile could not be created:`

**Comment by BTMuli** [comment]
这两天趁着周末我搬到Ubuntu上面跑好了😂，感觉用windows问题挺多的T_T

**Comment by Arondight** [comment]
> 用 gitbash 启动报错 `WARN logfile could not be created:`

警告应该没关系吧

**Comment by BTMuli** [comment]
```shell
node:events:504
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:9934
```
这个端口是写死的吗？能不能加个配置选项QWQ

**Comment by Arondight** [comment]
写死的，加不了，本来就不想一个机器跑多个，因为数据库不支持多进程，有多个 qq 可以写在配置文件里
