### ISSUE TITLE
渲染错误

### ISSUE THREAD

**Issue by BTMuli** [Arondight/Adachi-BOT#779]
### 问题描述

今日素材中有两类素材渲染错误
![QQ图片20220404103045](https://user-images.githubusercontent.com/72692909/161464311-7646f418-a44d-4165-82c8-99d35ed2a357.jpg)
![QQ图片20220404103108](https://user-images.githubusercontent.com/72692909/161464329-af38298d-2248-441e-a394-0edc28bd13fb.jpg)

### 复现流程

周一/周四素材
周二/周五素材

### 运行环境

```Text
操作系统：linux（Ubuntu）
内核版本：5.13.0-39-generic
内核架构：x64
处理器：  16.01%（Intel Core™ i7-10510U @ 1.8Ghz）
启动时间：3 hours
内存使用：47.12%（3.24 GB / 6.88 GB）
数据占用：827 kB
Node.js： 16.14.2
npm：     8.5.0
浏览器：  Chromium 100.0.4889.0
```

### 当前提交

```Text
commit 50edaf5a6c693c611d0f435009d6c3cd801665da (HEAD -> fortune, origin/fortune)
Author: github-actions <github-actions@github.com>
Date:   Sun Apr 3 16:55:38 2022 +0000

    Format code
```

### 代码状态

```Text
位于分支 fortune
您的分支与上游分支 'origin/fortune' 一致。

无文件要提交，干净的工作区
```

**Comment by Arondight** [comment]
昨天 json 改坏了

- [ ] 修复错误的 json
- [ ] 更好的逻辑，在 json 错误的情况下也能正常工作

**Comment by Mark9804** [comment]
我发现一个新问题，素材品质应该有四类，这里只显示了三类，电脑准备拿去以旧换新所以调试环境清空了，过几天看看是哪里的问题

**Comment by Arondight** [comment]
> 素材品质应该有四类，这里只显示了三类

我给限制死的，因为一星两星的没有橙色品质，现在去掉了，八竿子打不到一把升级过的低星武器，实在没必要

**Comment by Mark9804** [comment]
> 八竿子打不到一把升级过的低星武器

讨龙因为言语过激被踢出直播间
