### ISSUE TITLE
角色信息 CV 切分错误

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#781]
<img src="https://user-images.githubusercontent.com/9006264/161543571-21fdf468-cf3f-4b07-82cb-46e84afe5452.png" height="640" />

**Comment by Arondight** [comment]
他就是这个样子的，我手动改一下就好

准确来说没有切分的过程，拿到了两国 cv 后合成了一个不再使用的字段

**Comment by Arondight** [comment]
还是老大哥改吧，我也不知道 cv 到底是谁

**Comment by Arondight** [comment]
哦，不对，cv 没错啊，杨杨不是那个京剧腔的配音么，所有语音里都有他的

**Comment by Mark9804** [comment]
确实
