### ISSUE TITLE
关于信息查询

### ISSUE THREAD

**Issue by BTMuli** [Arondight/Adachi-BOT#787]
### 问题描述

考虑出个`任务 [世界任务]`之类的？用以查询任务相关攻略
攻略的挑选跟维护我可以负责，毕竟只是个纯体力活（
消息发送最好是卡片类的，我也不知道 bot 能不能发这种消息就是了

成就相关也可以搞一个，`成就 [成就名称]`之类的
同样也是发送卡片消息
也可以根据成就类型 选择纯文字（剧情成就）或者卡片（成就攻略）
或者单纯支持天地万象里面的隐藏成就的攻略也行
或者写个demo出来我自己有时间~抄作业~仿着写也行

角色攻略能不能搞一个，下午看到 `https://github.com/Le-niao/Yunzai-Bot` 用的 西风驿站 的图感觉也挺好的
可以的话我自己手写一个，反正跟 `周本` 是一样的逻辑

### 当前提交

```Text
commit 1b8816d3bdd8c923d8ef41e9a516c085f1d5a24e (HEAD -> fortune, origin/fortune)
Merge: 5f5fb6a 27b24d0
Author: BTMuli <72692909+BTMuli@users.noreply.github.com>
Date:   Fri Apr 8 23:37:44 2022 +0800

    Merge branch 'Arondight:master' into fortune
```

**Comment by Mark9804** [comment]
1. 恐怕你得自己写，因为我们两个维护者都没时间
2. 卡片类可以发，但是被风控的可能性很大，所以约等于不能发
3. 角色攻略不会做，不想教别人玩游戏
4. 成就类的一个是数据集太大，及时更新不好更新，一个是我们没时间，你得自己写

**Comment by Mark9804** [comment]
目前我们这个项目是本着能懒则懒的原则，我们希望在新版本出来之后最好啥都不用干他就能自己更新或者自己适配，你可以看我们的 [workflows](https://github.com/Arondight/Adachi-BOT/tree/master/.github/workflows) 仓库和 [更新爬虫](https://github.com/Arondight/Adachi-BOT/blob/master/tools/info.js) 就知道我们对懒是有多执着的追求了，还有我其实自己也在用一个 [脚本合集](https://github.com/Mark9804/adachi-resource-assistant) 来帮我找图和下载图片，前端也做了 [大量的适配](https://github.com/Arondight/Adachi-BOT/blob/27b24d0fed961ee57ecafffc452a94fc0958dc56/src/views/component/card/app.js#L101-L178) 来确保米游社之类的在更新之后不需要重新写逻辑来应对更新

但是成就每个版本都会增加新的内容，除非能找到一个三条命令行之内解决的方法，不然的话一更新就要一天两天的，我们现在的维护者都是打工人，这个维护成本太高了，可能我们就算做出来了也无力持续维护

**Comment by Arondight** [comment]
正在做牛马，真的没时间，~原地转岗观察期~

**Comment by Mark9804** [comment]
然后关于攻略这一块，虽然我们不太愿意加入这个功能，但是隔壁 bot 的逻辑和周本是不一样的

它先去请求米游社的攻略 API ，然后检索攻略帖子标题中是否含有想查找的角色的名字，然后去请求米游社内容 API ，获取返回的信息中的所有图片，然后发送这些图片。虽然本质上都是发送图片，但是他们的做法更复杂，也更省力（不用自己更新每个角色的攻略链接）

你可以使用项目中已经封装好的 `getCache` 来获取要发送的图片的 base64 编码，这点上的逻辑是一致的

https://github.com/Arondight/Adachi-BOT/blob/27b24d0fed961ee57ecafffc452a94fc0958dc56/src/plugins/material/material.js#L17-L18
