### ISSUE TITLE
npm 包漏洞

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#790]
5 个 high, 2 个 critical, 3 个 low

`npm audit fix`
`npm audit fix --force`

**Comment by Mark9804** [comment]
哦看了一眼，全是 pm2 包的，应该要升级一下 pm2

**Comment by Mark9804** [comment]
不对啊，怎么越装 high 越多了，老大哥看看

**Comment by Arondight** [comment]
不用管

1. 在我们的项目里不会造成任何安全问题
2. 需要 pm2 项目跟进发版才行
