### ISSUE TITLE
项目支持 ESM

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#80]
根据我这两个月从零到一的 JS 知识，和观察经验到以下事实。

1. 本项目当前使用的是 CJS，因为 CJS 某些方面的缺陷，现在已经少有新项目使用 CJS 了
2. 还在维护的模块很多已经变成 ESM，我不是很理解 ESM 和 CJS 的关系，但是一个结果就是较新的模块已经无法使用了，`require` 会直接报错
3. 当前大多数项目已经转移到了 TS，它和 JS 的关系据我理解可能像 Qt 之于 CPP，即是 JS 的一个语法扩展（带来了很多好的特性），但是仍然需要编译为 JS 才能被解释

我当前的想法如下。

1. 如果只有 TS 能使用 ESM，那么此项目改为 TS
2. 如果有 CJS 之外其他的 JS 标准能够使用 ESM，那么改用那个支持 ESM 的标准，这样修改可以最小化，但是因为 CJS 风评看上去不好，所以尽量不再使用 CJS
3. 有必要的话项目的文件结构按照新的 JS 标准的约定或者习俗组织
4. 代码尽量符合新的规范

这些做完之后，就可以使用较新的模块了，这是很重要的一件事。我不太明白 JS 的（具体是哪些）标准之间有什么区别，仅在此表述我的想法，但是需要支持导入 ESM 的目的是明确的。

因为当前代码也不是不能跑，所以此事不紧急。

**Comment by Arondight** [comment]
这个 [gist](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) 进行了一个很好的解释，但是我仍然需要更多地知识，最好一个现成的修改示例。

**Comment by Arondight** [comment]
找到一个自动转换 https://github.com/tbranyen/babel-plugin-transform-commonjs

**Comment by Arondight** [comment]
当前我借助 babel 实现了自动转换，但是遇到了一个大问题，ESM 不支持动态模块导入，import 后面必须跟字符串，这个问题怎么解决？ @SilveryStar 老大哥知道怎么搞么？

https://github.com/Arondight/Adachi-BOT/blob/e62e4f5734c51b9283bcc13760a4f09c1ab22a0e/src/utils/load.js#L23-L33

https://github.com/Arondight/Adachi-BOT/blob/e62e4f5734c51b9283bcc13760a4f09c1ab22a0e/src/utils/load.js#L60-L70

---

还有个问题就是 js-beautify 为啥老是把注释给上一个语句块？

```
if (a) {
}

// 关于 b 的注释
if (b) {
}
```

->

```
if (a) {
} // 关于 b 的注释

if (b) {
}
```

**Comment by Arondight** [comment]
我觉得还是不要瞎比搞了，能跑就行，这堆概念看得我都大

**Comment by Arondight** [comment]
找了个工具，不用改代码 https://www.npmjs.com/package/esm

**Comment by Arondight** [comment]
我花了一整天终于知道要怎么做了，得删掉分支重做一下，现在的提交太占空间了。

**Comment by SilveryStar** [comment]
1. `TypeScript` 是 `JavaScript` 的语法超集，主要还是用来补足 `JavaScript` 的不足和 `OOP` 支持
2. 事实上 `TypeScript` 版的新项目在导入插件的时候还是使用的 `CJS` 方式，见[TS文档](https://www.tslang.cn/docs/handbook/modules.html)，在 `Node.js` 中使用 `ESM` 动态导入，需要 `import()` 关键词，见 [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports)
3.  关于 「JS 标准的约定或者习俗」，我是纯野路子，不懂，自己凭感觉写的（
4. `js-beautify` 没用过
5. 如果想换 `TypeScript`，不妨来给 v2.x 做插件（？

**Comment by Arondight** [comment]
@SilveryStar 感谢老大哥，一天天的净面向网友编程了

**Comment by Arondight** [comment]
摸鱼两天才搞完，这玩意儿居然是没意义的，太强了

![548681EB-80B0-47F4-93EB-31E56E587CA8](https://user-images.githubusercontent.com/13673702/132812103-a540d9c4-f9f3-435c-8914-dd806e2f5a06.jpeg)
