### ISSUE TITLE
嘟嘟可描述换行符没有被正确识别

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#800]
<img width="194" alt="image" src="https://user-images.githubusercontent.com/9006264/167327104-6e7f8de9-3b04-46c2-9d3d-dc8cdb5827dc.png">
<img width="438" alt="image" src="https://user-images.githubusercontent.com/9006264/167327232-44fb8285-e658-4a4b-936e-3c571d52b485.png">

**Comment by Mark9804** [comment]
对了老大哥，缓存可以强制禁用吗，我想起来修这个地方的时候测试 bot 没有我的 cookie ，只能查八个，再查的话一直在调用缓存，最后把 info 数据库整个删了才强制刷新

现在短时间内连续查询米游社也可能是改了首页人物想看看新效果之类的，感觉比起之前不能调整的时候缓存的意义变得不是那么大了，有时还会起阻止刷新的反效果

**Comment by Mark9804** [comment]
> 改成 0

改成 0 我之前试过， 0 会被判 false 然后使用默认设置的 1 ，晚上回去再试试

**Comment by Arondight** [comment]
> > 改成 0
> 
> 改成 0 我之前试过， 0 会被判 false 然后使用默认设置的 1 ，晚上回去再试试

那就是代码有问题
