### ISSUE TITLE
天赋和武器回归

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#801]
### 问题描述

跟了几个版本，作者不知道为啥好像又行了，等到作者不行了，再把这批功能全噶了

### 当前提交

```Text
1
```

**Comment by Mark9804** [comment]
这是什么功能（已经忘了）

**Comment by Mark9804** [comment]
我想起来了，这个好像可以模仿每日素材做成自己的，老大哥不想写的话我就有生之年提个 pr 吧

**Comment by Arondight** [comment]
> 有生之年提个 pr 吧

可以啊，我先用着米游社的图，就是以前天赋武器周本那三张图，这个（用网页）做不做感觉都还好

**Comment by Arondight** [comment]
我突然想起来还得搞boss的头像，麻烦的话不要做了吧，作者鸽了就直接把功能全砍了

**Comment by Mark9804** [comment]
当然是做成每日素材那样的了，什么 boss 头像，不认识
