### ISSUE TITLE
手机扫码完成后按下 Enter 继续

### ISSUE THREAD

**Issue by KinChauAu** [Arondight/Adachi-BOT#81]
![image](https://user-images.githubusercontent.com/38379003/132619946-00704b4b-76c9-461c-9d70-75462224d4ce.png)
没有吐出二维码这里要怎么做呢？

**Comment by Arondight** [comment]
浏览器访问网址

**Comment by KinChauAu** [comment]
噢，感谢大佬，
![image](https://user-images.githubusercontent.com/38379003/132621976-5c1e9892-9f65-4503-a769-0c26121eadf0.png)
大佬，还有这个问题，为什么没有返回的，也没有报错

**Comment by Arondight** [comment]
![图片](https://user-images.githubusercontent.com/13673702/132622994-913bb3b2-f8fc-4637-ac1c-e9210ebba9d0.png)

**Comment by KinChauAu** [comment]
![image](https://user-images.githubusercontent.com/38379003/132627082-836432ba-9b86-463e-91af-60b507ce79f0.png)
![image](https://user-images.githubusercontent.com/38379003/132627108-b8607495-72fb-4fec-a7e3-128c186db785.png)
大佬，config/cookies.yml这里的cookies是怎么写的呢？

**Comment by Arondight** [comment]
#42 不要暴露自己的 Cookie，理论上可以使用你的 Cookie 通过登录米游社，然后游戏内扫码登录游戏。

**Comment by KinChauAu** [comment]
![image](https://user-images.githubusercontent.com/38379003/132630943-52194d88-655e-41fa-936c-2ca4784adc48.png)
好的，感谢大佬提醒，但是这里看还是报错了
![image](https://user-images.githubusercontent.com/38379003/132631018-c0afa877-000b-482d-ad94-1203e13a3729.png)

**Comment by Arondight** [comment]
https://github.com/Arondight/Adachi-BOT/issues/42#issuecomment-903958701

**Comment by KinChauAu** [comment]
大佬，这里看下能否做下README，因为这边测试在其他插件上使用获取到的Cookie都是能使用的，但是在咱们这边一直报错
![image](https://user-images.githubusercontent.com/38379003/132662443-9f162e01-89a0-4aa2-a24e-f91edc6edbb8.png)

**Comment by Arondight** [comment]
老大哥，是这样的。

1. 你看我发的回复，你把 `米游社COOOKIE` 这几个字删掉
2. pm2 的报错日志会一直显示，上面是最近的错误，下面是最近的输出，显示错误不代表这一次就有错

**Comment by Arondight** [comment]
@KinChauAu 我知道你是什么问题了，你把 `data/db/cookies.json` 删掉再跑

**Comment by KinChauAu** [comment]
可以了，感谢大佬，昨天就有研究过这个缓存的问题，发现cookies一直不变，但是没找到具体的

**Comment by Arondight** [comment]
这个问题需要修一下，不要把格式错误的 cookie 写入数据库
