### ISSUE TITLE
深渊其他层也许可以倒序排列

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#812]
现在：12，9，10，11
改进：12，11，10，9

<img width="400" alt="image" src="https://user-images.githubusercontent.com/9006264/168947503-031c5bcf-83db-4acd-bd68-0c79893824eb.png">

**Comment by Arondight** [comment]
我更新了代码没有用，还是数组倒序吧

**Comment by Arondight** [comment]
```

操作系统：linux（CentOS Stream）
内核版本：4.18.0-383.el8.x86_64
内核架构：x64
处理器：  1.11%（Intel Xeon® Platinum 8255C @ 2.5Ghz）
启动时间：15 days
内存使用：23.00%（900 MB / 3.91 GB）
数据占用：3.27 MB
Node.js： 16.14.2
npm：     8.5.0
浏览器：  Chromium 99.0.4844.84 Fedora Project
```

**Comment by Arondight** [comment]
> 那老大哥 revert 回去用数组实现吧，最近事情有点多不能随时摸鱼

ok

**Comment by Mark9804** [comment]
哦没事了，我补错了

flex-direction: column-reverse
