### ISSUE TITLE
接口又寄了

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#814]
rt.

_Originally posted by @Xm798 in https://github.com/Arondight/Adachi-BOT/discussions/813_

**Comment by Arondight** [comment]
不知道各位大佬的项目还在更么，粘贴复制圈了一下各位 @SilveryStar @KimigaiiWuyi @wudifeixue @ixCiel 

还没看，在上班，不知道啥问题

**Comment by KimigaiiWuyi** [comment]
> 不知道各位大佬的项目还在更么，粘贴复制圈了一下各位 @SilveryStar @KimigaiiWuyi @wudifeixue @ixCiel
> 
> 还没看，在上班，不知道啥问题

加`-record`

**Comment by Arondight** [comment]
> 加`-record`

没听懂啥意思

**Comment by ixCiel** [comment]
api-takumi.mihoyo.com

**Comment by Xm798** [comment]
> > 加`-record`
> 
> 没听懂啥意思

体力接口换成 api-takumi-record.mihoyo.com，但是其他接口貌似不是。我抓包看看

**Comment by ixCiel** [comment]
改成 api-takumi-record.mihoyo.com

**Comment by Arondight** [comment]
> 改成 api-takumi-record.mihoyo.com

我🌞，整天改这个干啥

**Comment by ixCiel** [comment]
后面是game_record的都改成api-takumi-record.mihoyo.com

**Comment by KimigaiiWuyi** [comment]
> > 加`-record`
> 
> 没听懂啥意思

就是改成上次那个上了`WAF`的API，除了签到都要改

**Comment by Arondight** [comment]
> 就是改成上次那个上了`WAF`的API

那不是 vps 又不能用了

**Comment by KimigaiiWuyi** [comment]
> > 就是改成上次那个上了`WAF`的API
> 
> 那不是 vps 又不能用了

但这次可以

**Comment by Mark9804** [comment]
啊这，绝了

**Comment by CeciliaAki** [comment]
求问如果要改接口的话在哪个源码文件里改…… OAO

**Comment by Arondight** [comment]
> 求问如果要改接口的话在哪个源码文件里改…… OAO

我已经改完了

**Comment by CeciliaAki** [comment]
非常感谢！！

**Comment by Mark9804** [comment]
像这种突然的变动为啥米游社 app 不会出问题，是每个版本硬编码写好的还是有一个统一的获取 api 地址的 api？

**Comment by Arondight** [comment]
> 还是有一个统一的获取 api 地址的 api

看请求没有

**Comment by Xm798** [comment]
> 像这种突然的变动为啥米游社 app 不会出问题，是每个版本硬编码写好的还是有一个统一的获取 api 地址的 api？

有没有一种可能是新的api早就上线了，只是今天突然把旧的掐了

**Comment by Mark9804** [comment]
我觉得这是一个整体迁移，连开服时期的 api 都迁移过去了

~~倒是更新新版本啊，搁着刷KPI呢~~
https://github.com/SilveryStar/Adachi-BOT/commit/aadc54a2123a97ec7f36c1d8e7b1f65711ff0cf7#

**Comment by davidelectricfree** [comment]
更新到最新代码，依然是服务商IP已被屏蔽，其他的原神机器人没问题。

**Comment by Arondight** [comment]
> 更新到最新代码，依然是服务商IP已被屏蔽，其他的原神机器人没问题。

如果还在使用 node 14，更新到 16，14去年就不支持了

**Comment by Mark9804** [comment]
重启了吗

> 更新到最新代码，依然是服务商IP已被屏蔽，其他的原神机器人没问题。

**Comment by Arondight** [comment]
> 重启了吗

大概是 14 不支持 Promise.any ，所有的错误我都报的是他贴的那句话
