### ISSUE TITLE
2022.5.18米游社接口被更改后无法使用米游社相关功能

### ISSUE THREAD

**Issue by CeciliaAki** [Arondight/Adachi-BOT#815]
### 问题描述

如题。
对原先已设置cookie，能够正常使用uid查询功能和实时便笺、签到等功能的机器人使用git pull更新接口后，再使用npm run init初始化启动机器人，随后在QQ上对机器人发送“uid”查询指令和实时便笺指令反馈如下：
![QQ图片20220518174640](https://user-images.githubusercontent.com/103917391/169013043-ece7043a-7a05-474b-8bfd-6d21582420c5.png)

### 复现流程

对5.18前已设置cookie，能够正常使用uid查询功能和实时便笺、签到等功能但是5.18下午接口更改相关功能失效的的机器人使用git pull更新接口后，再使用npm run init初始化启动机器人。

### 运行环境

```Text
npm run tool-status
```

### 当前提交

```Text
git log -1
```

### 代码状态

```Text
git status
```

**Comment by Mark9804** [comment]
开错地方了老大哥，去 ixciel 的 fork那里开
