### ISSUE TITLE
Vue 在 setup 顶层解构参数会导致失去响应性

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#817]
### 问题描述

不再在顶层解构

### 复现流程

1

### 运行环境

```Text
1
```

### 当前提交

```Text
1
```

### 代码状态

```Text
1
```

**Comment by Arondight** [comment]
或者其实用组合式的那套也挺好，代码也改不了多少

**Comment by Arondight** [comment]
额，标题是个报错……我们压根不管响应性，不过 eslint 很执着认为我们需要响应，所以得和 eslint 说明白

**Comment by Arondight** [comment]
props.data no
props.value.data no
unref(props) yes

eslint 真有你的，只认语法糖

**Comment by Arondight** [comment]
> 从 vue 的角度来说的话响应性我理解成「随着时间或者用户操作响应对应的状态改变」

我看老大哥最近在用 vue 搞网站，我感觉这个最好给你说明一下

```js
// 数据
const data = { name: "" };

// 组件 comp
let comp = "null";

// 渲染 comp
function render(text) {
  console.log("before:", comp);
  comp = text;
  console.log("after:", comp);
}

//
// 非响应
//
// 改变数据
data.name = "aba";
// 手动渲染
render(data.name);

//
// 响应式
//
// 通过 Proxy 或者 defineProperty 设置 getter 和 setter
const dataProxy = new Proxy(data, {
  set: function (obj, prop, val) {
    if ("name" === prop) {
      render(val);
    }

    obj[prop] = val;

    return true;
  },
});
// 改变数据并渲染
dataProxy.name = "bab";
```

上面的代码是响应式的核心思想。所以你在 Vue 中用到的响应式数据其实都是一个封装。

……所以我也没搞明白 eslint 为啥允许 `unref(ref)` 但是不允许 `ref.value` ，这俩都是一个东西

**Comment by Mark9804** [comment]
谢谢老大哥说明，ref/reactive 之前写 [轮播图组件](https://github.com/development-psychology-hiroshima/development.hiroshima-u.ac.jp/blob/3ea68f1dfb025624882f56d52bd51eb71aea02c1/src/components/bannerCarousel.vue#L47-L58) 的时候查了一下，不过不打算真干前端就没太关心原理，大概知道是个基于 proxy 的实现
