### ISSUE TITLE
退出指令

### ISSUE THREAD

**Issue by BTMuli** [Arondight/Adachi-BOT#824]
### 问题描述

管理员功能里面加入一个退出应用的指令感觉会方便很多...
而且这种情况下，也不用 <kbd>ctrl</kbd>+<kbd>c</kbd>来强制退出

### 当前提交

```Text
commit 01cedcb813af6a358f9d39a99529e762558d8114 (HEAD -> luck, origin/luck)
Merge: bc7c1342 225375b5
Author: BTMuli <72692909+BTMuli@users.noreply.github.com>
Date:   Fri May 27 22:29:10 2022 +0800

    Merge branch 'Arondight:master' into luck
```

**Comment by Mark9804** [comment]
> 而且这种情况下，也不用 <kbd>ctrl</kbd>+<kbd>c</kbd>来强制退出

用 ctrl + C 强制退出就是错误的吧，机器人提供了 `npm run start`, `npm run stop`, `npm run restart`

`npm run init` 只是一开始要和控制台交互（输入登录 ticket）才使用的，后面一般直接 `npm run start`

而且退出就不能自己启动了，我感觉反而挺困惑的，想不到具体的应用场景。什么情况下需要让机器人关闭但是又接触不到控制台？

**Comment by Arondight** [comment]
没有提供自杀机制的想法
