### ISSUE TITLE
素材分布地图

### ISSUE THREAD

**Issue by DongGua-Jun** [Arondight/Adachi-BOT#826]
### 问题描述

比如漂浮零/晶蝶/骗骗花的分布地图

### 当前提交

```Text
就酱
```

**Comment by Mark9804** [comment]
Duplicate of #181

**Comment by Mark9804** [comment]
这个有两个问题，一个是变成我们要维持一个很庞大的素材名称库，第二个是抓取逻辑很难实现，我们现在只有两个开发者，一个在享受福报一个在当科研民工，所以没有这个精力去实现这一整套逻辑

**Comment by DongGua-Jun** [comment]
害，好日子还在后头哩

**Comment by Arondight** [comment]
> 第二个是抓取逻辑很难实现

其实可以用米游社的 api 然后本地切图，不过本地表现也不太好，图太大了，密密麻麻全是点

**Comment by Arondight** [comment]
> 表现也不太好

不少人找素材都是视频跟跑，也没几个真去米游社开地图跑的，从这方面来看这功能作用也是有限的

**Comment by Arondight** [comment]
> 一个在享受福报

准确来说这两周真的是在玩，每天睡到中午，吃饭看直播打游戏吃饭逛街开罐小酒睡觉，完全没碰代码，感觉到了人生岔路口

**Comment by DongGua-Jun** [comment]
> > 一个在享受福报
> 
> 准确来说这两周真的是在玩，每天睡到中午，吃饭看直播打游戏吃饭逛街开罐小酒睡觉，完全没碰代码，感觉到了人生岔路口

隔壁那个看圣遗物的那么香，真的忍得住吗？

**Comment by Mark9804** [comment]
> 隔壁那个看圣遗物的那么香，真的忍得住吗？

不会做，做不来
![image](https://user-images.githubusercontent.com/9006264/172037841-fa2f6d1f-8e93-478b-90f2-4e51b3d54d07.png)

**Comment by DongGua-Jun** [comment]
> 

![E%4BX3Z0A1UBOJ%Y}~54_~U](https://user-images.githubusercontent.com/75875483/172037874-b301d396-c441-4ac8-b103-666a612d4c31.jpg)

**Comment by Mark9804** [comment]
> 隔壁那个看圣遗物的那么香，真的忍得住吗？

好消息是看起来真的可以做
https://github.com/yoimiya-kokomi/miao-plugin/commit/8dbcc30222004d04469eb9932d9a4b75d1afb430

**Comment by Arondight** [comment]
> 好消息是看起来真的可以做

这哪儿的 api ，看上去不是 orc ，应该是米家的非公开 api ？

https://enka.shinshin.moe/u/102445054/__data.json

**Comment by Mark9804** [comment]
https://enka.shinshin.moe

能做，我也不知道这玩意怎么实现的魔法

**Comment by Mark9804** [comment]
光学字符识别 (Optical Character Recognition, O**CR**)

**Comment by Arondight** [comment]
额，本来想问问作者怎么实现的，没有 discard 账号，还是算了，这个速度该是挺快的，如果稳定的话感觉也挺好的

**Comment by Mark9804** [comment]
discord 账号我有，但是这个看上去就不像是人家会说的样子

不过好处就是由一个半专业化的团队来管理 API ，米忽悠后端那边万一想冲 KPI 了慌的也不是我们，所以做进项目里感觉问题也不是很大

如果老大哥想做进来的话前端适配还是我来做

**Comment by Mark9804** [comment]
> 本来想问问作者怎么实现的

作者对外说是 OCR，但是这个速度要说是 OCR 的话我不太相信，不过看他的履历确实是 OCR 专精
<img width="462" alt="image" src="https://user-images.githubusercontent.com/9006264/172049622-ad5a7a07-e12e-4446-869f-58c71e5b5ca3.png">

**Comment by Arondight** [comment]
> 如果老大哥想做进来的话前端适配还是我来做

没想法，我好懒

**Comment by Mark9804** [comment]
> 没想法，我好懒

啊这，那等八月份我来做吧，做完看看 PR 进来

**Comment by Arondight** [comment]
> 八月份

那时候我可能已经做完了，但是最近不写代码，等到生活安定下来再说

**Comment by Mark9804** [comment]
> 最近不写代码，等到生活安定下来再说

OK

**Comment by CMHopeSunshine** [comment]
关于enka：https://github.com/EnkaNetwork/API-docs

**Comment by Mark9804** [comment]
感谢，其实 json 我逆的差不多了，这份文档还远没有详细到能用的程度，但是会减轻工作量
