### ISSUE TITLE
添加角色展柜信息展示

### ISSUE THREAD

**Issue by A-JiuA** [Arondight/Adachi-BOT#832]
### 问题描述

查看角色展柜信息[Enka.Network](https://enka.shinshin.moe)
这个网站只需要UID就可以查询到游戏内角色展柜的信息,比起米游社查询到的更详细,可以将数据导出为图片,网站也提供api来查询
我的想法是在使用`我的 <角色名>`、`游戏内uid、@群友的 <角色名>`命令时,如果该角色在对应uid的角色展柜中,则同时展示展柜中的信息

我已经实现了导出图片,原理是对网页截图,图片会保存在当前目录,文件名为`<UID><角色名>.png`。由于不会写nodejs,使用python进行编写,希望能提供一些帮助,[仓库](https://github.com/A-JiuA/PlayerCards)
使用:`python PlayerCards.py <UID> <角色名>`请使用准确的中文名
环境:Edge浏览器及对应webdriver
请提前下载对应版本[webdriver](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/)并放入系统PATH中
!!该程序没有图形界面

### 当前提交

```Text
commit 43243042933be949899444f00b8574eb122ccd6f (HEAD -> master, origin/master, origin/HEAD)
Merge: 7288f88d ae297c62
Author: Qin Fandong <shell_way@foxmail.com>
Date:   Mon Jun 6 18:58:46 2022 +0800

    Merge pull request #828 from BTMuli/dev

    更新周本图
```

**Comment by A-JiuA** [comment]
没看到上一个issue,先关了

**Comment by Mark9804** [comment]
感谢，导出图片这个思路挺狠的，我很喜欢

**Comment by A-JiuA** [comment]
> 

主要是菜，加上懒得用api重新生成图片（

**Comment by A-JiuA** [comment]
> 感谢，导出图片这个思路挺狠的，我很喜欢

主要是菜，加上懒得用api重新生成图片（
