### ISSUE TITLE
增加Wiki查询

### ISSUE THREAD

**Issue by A-JiuA** [Arondight/Adachi-BOT#835]
### 问题描述

现有信息查询信息过少，不方便
可以使用biliwiki、米游社观测枢等

### 当前提交

```Text
commit 43243042933be949899444f00b8574eb122ccd6f (HEAD -> master, origin/master, origin/HEAD)
Merge: 7288f88d ae297c62
Author: Qin Fandong <shell_way@foxmail.com>
Date:   Mon Jun 6 18:58:46 2022 +0800

    Merge pull request #828 from BTMuli/dev

    更新周本图
```

**Comment by Mark9804** [comment]
比如说要什么信息，如果确定加上的话我八月中才有时间写

现在的信息是内鬼网的

**Comment by A-JiuA** [comment]
> 比如说要什么信息，如果确定加上的话我八月中才有时间写
> 
> 现在的信息是内鬼网的

比如技能效果、倍率、推荐配装等等

**Comment by A-JiuA** [comment]
用biliwiki查比较方便，`https://wiki.biligame.com/ys/`+<名称>就可以找到相应的信息

**Comment by Mark9804** [comment]
#643 有部分讨论

主要考虑在能够自动更新的情况下添加新信息，所以比如说钟离E技能描述特别长的话观感不好，就会重新考虑

这个应该至少等到 enka 合并，重写信息布局以适应 enka 信息的时候会再考虑一下

~~如果到时候我十三机兵打完了的话~~

**Comment by Arondight** [comment]
这个问题讨论几次了，先走通 enka 的流程再说吧，到时候会新开议题。

另外我还有一周甚至更长时间才能（安心）写代码，看北京的疫情吧

**Comment by Mark9804** [comment]
说到这个问题，这个项目的时间资源是远远不够的，两个维护者，上面那位是后端，平时工作日要混饭吃，我是前端和美术，科研狗，手上堆了 1.5 篇论文要写，如果等我们开搞的话进度会很慢

如果想要贡献的话，可以提供一些参考图，这样能省下我做原型设计的时间 ~~开抄~~

或者有能力的话也欢迎 PR

**Comment by A-JiuA** [comment]
了解了，我要等暑假才有时间研究
