### ISSUE TITLE
需要一个默认行为列表

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#839]
是不是需要一个默认行为列表？

_Originally posted by @Arondight in https://github.com/Arondight/Adachi-BOT/discussions/838#discussioncomment-3078974_

**Comment by Arondight** [comment]
@Xm798 老大哥自行测试一下吧

**Comment by Arondight** [comment]
1. 配置文件需要补现象说明
2. 开发指引的例子该换了

明天改一改

**Comment by Arondight** [comment]
> 这个修改之后以前的配置还能用吗

这个修改是兼容的

**Comment by Mark9804** [comment]
<img width="591" alt="image" src="https://user-images.githubusercontent.com/9006264/177572035-5438a15f-65f8-4088-9d30-80624a393ea1.png">
默认行为列表的优先级好像太高了，连管理员都不放过

**Comment by Arondight** [comment]
确实是这样的，单独设置一下吧
