### ISSUE TITLE
如何只响应一个群的消息

### ISSUE THREAD

**Issue by 1578339936** [Arondight/Adachi-BOT#85]
由于本人账号加入了数十个各种类型的群聊，还有一些班级群，在开启机器人后我一些群聊直接踢出，所以能不能只在指定群聊开启机器人。

**Comment by Arondight** [comment]
不支持此功能，请申请单独的 QQ 来运行机器人。参考 #40 

如果你真的不想申请新 QQ，那你可以用 `响应群消息` 命令一个一个地去关群。

**Comment by 1578339936** [comment]
OK吧。。
