### ISSUE TITLE
“我的”忘加皮肤重定向了

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#856]
今天没时间

![image](https://user-images.githubusercontent.com/9006264/178651048-552f684e-8fa2-4c1a-8d21-7ccd187ed835.jpeg)

**Comment by Mark9804** [comment]
老大哥想帮忙擦一下烂摊子吗，加一个 directive， :src 用无皮肤的图片做保底， v-directive="皮肤URL" 覆盖过去

**Comment by Arondight** [comment]
> 老大哥想帮忙擦一下烂摊子吗，加一个 directive， :src 用无皮肤的图片做保底， v-directive="皮肤URL" 覆盖过去

看有没有空，还在赶火车🚄

**Comment by Mark9804** [comment]
只要我接下去全部换成证件照，就没有这个问题了
