### ISSUE TITLE
深渊接口是不是变了

### ISSUE THREAD

**Issue by BTMuli** [Arondight/Adachi-BOT#866]
### 问题描述

前提：使用本人cookie查询本人绑定uid深渊信息
非预期结果：查询到的信息仅有大概信息，缺失具体楼层情况

米游社`原神战绩`中并未直接显示具体楼层情况，而是要点击`查看挑战详情`才能跳转具体页面。
如果采用之前的模式，具体楼层情况数据无法获取。

### 复现流程

深渊

### 后台日志

```Text
略
```

### 运行环境

```Text
略
```

### 当前提交

```Text
commit 486a4a8125bd7cfc6525ac673ea9efe016b95f65 (HEAD -> dev, origin/dev)
Author: github-actions <github-actions@github.com>
Date:   Thu Jul 21 22:21:38 2022 +0000

    Update Node.js modules
```

### 代码状态

```Text
On branch dev
Your branch is up to date with 'origin/dev'.

nothing to commit, working tree clean
```

**Comment by BTMuli** [comment]
米游社如图
![Screenshot_20220722_115655_com.mihoyo.hyperion.png](https://user-images.githubusercontent.com/72692909/180359421-4efe6700-cf4b-4f9d-adc4-675fd08ed954.png)
本人查询情况如图
![-1f047244be5e34f8.jpg](https://user-images.githubusercontent.com/72692909/180359500-658a6d4c-e003-44d0-9f07-4d8257aef8df.jpg)
详情页如图
![1658462015684.jpg](https://user-images.githubusercontent.com/72692909/180359527-c7373f24-7835-4498-98b9-b02e7d533ec3.jpg)

**Comment by Mark9804** [comment]
麻烦还是照旧给一下 json，我这期深渊还没时间打，但是查看上期是正常的

**Comment by BTMuli** [comment]
你把缓存清一下，我刚刚查了上期没有详细楼层信息。
<details>
  <summary>上期json如下：</summary>
  <pre><code>
{
  "user": [
    {
      "uid": 500299765,
      "data": {
        "schedule_id": 49,
        "start_time": "1656619200",
        "end_time": "1657915199",
        "total_battle_times": 28,
        "total_win_times": 17,
        "max_floor": "12-3",
        "reveal_rank": [
          {
            "avatar_id": 10000030,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Zhongli.png",
            "value": 17,
            "rarity": 5
          },
          {
            "avatar_id": 10000029,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Klee.png",
            "value": 17,
            "rarity": 5
          },
          {
            "avatar_id": 10000032,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Bennett.png",
            "value": 17,
            "rarity": 4
          },
          {
            "avatar_id": 10000023,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Xiangling.png",
            "value": 17,
            "rarity": 4
          }
        ],
        "defeat_rank": [
          {
            "avatar_id": 10000029,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Klee.png",
            "value": 64,
            "rarity": 5
          }
        ],
        "damage_rank": [
          {
            "avatar_id": 10000030,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Zhongli.png",
            "value": 75698,
            "rarity": 5
          }
        ],
        "take_damage_rank": [
          {
            "avatar_id": 10000029,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Klee.png",
            "value": 87354,
            "rarity": 5
          }
        ],
        "normal_skill_rank": [
          {
            "avatar_id": 10000029,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Klee.png",
            "value": 334,
            "rarity": 5
          }
        ],
        "energy_skill_rank": [
          {
            "avatar_id": 10000032,
            "avatar_icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Bennett.png",
            "value": 63,
            "rarity": 4
          }
        ],
        "floors": [
          {
            "index": 9,
            "icon": "",
            "is_unlock": true,
            "settle_time": "0",
            "star": 9,
            "max_star": 9,
            "levels": [
              {
                "index": 1,
                "star": 3,
                "max_star": 3,
                "battles": [
                  {
                    "index": 1,
                    "timestamp": "1656683747",
                    "avatars": [
                      {
                        "id": 10000029,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Klee.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000032,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Bennett.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000023,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Xiangling.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000030,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Zhongli.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  },
                  {
                    "index": 2,
                    "timestamp": "1656683824",
                    "avatars": [
                      {
                        "id": 10000066,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayato.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000037,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ganyu.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000054,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Kokomi.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000002,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayaka.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  }
                ]
              },
              {
                "index": 2,
                "star": 3,
                "max_star": 3,
                "battles": [
                  {
                    "index": 1,
                    "timestamp": "1656683866",
                    "avatars": [
                      {
                        "id": 10000029,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Klee.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000032,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Bennett.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000023,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Xiangling.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000030,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Zhongli.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  },
                  {
                    "index": 2,
                    "timestamp": "1656683914",
                    "avatars": [
                      {
                        "id": 10000066,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayato.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000037,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ganyu.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000054,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Kokomi.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000002,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayaka.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  }
                ]
              },
              {
                "index": 3,
                "star": 3,
                "max_star": 3,
                "battles": [
                  {
                    "index": 1,
                    "timestamp": "1656683986",
                    "avatars": [
                      {
                        "id": 10000029,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Klee.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000032,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Bennett.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000023,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Xiangling.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000030,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Zhongli.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  },
                  {
                    "index": 2,
                    "timestamp": "1656684032",
                    "avatars": [
                      {
                        "id": 10000066,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayato.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000037,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ganyu.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000054,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Kokomi.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000002,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayaka.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "index": 10,
            "icon": "",
            "is_unlock": true,
            "settle_time": "0",
            "star": 9,
            "max_star": 9,
            "levels": [
              {
                "index": 1,
                "star": 3,
                "max_star": 3,
                "battles": [
                  {
                    "index": 1,
                    "timestamp": "1656684120",
                    "avatars": [
                      {
                        "id": 10000029,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Klee.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000032,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Bennett.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000023,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Xiangling.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000030,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Zhongli.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  },
                  {
                    "index": 2,
                    "timestamp": "1656684203",
                    "avatars": [
                      {
                        "id": 10000066,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayato.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000037,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ganyu.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000002,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayaka.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000054,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Kokomi.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  }
                ]
              },
              {
                "index": 2,
                "star": 3,
                "max_star": 3,
                "battles": [
                  {
                    "index": 1,
                    "timestamp": "1656684257",
                    "avatars": [
                      {
                        "id": 10000029,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Klee.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000032,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Bennett.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000023,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Xiangling.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000030,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Zhongli.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  },
                  {
                    "index": 2,
                    "timestamp": "1656684305",
                    "avatars": [
                      {
                        "id": 10000066,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayato.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000037,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ganyu.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000002,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayaka.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000054,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Kokomi.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  }
                ]
              },
              {
                "index": 3,
                "star": 3,
                "max_star": 3,
                "battles": [
                  {
                    "index": 1,
                    "timestamp": "1656684339",
                    "avatars": [
                      {
                        "id": 10000029,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Klee.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000032,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Bennett.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000023,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Xiangling.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000030,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Zhongli.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  },
                  {
                    "index": 2,
                    "timestamp": "1656684390",
                    "avatars": [
                      {
                        "id": 10000066,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayato.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000037,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ganyu.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000002,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayaka.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000054,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Kokomi.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "index": 11,
            "icon": "",
            "is_unlock": true,
            "settle_time": "0",
            "star": 9,
            "max_star": 9,
            "levels": [
              {
                "index": 1,
                "star": 3,
                "max_star": 3,
                "battles": [
                  {
                    "index": 1,
                    "timestamp": "1656684483",
                    "avatars": [
                      {
                        "id": 10000029,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Klee.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000032,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Bennett.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000023,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Xiangling.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000030,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Zhongli.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  },
                  {
                    "index": 2,
                    "timestamp": "1656684586",
                    "avatars": [
                      {
                        "id": 10000066,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayato.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000037,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ganyu.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000002,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayaka.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000054,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Kokomi.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  }
                ]
              },
              {
                "index": 2,
                "star": 3,
                "max_star": 3,
                "battles": [
                  {
                    "index": 1,
                    "timestamp": "1656684698",
                    "avatars": [
                      {
                        "id": 10000029,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Klee.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000032,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Bennett.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000023,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Xiangling.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000030,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Zhongli.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  },
                  {
                    "index": 2,
                    "timestamp": "1656684754",
                    "avatars": [
                      {
                        "id": 10000066,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayato.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000037,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ganyu.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000002,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayaka.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000054,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Kokomi.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  }
                ]
              },
              {
                "index": 3,
                "star": 3,
                "max_star": 3,
                "battles": [
                  {
                    "index": 1,
                    "timestamp": "1656684973",
                    "avatars": [
                      {
                        "id": 10000029,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Klee.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000032,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Bennett.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000023,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Xiangling.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000030,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Zhongli.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  },
                  {
                    "index": 2,
                    "timestamp": "1656685061",
                    "avatars": [
                      {
                        "id": 10000066,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayato.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000037,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ganyu.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000002,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayaka.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000054,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Kokomi.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "index": 12,
            "icon": "",
            "is_unlock": true,
            "settle_time": "0",
            "star": 9,
            "max_star": 9,
            "levels": [
              {
                "index": 1,
                "star": 3,
                "max_star": 3,
                "battles": [
                  {
                    "index": 1,
                    "timestamp": "1656685309",
                    "avatars": [
                      {
                        "id": 10000066,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayato.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000037,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ganyu.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000002,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayaka.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000054,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Kokomi.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  },
                  {
                    "index": 2,
                    "timestamp": "1656685422",
                    "avatars": [
                      {
                        "id": 10000029,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Klee.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000032,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Bennett.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000023,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Xiangling.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000030,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Zhongli.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  }
                ]
              },
              {
                "index": 2,
                "star": 3,
                "max_star": 3,
                "battles": [
                  {
                    "index": 1,
                    "timestamp": "1656687676",
                    "avatars": [
                      {
                        "id": 10000029,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Klee.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000032,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Bennett.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000023,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Xiangling.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000034,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Noel.png",
                        "level": 90,
                        "rarity": 4
                      }
                    ]
                  },
                  {
                    "index": 2,
                    "timestamp": "1656687763",
                    "avatars": [
                      {
                        "id": 10000030,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Zhongli.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000063,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Shenhe.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000002,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayaka.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000049,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Yoimiya.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  }
                ]
              },
              {
                "index": 3,
                "star": 3,
                "max_star": 3,
                "battles": [
                  {
                    "index": 1,
                    "timestamp": "1656689665",
                    "avatars": [
                      {
                        "id": 10000029,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Klee.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000032,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Bennett.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000023,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Xiangling.png",
                        "level": 90,
                        "rarity": 4
                      },
                      {
                        "id": 10000041,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Mona.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  },
                  {
                    "index": 2,
                    "timestamp": "1656689713",
                    "avatars": [
                      {
                        "id": 10000030,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Zhongli.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000063,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Shenhe.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000002,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayaka.png",
                        "level": 90,
                        "rarity": 5
                      },
                      {
                        "id": 10000049,
                        "icon": "https://upload-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Yoimiya.png",
                        "level": 90,
                        "rarity": 5
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ],
        "total_star": 36,
        "is_unlock": true
      }
    }
  ]
}
</code></pre>
</details>

**Comment by Mark9804** [comment]
有数据，判断写错了，等一下

**Comment by Mark9804** [comment]
@Arondight 

```js
lodash.first([1,2,3]) // === lodash.head([1,2,3])

lodash.hasIn(lodash.first([1,2,3]), "key")
lodash.hasIn([1,2,3], "[0].key") // 错误的写法
```
https://www.lodashjs.com/docs/lodash.head#_headarray

**Comment by Mark9804** [comment]
搞错了，写法可以，层级少了一层导致的找不到对应键值对
