### ISSUE TITLE
更新之后图片变为表情形式发送

### ISSUE THREAD

**Issue by Xm798** [Arondight/Adachi-BOT#88]
更新之后貌似图片使用动画表情的形式发送了？有点小，不太清楚。
![54D423CE16E06424D2B3028E86151567](https://user-images.githubusercontent.com/48074861/132883242-b95a84ac-11b0-4137-83c2-ac14a3b650c7.jpg)

**Comment by Arondight** [comment]
https://github.com/takayama-lily/oicq/issues/217

**Comment by Arondight** [comment]
#95
