### ISSUE TITLE
更新描述文件生成脚本

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#880]
### 问题描述

当前是个爬内鬼网的爬虫，但是内鬼网大改了，xpath 都失效了，改成一个根据安柏 api 的 json 生成，也不用爬虫了，速度也上去了。

https://api.ambr.top/v2/chs/weapon
https://api.ambr.top/v2/CHS/weapon/11417
https://api.ambr.top/v2/static/weaponCurve
https://api.ambr.top/v2/CHS/manualWeapon

https://api.ambr.top/v2/chs/avatar
https://api.ambr.top/v2/chs/avatar/10000069
https://api.ambr.top/v2/static/avatarCurve

https://api.ambr.top/v2/CHS/material/
https://api.ambr.top/v2/CHS/material/113036

### 当前提交

```Text
？
```

**Comment by Mark9804** [comment]
材料当中有一个稀有度等级字段 `rank` ，这个到时候也抓下来吧，背景我直接合成，不用等 bwiki 那边出了

**Comment by BTMuli** [comment]
~~到时候全部素材给翻新一遍~~

**Comment by Mark9804** [comment]
> ~到时候全部素材给翻新一遍~

不用，上层图像会把下层背景给覆盖掉的

**Comment by Arondight** [comment]
Duplicate of #885

**Comment by Mark9804** [comment]
老大哥，你还有什么要补充 commit 的吗，没有的话我感觉可以 merge 了

**Comment by Arondight** [comment]
> 有什么要补充 commit 的吗

没有，剩下的问题以后修，这几天没时间，赶项目
