### ISSUE TITLE
提纳里卡池卡片不显示元素

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#881]
这个是哪里出问题了
![-52cc5513ff334d5b.jpg](https://user-images.githubusercontent.com/72692909/184529296-dca8184c-13c4-4e85-8360-68a31bb59be9.jpg)

_Originally posted by @BTMuli in https://github.com/Arondight/Adachi-BOT/issues/843#issuecomment-1214312578_

**Comment by Mark9804** [comment]
哦不用看了，没有草元素图标

**Comment by Mark9804** [comment]
> 没有草元素图标

有，再看看
<img width="132" alt="image" src="https://user-images.githubusercontent.com/9006264/184529782-47bafce2-8743-4b90-a11c-c7e52b169063.png">

**Comment by Mark9804** [comment]
<img width="487" alt="image" src="https://user-images.githubusercontent.com/9006264/184529841-a77378cf-ca83-431e-8593-3b7e5230c73f.png">

元素类型返回了个 undefined

**Comment by Arondight** [comment]
我想直接把两个上游的配置文件剔除掉，不再依赖上游了

**Comment by Arondight** [comment]
娜乌·巴格·海思·菲克斯得
