### ISSUE TITLE
竭泽（弓）的描述大概是错了

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#889]
为什么会出现细剑

<img width="501" alt="image" src="https://user-images.githubusercontent.com/9006264/184800734-30ecbf84-3766-4a93-85ea-62e7e8c32297.png">

**Comment by BTMuli** [comment]
我的错，当时创建 json 内容直接拿的某个单手剑替换的o(TヘTo)

**Comment by Mark9804** [comment]
那就这样吧，等正式描述出来再说

**Comment by BTMuli** [comment]
前导页有描述，已经修复了 https://github.com/Arondight/Adachi-BOT/pull/890

**Comment by BTMuli** [comment]
下面突破材料第四个跟第五个顺序反了，上面突破材料背景全是紫的 https://github.com/Arondight/Adachi-BOT/commit/63e7223a850ba8b2ac72fd1f1c07046ddc6fe111

**Comment by Mark9804** [comment]
> 突破材料背景全是紫的

因为现在的材料名字在材料列表中找不到，紫色是 fallback

> 突破材料第四个跟第五个顺序反了

啊这，我今天早八到晚五，帮忙改一下吧

**Comment by BTMuli** [comment]
改了 https://github.com/Arondight/Adachi-BOT/pull/894
