### ISSUE TITLE
macOS 协议提示当前QQ版本过低，iPad 协议被识别为非官方客户端

### ISSUE THREAD

**Issue by citydirector** [Arondight/Adachi-BOT#901]
### 问题描述

![image](https://user-images.githubusercontent.com/45933075/186187076-86bb9815-ac08-4c56-863c-d590bcb8adec.png)

### 复现流程

模拟设备使用iMac

### 运行环境

```Text
操作系统：linux（Ubuntu）
内核版本：5.15.0-43-generic
内核架构：x64
处理器：  0.66%（AMD EPYC 7K62 48-Core Processor @ 2.6Ghz）
启动时间：25 days
内存使用：27.41%（1.13 GB / 4.12 GB）
数据占用：2.18 MB
Node.js： 18.1.0
npm：     8.17.0
浏览器：  Chromium 105.0.5173.0
```

### 当前提交

```Text
commit cb6f88b32ccb4aae698b1a202fd08fea94e383c9
```

### 代码状态

```Text
On branch master
```

**Comment by citydirector** [comment]
本来是这边用imac，gocqhttp那边用ipad的；现在临时的解决办法是这边用ipad，gocqhttp那边用imac

**Comment by Mark9804** [comment]
emmm，最近我看到 oicq 群里面确实有说当前版本可能跟不上风控逻辑，但是好像还都是个例，这个得等上游更新了

**Comment by citydirector** [comment]
ma耶，换了ipad之后连续(两次)被冻结账号，理由是使用非官方QQ，一登录就冻结，不能用这个了

**Comment by Mark9804** [comment]
？

这么说确实有这个情况？

有没有登陆日志，我上报给 oicq 那边

**Comment by citydirector** [comment]
我翻了翻bot-out.log，应该没什么帮助

**Comment by citydirector** [comment]
![image](https://user-images.githubusercontent.com/45933075/186234813-7391348b-21c0-4a65-8c93-31f12e96eeaf.png)

**Comment by Mark9804** [comment]
感谢，我看看上游有什么能做的

目前我知道的情况是假如退出重新登录的话会被弹出来，但是我自己是没复现

**Comment by Mark9804** [comment]
> ma耶，(模拟设备)换了ipad之后连续(两次)被冻结账号，理由是使用非官方QQ，一登录就冻结，不能用这个(ipad)了

你的这个问题我最近翻了一下，这不是新的风控类型，一年前就有人提出来了

https://github.com/mamoe/mirai/issues/1461

https://github.com/takayama-lily/oicq/discussions/243

最近 [oicq issues](https://github.com/takayama-lily/oicq/issues) 那边新增了三个报告（其中一个是我的），但是没有更多的人复现，目前只能等上游更新一遍协议看看情况

**Comment by Mark9804** [comment]
> 使用iMac

上游预计最近几天会更新

**Comment by xiaofeicn** [comment]
这个修复了吗

**Comment by Mark9804** [comment]
> 这个修复了吗

上游还没有发布新版本

**Comment by Arondight** [comment]
话说我一直用的 ipad 协议好像没啥问题

**Comment by Mark9804** [comment]
呃，看来上游是开摆了，提供一个临时 patch

在 bot 根目录下，运行以下内容

```bash
sed -i 's/537064315/537128930/' node_modules/oicq/lib/core/device.js
```

这个会同步 mac QQ 的协议设备 ID 到最新版本客户端

**Comment by Mark9804** [comment]
卧槽我也寄了

**Comment by Arondight** [comment]
Duplicate of https://github.com/takayama-lily/oicq/issues/408

**Comment by Mark9804** [comment]
我活过来了

https://gist.github.com/Mark9804/807eef4ebaf31ba4c43da9528a633968

**Comment by chongdong12** [comment]
> 我活过来了
> 
> https://gist.github.com/Mark9804/807eef4ebaf31ba4c43da9528a633968

请问这个问题解决了吗？我也遇到了这个问题，应该怎么处理呢？
![image](https://user-images.githubusercontent.com/95455587/199070227-aedc76a0-8d64-4345-9168-3482b99ce511.png)

**Comment by Mark9804** [comment]
QQ 版本过低的原因是 tx 升级了协议，多了一个字段，所以必须 oicq 库发布新的协议才能解决这个问题。

我上面那个脚本或许可以解，原理是把所有的信息随机化，不再用 `OICQX` 和 `MIRAI` 字段跳脸。

把这个脚本复制到项目根目录，用 node 跑一遍，然后用控制台里面生成的信息覆盖掉 `data/你的QQ号/device.json` 里面的信息。或许能登陆，但是不保证成功，oicq 群里也有改了好几遍登不上的

**Comment by chongdong12** [comment]
> QQ 版本过低的原因是 tx 升级了协议，多了一个字段，所以必须 oicq 库发布新的协议才能解决这个问题。
> 
> 我上面那个脚本或许可以解，原理是把所有的信息随机化，不再用 `OICQX` 和 `MIRAI` 字段跳脸。
> 
> 把这个脚本复制到项目根目录，用 node 跑一遍，然后用控制台里面生成的信息覆盖掉 `data/你的QQ号/device.json` 里面的信息。或许能登陆，但是不保证成功，oicq 群里也有改了好几遍登不上的

测试一下确实可以登录了，非常感谢！

**Comment by Arondight** [comment]
> 多了一个字段，所以必须 oicq 库发布新的协议才能解决这个问题

我扒了一下 mirai 没发现有协议改动呢
