### ISSUE TITLE
更新到新版本后启动卡在  浏览器：正在从 /usr/lib64/chromium-browser/chromium-browser 拉起实例。

### ISSUE THREAD

**Issue by shanananana** [Arondight/Adachi-BOT#915]
### 问题描述

直接启动就卡在 浏览器：正在从 /usr/lib64/chromium-browser/chromium-browser 拉起实例。

### 复现流程

直接启动

### 后台日志

```Text
0|bot      | app.js:
0|bot      | app.js:                █████                    █████       ███             █████               █████
0|bot      | app.js:               ░░███                    ░░███       ░░░             ░░███               ░░███
0|bot      | app.js:   ██████    ███████   ██████    ██████  ░███████   ████             ░███████   ██████  ███████
0|bot      | app.js:  ░░░░░███  ███░░███  ░░░░░███  ███░░███ ░███░░███ ░░███  ██████████ ░███░░███ ███░░███░░░███░
0|bot      | app.js:   ███████ ░███ ░███   ███████ ░███ ░░░  ░███ ░███  ░███ ░░░░░░░░░░  ░███ ░███░███ ░███  ░███
0|bot      | app.js:  ███░░███ ░███ ░███  ███░░███ ░███  ███ ░███ ░███  ░███             ░███ ░███░███ ░███  ░███ ███
0|bot      | app.js: ░░████████░░████████░░████████░░██████  ████ █████ █████            ████████ ░░██████   ░░█████
0|bot      | app.js:  ░░░░░░░░  ░░░░░░░░  ░░░░░░░░  ░░░░░░  ░░░░ ░░░░░ ░░░░░            ░░░░░░░░   ░░░░░░     ░░░░░
0|bot      | app.js:
0|bot      | app.js:
0|bot      | app.js:
0|bot      | app.js:                    项目主页：https://github.com/Arondight/Adachi-BOT
0|bot      | app.js:
0|bot      | app.js: 正在从 /Adachi-BOT/server.js 拉起文件服务器。
0|bot      | app.js: 正在从 /Adachi-BOT/bot.js 拉起机器人。
0|bot      | [2022-09-03T14:11:01.060] [MARK] [aPad:1746056731] - ----------
0|bot      | [2022-09-03T14:11:01.062] [MARK] [aPad:1746056731] - Package Version: oicq@2.3.1 (Released on 2022/6/21)
0|bot      | [2022-09-03T14:11:01.062] [MARK] [aPad:1746056731] - View Changelogs：https://github.com/takayama-lily/oicq/releases
0|bot      | [2022-09-03T14:11:01.063] [MARK] [aPad:1746056731] - ----------
0|bot      | [2022-09-03T14:11:01.064] [DEBUG] [aPad:1746056731] - 配置：加载了 1 条 Cookie 。
0|bot      | [2022-09-03T14:11:01.064] [DEBUG] [aPad:1746056731] - 配置：登录账号 1746056731 。
0|bot      | [2022-09-03T14:11:01.064] [DEBUG] [aPad:1746056731] - 配置：管理者已设置为 595759874 。
0|bot      | [2022-09-03T14:11:01.065] [DEBUG] [aPad:1746056731] - 配置：所有的消息都将被视为命令。
0|bot      | [2022-09-03T14:11:01.065] [DEBUG] [aPad:1746056731] - 配置：允许用户 @ 机器人。
0|bot      | [2022-09-03T14:11:01.066] [DEBUG] [aPad:1746056731] - 配置：群回复将会 @ 用户。
0|bot      | [2022-09-03T14:11:01.066] [DEBUG] [aPad:1746056731] - 配置：群消息复读的概率为 0.25% 。
0|bot      | [2022-09-03T14:11:01.067] [DEBUG] [aPad:1746056731] - 配置：上线不发送群通知。
0|bot      | [2022-09-03T14:11:01.067] [DEBUG] [aPad:1746056731] - 配置：不向新群友问好。
0|bot      | [2022-09-03T14:11:01.067] [DEBUG] [aPad:1746056731] - 配置：不向新好友问好。
0|bot      | [2022-09-03T14:11:01.068] [DEBUG] [aPad:1746056731] - 配置：不推送米游社新闻。
0|bot      | [2022-09-03T14:11:01.068] [DEBUG] [aPad:1746056731] - 配置：米游社新闻推送类型为 空。
0|bot      | [2022-09-03T14:11:01.068] [DEBUG] [aPad:1746056731] - 配置：角色查询不更新玩家信息。
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：耗时操作前不发送提示。
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：用户每隔 0 秒可以使用一次机器人。
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：不尝试撤回机器人发送的群消息
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：广播中消息间时延 0.00 秒。
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：深渊记录将缓存 1 小时。
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：玩家信息将缓存 1 小时。
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：清理数据库 aby 中超过 1 小时的记录。
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：清理数据库 info 中超过 168 小时的记录。
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：不使用前端调试模式。
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：不保存图片。
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：默认打开权限 artifact_auth 。
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：默认打开权限 character_overview_auth 。
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：默认打开权限 feedback_auth 。
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：默认打开权限 fun_auth 。
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：默认打开权限 gacha_auth 。
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：默认打开权限 music_auth 。
0|bot      | [2022-09-03T14:11:01.069] [DEBUG] [aPad:1746056731] - 配置：默认打开权限 rating_auth 。
0|bot      | [2022-09-03T14:11:01.070] [DEBUG] [aPad:1746056731] - 配置：默认打开权限 mys_news_auth 。
0|bot      | [2022-09-03T14:11:01.070] [DEBUG] [aPad:1746056731] - 配置：默认打开权限 qa_auth 。
0|bot      | [2022-09-03T14:11:01.070] [DEBUG] [aPad:1746056731] - 配置：默认打开权限 reply_auth 。
0|bot      | [2022-09-03T14:11:01.070] [DEBUG] [aPad:1746056731] - 配置：默认打开权限 query_gameinfo_auth 。
0|bot      | [2022-09-03T14:11:01.075] [DEBUG] [aPad:1746056731] - 浏览器：正在从 /usr/lib64/chromium-browser/chromium-browser 拉起实例。
```

### 运行环境

```Text
操作系统：linux（Fedora）
内核版本：5.6.13-100.fc30.x86_64
内核架构：x64
处理器：  7.01%（Intel Xeon® Gold 6161 @ 2.2Ghz）
启动时间：23 minutes
内存使用：77.15%（1.6 GB / 2.08 GB）
数据占用：236 kB
Node.js： 16.15.1
npm：     8.11.0
浏览器：  Chromium 81.0.4044.138 Fedora Project
```

### 当前提交

```Text
commit ccddd8e4dcb3a8faebc7c94d808aedcf57980778 (HEAD -> master, origin/master, origin/dev, origin/HEAD)
Author: github-actions <github-actions@github.com>
Date:   Fri Sep 2 22:22:22 2022 +0000

    Update Node.js modules
```

### 代码状态

```Text
(base) [root@snnnn1998 Adachi-BOT]# git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by shanananana** [comment]
![image](https://user-images.githubusercontent.com/39590172/188258564-cf1bec03-51fc-4e8f-8f54-5e9e37b9bd3d.png)
路径正常

**Comment by Arondight** [comment]
我对此一无所知，建议重启一下机器看看，一般是内存太小了，没拉起来，另外建议系统分一个 swap 文件挂上去

**Comment by shanananana** [comment]
![image](https://user-images.githubusercontent.com/39590172/188456867-87516876-e4ac-4f62-a36c-55a47d44041e.png)
重启后还是无法启动。free看内存有1.5g可用了。并且reset到较老版本项目是可以正常启动的。我不太理解分一个swap文件挂上去是什么意思

**Comment by shanananana** [comment]
尝试再renderOpen方法里加了些log。看下是否有帮助。可以看到走到了if的分支里。但是在执行puppeteer.launch时阻塞了。不太懂python。这个好像是三方库的函数？
![image](https://user-images.githubusercontent.com/39590172/188459855-cb719cb9-cbdc-4d30-a432-d2838aba8c35.png)
![image](https://user-images.githubusercontent.com/39590172/188459915-5befd557-4fbf-4697-9cbe-e81458e064e4.png)

**Comment by Mark9804** [comment]
> 并且reset到较老版本项目是可以正常启动的

这个可以正常启动的参数是什么样的？

**Comment by shanananana** [comment]
git reset --hard $commitId 。我不太能找到某一次commit导致的不可启动。因为太繁琐了
。不过可以确定某个commit之前一定是可用的。我去尝试一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Arondight/Adachi-BOT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 晚上10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Arondight/Adachi-BOT] 更新到新版本后启动卡在  浏览器：正在从 /usr/lib64/chromium-browser/chromium-browser 拉起实例。 (Issue #915)





  
并且reset到较老版本项目是可以正常启动的
  
这个可以正常启动的参数是什么样的？

**Comment by Mark9804** [comment]
启动参数是六个月前更改的 https://github.com/Arondight/Adachi-BOT/commit/8f992610b6c8f9434b2a88a0ec0e448acc027db6

尝试一下回滚到 https://github.com/Arondight/Adachi-BOT/commit/de3ab1dd41026ea3d36b9897e5197657db0b1c6b

如果可用，再把 puppeteer 升级上来看看（只升级 puppeteer）

**Comment by shanananana** [comment]
尝试了几个版本
de3able不可用。cf9635d10581a5746e66904575f3ef3e290fa14e（2022年4.16不可用）
c4536dff91ccee8cd544a0b9f356a6b8c8783ac9 2.28不可用
1aacf052ea29ecd63528bba3cc765926a021c312 可用（2.16最后一次commit）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Arondight/Adachi-BOT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 晚上10:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Arondight/Adachi-BOT] 更新到新版本后启动卡在  浏览器：正在从 /usr/lib64/chromium-browser/chromium-browser 拉起实例。 (Issue #915)





 
启动参数是六个月前更改的 8f99261
 
尝试一下回滚到 de3ab1d
 
如果可用，再把 puppeteer 升级上来看看（只升级 puppeteer）

**Comment by shanananana** [comment]
现在已经可以确定是这其中的一次commit导致的。使用2.19最后一次commit是可以运行成功的，但是2.21最后一次commit失败了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Arondight/Adachi-BOT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 晚上10:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Arondight/Adachi-BOT] 更新到新版本后启动卡在  浏览器：正在从 /usr/lib64/chromium-browser/chromium-browser 拉起实例。 (Issue #915)





 
启动参数是六个月前更改的 8f99261
 
尝试一下回滚到 de3ab1d
 
如果可用，再把 puppeteer 升级上来看看（只升级 puppeteer）

**Comment by shanananana** [comment]
![image](https://user-images.githubusercontent.com/39590172/188477235-ca40fa7a-2308-4276-abff-1e0304f8b661.png)
已确定是此次commit导致的错误 16119bc8593510e22a39b4710af0c71a9798aeaf

**Comment by Mark9804** [comment]
emmm，那还是等于不可用，因为 16119bc 的逻辑就是“假如拉起浏览器失败，则不执行后续操作”；
在 16119bc 之前，浏览器有没有拉起来和主线程没有关系，就算拉起失败了照样会执行登陆，提供部分功能

现在理论上你的任何绘图功能（`米游社`，`今日素材`等等）还是不能用的，因为浏览器没有成功启动

既然已经确定过不是启动参数导致的 puppeteer 运行不正常，你可以尝试一下假如你自己调用 chromium 的话能不能正常使用，如果依然不能的话你可能需要换一个 chromium 源（不要用第三方之类奇奇怪怪的源，之前有人遇到过用了第三方源结果出了奇怪的 bug）重新测试一遍

如果 chromium 可以启动的话，再来跟进一下

**Comment by shanananana** [comment]
@Mark9804 这个chromium 之前使用过米游社,深渊,今日素材等功能。但我很久不更新版本。忘记可用的commit了。
![image](https://user-images.githubusercontent.com/39590172/188480973-954f66c0-4196-49f0-8193-db8196c94bc8.png)

**Comment by Mark9804** [comment]
我看了一下浏览器相关的代码，这六个月以来唯一的改动是 https://github.com/Arondight/Adachi-BOT/commit/1c45d1bfc626749cfc7c6af87a28c626dc67c8d5 by @Arondight 

可能和 use strict 有关系？有点玄学，我猜的

**Comment by shanananana** [comment]
python代码看不太懂。但是我的qq号因为刚刚频繁在海外机器上登录被风控了（悲）。
这个现象好像仅出现在我这里。其他用户没有出现。可能和代码关系不太大。可能是某些奇怪的环境问题。等等把。说不定睡一觉明天就好了。或者下次想着搭一个机器人的时候就好了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Arondight/Adachi-BOT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 晚上11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Arondight/Adachi-BOT] 更新到新版本后启动卡在  浏览器：正在从 /usr/lib64/chromium-browser/chromium-browser 拉起实例。 (Issue #915)





 
我看了一下浏览器相关的代码，这六个月以来唯一的改动是 1c45d1b by @Arondight
 
可能和 use strict 有关系？有点玄学，我猜的

**Comment by Mark9804** [comment]
实在复现不出来，更新一下 chromium 看看呢，树莓派的版本都到 chromium 101 了

**Comment by Arondight** [comment]
我刚刚在 windows 下遇到了这个问题，启动的无头浏览器 bot 退出的时候没有杀掉，下次启动就卡在拉无头起来，任务管理器杀掉 chrome 进程，就不会卡住了

**Comment by Arondight** [comment]
@shanananana 所以你重启一下机器看看是不是会好，重启比较直截了当

**Comment by shanananana** [comment]
@Arondight 
![image](https://user-images.githubusercontent.com/39590172/188906170-45f353ea-7769-4e43-ab23-cbae8aa607e1.png)
没有chrome进程。不过我还是重启下试试

**Comment by shanananana** [comment]
已重启 还是卡在拉浏览器那一步。。

**Comment by shanananana** [comment]
![image](https://user-images.githubusercontent.com/39590172/188907976-dd31fdc5-1bfe-4d60-a768-f7eb85d61f3e.png)

**Comment by Arondight** [comment]
> @Arondight ![image](https://user-images.githubusercontent.com/39590172/188906170-45f353ea-7769-4e43-ab23-cbae8aa607e1.png) 没有chrome进程。

```shell
ps -aux | grep chrom
```

**Comment by shanananana** [comment]
@Arondight 如果需要的话 我可以提供服务器地址和密码供排查问题

**Comment by Arondight** [comment]
![图片](https://user-images.githubusercontent.com/13673702/188909831-e66b190a-aed7-4f4b-98bf-2577dbea4233.png)

**Comment by shanananana** [comment]
![image](https://user-images.githubusercontent.com/39590172/188910729-b9f97a48-d2bc-4b84-8f79-56059ddd820a.png)
![image](https://user-images.githubusercontent.com/39590172/188910771-3db8f426-5a74-4294-878d-c5b7372073d8.png)
没有

**Comment by Arondight** [comment]
你先把 https://github.com/Arondight/Adachi-BOT/blob/77fd56362fbeab3be14a977b5bd7a3839ae8946f/src/utils/render.js 拿去用吧，不好查了，最后记得加两行

```js
export async function renderOpen() {}
export const renderPath = "??";
```

**Comment by shanananana** [comment]
这是没有拉起来就跳过。不影响启动。只是相关功能不可用。还有其他改动吗

**Comment by Arondight** [comment]
> 这是没有拉起来就跳过。不影响启动。只是相关功能不可用。还有其他改动吗

没了，你不是说之前这个提交能发图的么

**Comment by shanananana** [comment]
![image](https://user-images.githubusercontent.com/39590172/188917361-f53d240a-5de8-470c-9e5f-2f3056b602be.png)
![image](https://user-images.githubusercontent.com/39590172/188917463-2c014f0f-1dc5-46be-adec-2c8bbd48bd7e.png)
它又坏掉了

**Comment by shanananana** [comment]
看log是拿到数据了 画图的时候没画出来

**Comment by shanananana** [comment]
不知道为什么我感觉换一个服务器重装可以解决

**Comment by Arondight** [comment]
> 不知道为什么我感觉换一个服务器重装可以解决

那大概是你的环境变了，而不是仓库代码变了引起的这个问题

```shell
lspci | grep -i vga
/usr/lib64/chromium-browser/chromium-browser --version
/usr/lib64/chromium-browser/chromium-browser --headless --remote-debugging-port=9222 https://baidu.com
```

**Comment by shanananana** [comment]
![image](https://user-images.githubusercontent.com/39590172/188925589-d183125c-16b4-4146-b77f-8d015337a1ee.png)
Failed to send GpuChannelMsg_CreateCommandBuffer.
![image](https://user-images.githubusercontent.com/39590172/188925880-014c4507-2e2c-4a51-8a9e-391cbe6e022d.png)

**Comment by Arondight** [comment]
升级一下版本吧，cs8 都到了 104 了

**Comment by shanananana** [comment]
这个之前改了bot拉浏览器启动参数dumpio:true后。打出过相同错误。网上查了不少内容。也没有解决

**Comment by Mark9804** [comment]
我感觉我们的代码应该是没有问题的，puppeteer 也没有问题，那么有可能是你的 chromium 实在是太旧了，可能有一些功能没有正式支持

**Comment by shanananana** [comment]
![image](https://user-images.githubusercontent.com/39590172/188928158-44388921-23ef-4c66-b602-c11d19eedf33.png)
我也怀疑是环境问题。正在尝试更新chrome。但是我不会更新chrome..

**Comment by Mark9804** [comment]
fedora 不太了解，大概是有提供官方 chromium 安装源的吧

**Comment by Arondight** [comment]
yum update chromium

**Comment by Mark9804** [comment]
还有你这个既然能连接 google 了，干脆就让 puppeteer 自己下一个 chromium 好了

**Comment by shanananana** [comment]
![image](https://user-images.githubusercontent.com/39590172/188929162-c0d37547-1c21-40c7-bdbb-b9d1a37da21c.png)

**Comment by Arondight** [comment]
> yum install epel-release
> 
> yum update chromium

粘贴复制一下

**Comment by shanananana** [comment]
![image](https://user-images.githubusercontent.com/39590172/188929524-cfe77858-8e73-484b-9640-9615a65b6c3f.png)

**Comment by shanananana** [comment]
真的不太熟yum。。我去查查

**Comment by shanananana** [comment]
我直接把 /usr/lib64/chromium-browser/chromium-browser 目录在的chrome 删除掉。puppeteer 会自己帮我下载吗？需修改其他配置吗？

**Comment by Arondight** [comment]
> 我直接把 /usr/lib64/chromium-browser/chromium-browser 目录在的chrome 删除掉。puppeteer 会自己帮我下载吗？需修改其他配置吗？

明天或者后天我上去操作一下吧，我要睡了，今天休班，明天估计没空

**Comment by shanananana** [comment]
好的 十分感谢！！！！

**Comment by Arondight** [comment]
@shanananana 服务器挨批密码发我邮箱，我晚上上去给你升级一下浏览器，记得告诉我 bot 在哪

**Comment by shanananana** [comment]
之前用的CentOS 。装另一个bot的时候需要依赖高版本glibc 。自己升级后出了很多问题比如ssh不上。就尝试了官方提供的其他系统镜像。发现了这个镜像的glibc版本符合要求。就用了这个系统了。总是十分感谢！！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Arondight/Adachi-BOT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月8日(星期四) 晚上9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Arondight/Adachi-BOT] 更新到新版本后启动卡在  浏览器：正在从 /usr/lib64/chromium-browser/chromium-browser 拉起实例。 (Issue #915)





 
@shanananana 升了一下浏览器就好了，几分钟就行，另外你的操作系统该换了，以后尽量别用 Fedora ，用 CentOS Stream
 {   "操作系统": "linux（Fedora）",   "内核版本": "5.6.13-100.fc30.x86_64",   "内核架构": "x64",   "处理器": "1.02%（Intel Xeon® Gold 6161 @ 2.2Ghz）",   "启动时间": "2 hours",   "内存使用": "26.29%（546 MB / 2.08 GB）",   "数据占用": "535 kB",   "Node.js": "16.15.1",   "npm": "8.11.0",   "浏览器": "Chromium 107.0.5289.0" }

**Comment by shanananana** [comment]
浏览器版本问题，更新浏览器版本即可成功。关闭issue

**Comment by Arondight** [comment]
不用谢，顺手送你两条命令用来更新浏览器

```shell
ver=$(curl -sSL "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2FLAST_CHANGE?alt=media")
curl "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F${ver}%2Fchrome-linux.zip?alt=media" -o ./chromium.zip
```

**Comment by Arondight** [comment]
> 之前用的CentOS

centos stream 和 centos 是两个系统 https://www.centos.org/centos-stream/

**Comment by shanananana** [comment]
看了一下 我不会(摊手)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Arondight/Adachi-BOT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月8日(星期四) 晚上9:55
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Arondight/Adachi-BOT] 更新到新版本后启动卡在  浏览器：正在从 /usr/lib64/chromium-browser/chromium-browser 拉起实例。 (Issue #915)





  
之前用的CentOS
  
centos stream 和 centos 是两个系统 https://www.centos.org/centos-stream/

**Comment by Mark9804** [comment]
所以最后就是浏览器版本过旧的问题？

需不需要加入 chromium 版本检测，低于 `98.x` 抛一个异常出来

**Comment by shanananana** [comment]
大概率是这个原因。
不能现象不能完全说明是浏览器版本过旧问题。
也可能是我的chrome源本来就有问题。或许换一个旧版本的chrome也可能可以运行。
建议观望一段时间。避免影响了(可能存在的)可以正常使用的旧版chrome用户。不过可以加一个10s没拉起浏览器。检测下版本。如果低于x版本。打一个log提示去更新版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Arondight/Adachi-BOT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月8日(星期四) 晚上10:47
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Arondight/Adachi-BOT] 更新到新版本后启动卡在  浏览器：正在从 /usr/lib64/chromium-browser/chromium-browser 拉起实例。 (Issue #915)





 
所以最后就是浏览器版本过旧的问题？
 
需不需要加入 chromium 版本检测，低于 98.x 抛一个异常出来

**Comment by shanananana** [comment]
已经确定是这次commit导致的&nbsp;16119bc8593510e22a39b4710af0c71a9798aeaf
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Arondight/Adachi-BOT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 晚上10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Arondight/Adachi-BOT] 更新到新版本后启动卡在  浏览器：正在从 /usr/lib64/chromium-browser/chromium-browser 拉起实例。 (Issue #915)





  
并且reset到较老版本项目是可以正常启动的
  
这个可以正常启动的参数是什么样的？

**Comment by shanananana** [comment]
十分感谢 我试一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月7日(周三) 晚上10:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Arondight/Adachi-BOT] 更新到新版本后启动卡在  浏览器：正在从 /usr/lib64/chromium-browser/chromium-browser 拉起实例。 (Issue #915)

**Comment by shanananana** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Arondight/Adachi-BOT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月8日(星期四) 晚上9:53
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Arondight/Adachi-BOT] 更新到新版本后启动卡在  浏览器：正在从 /usr/lib64/chromium-browser/chromium-browser 拉起实例。 (Issue #915)





 
不用谢，顺手送你两条命令用来更新浏览器
 ver=$(curl -sSL "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2FLAST_CHANGE?alt=media") curl "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F${ver}%2Fchrome-linux.zip?alt=media" -o ./chromium.zip

**Comment by shanananana** [comment]
今晚下班早的话就去试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月6日(周二) 中午11:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Arondight/Adachi-BOT] 更新到新版本后启动卡在  浏览器：正在从 /usr/lib64/chromium-browser/chromium-browser 拉起实例。 (Issue #915)
