### ISSUE TITLE
`信息` 查找不到任何角色和武器

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#919]
查了一下，`m_NAMES` 变量只有两个，好像没有被正确调用

<img width="571" alt="image" src="https://user-images.githubusercontent.com/9006264/188826422-d8126942-620e-4f76-9631-9b0aa536ba36.png">

看上去好像是插件配置没改过来
https://github.com/Arondight/Adachi-BOT/blob/9b4fb196cc25d0ab24682c349069277d72b995ed/src/plugins/overview/info.js#L26-L28

我的 dev 分支查不到角色和武器信息，老大哥那边行不行
<img width="575" alt="image" src="https://user-images.githubusercontent.com/9006264/188775846-6841d176-dd4a-4ec0-b5d6-2cfac1db4de2.png">

_Originally posted by @Mark9804 in https://github.com/Arondight/Adachi-BOT/issues/885#issuecomment-1238840251_

**Comment by Mark9804** [comment]
我懂了，没找到资源文件
![image](https://user-images.githubusercontent.com/9006264/188839986-e3b75e0f-72a8-4871-9eca-b2bbddf1dffb.jpeg)

**Comment by Arondight** [comment]
呃，忘了改了
