### ISSUE TITLE
问答功能给命令传递数据

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#925]
### 问题描述

{{TEXT}}传递丘丘消息
{{ID}}传递发送者id
{{NICK}}昵称

用法：reply: echo 我听到{{NICK}}刚才说了{{TEXT}}

### 当前提交

```Text
忘了
```

**Comment by Arondight** [comment]
这样问答功能可以做到的事情就更多了，例如

1. 看看系统服务的状态，并重启某一些系统服务
2. 把聊天信息中的 cookie 写到配置文件，然后重启签到程序实现签到

**Comment by Arondight** [comment]
作为环境变量或许更好

**Comment by Mark9804** [comment]
我上一个评论里面想加入热更主要是有热更兑换码的需求，不过能传递数据的话应该也能实现
<img src="https://user-images.githubusercontent.com/9006264/189076842-f4876610-4ede-4e54-a6a1-b58ec7bc6d06.jpeg" width="320" />

**Comment by Arondight** [comment]
```

+-----------+----------------+
|   环境变量    |        含义      |
+-----------+----------------+
| USER_ID   |    用户的 QQ 号    |
| USER_NAME |  用户的 QQ 昵称     |
| MSG_TEXT  |   触发此问答功能的聊天信息 |
+-----------+----------------+

```
