### ISSUE TITLE
这图怎么看都是被拉伸过了吧

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#926]
![image](https://user-images.githubusercontent.com/9006264/189267566-40157c3d-27b6-4aea-915c-27ba5baf4e50.jpeg)

**Comment by Mark9804** [comment]
@Arondight 老大哥，你 resize 图片的时候直接拉伸了，实际上是要用空白像素填满不足的空间的

**Comment by Mark9804** [comment]
只能重新扒一遍图了，前端对于错误的图片无能为力

**Comment by Arondight** [comment]
> @Arondight 老大哥，你 resize 图片的时候直接拉伸了，实际上是要用空白像素填满不足的空间的

这样啊，理解错了

**Comment by Arondight** [comment]
晚上再搞吧，我改改脚本把角色武器重新拉一遍

**Comment by Mark9804** [comment]
我在搞了

**Comment by Arondight** [comment]
> 我在搞了

把 -c 的逻辑单独列出来，裁剪和缩放分开

**Comment by Arondight** [comment]
一个是 info.js ，一个是 resize.js

**Comment by Mark9804** [comment]
呃，我刚刚发现角色图好像不需要 resize 也能自己缩放，武器有点问题，到时候看一下

角色不需要 resize 了

**Comment by Mark9804** [comment]
> 角色不需要 resize 了

武器也不需要吧，后端 resize 和前端 resize 有什么区别，全扔给我适配好了

**Comment by Arondight** [comment]
都统一逻辑吧，info.js 函数加个参数，遇到了就只裁剪（填充），resize.js 也一样

**Comment by Arondight** [comment]
我感觉图片是正常的最好，别人也能用

**Comment by Arondight** [comment]
要不然你先别急，我晚上回去拉图，这次我想把吐都整规范了

**Comment by Mark9804** [comment]
行，有一个注意点

`sharp.position`，角色图应该是 `bottom`，武器图是 `center`

`gravity`我也不太清楚有什么用，晚上试试看

晚上老大哥先别急着全量更新，先 push 一下甘雨，凝光，匣里龙吟和弓藏的原图上去，我们测试完了合适的参数之后再全量更新

**Comment by Arondight** [comment]
就是说角色填充上方和左右，武器填充四周对吧？

**Comment by Mark9804** [comment]
> 就是说角色填充上方（和左右），武器填充四周对吧？

sharp 的算法应该是这样的，实际开放给我们的 API 是 sharp.position

武器我不太确定，可能用 inside 会好一些？先用几个样本试试看

**Comment by Arondight** [comment]
> 实际开放给我们的 API 是 sharp.position

老大哥看错了吧，填充和裁剪是用 extend 和 extract 做的

https://sharp.pixelplumbing.com/api-resize#extend

**Comment by Mark9804** [comment]
> 先 push 一下甘雨，**凝光**

凝光原图横向是 358 > 320

**Comment by Arondight** [comment]
> > 先 push 一下甘雨，**凝光**
> 
> 凝光原图横向是 358 > 320

那是裁剪到320还是锁放到320呢

**Comment by Mark9804** [comment]
不要裁剪，我想看到内鬼网的每一个不透明的像素都出现在我们的资源列表里

**Comment by Arondight** [comment]
> 不要裁剪，我想看到内鬼网的每一个不透明的像素都出现在我们的资源列表里

所以就是图片尺寸大于320锁放，小于320填充？

**Comment by Mark9804** [comment]
横向大于 320，或者纵向大于 1024（虽然后者可能性几乎没有），则缩放；

否则填充

**Comment by Arondight** [comment]
赶了个火车，开工晚了一些，我想问一下，如果硬要给武器补，那武器是补上，还是上下都补

**Comment by Mark9804** [comment]
# 人物

左右不满 320 的，左右各补 `parseInt((320 - pic_width) / 2)`
纵向不满 1024 的，在图片上方补 `parseInt(1024 - pic_height)`

左右超过 320 的，**保持比例**缩放到 320，然后视情况在上方补上像素补到 1024（我中午推的 commit）
纵向超过 1024 的，保持比例缩放到 1024，然后视情况在左右补上像素补到 320

# 武器

左右不满 320 的，左右各补 `parseInt((320 - pic_width) / 2)`
纵向不满 1024 的，图片上下各补 `parseInt((320 - pic_height) / 2)`

左右超过 320 的，保持比例缩放到 320，上下补充
纵向超过 1024 的，保持比例缩放，左右补充

**注意像素只能是整数，一定要 parseInt**

**Comment by Arondight** [comment]
## commit

https://github.com/Arondight/Adachi-BOT/commit/15740c0b1a9084e360e402b2435486a6d828a6ca

## 测试代码

```js
import fs from "fs";
import { imgMeta, toWebp, toWebpFile, webpOpt, webpPos } from "#utils/sharp";

(async function main() {
  const [file, output] = ["t.png", "t.webp"];
  let gachaImg = fs.readFileSync(file);
  const { width, height } = await imgMeta(gachaImg);
  const [widthTo, heightTo] = [320, 1024];

  if (width > widthTo || height > heightTo) {
    const [xs, ys] = [widthTo / width, heightTo / height];

    let [x, y] = [widthTo, heightTo];

    if (xs < ys) {
      y = height * xs;
    }

    if (ys < xs) {
      x = width * ys;
    }

    gachaImg = await toWebp(
      gachaImg,
      { resize: webpOpt.RESIZE, size: x },
      { resize: webpOpt.RESIZE, size: y },
      webpPos.CENTER
    );
  }

  await toWebpFile(
    gachaImg,
    output,
    { resize: webpOpt.CROP, size: 320 },
    { resize: webpOpt.CROP, size: 1024 },
    webpPos.BOTTOM
  );
})();
```

## 测试结果

### 扁扁图

#### from

![图片](https://user-images.githubusercontent.com/13673702/189391777-60754cec-7312-4dfc-a68f-037ed71ff712.png)

#### to

![图片](https://user-images.githubusercontent.com/13673702/189391856-94ecd85c-ae45-4cdb-87e5-c2015ae9743b.png)

### 长长图

#### from

![图片](https://user-images.githubusercontent.com/13673702/189392075-62246d1d-eafb-4bd6-a2e6-84fbd42c87fc.png)

#### to

![图片](https://user-images.githubusercontent.com/13673702/189392131-d308dda3-3ef4-493f-9baa-c7fd0ab518c5.png)

### 小图

#### from

![图片](https://user-images.githubusercontent.com/13673702/189392285-5825207a-2ed4-491c-b959-492a923311e3.png)

#### to

![图片](https://user-images.githubusercontent.com/13673702/189392347-728c18a5-753a-4af0-a492-1268df80e3bb.png)

### 四张图片

![图片](https://user-images.githubusercontent.com/13673702/189393281-858e3f21-94f4-43b2-b9a6-960487c5b842.png)

![图片](https://user-images.githubusercontent.com/13673702/189393318-c706a50c-753c-4741-b2cc-f56ad9769f60.png)

![图片](https://user-images.githubusercontent.com/13673702/189393606-6e3f2afa-a89a-4502-b44c-8d2d86685f8b.png)

![图片](https://user-images.githubusercontent.com/13673702/189393884-ea2372a7-c26c-4e6d-93e2-07ae87b212df.png)

**Comment by Mark9804** [comment]
用文字测试比例，聪明啊老大哥

上床了，明天看

**Comment by Arondight** [comment]
如果老大哥看的没有问题，干脆重新拉一遍吧，我家里往不好，拉这个好费劲，vps 上拉了又不能随时看。

另外你的 webp 参数被我改了，因为现在会有多次调用的问题，如果不是 100% ，会越来越失真，与其扣那 5%，不如相信 webp 吧

**Comment by Arondight** [comment]
另外 `tool-resize` 的功能我也加强了一下，你调图片的时候或许有用

```
$ npm run tool-resize -- --help

> adachi-bot@1.5.3 tool-resize
> node ./tools/resize.js "--help"

-f <string> -w <number> -h <number>

Options:
      --help      Show help                                            [boolean]
  -f, --file      图片文件路径                                     [string] [required]
  -o, --output    输出文件路径（不指定则覆盖图片文件）                                    [string]
  -w, --width     宽度（像素）                                                [number]
  -h, --height    高度（像素）                                                [number]
  -c, --crop      进行裁剪或填充而非缩放                                          [boolean]
  -p, --position  此选项为裁剪和填充的基准位置
  [string] [choices: "center", "top", "left", "bottom", "right", "top_left", "to
                    p_right", "bottom_left", "bottom_right"] [default: "center"]

Examples:
  -f ./resources/character/gacha/刻晴.webp -w 320 -h 1024 -c -p bottom
  -f ./resources/weapon/gacha/天空之刃.webp -w 320 -h 1024 -c -p center
```

**Comment by Arondight** [comment]
@BTMuli 老大哥以后如果扒图也注意一下，现在填充和缩放的规则已经由 @Mark9804 老大哥定下来了

**Comment by Mark9804** [comment]
压缩比例不是线性的，95% 和 100% 的差距能达到 1.5-3倍

如果不能避免多次压缩的话，不如一次 2%

**Comment by Mark9804** [comment]
单杠的规则老大哥确定这样写是对的吗

https://github.com/Arondight/Adachi-BOT/blob/15740c0b1a9084e360e402b2435486a6d828a6ca/tools/resize.js#L67-L70

<img width="806" alt="image" src="https://user-images.githubusercontent.com/9006264/189467145-ed31fa33-fa89-49fd-870d-af68162acca0.png">

**Comment by Arondight** [comment]
> 单杠的规则老大哥确定这样写是对的吗

这不就是常用的位运算嘛

**Comment by Arondight** [comment]
> 或者前面不压缩，到最后一步再统一过一遍压缩

可以，老大哥先看看图合不合规，合规的话我改改webp参数相关就行

**Comment by Mark9804** [comment]
我这两天在实验室搬砖，能看多少随缘吧

**Comment by BTMuli** [comment]
中秋节了，别忙了，放个假吃快月饼吧(＊ﾟ◇ﾟ)

**Comment by Mark9804** [comment]
角色可以了，武器我要再试一下应该给到多少，320 太小了

<img width="367" alt="image" src="https://user-images.githubusercontent.com/9006264/189471128-c3bb4ff0-04ee-460e-8dfe-a30760a1322d.png">

**Comment by Mark9804** [comment]
老大哥，现在的脚本有批量拉取的功能吗，我想在本地全量拉一遍武器图片做测试

**Comment by Arondight** [comment]
> 现在的脚本有批量拉取的功能吗

删掉已有的图片（除了三星堆），然后跑

```bash
npm run tool-resources -- -n 笛剑 嘟嘟可故事集 反曲弓 祭礼弓 薙草之稻光 新手长枪 弹弓 雾切之回光 吃虎鱼刀 托马 天空之翼 试作古华 决斗之枪 可莉 祭礼大剑 昭心 赤沙之杖 尘世之锁 暗巷猎手 斫峰之刃 佣兵重剑 天空之脊 黑岩刺枪 黑岩战弓 狼的末路 赛诺 降临之剑 无锋剑 信使 笼钓瓶一心 暗铁剑 波乱月白经津 神乐之真意 珊瑚宫心海 苍古自由之誓 恶王丸 丽莎 铁蜂刺 天空之卷 优菈 黑岩斩刀 赤角石溃杵 黑剑 辰砂之纺锤 口袋魔导书 夜兰 菲谢尔 安柏 护摩之杖 琴 流月针 魈 以理服人 西风猎弓 祭礼剑 风鹰剑 破魔之弓 圣显之钥 试作斩岩 甲级宝珏 莫娜 雨裁 旅行剑 温迪 飞天御剑 四风原典 龙脊长枪 飞雷之弦振 钢轮弓 多莉 息灾 钺矛 铁影阔剑 阿莫斯之弓 无工之剑 白缨枪 喜多院十文字 松籁响起之时 千岩古剑 刻晴 甘雨 黑岩长剑 落霞 磐岩结绿 西福斯的月光 宗室秘法录 白影剑 北斗 烟绯 银剑 暗巷闪光 盈满之实 玛海菈的水色 胡桃 迪卢克 凯亚 黑缨枪 历练的猎弓 忍冬之果 西风长枪 雷泽 铁尖枪 五郎 螭骨剑 迪奥娜 匣里日月 神里绫人 幽夜华尔兹 猎弓 万国诸海图谱 班尼特 试作金珀 和璞鸢 匣里龙吟 流浪乐章 异世界行记 诺艾尔 翡玉法球 竭泽 早柚 神射手之誓 达达利亚 绝弦 衔珠海皇 宗室猎枪 桂木斩长正 天空之刃 砂糖 枫原万叶 云堇 荒泷一斗 千岩长枪 雪葬的星银 试作星镰 冬极白星 训练大剑 柯莱 宵宫 天目影打刀 香菱 行秋 匣里灭辰 贯虹之槊 风花之颂 风信之锋 「渔获」 提纳里 七七 苍翠猎弓 祭礼残章 坎蒂丝 学徒笔记 原木刀 八重神子 阿贝多 西风秘典 终末嗟叹之诗 宗室大剑 雷电将军 流浪的晚星 旅行者 证誓之明瞳 埃洛伊 讨龙英杰谭 罗莎莉亚 冷刃 重云 钟剑 白辰之环 不灭月华 贯月矢 鸦羽弓 猎人之径 西风大剑 飞天大御剑 曚云之月 芭芭拉 魔导绪论 辛焱 若水 黎明神剑 久岐忍 申鹤 钟离 暗巷的酒与诗 天空之傲 宗室长剑 神里绫华 掠食者 白铁大剑 凝光 黑岩绯玉 沐浴龙血的剑 试作澹月 鹿野院平藏 腐殖之剑 宗室长弓 妮露 九条裟罗 西风剑 弓藏 森林王器 王下近侍 断浪长鳍
```

**Comment by Arondight** [comment]
所有的名字

```bash
find ./resources/info/doc/ -type f -name '*.json' | xargs -I {} basename {} | cut -d . -f 1
```

**Comment by Arondight** [comment]
所有的角色 

```bash
find ./resources/info/doc/ -type f -name '*.json' | xargs -I {} sh -c 'grep "\"角色\"" {} >/dev/null 2>&1 && basename {}' | cut -d . -f 1
```

所有的武器

```bash
find ./resources/info/doc/ -type f -name '*.json' | xargs -I {} sh -c 'grep "\"武器\"" {} >/dev/null 2>&1 && basename {}' | cut -d . -f 1
```

**Comment by Arondight** [comment]
> 单杠的规则

话说这玩意儿我们一般都叫“按位或”（[文档](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_OR)）。以前写 c 的时候经常用为位运算，后面写脚本了真不太常用了。

通常 unix 的文件权限其实就是这么来的，某一位可以是 `1` （执行）、 `2`（读） 、 `4`（写） ，也就是 `1 << 1` 、 `1 << 2` 、 `1 << 3`，也就是二进制的 `001` 、 `010` 、 `100` 。

假设权限为 `6` ，也就是 `110` ，也就是 `100 | 010` ，也就是 `4 | 2` ，也就是`读写` 。

检测 `6`（`110`） 中 `写` 是否置位 `if (6 & 4)` ， `110` 和 `100` 按位与，得到 `100` ，不为0，说明存在。反之 `6 & 1`， `110` 和 `001` 按位与得到 `000` ，说明不存在 `执行` 权限

**Comment by Arondight** [comment]
webp 选项我试了下应该好了，刚才推上去了

**Comment by Arondight** [comment]
> webp 选项我试了下应该好了，刚才推上去了

调了下参数，90 和 95 好像写反了

**Comment by Arondight** [comment]
> 角色可以了，武器我要再试一下应该给到多少，320 太小了

我改了一下代码，现在武器预期尺寸大于图的时候也进行等比缩放了

**Comment by Mark9804** [comment]
看到卡池图源走的是 celestia，那里面的图应该都是规范的尺寸，要不要信任

**Comment by Arondight** [comment]
> 看到卡池图源走的是 celestia，那里面的图应该都是规范的尺寸，要不要信任

看你，网页要啥我就做啥

**Comment by Mark9804** [comment]
> 网页要啥我就做啥

呃我唯一的要求只有统一，之前我们在用内鬼网的图，那个尺寸千奇百怪的，所以才需要 resize.js 这个扭曲的产物

我刚刚看了一下，应该可以认为 celestia 提供的武器图一定是 `512 × 1024` px 的，这样的话武器卡池图片就不用 resize 了

只可惜他们的角色卡池图是完全体大图，如果像内鬼网那样裁剪好然后也是一个固定尺寸的话，resize 都可以不要，可以更省力

那么现在武器图就不用 resize，也不用再转一遍 webp 了（看上去已经压缩过），角色图因为内鬼网那边第一不能信任尺寸第二压缩属实拉胯，所以 resize 和 webp 依然都需要过一遍

**Comment by Arondight** [comment]
听起来简单了，武器把尺寸改成 512 ，参数 loseless 打开，实际上就不会做事了，逻辑虽然没用不过留一下吧，说不定哪天又得找新图源了

**Comment by Arondight** [comment]
我感觉把 512 切到 320 是不是好一些

**Comment by Mark9804** [comment]
> 我感觉把 512 切到 320 是不是好一些

我也有过这个想法，但是后端一旦做了这个改动就是破坏性的（如果某张图 320 之外有像素的话，修改就只能重新去源站扒），相比之下扔给前端缩放的话就是非破坏性的，原图是什么样就是什么样

所以我觉得不用改

**Comment by Arondight** [comment]
> 如果某张图 320 之外有像素的话，修改就只能重新去源站扒

前端也没法处理这个问题吧

**Comment by Arondight** [comment]
切到 320 首先是角色武器统一，其次更换图源方便

我是觉得有一天或许会换到毛子的网站的，首先毛子有下版本的图，另外毛子无视 dmca，当前武器扒不了下版本的

**Comment by Arondight** [comment]
另一方面来说，就算维持 512 ，也得把毛子的下版本武器给弄到 512 ，好像工作是一样的

**Comment by Mark9804** [comment]
这样的话

武器图横向超过 320 的裁切到 320 （320 之外的不要了，好像都是空白像素，缩放反而尺寸不对），没到 320 的补到 320
纵向和角色一样保持 1024 不变

> 毛子的下版本武器

毛子的图不知道切了多少，我想用 scale 试试看保持比例，老大哥先改 resize 逻辑，我这边统一拉下来测试吧

**Comment by Arondight** [comment]
好的，那 webp 不进行二次压缩了是吧

**Comment by Mark9804** [comment]
> 那 webp 不进行二次压缩了是吧

毛子的角色卡池图继续压，太大了

**Comment by Mark9804** [comment]
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/9006264/189943324-183ad1db-6dfd-448b-bee9-74d2109dc865.png">
