### ISSUE TITLE
旅行者 json 生日错了

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#932]
![image](https://user-images.githubusercontent.com/9006264/192570341-f17d9934-8a5a-48db-a7bf-146cd3676ca6.png)

**Comment by BTMuli** [comment]
旅行者不就是玩家吗，生日要不设成跟派蒙的一样？

**Comment by Mark9804** [comment]
> 应该不用这么搞，大概率引起误解，而且大多数丘丘用户也不知道自己瞎填的啥生日

__Originally posted by @Arondight in https://github.com/Arondight/Adachi-BOT/issues/423#issuecomment-975554941__
