### ISSUE TITLE
帮助文字乱码

### ISSUE THREAD

**Issue by zmy15** [Arondight/Adachi-BOT#942]
### 问题描述

![103fe6f5fc02009cef01a9dd11e04a7](https://user-images.githubusercontent.com/109537161/195628551-9d79cef3-2c7d-4998-b90a-f3c071e4a38c.jpg)

### 复现流程

输入"帮助"时,机器人返回乱码

### 运行环境

```Text
操作系统：Windows（Microsoft Windows 10 专业版）
内核版本：10.0.19043
内核架构：x64
处理器：  9.66%（Intel Core™ i5-5200U @ 2.2Ghz）
启动时间：9 days
内存使用：66.04%（5.61 GB / 8.5 GB）
数据占用：994 kB
Node.js： 16.15.0
npm：     8.5.5
浏览器：  chrome 101.0.4951.54
```

### 当前提交

```Text
commit 0e09c6facdb5551fb1382ff6ac8a3de5eb4845c7 (HEAD -> master, origin/master, origin/dev, origin/HEAD)
Author: github-actions <github-actions@github.com>
Date:   Mon Oct 10 20:11:03 2022 +0000

    Update material.json
```

### 代码状态

```Text
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   103784
        new file:   105656
        new file:   186312
        new file:   36660
        new file:   90972
        new file:   mintty.exe.stackdump
```

**Comment by Mark9804** [comment]
Windows 尝试一下使用 UTF-8 编码

https://zhuanlan.zhihu.com/p/153219931

**Comment by zmy15** [comment]
> 

修改了,依旧是这样

**Comment by zmy15** [comment]
> 其他命令会乱码吗，比如 `系统信息`

其他所有命令都不会乱码

**Comment by Mark9804** [comment]
检查一下你的 `config_defaults/qa.yml` 的编码。另外机器人默认的使用帮助是 `help`

**Comment by Arondight** [comment]
这个是 qa.yml 的示例，这个文件没做 windows 的 cp936 支持，一切都是基于 utf8 bash 的

https://github.com/Arondight/Adachi-BOT/blob/master/config_defaults/qa.yml

我觉得我加个说明和环境判断比较好

**Comment by zmy15** [comment]
> 

![批注 2022-10-14 230346](https://user-images.githubusercontent.com/109537161/195879505-10c2605f-e9f7-4c65-af5b-e69852b9b4f1.png)
群里有人发"帮助",才发现有乱码

**Comment by Arondight** [comment]
我觉得给配置加一个选项区分系统更好一些

```
platform:
  - linux
  - win
  - mac
```

**Comment by Arondight** [comment]
https://github.com/Arondight/Adachi-BOT/commit/4f6d84f698feba152ed4dc97450b8fa5d86a223f
