### ISSUE TITLE
龙哥没了

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#944]
### 问题描述

![图片](https://user-images.githubusercontent.com/13673702/196386558-c9878be5-1325-4c4e-a8c1-cd2cbd60d68e.png)

### 复现流程

看看龙哥

### 运行环境

```Text
环境很好，一年70块钱，建议下次便宜一点
```

### 当前提交

```Text
最新提交
```

### 代码状态

```Text
代码健康
```

**Comment by Mark9804** [comment]
荧妹在吗

**Comment by Mark9804** [comment]
角色列表是从哪里读取的，里面没有荧妹

<img width="279" alt="image" src="https://user-images.githubusercontent.com/9006264/196418106-ae0cc346-9f45-4a48-aebe-c6637181d750.png">

**Comment by Arondight** [comment]
空和莹的英文是啥

**Comment by Mark9804** [comment]
Aether（空）, Lumine （荧）

**Comment by Mark9804** [comment]
但是游戏里面更多的是 PlayerBoy, PlayerGirl

**Comment by Arondight** [comment]
旅行者的名片咱们是手动加的吗

**Comment by Arondight** [comment]
https://github.com/Arondight/Adachi-BOT/commit/7984af4eeb627cd0efbfaaa017df97e9d3941f7d

**Comment by Mark9804** [comment]
> 旅行者的名片咱们是手动加的吗

我忘记了，有一个叫 `旅行者.webp` 的名片图
