### ISSUE TITLE
解决 oicq 版本过低的问题

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#969]
### 问题描述

https://github.com/ds300/patch-package

https://github.com/mamoe/mirai/blob/dev/mirai-core/src/commonMain/kotlin/utils/MiraiProtocolInternal.kt

项目 patch 一下，原作者应该是摆烂了

### 复现流程

1

### 后台日志

```Text
1
```

### 运行环境

```Text
1
```

### 当前提交

```Text
1
```

### 代码状态

```Text
1
```

**Comment by Arondight** [comment]
用 mirai 的还是版本过低

**Comment by Arondight** [comment]
https://github.com/mamoe/mirai/pull/2312/files

**Comment by Arondight** [comment]
icqq 也没见有相关修改呢

@ixCiel 协议改动你知道那个框架改了吗我抄过来，还是说目前所有框架都没动静

**Comment by ixCiel** [comment]
不清楚，但是提示版本过低并不都是真的因为版本过低，感觉是另一种封禁。我两个QQ号，一个可以正常使用。另一个用密码登录就会提示版本过低，但是换成扫码就可以使用。

**Comment by Arondight** [comment]
啊这，我晕了，已经弄不清 oicq 到底有没有问题了

**Comment by Arondight** [comment]
@Mark9804 老大哥知道点啥吗

**Comment by Mark9804** [comment]
> icqq 也没见有相关修改呢

https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/blob/develop/icalingua/src/main/adapters/oicqAdapter.ts#L1895-L1916

icalingua 那边维护者也不懂协议分析

> 已经弄不清 oicq 到底有没有问题了

有，mirai 也有，都是协议过旧没人去抓新包，所以 mirai 也没看到相关更新

mirai 我还没用过，oicq 这边之前有猜测是因为 device.json 里面用 OICQ 跳脸被杀了

老大哥要是真想修得从抓包开始，虽然B站有教程，但是我也没具体看过

https://space.bilibili.com/49968119

**Comment by Arondight** [comment]
> 都是协议过旧没人去抓新包

啊这，看来只能等一个大牛了，我把代码抄一抄，在我们这儿给 oicq patch 一下

**Comment by Mark9804** [comment]
直接把我上面发的 icalingua 的抄下来就可以了，维护协议这种精力消耗和法律风险都大的东西我真心不建议，珊瑚虫QQ 坟头草都三米高了

**Comment by Arondight** [comment]
好吧

**Comment by Arondight** [comment]
@Mark9804 @ixCiel @BTMuli @citydirector @xiaofeicn @chongdong12 你们试一下 dev 分支有用吗

```
git pull origin dev
npm run install-dev
rm -rvf ./data/<qq>/
npm run init
```

**Comment by Arondight** [comment]
我开小号试的，好像安卓协议还是版本过低，手表没试，我不知道是不是还需要按照 mirai 修改一下安卓的协议

**Comment by Mark9804** [comment]
我之前就靠着这个解的，用的 iPad 协议，但是不是所有人都有效

**Comment by Arondight** [comment]
我又强制推送了一次，把安卓设备也更新了

**Comment by Arondight** [comment]
> 我之前就靠着这个解的，用的 iPad 协议，但是不是所有人都有效

你生成的配置文件和 icalingua 的还不太一样

**Comment by Arondight** [comment]
我改了安卓配置后登录安卓提示变成了不在常用网络了

**Comment by Mark9804** [comment]
https://github.com/mamoe/mirai/discussions/2424

mirai修了

**Comment by Arondight** [comment]
> [mamoe/mirai#2424](https://github.com/mamoe/mirai/discussions/2424)
> 
> mirai修了

不是说是协议的问题嘛，怎么也只改了点配置

**Comment by Mark9804** [comment]
更新了协议配置大概也算协议太旧

**Comment by Arondight** [comment]
明后天我更新一下，也是打个js补丁等上游更新

**Comment by Arondight** [comment]
1. 只有安卓，没有 pad ，oicq 的各种协议都是基于 pad 的
2. 改了似乎也不能用，一直在连接服务器，反正以前也不能用，于是就提交上去了
