### ISSUE TITLE
米游社域名换了

### ISSUE THREAD

**Issue by BTMuli** [Arondight/Adachi-BOT#970]
### 问题描述

本来的 `bbs.mihoyo.com`现在直接换成`https://www.miyoushe.com`了，一些咨讯API感觉也要改了

### 复现流程

null

### 后台日志

```Text
null
```

### 运行环境

```Text
null
```

### 当前提交

```Text
null
```

### 代码状态

```Text
null
```

**Comment by Arondight** [comment]
原来的还能用吗

**Comment by BTMuli** [comment]
看了下已经是502了，
![image](https://user-images.githubusercontent.com/72692909/205112441-e210a5ce-8621-4c42-94e9-138935422a65.png)
> 还有宿舍停电了我也要无了

**Comment by BTMuli** [comment]
然后已经开了`f12`防护了，起码以前开着网页米游社跟开发工具还是能跑的，现在要么刷新不了，要么一直`debug`。

还有就是Bot的`米游社`命令一直提示`无法获取可用Cookie`，不知道跟这个有没有关系

**Comment by BTMuli** [comment]
https://bbs-api-static.miyoushe.com/ 拿之前的一个小爬虫试了一下，有返回
![image](https://user-images.githubusercontent.com/72692909/205116372-e387c32f-1437-4c4a-a682-8af0ef83ee8f.png)
一堆v2...这是整个全给升级了是吗。
![image](https://user-images.githubusercontent.com/72692909/205117712-badbd111-4a7c-4cc9-9866-872e911f6b36.png)

**Comment by BTMuli** [comment]
https://github.com/Le-niao/Yunzai-Bot/commit/66adc7ca88b77bc84033ae3717b8a221116d5cf4

隔壁的，果然换了

**Comment by Arondight** [comment]
确认不存在此问题
