### ISSUE TITLE
项目前端工程化

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#982]
最近跟着其他大哥一起写项目，逐渐感觉我们的前端一开始就应该工程化，是当年的我太菜了

优点
1. 更好的开发和维护支持。工程化之后可以使用 ts 类型注释和 vue sfc，webstorm 开发效率大大提升，也能通过静态类型检查解决一些隐藏问题。加上现在的技术栈因为当时我水平有限比较畸形，不能让之后有接手想法的人走弯路
2. tree shaking 和编译时优化。大幅提升加载速度的一项技术，不用一点点抠性能，可以根本上解决 `今日素材` 解析时间太长刷不出图的问题

缺点
1. 需要构建才可以使用，构建产物放进 git 我觉得是没有必要的，在启动脚本里面塞一个 vite build，构建时间应该在 8-10s。也就是如果不做多线程的话，bot 的冷启动时间会慢 8-10 秒左右；或者后台常驻 vite server，替代掉现在的 express server

**Comment by Arondight** [comment]
是的，我早有这个想法，但是又觉得没必要

另外

1. 用户构建的话需要安装很多模块，我感觉 vite 打包后上传也挺好
2. 其实现在这样也挺好，因为咱俩的开发工作基本上停滞了，没必要再去折腾，另外对用户也无感，顶多其他开发者看着觉得菜的抠脚

**Comment by BTMuli** [comment]
这几天折腾vite-electron感觉挺好上手，~~指深入就是个天坑~~

项目本身还是用的vue2加express，能升级到vue3加vite会快很多

而且按照项目性质，bot做的就是消息转发功能，感觉完全可以分离开来变成两个模块，前端构建模块就能用electron做调试

~~上面纯属梦话，真重构不如新建项目~~

~~md学了一堆没落地纯属空中楼阁~~

**Comment by Mark9804** [comment]
> 而且按照项目性质，bot做的就是消息转发功能，感觉完全可以分离开来变成两个模块，前端构建模块就能用electron做调试

你要找的是不是： [Icalingua-plus-plus/Icalingua-plus-plus: A client for QQ and more.](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus)

**Comment by BTMuli** [comment]
> > 而且按照项目性质，bot做的就是消息转发功能，感觉完全可以分离开来变成两个模块，前端构建模块就能用electron做调试
> 
> 你要找的是不是： [Icalingua-plus-plus/Icalingua-plus-plus: A client for QQ and more.](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus)

草，我的意思是不管QQ登录了，直接搞个窗体模拟输入内容获取返回

**Comment by BTMuli** [comment]
~~差不多是这样~~

![image](https://user-images.githubusercontent.com/72692909/221108794-0b141803-6b1f-405f-94dd-4bff24ef92cc.png)

**Comment by Mark9804** [comment]
emm，服务器上没有gui的说法

**Comment by BTMuli** [comment]
> emm，服务器上没有gui的说法

这就不是放在服务器上的...主要就是~~方便前端开发人员调试~~

项目前后端分离能搞好的话这个写起来就很快（应该）

**Comment by Arondight** [comment]
> ~差不多是这样~
> 
> ![image](https://user-images.githubusercontent.com/72692909/221108794-0b141803-6b1f-405f-94dd-4bff24ef92cc.png)

这应该是 bot 框架自带的功能，不应该我们搞

当初上了 oicq 的黑车，有点后悔

**Comment by BTMuli** [comment]
> 这应该是 bot 框架自带的功能，不应该我们搞
> 
> 当初上了 oicq 的黑车，有点后悔

能搞原生的都是大佬

**Comment by Mark9804** [comment]
不做工程化了，又不是不能跑.jpg

题外话，最近适配 Safari 给我一度写自闭了，新时代 IE 名不虚传
