### ISSUE TITLE
海哥裂了？

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#992]
### 问题描述

![图片](https://user-images.githubusercontent.com/13673702/220135822-019f92af-8212-44bf-87ab-f834b1ebf1dc.png)

### 复现流程

1

### 后台日志

```Text
1
```

### 运行环境

```Text
1
```

### 当前提交

```Text
1
```

### 代码状态

```Text
1
```

**Comment by Mark9804** [comment]
有这张图吗

**Comment by Mark9804** [comment]
没图那肯定裂了
<img width="230" alt="image" src="https://user-images.githubusercontent.com/9006264/220136321-86737d91-d49a-46b7-8945-f1cbced1204a.png">

**Comment by Arondight** [comment]
这图哪里来的，给忘了

**Comment by Mark9804** [comment]
随便找个有完整立绘的网站扒下来就行，麻烦老大哥上传一下了

![UI_Gacha_AvatarImg_Alhatham](https://user-images.githubusercontent.com/9006264/220137167-b2f8a95a-fb03-4d0c-b825-f976d733db98.png)

**Comment by Arondight** [comment]
牛的

**Comment by Arondight** [comment]
图像哪儿扒的，瑶瑶有裂了

**Comment by Mark9804** [comment]
https://api.ambr.top/assets/UI/UI_Gacha_AvatarImg_Yaoyao.png

然后随便拿个什么工具裁个 1:1 的正方形

**Comment by Arondight** [comment]
我感觉可以做到自动化脚本上

**Comment by Mark9804** [comment]
也行，主要是自动化工具不一定能裁到头

以图像中心为原点，大概看看裁一个什么位置合适

**Comment by Arondight** [comment]
以后再加吧，调起来好麻烦
