### ISSUE TITLE
扫码登陆失败

### ISSUE THREAD

**Issue by FightForBeauty** [Arondight/Adachi-BOT#995]
### 问题描述

根据文档流程走，无论是扫码登陆或者是密码验证均失败，具体入下图

![image](https://user-images.githubusercontent.com/127087793/223053978-3d2b0448-8db1-4b65-86b2-185db4170e4d.png)

### 复现流程

npm run init

### 后台日志

```Text
"--end--": "修改后可能需要重新验证设备。"
```

### 运行环境

```Text
adachi-bot@1.5.4 tool-status
> node ./tools/status.js
```

### 当前提交

```Text
commit 36d3f1b0ac6d946c84360d20b4b99e66fa143cd9 (grafted, HEAD -> master, tag: v1.5.4, origin/master, origin/HEAD)
Author: Qin Fandong <shell_way@foxmail.com>
Date:   Wed Mar 1 14:12:49 2023 +0800

    v1.5.4
```

### 代码状态

```Text
On branch master
Your branch is up to date with 'origin/master'.
```

**Comment by Arondight** [comment]
Duplicate of https://github.com/takayama-lily/oicq/issues/507

**Comment by Arondight** [comment]
考虑换到 icqqjs/icqq

**Comment by Arondight** [comment]
@Mark9804 我看你朋友不是也会改协议了……

**Comment by Mark9804** [comment]
啊？我朋友？

**Comment by Arondight** [comment]
我记得你说的你朋友搞了个 icqq ，但是没有能力维护协议，基本上没有前途

**Comment by Mark9804** [comment]
老大哥记错了，我没有做这个的朋友，可能我当时说的是 oicq QQ 群里的群友

**Comment by Arondight** [comment]
哦，那我是记忆混乱了，我看了下这个项目，基本上可以直接切过去了，无缝切换，而且这个项目目前还是 oicq 的超集

**Comment by Arondight** [comment]
再试试呢，应该行了吧

**Comment by lc-cn** [comment]
> 哦，那我是记忆混乱了，我看了下这个项目，基本上可以直接切过去了，无缝切换，而且这个项目目前还是 oicq 的超集

收到大佬的夸赞，好开心

**Comment by dmlgzs** [comment]
> 哦，那我是记忆混乱了，我看了下这个项目，基本上可以直接切过去了，无缝切换，而且这个项目目前还是 oicq 的超集

[Icalingua++](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus) 和其对应的[协议库分叉](https://github.com/Icalingua-plus-plus/oicq-icalingua-plus-plus)也求个 star，icqq 登录流程相关的代码是从这个上面移植的（）

**Comment by gaqwe767** [comment]
已经更新了icqq，但是有的QQ怎么登都登不上（还是提示版本过低），换个QQ又可以了...

**Comment by Arondight** [comment]
> 已经更新了icqq，但是有的QQ怎么登都登不上（还是提示版本过低），换个QQ又可以了...

@lc-cn 得问这位老大哥，协议是他在维护，我只会用，不懂这个

**Comment by Arondight** [comment]
@lc-cn 我发现你这个项目没有 issue 和 discussion ，你可以给客服写个申请，把你的项目和原项目的 fork 关系接触，很简单一句话就行，然后你要说你想保留项目自己的 star 和 fork 关系，这样你的项目也能被其他人看到，说不定就有人愿意做贡献的

**Comment by Arondight** [comment]
@lc-cn https://support.github.com/contact?flow=detach_fork&subject=Detach%20Fork&tags=rr-forks

现在好像都上 ai 了

**Comment by Arondight** [comment]
> 密码登陆老问题
> 
> <img alt="image" width="789" src="https://user-images.githubusercontent.com/9006264/232049793-cf46e242-b0bc-487f-b719-81a9d025801f.png">

奶奶滴，又出问题了啊？

**Comment by Arondight** [comment]
更新一下又好了
