### ISSUE TITLE
new ver

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#997]
### 问题描述

白术卡维和他们的武器

### 当前提交

```Text
1
```

**Comment by Arondight** [comment]
卡维是四星啊，少了一把武器

**Comment by Mark9804** [comment]
五号可以吗

**Comment by Arondight** [comment]
> 五号可以吗

当然可以呀，新版本还早着呢

**Comment by Mark9804** [comment]
补**白术、卡维**两个人的立绘，武器因为用的证件照所以不用补，是这样吗

**Comment by Arondight** [comment]
嗯嗯，我忘了立绘从哪儿拿怎么裁剪了，你补一下吧

**Comment by Arondight** [comment]
我擦还有两套圣遗物 @BTMuli 老大哥有空帮忙搞一下吗

**Comment by Mark9804** [comment]
干脆老大哥顺带把立绘也弄了吧，我开学了有点忙

**Comment by BTMuli** [comment]
> 干脆老大哥顺带把立绘也弄了吧，我开学了有点忙

行吧
